### ISSUE TITLE
.gardenignore doesn't work with unstaged files/dirs

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1006]
### Current Behavior

Adding an entry to `.gardenignore` for a file or directory that hasn't been staged with Git won't work and Garden will continue to watch and build the content.

### Expected behavior

It should work for un-staged content.

### Reproducible example

1. Go to `demo-project`
2. Create `test.txt` and `.gardenignore` files in `frontend` dir
3. Add `test.txt` to `.gardenignore`
4. Run a Garden command
5. Notice that `test.txt` is copied to `.garden/build/frontend`
6. `git add` the file and notice that it now works.

### Workaround

Stage the file you want to ignore.

**Comment by edvald** [comment]
That feels like an odd artefact of the git implementation, which we use to implement the gardenignore support. Why would it require a file to be staged to be gitignored...?

**Comment by edvald** [comment]
Could be our fault though, maybe we're incorrectly re-adding the file in a different phase.

**Comment by eysi09** [comment]
Yeah I suspect it's the latter but haven't dug into it though. I remember bumping into something similar in the past.
