### ISSUE TITLE
Garden won't re-build module on changes to garden.yml if it contains an include directive

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1007]
### Current Behavior

This is kind of an edge case but if the `garden.yml` file contains an `include` directive, and is modified in such as way that it doesn't effect the `build` directory, e.g. the `include`s aren't changed, it won't re-build the module.

So basically it looks like the `garden.yml` file isn't being included in the content hash when `include` is used. Works fine otherwise. 

### Expected behavior

Garden should re-build a module on changes to `garden.yml`. 

### Reproducible example

1. Pick an example project
2. Add an include directive to a module `garden.yml`
3. Change the `garden.yml`
4. Notice that Garden doesn't re-build the module

### Workaround

Do a manual force re-build if you need to re-build after changing a `garden.yml` file that has an `include` directive.

**Comment by eysi09** [comment]
This is kind of edge case-y but still setting `prioritiy:medium` since the `include` directive seems to be used quite a lot.

**Comment by edvald** [comment]
Referring back to Slack discussion, I'd say this would be best solved by using the actual config as part of the hash, instead of hashing the `garden.yml`.

**Comment by eysi09** [comment]
Closed with #1009

**Comment by edvald** [comment]
Did you validate that this is no longer an issue?
