### ISSUE TITLE
Switch from watchman to chokidar

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#101]
Watchman is good for performance but we want the basic installation process to be more straightforward. We can use https://github.com/paulmillr/chokidar, which is performant and well maintained (it's used by VSCode among others).

**Comment by thsig** [comment]
I looked into replacing Watchman with chokidar in our FS watching logic, should be relatively straightforward.

**Comment by thsig** [comment]
Similarly, it shouldn't be too hard to support both of them.

**Comment by edvald** [comment]
As discussed AFK, we're going to abandon watchman in favor of Chokidar, which is well supported and portable. Renaming the issue accordingly.
