### ISSUE TITLE
`garden get debug-info` dumps far too much info about Kubernetes clusters

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1024]
### Current Behavior

Running the `garden get debug-info` .zip generation command doesn't tell you what debug information is being gathered. I was suspicious, so I took a look inside the .zip. I was mildly surprised to see the entire tree of `garden.yml` files, since to my mind it wouldn't help reproduce most failures without source code and environment. I was _really_ surprised to see that it fetches multiple namespaces worth of Kubernetes information, including the entire pod body of _all_ pods in the namespace.

### Expected behavior

This simply isn't appropriate info to encourage users to disclose in a public bug report, since unrelated workloads won't help debug Garden but may greatly facilitate intrusion attempts into their cluster. For example: listing vulnerable container images that they're running, misconfigurations with privileged pods, lack of pod security policies, implementation details about internal cluster services, and so on.

### Suggested solution(s)

Running a debug command should only fetch Garden-relevant debugging info, and only info that is safe to share in a public setting.  I'd suggest only collecting Kubernetes objects with a Garden-specific label; collecting less information about them where possible; and explicitly listing every namespace that data is being retrieved from (such as `Adding Garden-created Pods from namespace_one...`).

Collecting more sensitive information should require an extra flag, and warn users to send it to the maintainers through a private channel.

### Your environment

```
eronarn@Jamess-MacBook-Pro investment_automation]$ garden version
0.10.2
```

**Comment by edvald** [comment]
All good points @Eronarn and no objections. The objective is not at all to collect sensitive information, and we don't want to overreach.

@10ko could you get on this? At a minimum we should not suggest posting this here on GitHub (that we can fix immediately).

**Comment by 10ko** [comment]
I was writing my answer while you were typing @edvald. 

@Eronarn I agree with all the objections and I will disable immediately the suggestion to attach the output.
I have to admit there might have been poor scoping on my side and I can imagine we assumed the command to be run on local, throwaway clusters. With deploy to remote cluster, this is clearly not the case anymore and as you said it could expose sensitive data.

I will rework the command to: 
 - limit namespaces to garden-system and project namespace
 - have better logging and explicitating what it is being exported.

I am not sure if it makes sense to include a flag to export everything at all, since I don't think it would add any benefit on our side to know that much info.

I'll keep you posted and update this issue once a PR is up.

Thanks again for spotting this!
Emanuele

**Comment by Eronarn** [comment]
Thanks for being responsive!

To clarify, I tested this out using our generic `staging` namespace as the Project namespace, rather than a Garden-specific namespace - the workloads don't use customer data, but the _config_ is often similar to our `production` namespace (on a different cluster). I think the "blast radius" would've been a lot smaller if I'd used a dedicated namespace for testing Garden; but even then this issue may come up for debugging Garden in CI/CD use cases, where users actually do intend to write to production-like namespaces.

**Comment by edvald** [comment]
That makes perfect sense. As it happens, @10ko is currently working on features geared towards production deployments, so it's getting more and more relevant if anything.

We really appreciate the detailed report. It's all too easy to fall into blind spots sometimes, and it's certainly not the idea to jeopardize the security of our users! Please don't hesitate to keep the feedback coming. Could I perhaps ask you for a review on the PR when it's ready?

**Comment by Eronarn** [comment]
Sure thing; if you have instructions for running a dev build I'd be happy to re-run the dump against our cluster and scan through the results to see if it looks more reasonable.
