### ISSUE TITLE
Kaniko version is hardcoded

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1031]
### Current Behavior

The Kaniko release is currently hardcoded to v0.8.0, which is about 6 months old: https://github.com/garden-io/garden/blob/master/garden-service/src/plugins/kubernetes/container/build.ts#L35

The current Kaniko release is v0.10.0, as of mid-June: https://github.com/GoogleContainerTools/kaniko/tree/v0.10.0

Newer versions of Kaniko contain some important fixes, such as this bug that causes builds to fail when combining layer caching and Dockerfiles that contain `USER`: https://github.com/GoogleContainerTools/kaniko/issues/596

However, Kaniko releases are also fairly unstable, meaning that as an end user I might need to try out several specific commits. (As an example, it looks like v0.9.0 was broken, and v0.10.0 may have broken caching.)

### Suggested solution(s)

Provide a configuration option for choosing the Kaniko image version, or perhaps for patching the manifest before it is submitted (like with kustomize).

**Comment by Eronarn** [comment]
(That being said, the Kaniko support got me 90% through building this particular Dockerfile fairly seamlessly. I think that needing to change Kaniko versions says more about the instability of the Kaniko project itself.)

**Comment by edvald** [comment]
👍 Happy to update the default and add an option.

**Comment by edvald** [comment]
Turns out I can't get either v0.9.0 or v0.10.0 working. Will need to investigate a bit further.

**Comment by Eronarn** [comment]
I looked over their issues/releases, and it seems like their release process may not actually be doing thorough testing :/ For now we're using the Docker cluster builder for evaluation, but certainly Kaniko would be preferable if it can be made to work.
