### ISSUE TITLE
Allow publication of test reports

### ISSUE THREAD

**Issue by psoares** [garden-io/garden#1032]
I have a java project that uses the gradle build tool. Gradle provides html test reports, which get written to `theproject/build/reports/`. That directory has the following layout:

```
tests
  |---test
           |--- classes
           |--- css
           |--- js
           |--- packages
           |--- index.html
```

It would be nice if in `garden.yml` one could somehow publish that index.html file, properly formatted, to the garden dashboard's test results.

As a workaround, currently I tweak the gradle build so it outputs informative messages to the console, in case it helps anyone trying to do the same, by adding the following to `build.gradle`:

```
test {
    testLogging {
        // set options for log level LIFECYCLE
        events "PASSED", "STARTED", "FAILED", "SKIPPED"
        exceptionFormat "short"
    }
}
```
More on that here: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLoggingContainer.html

**Comment by daviddawson** [comment]
We have a similar use case to this (as well as other stuff, but this is pertinent).

Right now, we have a few kubernetes clusters for our dev pipeline (dev, staging, prod) and a separate "support" infrastructure, non k8s. One part of that is Teamcity running various things, including various tests.  Right now, we're expanding our UI testing quite a lot, primarily using Cypress and node.js.   They mostly run against the apps on the dev k8s cluster.    

These tests are pretty heavyweight, and are being orchestrated on the teamcity agent VMs using docker compose.  They start the test env containers, then run a 1 time task to run the cypress tests within a container that can access the test containers within the docker managed network.  There is a host mapped docker volume that cypress outputs to, with the end result being that the test reports appear at /test/output (or whatever), with that being the folder thats been mapped to the test task container volume. 

That does _work_, but its saturating the test VMs, as they also run non docker workloads, and we can't reliably control resource allocation. We end up restarting some VM or other every few days.

What would be good is to allow us to implement something similar to this workflow using garden. 

Our main requirements (to make this easy to adopt straight away in our current setup) are :-

* create a test environment, isolated within k8s (ie, namespaced)
* The containers need to be able to be built from the current source, without having to go through our normal registry, like the docker-compose `build.dockerfile` statement
* We need to run a test task like container (semantically the same as a k8s job)
* The test results/ reports that are within the Job (/ whatever) filesystem once it completes, need to be copied back to the client for us to process in the teamcity agent

Personally, I would prefer a generic `output` directory with 1 folder per task.  CI tools make it easy to glob for files to process, so a little extra structure preserves information for debugging, while still being easy to process.

**Comment by Eronarn** [comment]
We have a similar desire for this feature: run ETL jobs using a deployed Garden container, using in-cluster shared data, and then return the output so we can test it with various local scripts.
