### ISSUE TITLE
services[].ports[].nodePort doesn't support assignment by cluster

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1057]
### Current Behavior

The [Garden documentation](https://docs.garden.io/reference/module-types/container#services-ports-nodeport) for the `nodePort` option expects a number representing the specific `nodePort` to allocate. However, ports are a cluster-wide resource that must be shared with other services (including services that the user can't observe due to namespaces). This `nodePort` value also must fall into a range of available ports, which itself can vary between clusters.

As per the [https://kubernetes.io/docs/concepts/services-networking/service/#nodeport](NodePort documentation), it's actually not required to set a `nodePort` value on the `spec` when you submit it. If you don't, an available `nodePort` will be _assigned_ and placed on the `spec` object. This workflow is actually preferred in Kubernetes due to the challenges in managing static ports - some examples of that [here](https://oteemo.com/2017/12/12/think-nodeport-kubernetes/).

### Suggested solution(s)

`nodePort: true` is an acceptable parameter. Setting it will omit sending the field at all, allowing the cluster to return a valid port.

### Additional context

We're investigating Garden for our development environments. Since we expect that multiple developers will be working on the same project, and that they won't be able to query for all currently in-use ports, we'd strongly prefer not to use hardcoded NodePorts.

Typically NodePorts wouldn't be used at all, so that wouldn't be a problem; but we're currently trialling the nginx ingress controller vs. the AWS ALB ingress controller. The latter supports the `NodePort` and `LoadBalancer` service types, but _not_ `ClusterIP` (because the `ClusterIP` only exists _within_ the cluster so it's not sufficient for the LB to route to). The lack of dynamic assigned `NodePort`s within Garden would therefore present a challenge for using the AWS ALB ingress controller.

### Your environment

```
[eronarn@ip-192-168-10-243 qbernetes]$ garden version && kubectl version && docker version
0.10.2
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f97efcc
 Built:             Wed Jun  5 01:37:53 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       f97efcc
  Built:            Wed Jun  5 01:42:10 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
Ah yes, you're right, we should also allow `nodePort: true` and have the cluster pick the port. Tagging for next release.

**Comment by Eronarn** [comment]
That's so fast! Great job 💪

**Comment by edvald** [comment]
Thanks, and our pleasure! Sometimes I can't resist the little dopamine surge of a quick uncontentious PR :)

**Comment by Eronarn** [comment]
@edvald On experimenting with this further with a static nodeport, it looks like if a nodeport is set, it creates a new service (so I end up with `web` and `web-nodeport` services); but that `web-nodeport` service isn't used by the created ingress. So that also breaks the AWS ALB ingress controller's assumptions, I'm afraid :/

Let me know if you think that's worth filing a separate issue. Though for now, I'm moving on to the nginx controller again, since that seems to be what Garden expects.

**Comment by edvald** [comment]
Ah yes, good point. I kept the existing behavior in the PR, but I agree, it would make sense to combine the two.
