### ISSUE TITLE
Docs: add a secrets management guide

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#1092]
We're currently lacking a comprehensive guide on secret management. We've documented the individual commands to manage secrets and have example projects, but an actual guide showing how it works, best practices and that we can update as we add support third-party secret management solutions (such as Vault).

**Comment by eysi09** [comment]
We might consider coupling it with a guide on env vars. They're documented elsewhere but something like  **Secrets and Environmental Variables** under **Using Garden** would probably be useful for a lot of people.
