### ISSUE TITLE
Garden won't find modules that are git submodules

### ISSUE THREAD

**Issue by Decisional** [garden-io/garden#1097]
Hey there.

I have a simple meta-repository: The garden project level configuration resides in the root directory, modules are stored in git submodules that are mounted in this root. 

_meta # meta git repository
├── submodule
│   ├── Dockerfile
│   └── garden.yml
└── not-a-submodule
│   └── garden.yml
└── garden.yml

When adding a garden module configuration in one of the submodules,  garden won't find them with `garden scan` from the root directory. Simply `cp submodule/garden.yml not-a-submodule/` will make garden pick up the configuration from the folder that's not a submodule. Adding the not-a-submodule directory to .gitignore doesn't change anything.

Any thoughts? :confused:

**Comment by edvald** [comment]
Ah, I think that's a bug. Sorry about that!

cc @eysi09. I guess we should be running `ls-files` with `--recurse-submodules`: https://stackoverflow.com/questions/36848544/git-finding-a-list-of-files-e-g-using-git-ls-files-including-submodules

**Comment by gen1321** [comment]
I have same issue
