### ISSUE TITLE
Support for nested Garden projects

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#1119]
For very large projects it would be helpful to have the ability to split up the stack into multiple sub-projects.

@elliott-davis perhaps you could elaborate!

**Comment by edvald** [comment]
I've been pondering this. I think we should absolutely support nested projects properly, and need to work out the design and scope. 

That said, you _can_ currently have nested projects underneath the project root, or in remote sources, in the sense that we simply ignore nested project definitions and we just pick up the modules. This actually works fine in some scenarios, but it would be good to come up with a more formal way of dealing with nested projects.

Things we may want to consider include:
- How do we propagate environment and provider configuration? Currently you'd need to duplicate those in nested projects, but it would surely be useful to be able to reference between projects somehow. Maybe a project could reference a parent project, which we could pull the config from, but then only work with the modules in the nested project.
- It'd be great if project variables from parent projects would propagate to nested projects.
- Would it make sense to namespace identifiers? For example, for modules under a nested project to be referable with prefixes, e.g. `nested-project.some-module`. This way, you wouldn't have to worry about name collisions across projects. And modules within the same project (or level of nesting) could omit the prefix so the project works independently.

Maybe "all we need" (which is easy to explain but not quite trivial to implement) is the following:
1. Allow projects to define a _parent_, which the project can inherit configuration from, including environments, provider configs, and variables. The project can then override each of those as necessary.
2. Support project namespaces in module, service, task and test names, similar to when you need to call services across Kubernetes namespaces. Within a project, you use the name directly. Across sub-projects, you prefix with the project name to disambiguate. And by extension we allow identifiers to "conflict" across projects.

Are there other requirements to consider?

**Comment by edvald** [comment]
Superseded by #1477
