### ISSUE TITLE
npm install && npm run build on a fresh checkout fail

### ISSUE THREAD

**Issue by dcharbonnier** [garden-io/garden#1135]
after a fresh checkout the build does not run, looks like the problem is just that there is no build folder
```
lerna ERR! npm run clean stderr:
sh: 1: shx: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! garden-service@0.10.6 clean: `shx rm -rf build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the garden-service@0.10.6 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by edvald** [comment]
Hey @dcharbonnier! It seems you're just missing an `npm install` ahead of running the build, the error is complaining that `shx` is not found, which is one of the dependencies. Have you followed the steps in CONTRIBUTORS.md?

**Comment by dcharbonnier** [comment]
This issue is to mention that it's not very intuitive for a new user,  you expect to do an `npm install && npm run build`, it's not obvious at first that it's a lerna project.
With a simple ` "clean": "if [ -d build ]; then shx rm -rf build; fi;",` you can make the start easier.
Not sure you target windows install.

**Comment by eysi09** [comment]
We do have a `clean` script in our `package.json`. This is also documented in our `CONTRIBUTING.md` guide so I'll go ahead and close this one.

**Comment by dcharbonnier** [comment]
the clean is failing when there is no previous build, that's the point of this issue

**Comment by eysi09** [comment]
Isn't the clean failing because NPM can't find `shx`? Running `npm run clean` works fine for me, without the `build` dir.

I've also added the `npm install` step to the contributing docs: #1188.
