### ISSUE TITLE
Helmfile support?

### ISSUE THREAD

**Issue by camertron** [garden-io/garden#1152]
Hey gardeners, is helmfile support on the horizon at all? Thanks for a great tool!

**Comment by edvald** [comment]
Hey @camertron! Very glad you're finding it useful :)

We hadn't dug into Helmfiles, pretty much because it hadn't come up before, but we're happy to look into it. Maybe you could help us out by describing how you're using it? That'd be super helpful to guide us in the implementation.

**Comment by camertron** [comment]
Hey @edvald, we're in the process of moving our deployments over to Helm and Helmfile, and would like to be able to do the same for local development. It would be great to be able to use Garden to launch all the necessary components of our stack locally using our various Helm charts. Right now, we're using a specific values.yaml file for development, but it would be nice to be able to add the development environment to our Helmfile and point garden at it.

Not very specific I know. What else would you like to know?

**Comment by hookercookerman** [comment]
+1 for helmfile we tend to use it everywhere; not unless you know of a workaround its pretty much a none start for us to evaluating this tool: cheers 👍
