### ISSUE TITLE
kustomize support

### ISSUE THREAD

**Issue by kvokka** [garden-io/garden#1192]
## Feature request

Since version 1.14 k8s support kustomize tool for secrets generation. For this purpose you can use `kubectl apply -k` command. 

Is it possible to add such module `type`? If this functionality is already supported, can you share, how to do it?

Thank you.

Connect #1092

**Comment by edvald** [comment]
We don't currently support `kustomize` but we should. I'll flag this as a feature request.

**Comment by davestephens** [comment]
Is this still on the roadmap?

**Comment by arlyon** [comment]
Not stale, still a wanted feature

**Comment by edude03** [comment]
Would like to see this as well

**Comment by nvmker** [comment]
Still need kustomize support for garden
