### ISSUE TITLE
Allow base64 encoding/decoding in template syntax

### ISSUE THREAD

**Issue by kvokka** [garden-io/garden#1193]
## Feature request

In the https://github.com/garden-io/garden/blob/6c27c6c4aac02879390b21eec26cdff5b3ea09aa/examples/kubernetes-module/garden.yml#L8 you can find the example of the saved secret, which is crypted with base64. It is uncomfortable for local development.

Can we store it as plain text and convert to base64 in the background?

**Comment by edvald** [comment]
Garden as such doesn't do any encoding or decoding of variables, so this is purely for the purpose of the example, where we place the value in the Kubernetes manifest. It would be handy though to have helper functions for template strings, to encode and decode base64.

I believe the Postgres helm chart (which we would generally recommend over using raw manifests) does base64 conversion for you. See the `vote-helm` example for how to use the Postgres Helm chart in a `helm` module.

**Comment by kvokka** [comment]
Thank you for such a quick response!

The main question is, when I need to create some secrets with out Helm. At the moment I'm trying to apply garden to existed configuration, with some quirks and hacks in place. And it will be cool to sort everything out and put every secret to the corresponding chart or manifest in the future. But i want to be able just to stub something. With base64 encoding for dev i have to store all variables like

```yaml
  foo: YmFyCg== # bar
```

And i thought, that it may be cool to be able to use more user-friendly syntax (it may be solved with this https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md)

**Comment by edvald** [comment]
Understood. I do think deferring this to kustomize could be good, but base64 encoding is a reasonably common enough task to leave that as an open feature request. I'll rename the issue accordingly.
