### ISSUE TITLE
A GetServiceStatusTask should not be executed concurrently with build tasks for its parent module's build dependencies

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#1196]
### Current Behavior

`BuildTask`s for build dependencies of a module A can be executed concurrently with `GetServiceStatusTask`s for A's services.

This can result in the `GetServiceStatusTask` failing, because it may start syncing module A's build directory before dependency products from its dependencies have been synced in.

### Expected behavior

`GetServiceStatusTask`s aren't run before its parent module's build dependencies' build tasks have been run.

### Reproducible example

This should come up (at least sporadically) when deploying any service whose parent module has build dependencies with copy specs.

### Suggested solution(s)

Add a `SyncBuildProducts` task, make `BuildTask` and `

### Additional context

Here's the relevant context from the Slack thread where a user first posted about this problem.

<img width="496" alt="Screenshot 2019-09-17 at 18 03 39" src="https://user-images.githubusercontent.com/382137/65059028-8c508900-d975-11e9-9b22-b050193709c3.png">
<img width="1423" alt="Screen Shot 2019-09-04 at 7 02 08 PM" src="https://user-images.githubusercontent.com/382137/65059050-93779700-d975-11e9-9b1a-cb10ce889586.png">

**Comment by edvald** [comment]
This notably will only work right if we stage builds in a directory specific to the version we're building, which is a change we want to make anyway for other concurrency-related reasons.
