### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kvokka** [garden-io/garden#1202]
## Thank you

I opened a lot of issues on this repo today. It may looks like I do not appreciate the tool. 
It is not correct and the tool is really great and I want do it better where I can. 

The only goal of this issue is say thank you to the team!

**Comment by eysi09** [comment]
Thank you @kvokka! We're of course always looking to improve and stabilise Garden and welcome all the feedback and bug reports we can get! We wouldn't be where we are without all this help from the community.

I think I'll leave this open just a little while longer :)

**Comment by eysi09** [comment]
Time to close this one.
