### ISSUE TITLE
Feature Request: Support Creating Annotations and Labels on Namespaces

### ISSUE THREAD

**Issue by stevenpall** [garden-io/garden#1218]
I have a specific use case for adding a label to the namespace(s) created by container modules (secret sync via Kubed: https://appscode.com/products/kubed/0.5.0/guides/config-syncer/intra-cluster/). One other use case I can think of for this is enabling Istio sidecar injection (also configured by a namespace label).

I think it might be generally useful to be able to configure generated namespaces in a number of ways, but perhaps this could be a good starting point.

**Comment by edvald** [comment]
Yep, we bumped into this ourselves recently. I think this makes sense as a config flag on the `kubernetes` provider.

**Comment by stevenpall** [comment]
@edvald  Any update on this?
