### ISSUE TITLE
Fetch logs hangs on Dashboard

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1226]
### Current Behavior

The API request for logs never returns.

**Comment by WeitBelou** [comment]
Hello!
It seems like I have encountered the same issue.

## Garden
```
$ garden version
0.10.11
```

## Steps to reproduce:
1. Create module with type container with hot reload
3. Run `garden dev --hot=*`
4. Wait until service deployed
5. Check logs
6. Edit garden.dev to trigger redeploy
7. Edit source code to trigger hot reload
8. After hot reload succeeded `/logs` hangs

**Comment by eysi09** [comment]
Thanks for the report. I'll look into this case as well. On my end they simply don't load to begin with.

**Comment by eysi09** [comment]
@WeitBelou Unfortunately this doesn't close the issue you mentioned, it is logged separately in #1246.
