### ISSUE TITLE
File watcher should handle changes to garden.yml files

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#123]
Currently, only builds, deploys and tests (depending on the command) are run when module sources change. If a `garden.yml` file is modified, the changes aren't reflected in the process.

Reloading modules should not be too difficult if we specifically catch changes to a module's `garden.yml` file. We would basically need to trigger a reload of the module (which is possible currently in the `Garden` class), and stop+restart the `processModules` method (otherwise we could run into a bunch of inconsistencies).

Handling the project `garden.yml` might be slightly trickier, but should be achievable. We'd need to refactor the `Garden` class slightly to allow it to be reset, and we'd need to stop and restart `processModules` as well.

The alternative would be to just restart the whole process, but that would be kinda lumpy if you're making rapid changes to configs.

In any case we'd also need to elegantly handle errors in the `garden.yml` file, and not just crash the process.

**Comment by thsig** [comment]
Fixed here: https://github.com/garden-io/garden/pull/157
