### ISSUE TITLE
Allow pulling images from private registries when using remote building

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1236]
This is a non-trivial feature but one that gets asked about a lot and something users have tripped over.

Adding here to start the discussion and brainstorm on alternatives and workarounds.

**Comment by khaled** [comment]
any idea when this one might land? what are the main difficulties in implementing it?

**Comment by edvald** [comment]
The complexity was in handling auth to the private registry, but I think we've worked something out. Expect this to land in 1-2 weeks.

**Comment by khaled** [comment]
thanks @edvald! let me know if i can be of any help...
