### ISSUE TITLE
Dashboard build issue

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1240]
Currently we can't import functions from the `garden-service` package to the `dashboard` package if the function has a 3rd party dependency. 

This is because such an import will cause the `dashboard` to indirectly depend on the `parse5` package which is a dependency of the `cli-highlight` package that we use to highlight YAML.

Having a dependency on `parse5` causes the following Webpack warning:

`Critical dependency: the request of a dependency is an expression`

This happens when packages have dynamic imports. Here's the relevant parse5 issue: https://github.com/inikulin/parse5/issues/240.

And here's a discussion on the issue in the Webpack repo: https://github.com/webpack/webpack/issues/196

CRA is configured to throw on Webpack warning in CI which means that building the `dashboard` always fails in CI. This has been [raised several times in the CRA repo](https://github.com/facebook/create-react-app/search?q=Critical+dependency%3A+the+request+of+a+dependency+is+an+expression&type=Issues) without any proper resolution.

I believe we the following options to resolve this:

1. Build the dashboard with `CI=false`. The only difference is that the build script won't throw on warnings.
2. Fork `react-scripts` and extend the Webpack config to allow these kind of imports. We'd have to maintain it as a separate NPM package. This is better than ejecting because it's easier to rebase the upstream. Will also be useful if we need to make more changes in the future.
3. Add a new package to the Garden monorepo that includes utility functions that both `garden-service` and `dashboard` shares and that only have web-friendly dependencies.

Currently, we're simply not importing functions that have 3rd party dependencies from the `garden-service` package.

IMO, both 2. and 3. are valid options. It's fine to have non web-friendly packages at the moment since the dashboard is hosted locally. However, when we have a version that's served over the wire, the issue above would likely increase the bundle size since Webpack can't do tree shaking on these kind of dynamic imports.

**Comment by edvald** [comment]
Is this still an issue @eysi09?
