### ISSUE TITLE
Build-Error doesn't provide enough context to troubleshoot

### ISSUE THREAD

**Issue by D-Dinh** [garden-io/garden#1242]
### Current Behavior

Failed building my-service. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command failed with exit code 1 (EPERM): $USER_HOME/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=kubernetes --namespace=garden-system exec -i garden-docker-daemon-bcb7d56c-vfxk2 -c docker-daem
on -- docker build -t 127.0.0.1:5000/my-name-space/my-service:v-59c918a2ed -f /garden-build/da138e2e-d1d1-4796-86c6-601acffc8d52/my-service/Dockerfile.test /garden-build/da138e2e-d1d1-4796-86c6-601acffc8d52/my-service/
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 build task(s) failed!

### Expected behavior

The error output should contain clear steps on the problem and potential solutions.

### Reproducible example
1. Enable `cluster-docker` buildMode.
2. Create a docker file that uses a private registry or depends on an image that doesn't exist
3. `garden build my-service`

### Workaround

Revert to 10.6

### Your environment

`garden version: 0.10.11`

```
kubectl version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version: Docker version 19.03.2, build 6a30dfc`

**Comment by eysi09** [comment]
Hi @D-Dinh 

You're absolutely right that the error message could be more helpful. We'll look into this.

Otherwise, the issue is documented here: #1236 and in [our docs](https://docs.garden.io/using-garden/in-cluster-building#pulling-base-images-from-private-registries).

**Comment by eysi09** [comment]
The error message now contains more details, due to #1284
