### ISSUE TITLE
docs: Project/Modules links don't work in "Config Files Reference" page

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1249]
In the first sentence in https://docs.garden.io/reference/config#project-configuration.
>Below is the schema reference for the *Project* and *Module* garden.yml configuration files.

*Project* and *Modules* are anchor links but don't point to anything.

**Comment by eysi09** [comment]
Looks like the markdown link checker misses internal header links. Here's the relevant issue: https://github.com/tcort/markdown-link-check/issues/65
