### ISSUE TITLE
Conditional deployment of modules

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#1250]
We currently have no straightforward way to conditionally deploy modules. This could be useful in cases where a user, for example, would want to deploy a database in their dev environment but use a hosted service when deploying to production.

We only support `skipDeploy` for Helmcharts and openfaas functions. We have the`modules.exclude` and `modules.include` fields available at the project level, but these are limited in functionality because on invocation, Garden has no awareness of, for example, what environment it's deploying to.

Some ideas:
 - have `modules.include|exclude` in the environment config?
 - make `skipDeploy` part of the base module config?
 - all of the above?

**Comment by eysi09** [comment]
Closed with #1515.
