### ISSUE TITLE
two way sync?

### ISSUE THREAD

**Issue by khaled** [garden-io/garden#1253]
One of the nice things about garden is that I can pull a project repo,  run `garden dev`, and have an app running on a cluster, without having to have any of the required dev and build tools installed locally.  The required tools are specified by and run within associated containers.  I just iterate on the code, and the containers are automatically rebuilt or synced to within the cluster.  So far so good.

In some cases though, I need to run some of the aforementioned tools to manipulate source files.  For instance, `npm install someLib` (updates `package.json`, `package-lock.json`) or `rails generate migration Foo` (creates a new migration source file).

I can run the above commands as garden tasks, but that will manipulate the source files in the (ephemeral) container.  The question then becomes, how do I transfer these files from the container back to my local disk, so that I can later commit & push them?

It would be nice if garden had a straightforward solution for this.  Perhaps it could be something like a two way sync - a module could specify a sync from `src/` in its container back to `src/` on the local machine.

FWIW, my current approach for handling this is to directly run module containers locally (i.e. additional instances outside of kubernetes), with a volume mount into the local fs.  I automate this process with [VS Code's remote containers feature](https://code.visualstudio.com/docs/remote/containers#_attaching-to-running-containers), pointing the `devcontainer.json` to a module's `Dockerfile`.  I run whatever commands I want within a container shell.   This is a bit inconvenient though, because I have to set up multiple environments (e.g. one for each module) and switch back and forth between them.

### Environment

```
$ garden version
0.10.11
```

**Comment by eysi09** [comment]
Hi @khaled and thanks for the issue!

We currently don't support bi-directional sync but this has come up in the past. We use `rsync` to do the syncing which doesn't support bi-directional sync, so we'd need to switch to something like `unison` or `mutagen`.

Currently we usually run these commands locally. E.g. we'll generate the migration locally with `rails  generate migration Foo` and run the migration itself as a task (`rails db:migrate`) inside a container. Obviously this assumes some dev dependencies being installed locally.

I'll flag this as a `discussion` issue so that we can collect some more use cases, discuss workarounds, and ponder the design of a bi-directional sync feature (cc @thsig, @edvald).

**Comment by khaled** [comment]
@eysi09 thanks for your input on this, and let me know if there’s any way I can help!

**Comment by Eronarn** [comment]
Personally I'd like to see a way to locally run the remotely built Docker container (like `garden run mymodule --local --interactive` or whatever). This won't work for all workflows, but it would cover most of the need for this feature that I've had.

**Comment by lukad** [comment]
I just started using garden and I think two way sync would be very useful. In one of the rails projects I'm working it's not trivial for me to even run `bundle install` locally without several workarounds. So running my generators and db tasks is not really an option. My current workaround is to `garden exec` into the container and manually copy paste the generated files to my local repository. I would greatly appreciate bidirectional sync in garden.
Let me know if I can help with that.

**Comment by edvald** [comment]
I happen to be working on it as we speak :) Can't give an exact ETA just yet but it'll be there within a release or two (no doubt with some iteration along the way)

**Comment by lukad** [comment]
That's awesome! Thanks for your work.

**Comment by edvald** [comment]
Closed by #2352, which adds two-way sync support!
