### ISSUE TITLE
Ternary operator can't return arrays

### ISSUE THREAD

**Issue by edkeeble** [garden-io/garden#1254]
### Current Behavior

When making use of a ternary operator within a module's garden config file, providing arrays for the return values raises an "Invalid template string" error.

### Expected behavior

The ternary operator should return an array value.

### Reproducible example

Define a module, like so:

```
kind: Module
type: container
name: somecontainer
services:
  - name: someservice
     dependencies: "${environment.name == 'local' ? ['something'] : []}"
```

Run `garden validate`. It should raise the following error: `Invalid template string ${environment.name == 'local' ? ['something'] : []}: Unable to parse as valid template string.`

### Workaround

This isn't a general workaround, but for my particular use case (defining dependencies based on the environment, wherein a particular module may only be present in a local environment), I've removed the dependencies property and resorted to just running an environment-dependent startup script for the service, which only checks if the local dependency is running if it's in the local env. This isn't ideal, since it removes the dependency from the stack graph, even in environments where the dependency should exist.

### Suggested solution(s)

I'm not entirely sure and would need to dig into the source to figure out why this error is being thrown.

### Additional context

I also looked at simply using a variable defined on each environment to specify dependencies, but it appears that variables can only hold a number, string or boolean value.

### Your environment

`garden version`
0.10.12

`kubectl version`

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

`docker version`

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by edvald** [comment]
Hey @edkeeble, thanks for reporting this! 

So basically we only support returning primitives from template strings, and not arrays. Allowing array outputs would introduce a fair amount of added complexity, so we haven't yet prioritized that. 

I'll file this as a feature request though, and we'll look into when we might implement it.

**Comment by edvald** [comment]
I believe the underlying issue here (changing dependencies based on the environment running) is largely covered by #1515. I'll close this one. Feel free to re-open if there are other uses you have in mind for handling arrays in template strings.
