### ISSUE TITLE
A guide for writing plugins

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1258]
With #1256, we're formalising how to extend plugins. This is the first step towards a true plugin SDK. It would therefore be useful to have a public guide on how to write plugins for Garden.

**Comment by raybotha** [comment]
I think a guide would be very useful. I'd be interested in writing a plugin, especially for knative services, but that PR is a bit deep.

**Comment by RichiCoder1** [comment]
Ditto. I'm now interested in writing one for something like [OAM](https://oam.dev/). Would love to understand the extensibility store.
