### ISSUE TITLE
"garden delete environment" doesn't delete the project--metadata namespace

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#1266]
IMHO the expected behavior for `garden delete environment` should be to delete everything related to the current project from my cluster. This would be both the `project` namespace, and the `project--metadata` namespace.

Local testing indicates the `project--metadata` namespace stays there.

If there's a reason for that, it should be explained in the command description with `garden help delete` or in the [documentation](https://docs.garden.io/reference/commands#garden-delete-environment).

IMHO though, the most intuitive behavior would be to delete both namespaces.

**Comment by edvald** [comment]
I agree, and I had actually changed this in a branch, where I had other WIP commits. I'll just push that one commit now.
