### ISSUE TITLE
Unrecognized apiVersion

### ISSUE THREAD

**Issue by chuan137** [garden-io/garden#1273]
Hi Gardener,

not sure if this a bug or problem with my settings. I am running the remote-k8s example. My local k8s is on version 1.10, and remote is on 1.7. And I see following errors. Is it because my server k8s version is too old?

```
Failed resolving provider kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unrecognized apiVersion: rbac.authorization.k8s.io/v1
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Failed resolving one or more provider configurations:
- kubernetes: Unrecognized apiVersion: rbac.authorization.k8s.io/v1
```

**Comment by eysi09** [comment]
Hi @chuan137 

It looks like you need version 1.8 or greater to use the RBAC API (https://kubernetes.io/docs/reference/access-authn-authz/rbac/). 

Garden needs it for setting up Tiller which it requires for users that use the helm module type and for some internal system services.

Are you able to upgrade your cluster to 1.8 (or greater)?

**Comment by 10ko** [comment]
Hi @chuan137,
As mentioned by @eysi09 Garden might not support some old version of kubernetes but unfortunately this limitations are not mentioned anywhere. 
I created an issue for that and we will update the docs accordingly soon.

Thanks for taking the time to report this. 🙏

**Comment by chuan137** [comment]
@eysi09 @10ko thanks for the reply. I will try on a different 1.8 cluster

**Comment by chuan137** [comment]
sorry to repopen this

I moved to a 1.8 cluster, but I got a similiar error, the problematic versions are api/v1beta and etc. It seems that our cluster api supports only the beta versions. Is it possible to support the betas? Or can I patch the package changing all the api versions for my case?

**Comment by eysi09** [comment]
It looks like the issue is with `apps/v1`, which, as far as I can tell, was introduced in 1.9 (here's the [changelog entry](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#workloads-api-appsv1).

Back to @10ko point, we need to document the minimal supported version. Question is, which version is that (cc @edvald).

**Comment by edvald** [comment]
I believe it is actually 1.9, but it would be worth doing a quick sanity check on that with e.g. minikube.

**Comment by edvald** [comment]
Overall our goal (which we should btw document) is to support approximately two years' worth back of Kubernetes major releases, of which 1.9 happens to be the oldest at the moment. We should formalize these in documentation, tests, and in explicit version checks in our code.

**Comment by Tails** [comment]
And how far does it go up? Is 1.16.2 of Kubernetes supported?

**Comment by edvald** [comment]
It is, yes. We fixed that issue with the OpenFaaS plugin, and have now added a test for 1.16.x in CI.
