### ISSUE TITLE
Unrecognized resource type batch/v1beta1/CronJob

### ISSUE THREAD

**Issue by garoose** [garden-io/garden#1275]
### Current Behavior

Attempting to deploy a Helm chart for a CronJob resource fails with
`Unrecognized resource type batch/v1beta1/CronJob`

### Expected behavior

The resource deploys successfully, as it does with `helm upgrade --install`

### Reproducible example

See https://github.com/garoose/garden-cron-job-test for a small example of the problem

### Your environment

`garden version`
0.10.13

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client:
 Version:           18.09.7
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Tue May  7 17:57:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by eysi09** [comment]
Hi @garoose!

Thanks for reporting this and for the repro example! This should be a quick fix.
