### ISSUE TITLE
Deleted files not removed from .garden/build directory

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1278]
### Current Behavior

Deleted are not synced to the build directory, meaning files stay there even after they're deleted from the project proper. 

### Expected behavior

Deleting a project file should also remove it from the build directory, next time Garden stages a build.

### Workaround

Delete the module build directory: `rm -rf .garden/build/my-module`

**Comment by Eronarn** [comment]
I ran into this as well, it was rather frustrating to debug.
