### ISSUE TITLE
No way to add tolerations to `garden-registry-proxy`

### ISSUE THREAD

**Issue by to266** [garden-io/garden#1279]
### Current Behavior

If a node with taints is added (with, for example, GPU), the `garden-registry-proxy` daemonset never gets deployed there, since by default it does not have any tolerations

### Expected behavior

I would expect to be able to configure that in project-level `garden.yaml`.

### Workaround

```
kubectl -n garden-system edit daemonsets.apps garden-registry-proxy
```
and then add the needed tolerations to the definition.

**Comment by eysi09** [comment]
@edvald Thoughts on how we can do this a clean manner? 

Something like: `gardenRegistryProxyTolerations` in the provider config doesn't feel very slick (and confusing to those not familiar with the remote building internals). 

We could group remote building config together under a common key, with nested keys for each service. Something like: `remoteBuilding.gardenRegistryProxy.tolerations: {}`. We could then move the other config options under `remoteBuilding` in v0.11 (or deprecate them and allow both versions for now).
