### ISSUE TITLE
Mirror examples to separate repo

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#128]
It would be cleaner to have all the examples (and there should be many more over time) to a separate repo. We'd need to stop using the hello-world as part of our tests, but we want to do that anyway.

**Comment by edvald** [comment]
Actually, we may want to keep them in the same repo if we go for #171 ?

**Comment by eysi09** [comment]
Would be nice to be able to git clone the examples separately though.

**Comment by eysi09** [comment]
There's actually already an examples repo: https://github.com/garden-io/garden-examples

Wasn't the plan to maintain those examples separately and have other examples within the project that would function more as integration test?

**Comment by ellenkorbes** [comment]
I propose we should keep the examples in the main repo, and then have them mirrored to a separate examples repo.

This way it's easier for us to commit changes to the code functionality and the respective adjustments to the examples in one single PR, for example, but we still have a separate and much lighter/smaller repo of examples only that we can use for didactic reasons.

Thoughts?

**Comment by thsig** [comment]
Ellen and I talked about this earlier — just to clarify, mirroring = running a script that automatically updates the examples repo with changes to example projects in the main repo.

That way, example projects are still maintained/developed as part of the main dev workflow.

**Comment by edvald** [comment]
Good idea! We could rig that up via Github hooks on master.

**Comment by eysi09** [comment]
I'm going to close this one since we have some other thoughts on how to maintain the examples as well, e.g. as submodules in the main project.
