### ISSUE TITLE
Better error messages when tasks fails

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1282]
We print the `error.message` part when tasks fails. This is not always very informative.

Case in point, if we have an exec module that runs the command `[mkdir, foo]` where the dir `foo` already exists, we get the following error:

```
Failed building my-module. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command failed with exit code 1 (EPERM): mkdir foo
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 build task(s) failed!
```

...which doesn't tell us a lot.

 If we however print `error.all` (assuming the error originated in an `execa` call, `all` is basically `stdout + stderr`), we get:

```
Failed building my-module. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
mkdir: foo: File exists
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 build task(s) failed!
```

...which is way more helpful.

The underlying issue is that we use different libraries to run these kind of commands and they return error objects of different shapes. We should aim to standardise these and include the `stderr` part when applicable.

**Comment by edvald** [comment]
This issue came up after an "upgrade" of execa. We should check if this issue has been addressed upstream. If not, we should wrap all execa calls to address this, because this can come up pretty much everywhere we use it, and manually catching each case is not really viable.

**Comment by eysi09** [comment]
AFAICT, the `error.message` part has always been like this. But we should wrap it and add more details.

**Comment by edvald** [comment]
Ah, so the issue is perhaps that we're pulling `error.message` instead of using `error.toString()`, or something to that effect.

**Comment by eysi09** [comment]
It's rather that `execa` isn't appending `stdout | stderr` to the message. Basically this: https://github.com/sindresorhus/execa/issues/369

So it's probably best to wrap execa, catch the error and do something like: `error.message = error.message + "\n" + error.all` before throwing it.

**Comment by edvald** [comment]
Ahaa that explains the difference. We use the `shell` option in a couple of places, and have removed it in some calls so the error message is less informative. In any case, we should still wrap execa calls so we can control this more precisely.

And ideally we should set some length boundaries on what we print.

**Comment by eysi09** [comment]
The code I was testing did set `shell` to true but to no avail.
