### ISSUE TITLE
Warn if the Docker context is much larger than the repo size

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1286]
When converting non-Dockerized repos to Garden, it can be frustrating to figure out the right set of includes/excludes across the different ignore files. I wound up with one case where my repo built with 30 MB of Docker context, while another developer built with 1.3 GB of Docker context. This slows down builds and can also introduce subtle, hard-to-debug problems (like accidentally syncing locally built artifacts).

I'm not sure what the heuristic here would be but it would be great to have a warning if your Docker context is excessively large.

**Comment by edvald** [comment]
I think #1387 might go a long way to solve this.
