### ISSUE TITLE
Remote source changes aren't updated - buildMode: 'local-docker'

### ISSUE THREAD

**Issue by D-Dinh** [garden-io/garden#1290]
### Current Behavior
Given a project has been built/deployed with a remote source, when changes are made to the remote source, re-building/deploying the project doesn't include changes made to the remote source.

`✔ localstack          → Pushing image localstack:v-29507ac712 to cluster...`

### Expected behavior

The project re-builds the remote source, based on changes for local builds.
`garden build --force <remote-source's module>` should also fetch updates.

`✔ localstack          → Fetching from file:///git/localstack#Garden`

### Workaround

Remove the project's `.garden/sources`

### Your environment

```
garden version:
0.10.13
```

```
kubectl version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

```docker version:
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.12.10-eks-825e5d
  StackAPI:         Unknown
```

**Comment by eysi09** [comment]
Are you referring to changes being made to the remote source upstream? If so, that is actually intentional. You need to use the `garden update-remote source|module|all` command to explicitly update the remote source.

This is so that changes to the upstream won't have unexpected effects on your own project. That being said, we should probably notify the the user if the upstream is different from the local clone.

**Comment by D-Dinh** [comment]
You are correct, I forgot to run garden update-remote. A gentle reminder would be great as well!
