### ISSUE TITLE
Fetching helm fails on Windows

### ISSUE THREAD

**Issue by kapolos** [garden-io/garden#1299]
I just installed the latest `garden` on Windows 10 Pro. Trying to set it up with remote kubernetes. 

`garden plugins kubernetes cluster-init` fails on the helm step

![image](https://user-images.githubusercontent.com/10794126/68017944-9cf85c80-fca0-11e9-97dd-ea87a621d411.png)

I tried downloading the helm binaries directly and place them in `.garden\tools\helm` but the script doesn't recognize them, so it re-downloads and fails at the rename step.

![image](https://user-images.githubusercontent.com/10794126/68018131-0c6e4c00-fca1-11e9-833a-7c3e862001e3.png)

**Comment by edvald** [comment]
Hey @kapolos. Could this be your issue? https://docs.garden.io/troubleshooting#im-getting-an-eperm-operation-not-permitted-rename-error-on-windows

**Comment by kapolos** [comment]
That was it! I'm using Kaspersky instead of Windows Defender but disabling the real-time protection allowed it to continue.

Thank you very much @edvald !

I'm getting a time-out deploying the nfs provisioner now but I'll investigate and open a new ticket if necessary.
