### ISSUE TITLE
garden validate shouldn't require an environment

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1302]
Our CI environment doesn't have direct access to the Kubernetes cluster that our standard environment represents. This means that running `garden validate` will fail with a variety of provider-related issues, even though most validation could be performed without connecting to any cluster.

In the interim we've had to add a blank "local" environment to run validation against; but this is error-prone and makes the YAML more confusing.

**Comment by edvald** [comment]
Makes sense. The reason for requiring an environment is that otherwise we may not be able to resolve all templated values. We could perhaps add an option, so that you could do a shallow validation, that doesn't require a full resolution on all configs. Shouldn't be too hard.
