### ISSUE TITLE
Rsync on build fails on Windows

### ISSUE THREAD

**Issue by kapolos** [garden-io/garden#1304]
Windows 10 Pro, real-time protection off, remote kubernetes ,latest garden.

`garden build` errors out on rsync step:

![image](https://user-images.githubusercontent.com/10794126/68054570-394d4e00-fcf7-11e9-9cf5-8b97ace8d4e5.png)

Maybe that `/./modulename` part at the end isn't making it happy.

--

![image](https://user-images.githubusercontent.com/10794126/68054793-d0b2a100-fcf7-11e9-9845-9b81042d21df.png)

![image](https://user-images.githubusercontent.com/10794126/68054806-da3c0900-fcf7-11e9-91da-a0752bb5efa7.png)

**Comment by eysi09** [comment]
Hi @kapolos

Do you have reproducible example? We test every Garden release on Windows and we haven't seen this before.

**Comment by edvald** [comment]
Note: This may be fixed in 0.10.5. We made some adjustments to how we rsync that could affect this, but unfortunately we don't have a reproducible case at the moment to test it ourselves.

**Comment by kapolos** [comment]
I don't get the error on `0.10.16`, thank you @edvald .
