### ISSUE TITLE
Feature Request: Run Helm tests from Garden

### ISSUE THREAD

**Issue by garoose** [garden-io/garden#1323]
**Feature**
It would be useful for us to be able to run a Helm test via Garden. Helm tests allow the tests they describe to run in completely identical environments to the services they're testing. This can be useful in the case of tests that themselves talk to the Kubernetes API, and therefore require a specific service account.

**Workaround**
We get around this through an _exec_ module and a shell script that calls Helm test.

**Comment by edvald** [comment]
Hey @garoose. That makes sense, I think it would make sense to do this automatically or add an option on the module type.
