### ISSUE TITLE
Garden CLI prompt can't be cleanly turned off in CI

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1324]
### Current Behavior

I installed Garden on our CI, which frequently has fresh servers. On a new server, I got a prompt about analytics. The documented way to turn the prompt off, also triggers the prompt:

```
[buildkite-agent@ip-172-16-6-43 data-depot-db-service]$ garden config analytics-enabled false
? Thanks for installing Garden! We work hard to provide you with the best experi
ence we can.
It would help us a lot if we could collect some anonymous analytics while you us
e Garden.
You can read more about what we collect at https://github.com/garden-io/garden/b
lob/master/README.md#Analytics

Are you OK with us collecting anonymized data about your CLI usage? (Y/n) 
```

### Workaround

```
echo "Y" | garden config analytics-enabled false
```

### Suggested solution(s)

Have a CI mode that disables features like this.

### Your environment

Garden version: 0.10.12

**Comment by edvald** [comment]
Hey @Eronarn . We do use a library to detect CI, but seems it doesn't always work. We will be removing this prompt soon, so the problem go away, but glad you found a workaround for the meantime.

**Comment by 10ko** [comment]
Hi @Eronarn, reading through your log looks like the CI you are using is Buildkite which should be supported by [ci-info](https://www.npmjs.com/package/ci-info), which expects an environment variable called `BUILDKITE: true`.
Is that the case? If not could you tell us more about your CI setup?
Thanks.

**Comment by Eronarn** [comment]
I was both testing the script locally and SSHed into a BK instance, and neither of those would've provided an env var. Sounds like this can just be closed then.
