### ISSUE TITLE
`garden delete environment` assumes garden-specific deployment namespace

### ISSUE THREAD

**Issue by danisim** [garden-io/garden#1326]
### Current Behavior

`garden delete environment` makes the assumption that you have a namespace dedicated to garden deployments as it tries to delete the namespace as a part of cleaning up. For our company's case, we currently deploy garden development environments to our _staging_ namespace which has other deployments that we would not want a developer with namespace delete access to accidentally tear down.

### Expected behavior

The command description that `garden delete environment` `Deletes a running environment` did not make it clear to me that the command was going to attempt to delete the deployment namespace. (I was running in a developer context without namespace access so it wasn't a big deal, but some users at our company do have namespace delete access.)

### Suggested solution(s)

We think it would make sense if the namespace was deleted as a part of this command only if it was flagged to have been created by Garden in the first place.

Thanks for your time!

**Comment by edvald** [comment]
Hey @danisim. Thanks for the feedback—I'm glad it didn't cause any harm! 

Your suggestion is on point, we should at least only clear namespaces created by Garden (with our annotation, something like that).
