### ISSUE TITLE
Garden prepends `GARDEN_VARIABLES_` to env vars from `varfile`

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1331]
### Current Behavior

If you specify a `varfile` for your environment, Garden will prepend the variables names with `GARDEN_VARIABLES_<VAR_NAME>`

So e.g, the entry:

```
DB_HOST=postgres
```

 becomes `GARDEN_VARIABLES_DB_HOST` in your runtime environment.

### Expected behavior

Garden doesn't prepend anything to `varfile` variables. 

### Reproducible example

1. Create a file called in `garden.local.env` in `demo-project` root and add:

```
FOO_BAR=BAS
```

2. Run `garden deploy`

3. Run `garden exec frontend printenv | grep FOO_BAR` and notice that it returns `GARDEN_VARIABLES_FOO_BAR`

**Comment by edvald** [comment]
This is by design. The varfiles are meant to populate Garden variables, which are not supposed to be automatically injected as environment variables of the same name. You need to explicitly insert those via the `env` key on container or exec services if you want them there.

**Comment by eysi09** [comment]
Right. My bad.

**Comment by mnpenner** [comment]
> You need to explicitly insert those via the `env` key on container or exec services if you want them there.

Do you mean in the Dockerfile or what? I really don't want to bake my secret keys into the Dockerfile and I want to be be able to easily swap them for dev and production.
