### ISSUE TITLE
Exec module test output is not captured

### ISSUE THREAD

**Issue by garoose** [garden-io/garden#1333]
## Bug
Exec module test output is not captured as a test-result, and not shown below debug level logging when run interactively. Also test failure is not shown when run interactively.

### Current Behavior

* After running an exec module test non-interactively, `garden get test-result` returns no results.
* Running an exec module test interactively shows no output and does not fail on test failure.

### Expected behavior

* After running an exec module test non-interactively, `garden get test-result` shows the results.
* Running an exec module test interactively shows the test output and informs of test failure.

### Reproducible example

See a test repo here https://github.com/garoose/garden-exec-results-test

### Workaround

Enabling debug logging when running an exec module test non-interactively (`garden test`) will both error on test failure, and show the output in the test log.

### Your environment
* `garden version`
`0.10.14`

* `kubectl version`
```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
* `docker version`
```
Client:
 Version:           18.09.7
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Tue May  7 17:57:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

(Also wanted to say I appreciate all the work you're doing with Garden and your responsiveness to issues!)

**Comment by eysi09** [comment]
Hi @garoose!

Likewise, thank you for the detailed error reports and repros. This should be an easy fix. We made some changes to the `exec` module type recently which might have caused a regression (which should not escape our tests nonetheless).

**Comment by eysi09** [comment]
Actually, I spoke a little too soon there. The `exec` module type currently doesn't have any mechanism for storing tests results. In contrast the Kubernetes provider stores tests results as ConfigMaps. This shouldn't be difficult to add though and I'll update the labels accordingly.

In the mean while, could you use the container module type as a workaround?

**Comment by garoose** [comment]
Ah okay well that explains it! We may be able to create another docker image that includes the test with the service and run it that way. We may also rewrite our test to allow access to Kubernetes in a different way (e.g. create a separate service account and pass it in via the environment). For reference our use of the exec module is related to the other feature I filed #1323.
