### ISSUE TITLE
Client-server architecture for Garden

### ISSUE THREAD

**Issue by burdiyan** [garden-io/garden#1344]
This is more of an idea or feature request than issue or anything else.

My largest frustration working with Garden is long feedback-loop for running most of the commands.

Seeing `⠹ providers                 → Getting status...` all the time at the beginning is a bit annoying, and it takes time.

My idea is that maybe if Garden needs some "state" to be "reconciled" between all the runs, it could be a good idea to architect Garden service as a persistent server that is running in the background, and CLI would be a client for this server? This way the server could keep things in memory and be more responsive to the CLI.

I don't know if you've ever considered that, and how much of a rearchitecturing this might imply. Just throwing the idea into the air basically.

This is inspired by how [Bazel](https://www.bazel.build) works.

**Comment by eysi09** [comment]
Hi @burdiyan!

Thanks for opening the issue. This actually on our internal roadmap, pretty much as you describe it. We've already started work on a few things we need in preparation for it.  

This issue is a good starting point for further discussion so I'll leave it open.

**Comment by edvald** [comment]
Yep exactly, this is what we are edging towards. We have architected with this in mind, but it adds some complexity so we're working on it gradually. 

In the meantime, we are introducing some optimizations in our next release to shorten the init time (#1303) and may take further steps in that direction alongside the client-server transition.

**Comment by burdiyan** [comment]
Yay! Good to know :) Excited to see how this will evolve. Thanks a lot for this cool project!

**Comment by vvagaytsev** [comment]
Thanks for the input @burdiyan. We're working towards the client-server architecture. Please check out the new `garden dev` command in Bonsai.
