### ISSUE TITLE
Port forward URL doesn't work after re-deploy

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1345]
### Current Behavior

After a re-deploy in watch mode, the port-forward link that Garden prints stops working (`→ Forward: http://localhost:60749 → frontend:8080 (http)`) and the page returns an empty response.

### Expected behavior

The link continues to work.

### Reproducible example

1. `garden deploy -w` in `demo-project`.
2. Open the `Forward: http://localhost:<port>...` link for, say, the frontend service
3. Change some code to trigger a re-deploy of the service
4. Try the link again and notice that it doesn't work

**Comment by edvald** [comment]
Huh. I somehow believed the underlying port-forward process would exit when the connected pod is killed. Guess we need more elaborate connection management to account for that then.

**Comment by mjgallag** [comment]
Ran into this issue today and did a little research, [here's](https://github.com/GoogleContainerTools/skaffold/issues/2523#issuecomment-513993027) how Google's Skaffold worked around it.

**Comment by olivercodes** [comment]
If nobody is working on it, I'd like to help (and make my first contribution to garden). While I work, is the community slack the best place to ask questions?

Current investigation lead me to this function:
https://github.com/garden-io/garden/blob/4fa85dce5187e2b0c2636a9861056e0a10b6d937/garden-service/src/plugins/kubernetes/port-forward.ts#L64

**Comment by edvald** [comment]
Hey @olivercodes! Sorry about the late response, been taking it easy over the holidays :P

Probably best to start by explaining the overall architecture here. 

The Garden CLI itself creates its own basic TCP proxy (see https://github.com/garden-io/garden/blob/master/garden-service/src/proxy.ts), and binds the user-facing local ports (the ones we print the CLI) as soon as we get an indication of which ports are exposed on the deployed services. Then, when the user connects to one of those ports, we call out to the `getPortForward` handler on the provider (currently just implemented on the `kubernetes` provider) to start an actual tunnel to the service port. This means that A) we don't create unnecessary tunnels on startup, while at the same the B) we keep a persistent user-facing port even if the k8s port forward needs to be replaced.

What's broken here is the reconnection when the remote service is replaced. It's actually broken in two places, both in the k8s provider (where the port-forward process stays up even though we can no longer connect through it), and the failure handling in the Garden proxy is not really implemented (https://github.com/garden-io/garden/blob/b244c8e077cac155433c50d3238b0f91485ecd89/garden-service/src/proxy.ts#L55).

I just posted #1467 which deals with a separate thing (and tbh has more to do with the introduction of the sqlite datastore) but is in the general realm of port forwarding. I'll take a quick look at this now to troubleshoot, and ping back with results :)

**Comment by olivercodes** [comment]
@edvald - no worries, I had some free time on the holidays and went poking around. 

It seems like your pr may fix this issue, happy to help test if that's more valuable.
