### ISSUE TITLE
Windows installation didn't detect my already installed Git/Docker

### ISSUE THREAD

**Issue by duizendnegen** [garden-io/garden#1354]
### Current Behavior

Running `Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/garden-io/garden/master/support/install.ps1'))` attempted to install `git`, `rsync` and `Docker` even though at least `git` and `Docker` were present on `$PATH`.

### Expected behavior

Take the already installed `git` and `Docker` binaries instead of downloading new ones.

### Reproducible example

1. install Docker in its default location
2. run the Windows Garden installation script
3. observe it trying to install Docker again

### Workaround

Downloaded the `.zip` file from `releases`, pushed it somewhere on my `$PATH`

### Your environment

Windows 10

`garden version`

```
0.10.15
```

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
I actually think we should no longer be installing Docker automatically, or at the very least make it optional in the installation script. Git and rsync are more hard requirements, but we should figure out why the script didn't detect the already installed ones.

**Comment by RichiCoder1** [comment]
:+1: For not installing automatically and just doing a dependency check/info message
