### ISSUE TITLE
Enable running garden commands from subdirectories in a project directory

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#136]
Currently you can only run from the root directory of a project. We should add a step when starting up to walk up the directory tree from the current working directory and find the closest `garden.yml` that has a `project` key.

The logic for this should probably be in the `Garden.factory()` method, since it will involve parsing `garden.yml` files.

**Comment by ellenkorbes** [comment]
Assigning this to myself. I guess it can be a good first code-related commit as I get familiar with how things work.
