### ISSUE TITLE
Improve error message when local-kubernetes cannot be initialised

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1366]
### Current Behavior

When running `garden deploy` against a `local-kubernetes` cluster which is not running I get the following error:

```sh
14:18 $ g deploy
Deploy 🚀

✖ providers                 → Error

Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to connect to Kubernetes cluster. Got error:

Cannot read property 'split' of undefined
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Failed resolving one or more providers:
- local-kubernetes
```

### Expected behavior

A better error message than `Cannot read property 'split' of undefined`.

### Reproducible example
- Stop your Docker for Desktop
- Run `garden deploy` on the `examples/demo-project`

**Comment by edvald** [comment]
I believe this has been fixed. @10ko can you confirm?

**Comment by 10ko** [comment]
Yes, this is now fixed, thanks.
Closing.
