### ISSUE TITLE
Support building garden with node 12.x/13.x

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1407]
Our current setup for developing garden only supports node `10.x.x`.

Please, migrate dependencies to node 12.x/13.x.

Known issues:
 - `fsevents 2.x.x` is needed as explicit dependency when building on MacOS on `node 12.x.x`.
 - Building with `node 12.x.x` on Linux fails.
 - When explicitely specifiying `fsevents` as `devDependency`, the build will fail on Linux

cc: @solomonope

**Comment by edvald** [comment]
The reasons for not moving to Node 12.x include lack of support from zeit/pkg: https://github.com/zeit/pkg/issues/673. It looks like we may need to fork pkg, since it doesn't appear to be actively maintained.

I'm unsure what the value is in supporting Node 12.x to begin with, so we've not prioritized it.

**Comment by khaled** [comment]
FWIW, it seems [node 12 is supported](https://github.com/zeit/pkg/compare/4.3.8...4.4.0), just not announced.  Tried it just to make sure:

```
▶ docker run -it --rm --entrypoint /bin/sh node:lts
# npm -g i pkg
/usr/local/bin/pkg -> /usr/local/lib/node_modules/pkg/lib-es5/bin.js
+ pkg@4.4.1
added 138 packages from 199 contributors in 10.064s
# echo "console.log('hello')" > index.js
# node index.js
hello
# pkg index.js
> pkg@4.4.1
> Targets not specified. Assuming:
  node12-linux-x64, node12-macos-x64, node12-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.13.1-linux-x64   [====================] 100%
  fetched-v12.13.1-macos-x64   [====================] 100%
  fetched-v12.13.1-win-x64     [====================] 100%
# ls
bin  boot  dev  etc  home  index-linux  index-macos  index-win.exe  index.js  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
# ./index-linux
hello
```
