### ISSUE TITLE
Relative, intra-repo symlink in git is skipped by Garden

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1421]
### Current Behavior

We have a repo with a relative, intra-repo symlink checked into git. The repo is named `libpy`, and the symlink is from `libpy/include` to `include`:

```
[eronarn@ip-192-168-10-243 libpy]$ pwd
/Users/eronarn/Code/libpy
[eronarn@ip-192-168-10-243 libpy]$ ls -lath ./libpy
total 12K
drwxr-xr-x  5 eronarn staff  170 Dec 11 10:24 .
drwxr-xr-x 24 eronarn staff  816 Dec 11 10:24 ..
-rw-r--r--  1 eronarn staff  655 Dec 11 10:24 __init__.py
-rw-r--r--  1 eronarn staff 3.4K Dec 11 10:24 build.py
lrwxr-xr-x  1 eronarn staff   11 Dec 11 10:24 include -> ../include/
```

This is to facilitate shipping includes via Python packaging installs, while still having them in the right place for the Makefile.

Garden detects the symlink, as with `--log-level=5` we see it in the list of synced files:

```
/submodules/libpy/libpy/__init__.py
/submodules/libpy/libpy/build.py
/submodules/libpy/libpy/include
/submodules/libpy/setup.py
```

However, the symlink is _not_ synced to the `.garden/build` directory; not rsynced from there, and not present during the Docker build. This subsequently prevents compilation. The upshot is that with the same code checked out, our Dockerfile builds with `docker build .` but not with `garden build`.

### Expected behavior

Non-Garden and Garden docker builds produce the same results.

### Additional context

I think this might have been broken by this bugfix: https://github.com/garden-io/garden/pull/1044/files

### Workaround

For now we're adding a hack to the Dockerfile, to re-copy these files rather than to copy the symlink (which is missing from .garden entirely)

### Suggested solution(s)

Garden should check whether symlinks are both relative and intra-repo, and if so, allow syncing them (since they won't present an issue for Docker).

If Garden does have to skip a symlink, this should be easily determinable when running at high log levels. Right now it shows up in the sync list file and there is no message indicating it was subsequently dropped.

### Your environment

```
0.10.15

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

**Comment by edvald** [comment]
Hey @Eronarn. This would make sense, yes. The symlinks are basically getting dropped as we sync into the build staging directory, and we don't parse rsync logs to notify if anything is being dropped (which I _think_ rsync logs). We would need a fair amount of additional logic to be able to pick which symlinks we allow, but it's worth doing.

I guess an open question would be how precisely we handle symlinks then. Couple of viable options I can see:
A) We allow relative symlinks within a _module root_, drop everything else.
B) We allow relative symlinks within a _repo root_ and resolve the symlinks when syncing, copying the actual files/dirs referenced.

The reason we can't just copy symlinks that are within the repo root but outside of the module root, is that they won't resolve correctly from the build staging directory, and they might cause further problems when e.g. syncing to the remote builder etc.

I could lean both ways tbh, just pros and cons to consider. Option A is most similar to Docker behavior, but option B allows a little more flexibility at the expense of more data to copy around.

Can we think of good enough use-cases to go for option B or should we aim for A? Am I missing a third option?

**Comment by edvald** [comment]
I opted to start with A ^

We can consider option B later if we deem it useful/necessary.
