### ISSUE TITLE
Support Rio

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1458]
[Rio](https://rio.io/) is an "Application Deployment Engine for Kubernetes" from Rancher. Support for it has come up a couple of times in our community Slack so I'm creating this issue so that we can further expand on how that might look like. 

Note that Rio is currently in beta. Here's a [link to their GitHub repo](https://github.com/rancher/rio) which also contains the docs.

**Comment by thsig** [comment]
We're not planning on adding Rio support for now, feel free to reopen if this becomes relevant again.
