### ISSUE TITLE
Garden fails to create garden-system namespace on Microk8s

### ISSUE THREAD

**Issue by GavinRay97** [garden-io/garden#1464]
This only happens for tests it seems, regular services and tasks appear to function normally.

Creating the `garden-system` namespace manually will resolve this.

![image](https://user-images.githubusercontent.com/26604994/71379560-be3b4200-2599-11ea-9562-db849b5e5b0b.png)

**Comment by eysi09** [comment]
Thanks for reporting this. Should be an easy fix.

**Comment by dsalahutdinov** [comment]
Hey! I've faced the same problem with `minikube` and `demo-project`
Seems adding namespace manually `kubectl create ns garden-system` fixed the problem
