### ISSUE TITLE
alpine install.sh

### ISSUE THREAD

**Issue by dcharbonnier** [garden-io/garden#1469]
The script install a glibc version on alpine, a quick fix :
`curl -sL https://gist.githubusercontent.com/dcharbonnier/1fb132d481856ef22ebda0240b40ce75/raw/c3b87d5e8069801bc8db96a8afe4b7362398cfde/garden-install.sh | bash`

**Comment by eysi09** [comment]
Thanks for the fix! Would you mind creating a PR for this? The install script is in the `support` directory: https://github.com/garden-io/garden/blob/master/support/install.sh.
