### ISSUE TITLE
Nice to have: Show example of telemetry sent

### ISSUE THREAD

**Issue by davestephens** [garden-io/garden#1489]
Not so much a bug, but more a nice to have. 

I'd feel more comfortable having analytics/telemetry enabled if an example of what is sent was shown in the readme. I could go digging through source and work it out but would save time if it was provided.

I'd like to help you guys out with this (as I'm sure many others would) but need to be confident I'm only sending data I'm comfortable with.

**Comment by edvald** [comment]
That makes sense! cc @10ko. We could write it up in more detail, and even potentially list what we send somewhere (at least the _types_ of events, and which metadata is included).

As a rule we never send any user-defined strings, only hashes and aggregates, and users and projects are identified only by opaque hashes or randomly generated strings. We really don't want to get any sensitive data :) But you're absolutely right, it would be good to expand a bit on all this in our docs.

**Comment by 10ko** [comment]
+1 
I agree, we can definitely do this.
As Jon mentioned we really don't want to store any personal or identifiable data, due to GDPR and other similar regulations.
I will put something more specific in the docs.

**Comment by davestephens** [comment]
Sounds good. I trust what you guys are saying, but for the more cynical amongst us it would definitely help to have an example. 

Or maybe for bonus points, a way to show what is being sent as part of debug logging perhaps? Ie `-l silly` shows the payload being fired off... (note that I haven't checked this already happens or not!)
