### ISSUE TITLE
Disable gitignore during garden build

### ISSUE THREAD

**Issue by eistin** [garden-io/garden#1492]
### Environment

I am using garden as a development environment.
I use a master project which contains the micro-services as submodules.

### Problem

I have credentials files for my micro-services that I don't want to commit, they are therefore in the gitignore files. But Garden don't allow to copy files described in the gitignore into the docker image -> `no such file or directory`.

### Solution

Disable the .gitignore and just use the .gardenignore file during garden build.

Or is there another clean way to manage this case ?

**Comment by eysi09** [comment]
You can specify which ignore-files Garden reads via the project level `.dotIgnoreFiles: []` directive. So if you do something like `.dotIgnoreFiles: [".gardenignore"]`, it will use that one and not `.gitignore`. Downside is that you might need to copy the entries in the files.

For your use case, it might be better to look at varfiles. See [this section of our docs](https://docs.garden.io/guides/variables-and-templating#variable-files-varfiles) for details.

As a more general point, it's not considered good practice to [bake secrets into Docker images](https://medium.com/@mccode/dont-embed-configuration-or-secrets-in-docker-images-7b2e0f916fdd). So using runtime secrets instead might be a better choice, [see this section of our docs](https://docs.garden.io/guides/container-modules#secrets) for more.

**Comment by eistin** [comment]
Thank you for your answer @eysi09.
I succeeded to manage the ignore files.

I understand this general point and agree with it, but I struggle to pass a firebase config file (which is json) as a secret. So I thought the correct way to do it is by passing the credential file to the container.

**Comment by eysi09** [comment]
Glad to hear it worked out. I'll close the issue.
