### ISSUE TITLE
cert-manager: add support for LE DNS-01 challenge

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1499]
As requested by @DanielKillenberger, it would be nice to add support for the Let's Encrypt DNS-01 challenge (see [challenges types](https://letsencrypt.org/docs/challenge-types/)).

From our [Slack conversation](https://kubernetes.slack.com/archives/CKM7CP8P9/p1578301815220600):

>I feel like the wildcard domains are a big part of working with garden in teams, as everyone gets their own namespace with their own subdomain.
For that reason I would see it as superb if garden would also make sure that that workflow includes the appropriate tls certificates.
It would just be very comfortable.

Given the described workflow above, the current HTTP-01 challenge garden supports is not very user friendly since it doesn't support wildcard domains.

**Comment by to266** [comment]
Bump  / +1 for this please :)

**Comment by eysi09** [comment]
We haven't prioritised this but I'll re-open and remove the stale label.
