### ISSUE TITLE
Version docs.garden.io

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#1500]
Currently any merge to master triggers an update to our documentation site. This can be confusing, since our docs always reflects latest master (essentially our _next_ release), and not the latest stable release.

We should use versioning for the docs, make the default docs view reflect the latest stable release, and allow an option to look at the _next_ docs as well. Mechanically I'm not 100% sure what the best approach is, since I haven't dug much into how Gitbook works, but I imagine this is a supported use case.

**Comment by eysi09** [comment]
It's supported but it will trigger the two Gitbook <> GitHub repo sync. At least last I checked. Basically Gitbook will have to merge their version of our docs to our upstream repo. Their version is slightly different as they reformat the .md files and add some metadata.

**Comment by edvald** [comment]
Ah. Great. Maybe we can check if that's still the case, somehow? If so, I suppose we need to defer until we migrate away from it.

**Comment by eysi09** [comment]
We now have a `master` version and a `latest-relese` version.
