### ISSUE TITLE
Better in-cluster builder garbage collection with Docuum

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1501]
Currently, users have to manually clean up space in the in-cluster registry with the `garden plugins kubernetes|local-kubernetes cleanup-cluster-registry` command.

We can make this nicer by integration with [Docuum](https://github.com/stepchowfun/docuum) which does LRU eviction of docker images. It could run as sidecar with the docker daemon.

**Comment by 10ko** [comment]
Docuum sounds great but it looks it's very early stage (first commit 9 days ago).
Maybe we could wait for it to be stabilize a bit? Is there another alternative?

**Comment by edvald** [comment]
I'm not aware of any alternatives, unfortunately. Perhaps we could integrate it under an (undocumented/internal) flag and try running it ourselves for a while?

**Comment by 10ko** [comment]
Worse case scenario I get to learn Rust and contribute to it. :)
We can try it out for sure. 👍
