### ISSUE TITLE
Feature Request: Set global CLI option defaults

### ISSUE THREAD

**Issue by parkerself22** [garden-io/garden#1523]
Hey team, really enjoying using garden so far. I've been running into this issue where the default value of `fancy` for `--logger-type` does not play nicely with the terminal in my IDE (webstorm), and I'm constantly forgetting to pass the flag to change it to `basic`, which made me think this may be a useful feature. Apologies if this functionality is available and I somehow missed it, I've gone through the docs pretty thoroughly and haven't seen it mentioned.

### What should the user be able to do
Set a default value for global CLI options. I've thought of two ways this of implementing this (though I'm not familiar with the internals of the project so I'm sure you'll have better ideas).

**Idea A**. Set the default value for a global cli option via the `garden config` command. Example: 
```
$ garden config logger-type basic
✔ Global default for CLI flag --logger-type set to 'basic'
```

**Idea B**: A `cli` key in the project configuration file. Example:
```yaml
kind: Project
name: myProject
cli:
    loggerType: basic
...
```
### Why do they want to do this
Like I mentioned above, I have an immediate need for this because remembering to pass the `--logger-type=basic` flag for every command is quite tedious. Other global options where I could see this being useful is `--log-level`, `--env`, and `--output`. 

#### Priority: Probably pretty low, though I would greatly appreciate it :)

Thanks!
Parker

**Comment by edvald** [comment]
Hey @parkerself22! That's totally valid, and we've pondered more generically supporting user-level options like this. But, part of it is actually lack of documentation and consistency in our supported environment variables. We do actually have `GARDEN_LOGGER_TYPE` and `GARDEN_LOG_LEVEL` which take the same parameters as the corresponding CLI flags.

We should both document those better, and generally support any passing global CLI options through environment variables. But I hope those two are helpful in the meantime :)

**Comment by edvald** [comment]
Also, many thanks for the well formulated request! It's great to get good context like this. Please keep the feedback coming.

**Comment by parkerself22** [comment]
@edvald thanks for the quick reply, definitely helpful! Had a feeling I was missing an environment variable option or something. Hopefully I'll find the time to contribute more than just a feature request sometime soon, this being written in typescript makes me really want to dig in!

**Comment by edvald** [comment]
Please do! We want and plan to make the whole contributor experience more accessible, but meanwhile we're very happy to assist through chat etc. If you have an idea we can give a bit of an intro, or even chat about good things to start with. Just ping here or on the Kubernetes Slack (we're on the #garden channel there).

**Comment by 10ko** [comment]
I also really liked the structure. This could maybe be turned into a feature request template.
Maybe your first PR @parkerself22? :)

If not I will take care of it in the next days. 
Again thanks for the request.

**Comment by eysi09** [comment]
For reference, there's also #309 which addresses the same concern. The idea there is to use runtime config files (e.g. `.gardenrc`) instead of the `garden.yml` config since these are often user level configuration options that you wouldn't want to check into version control.
