### ISSUE TITLE
[FEATURE]: custom port in portforwarding

### ISSUE THREAD

**Issue by alexanderaucobo** [garden-io/garden#1542]
### Background / Motivation

I need to set a custom port in the automatic port forwarding

### What should the user be able to do?

set a custom port for the portforwarding

### Why do they want to do this? What problem does it solve?

the port forward dosnt choose automatically port 80 (is configured as Service and / container port)

### Suggested Implementation(s)

In the ports section a key/value pair like: "localport: 80"

### How important is this feature for you/your team?

Crucial (Garden is unusable for us without it)
High (Not having this feature makes using Garden painful)
**Medium (Using Garden without it is mildly inconvenient)**
Low (Nice to have someday)

**Comment by eysi09** [comment]
Hi @alexanderaucobo and thanks for the issue! This should be relatively easy to support. We'd also be happy to get you started if you want to take a stab at this yourself :)

**Comment by alexanderaucobo** [comment]
Hi @eysi09 sorry for that but i cannot do this at my own. I hope i can help in future

**Comment by 10ko** [comment]
+1 I'd love to see this implemented.

**Comment by 10ko** [comment]
Being unable to choose a predefined port for the forwarding makes using specific modules very painful. In my case I want to be able to check the data in my DB and the connection parameters change at every Garden restart.
I'd like to see this prioritized and I'd be happy to make a PR if nobody else wants to/can't.

**Comment by eysi09** [comment]
Opening this one again. Also being requested through our community Slack.

**Comment by tedchang77** [comment]
Garden uses the host ip and random port (if there is a collision) for port forwarding.  It would be great if it the tool could have behavior similar to  kubefwd where you can use the service name and port defined in the k8s service definition.  here's a diagram of how it would work taken from the kubefwd documentation: 
![image](https://user-images.githubusercontent.com/2523109/117232242-c2fb4180-adee-11eb-8da6-acf9afb3ab4e.png)

**Comment by thsig** [comment]
I believe this functionality has been added since this feature request was submitted, see the reference docs here:

https://docs.garden.io/reference/module-types/container#services-.ports-.localport

Please let us know if you're aware of any limitations/problems with the current implementation and we'll take another look.
