### ISSUE TITLE
Hot-reload should respect include/exclude/.gardenignore on initial sync.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1553]
### Current Behavior

It looks like when running Garden with hot-reload enabled the entire src folder is synced on the remote pod. While `include`, `exclude` fields and `.gardenignore` file are taken into account when a change has happen, they are not when the first sync is carried on.

See this [Slack conversation](https://kubernetes.slack.com/archives/CKM7CP8P9/p1579569290023200) with @lpetre.

### Expected behavior

The initial sync respects `include`, `exclude` fields and `.gardenignore`.

### Workaround

None.

### Your environment

`garden version`: v0.11.1

**Comment by edvald** [comment]
Bumping this one @thsig, came up on Slack from @khaled.

**Comment by khaled** [comment]
I'm seeing something like this happen for one of my modules in particular, and it seems to happen on every hot reload.  I took a look at the pod logs and it looks like the rsync container is iterating through a bunch of files in `node_modules` that should be excluded per both the project level `.gitignore` and module level `.gardenignore`

Also, the last message in the rsync container log seems to indicate that more bytes are being sent that I'd expect, e.g: 
```
2020-02-27T14:49:37.298110984Z 2020/02/27 14:49:37 [30] sent 6989 bytes  received 554132 bytes  total size 171379966
```

**Comment by edvald** [comment]
Stale bot being a little eager these day. This is still on the roadmap.

**Comment by eysi09** [comment]
@thsig, this has been fixed, right?

**Comment by thsig** [comment]
Yeah, that’s right. I’ll close this now.
