### ISSUE TITLE
Bug: "garden delete service <service-name>" doesn't delete pvc when module is Helm type

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1578]
### Background / Motivation

Sometimes I want to start with a clean slate when developing a new service and sometimes residual service data might be stored in a volume the service was using. At the moment, the only way to delete the volumes (when using the `kubernetes` provider) is through `kubectl`.

### What should the user be able to do?

Whenever I run the `garden delete service <service-name>` command I would like to be able to delete any `pvc` associated with my service.

### Why do they want to do this? What problem does it solve?

See background section above.

### Suggested Implementation(s)

Implement a flag `--purge` and delegate what/how to purge to the plugins.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by edvald** [comment]
Hmm. What situation are you running into when a volume is not being deleted with the current setup?

**Comment by 10ko** [comment]
I am deploying a postgres db (very similar to the one in the vote-helm example).
Deleting the service does not delete the pvc. 
Maybe is a misconfiguration on my side?

**Comment by edvald** [comment]
Ah so the Helm chart isn't cleaning up its resources... Why am I not floored with surprise. Ok, I'd actually qualify that as a bug. Maybe it's something to do with how we call the uninstall command, maybe it's the Helm uninstall command not doing what's expected.

**Comment by 10ko** [comment]
And bug it is. :)

**Comment by edvald** [comment]
👍

I btw have had my fair share of Helm lately, so I'll patiently wait for someone else to tackle this 😬 Doesn't look like we're doing anything unusual with respect to `helm uninstall`, so it's probably something deeper down the rabbit hole.

**Comment by jfri3d** [comment]
This is most likely a helm issue and not related to garden. Two things come to mind - finalizers and pvc reclaim policy. 

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain
