### ISSUE TITLE
Helm modules deletes the build folder when trying to access logs through the dashboard.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1583]
### Current Behavior

From Slack user Yann Irbah:

> :wave: Hi there. I (finally) started to add Garden to one of our new projects and I have a weird behavior. Everything was working fine with simple container modules. Then I started using Helm modules and every time I try to access logs through the UI, it deletes the `build` folder for the modules in the `.garden` directory and start looping with the following error `.garden/build/blueprints-chart/garden-values.yml: no such file or directory` (which makes sense since the directory is empty at this point).

Link to [discussion](https://kubernetes.slack.com/archives/CKM7CP8P9/p1581085718213500).

**Comment by l0ck3** [comment]
I'm currently creating a demo project to reproduce the issue. I'm gonna link it here if it can help.

**Comment by l0ck3** [comment]
https://github.com/l0ck3/demo-project-helm
