### ISSUE TITLE
Helm module not apply custom values files over chart defaults.

### ISSUE THREAD

**Issue by davidjeddy** [garden-io/garden#1642]
## Bug

Per https://github.com/garden-io/garden/issues/1638 the Helm module now includes custom_values.yaml into the ./.garden/build/{module name}/ directory. After deploying the module values from said custom_values.yaml are not applied over the Helm charts default values.

### Current Behavior

Custom Helm chart values not applied over default values.

### Expected behavior

Overwrite Helm chart default values w/ specified custom values

### Reproducible example

- Using MariaDbb-Galera cluster
- Create custom values.yaml
- Include custom values.yaml in Garden module
- Build and deploy

![Screenshot from 2020-02-25 11-37-23](https://user-images.githubusercontent.com/6232455/75267263-065a2900-57c4-11ea-94f7-970072a8c7c1.png)

### Workaround

none known

### Suggested solution(s)

Apply custom values.yaml to .rendered.yaml AFTER the default chart values have been rendered

### Additional context

n/a

### Your environment

```sh
❯ garden version &&
> kubectl version &&
> docker version
0.11.4
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Thank you for the time and effort, much appreciated.

**Comment by edvald** [comment]
This is actually how it's meant to work already... I wonder what's failing here. How are you specifying the `valueFiles` field?

**Comment by davidjeddy** [comment]
In this use case we are not using `valueFiles`. Only the `include: [...]`.

**Comment by edvald** [comment]
Hey @davidjeddy. So, I was trying to reproduce this, and then it occurred to me to check whether the intended/designed behavior matches your expectations.

The precedence order is as follows (in increasing order of precedence, i.e. last is preferred):

1. The chart default `values.yaml` file
2. Any files specified in `valueFiles` in the `garden.yml`
3. The values specified on the `values` field in `garden.yml`

As far as I can tell, that's working as expected. If that's not what you're finding, it'd be useful to see the `garden.yml` to see what's going on.

**Comment by edvald** [comment]
Perhaps the confusion relates to using the filename `values.yaml`, because that is what Helm uses by default, and therefore has the lowest precedence.

**Comment by edvald** [comment]
Ah now I see. So, the issue that we fixed (#1637) was that when you specified `valueFiles` they weren't automatically included in the `include` field. That's been fixed and released, so you just need to specify the `valueFiles`  field, but you needed to specify that one either way, otherwise the file won't be picked up. Let me know if that does the trick.

**Comment by davidjeddy** [comment]
If I understand correctly both `include: []` AND `valueFiles: []` must be set in order to over ride Helm Chart default values?

**Comment by davidjeddy** [comment]
Ok, got it to work. For anyone who finds this later:

```yaml
# for any and all files that should be considered part of the module
include: [
  reference_values.yaml
]
...
# HELM value overrides
valueFiles: [
  reference_values.yaml
]
```

So the Helm value over ride must first be part of the module (`include`) AND stated as the over ride (`valueFiles`). 

This now makes sense to me. :bulb:

**Comment by edvald** [comment]
Glad it worked out! As of next release the additional `include` field is not necessary btw, that was a bug on our side.
