### ISSUE TITLE
[FEATURE]: Allow setting resource requests on the container module

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1646]
### Background / Motivation

Currently you can only set resource limits on container modules. But some users have requested setting resource requests as well.

Feels like this is generic enough to belong on the `container` module. For example docker swarm has a resource `reservations` field.

### What should the user be able to do?

Set resource requests on a container module, similar to resource limits.

### Why do they want to do this? What problem does it solve?

From community Slack:

> For doing things like running tests in CI with garden, we might want to make sure we have the correct reservations

### Suggested Implementation(s)

Same as for resource limits.

**Comment by eysi09** [comment]
Also mentioned to bump the default to 100m.

**Comment by mitchfriedman** [comment]
Can we also be able to change the requests on tests/tasks as well?

We have some giant webpack builds and want to make sure they complete in a reasonable amount of time and don’t run out of memory.
