### ISSUE TITLE
[FEATURE]: Ability to pull images from in-cluster registry

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1647]
### Background / Motivation

The ability to run pull images from the in-cluster registry. This has come up a few times in conversations for users.

### What should the user be able to do?

Run `garden plugins kubernetes pull [module-names]` 

### Why do they want to do this? What problem does it solve?

E.g. when running a project locally but re-using images built in the remote environment. 

From Slack conversation:

> there’s a good chance that at times, pieces of the stack would be run locally. For example, a frontend engineer might want to pull down the backend image (from the cluster repository) and run that backend service locally and do local development on the frontend service (faster rsync of changes, etc)

### Suggested Implementation(s)

Use the `publish` functionality which basically does the same.

**Comment by mitchfriedman** [comment]
This got added here https://github.com/garden-io/garden/pull/1681
