### ISSUE TITLE
undefined is not a function on most commands

### ISSUE THREAD

**Issue by wojtkowiak** [garden-io/garden#1651]
### Current Behavior

Just started learning Garden yesterday. Got to the point where I created project and started building first module. The `garden build` command was running without any problem. I mean it was at least doing something. Today I have this, and almost any command end with this error. The only thing that happened on my mac is that CleanMyMac was run today so my suspicion is it might have cleaned some temp files garden depends on.

![image](https://user-images.githubusercontent.com/8668306/75542460-28e87e00-5a20-11ea-97f7-e55638985ff6.png)

```
undefined is not a function
TypeError: undefined is not a function
    at Object.<anonymous> (/snapshot/project/garden-service/tmp/dist/build/src/config/project.js:0)
    at Generator.next (<anonymous>)
    at /snapshot/project/garden-service/tmp/dist/build/src/config/project.js:0
    at new Promise (<anonymous>)
    at /snapshot/project/garden-service/tmp/dist/build/src/config/project.js:0
    at Object.resolveProjectConfig (/snapshot/project/garden-service/tmp/dist/build/src/config/project.js:0)
    at Function.<anonymous> (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
```

```
 ✘  omega@Omega  ⎈ docker-desktop  ~/projects/coin   master ± garden publish
undefined is not a function
 ✘  omega@Omega  ⎈ docker-desktop  ~/projects/coin   master ± garden scan
undefined is not a function
```

### Expected behavior

Garden running normally.

### Reproducible example

I do not think I can provide one. Installed garden on other machine, works perfectly fine. But on this one, I have tried deleting `.garden` both in the project and `~/.garden`. Reinstalled garden with brew. Nothing helped.

### Your environment

`garden version` `0.11.5`

`kubectl version`
```
lient Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
Hey @wojtkowiak. That is definitely odd. Might have something to do with the specific project config though (like something not parsing right and then bad error handling on our side), not sure. Do the commands work for e.g. one of our example projects?

**Comment by wojtkowiak** [comment]
@edvald sorry, should've tried that one before bothering you. It worked in the demo project. 
Found the cause of this... Created a blank project and started apply changes for the garden.yml I have.
Somehow I accidentally deleted the hypen here:
```yml
environments:
  name: local
```
```
garden validate
undefined is not a function
```
after fixing:

```yml
environments:
  - name: local
```
```
garden validate
Validate ✔️
```
Not sure if you are doing and yml schema validation but in this case it would have saved me an hour wasted on my stupidity ;)

**Comment by edvald** [comment]
I see this as our fault :) that error message is not at all helpful, we will fix that!

**Comment by wojtkowiak** [comment]
Yeah, agree, an error pointing me to `garden.yml` could help ;) but you just can't be prepared for all that sh*tty input a user (especially developer) can provide 🙂 
Thanks!
