### ISSUE TITLE
Issues with storing test and task results

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#1652]
### Current Behavior

Currently, large log outputs can cause exceptions when trying to store test results. We already made a half-way fix by truncating the log output, but we don't do that for the provider-specified outputs, so the issue can still come up in some scenarios.

We also do not currently store test and task artifacts as part of the test/task results. This can lead to unexpected issues, especially in pipelines and automated workflows.

### Expected behavior

The full test/task logs should be stored and then retrieved when getting cached results. Same goes for artifacts.

### Reproducible example

Have a `container` test command return a very large (more than 1MB) response. An error will be thrown.

### Workaround

Reduce the log output from the affected commands, if possible.

### Suggested solution(s)

We should store results, logs and artifacts in a PVC, that's mounted as part of the test/task container.

### Your environment

Latest Garden master.

**Comment by lucas-sonnabend** [comment]
I'm not sure whether it is directly related to this bug, but one weird effect we are seeing is that if you define artifacts for a test, then the test output is being truncated

**Comment by edvald** [comment]
That is sort-of connected, but might be worth looking at specifically since there is a partially different code path used when artifacts need to be copied after a task/test run.
