### ISSUE TITLE
[FEATURE]: module docs config field

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1668]
### Background / Motivation

Me and @eysi09 were discussing it would be cool to have a way for specifying in the module `garden.yml` a path pointing to the documentation for that module and make it accessible in the dashboard or in the cli.
This could make your life easier when, for example, you are breaking the integration tests for a module you didn’t write or you are curious about how to run a specific module but you don’t want to go through the entire repo to look for docs.
### What should the user be able to do?

Up for discussion but ideally specify a `documentation: path/to/docs` in the module `garden.yml`

### Why do they want to do this? What problem does it solve?

See above.

### Suggested Implementation(s)

As @eysi09 suggested we could start simply exposing a link to a `README.md` file if present in the root.
If the users like it we could add more complex cases like point to documentation urls, wiki pages, etc. 

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Just FYI, we still have plans for building something like this. We've been referring to it internally as "stack docs" (definitely not the final name). 

But this ticket is quite dated and we can write up a new one once we properly schedule this.
