### ISSUE TITLE
Cluster initialise failed with kaniko and external registry

### ISSUE THREAD

**Issue by mitchfriedman** [garden-io/garden#1672]
## Bug

When initialising a fresh cluster with garden services and `kaniko` in cluster building and **an external docker registry (ECR),** we got an error messaging saying garden failed to communicate with the docker daemon.

We tried to get around this by changing our in cluster builder to `cluster-docker` to initialise the docker daemon. The docker daemon failed to be brought up because the proxy failed to resolve the in cluster registry.

### Current Behavior

Garden fails to initialise the cluster with this setup.

### Expected behavior

The proxy failing to talk to the registry should be ignored since we don't need the in cluster registry.

### Reproducible example

Our provider configuration looked like:

```
    buildMode: kaniko
    deploymentRegistry:
      hostname: "${var.AWS_ACCOUNT_ID}.dkr.ecr.${var.AWS_REGION}.amazonaws.com"
```

### Workaround

We changed the buildMode to `cluster-docker` and removed the `deploymentRegistry` temporarily. Then we could add these both back in later.

### Suggested solution(s)

The failing proxy connection should be ignored/not checked, and when using kaniko, we shouldn't need a docker daemon running in the cluster. Unsure why garden failed with this.

### Your environment

0.11.5

**Comment by edvald** [comment]
I'm wondering if this has been fixed between the last release and current master. Could you see if this issue remains with the edge release?

**Comment by edvald** [comment]
If it is still an issue, an error log would be super useful, to see where the actual error is emitted.

**Comment by mitchfriedman** [comment]
We are actually building from master/source, so this is still an issue. Unfortunately our cluster has been initialised now and we are running some tests, so we can't re-initialise for the moment. Someone else in slack has seen this as well (https://kubernetes.slack.com/archives/CKM7CP8P9/p1583576758306400), so perhaps they can paste their recent error report. We can try next week to get an error message for you.
