### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#168]
It would be super nice to have a homebrew package, and to automate the release process along with the npm release. Especially since we do have peer dependencies like git and rsync, that we can't bundle, and we're likely to add more of those if anything.

**Comment by Deepakkothandan** [comment]
@edvald  I will give it a try on the weekend. I have **some hotspot** connectivity 😄

**Comment by edvald** [comment]
Ah, I just wrapped it up! It touched on a few things I wanted to fix along the way. But I appreciate that! 

Do you have any experience with Debian packages? We'd love to have that in place as well, but there I'm rather lost myself :P

**Comment by Deepakkothandan** [comment]
@edvald yep, I can work on that.. is there any other distro you are targeting too ?

**Comment by edvald** [comment]
Thanks! I'm not sure yet which distros are most relevant to have packages for, so I figure Debian/Ubuntu makes sense to start. I'll create a separate issue for that.
