### ISSUE TITLE
garden build should not create namespaces in kubernetes cluster

### ISSUE THREAD

**Issue by khaled** [garden-io/garden#1686]
### Current Behavior

`garden build` creates k8s namespaces for projects despite the fact that its not going to deploy.

### Expected behavior

Namespaces should not be created.  Should not modify the cluster except for cases where there is an in-cluster build, etc.

### Reproducible example

Run `garden build` on any project

### Your environment

`garden version`
`0.11.4`

**Comment by khaled** [comment]
can this be re-opened?

**Comment by edvald** [comment]
Yep, sure thing!
