### ISSUE TITLE
Garden fails to include src files for Dockerfiles with base images

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1707]
### Current Behavior

If a user doesn't specify the `include/exclude` field in a `container` module, Garden will try to guess it from the Dockefile. However, if the Dockerfile doesn't have any COPY/ADD directives, for example because they're specified in a base image Garden won't pick up the files.

### Expected behavior

Garden should include the necessary build context.

### Reproducible example

Go to the `base-image` example, remove the `include` from the `backend/garden.yml` file and run `garden build`. 

### Workaround

Add an include to the module in question.

**Comment by edvald** [comment]
I'm not sure I understand. Why would you want files from the base image build context to be used in the build context for an image that references it?

**Comment by edvald** [comment]
Ah I see now. This specifically refers to using `ONBUILD ADD/COPY`. You're right, we have not considered that case. I would argue that using ONBUILD is not very good practice in general, but that's just an opinion, and we should investigate how we could possibly work this out.

I'm not sure it's even feasible though :/

**Comment by edvald** [comment]
In the meantime, I suggest the base-image example should not use the ONBUILD directive
