### ISSUE TITLE
Terraform apply-root | apply-module commands can't receive input

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1709]
### Current Behavior

If you run `garden plugins terraform apply-root | apply-module`, the command will ask for input from the user. However, the logger won't register the input and the command eventually times out.

### Expected behavior

The user should be able to type in the needed input.

### Reproducible example

Run `garden plugins terraform apply-root` in the `terraform-gke` example.

### Workaround

Run the command with `-auto-approve`:

```
garden plugins terraform apply-root|apply-module -auto-approve
```

or call Terraform directly with:

```
~/.garden/tools/terraform-<VERSION>/<HASH>/terraform apply -var-file garden.tfvars.json
```

in the directory where the Terraform resources are defined.

### Suggested solution(s)

Calling `logger.stop` should prevent this.

**Comment by edvald** [comment]
Hmm. Why is using `logger.stop()` necessary when using the basic logger? I had no idea that was the case, and I feel like I tested this actually... Any chance you're overriding the default logger type, e.g. with an env variable?

**Comment by eysi09** [comment]
You're right, this shouldn't happen with the basic logger. And I'm pretty sure I was using it.

**Comment by eysi09** [comment]
@edvald, you were looking into this, right?
