### ISSUE TITLE
broken link on the garden.io website

### ISSUE THREAD

**Issue by HanEmile** [garden-io/garden#1721]
### Current Behavior

The "Install Garden" link at the bottom of the [garden.io](https://garden.io/#keep-in-touch) page links to [https://docs.garden.io/installation](https://docs.garden.io/installation). This results in getting a message "page not found".

### Expected behavior

The link should (in my opinion) point to [https://docs.garden.io/basics/installation](https://docs.garden.io/basics/installation), as it is the page that describes how to install garden.

### Reproducible example

[https://garden.io/#keep-in-touch](https://garden.io/#keep-in-touch)

### Workaround

A workaround would be to directly go to the second step (looking through the documentation) to find the page describing how to install garden.

### Suggested solution(s)

Fix the link as described in the expected behavior section above.

### Your environment

The garden, kubectl and docker version is not relevant in this scenario.

---

### Additional

Is there a repo containing the source of garden.io website? This issue doesn't really address the source of garden itself, but I thought there might be people here that might be able to fix this or route this information in the right direction.

**Comment by eysi09** [comment]
Thanks for flagging this @HanEmile! The repo for the website is actually private but I just updated the links. 

Let us know if you have an other questions/issues!
