### ISSUE TITLE
[QUESTION] Use across multiple repos

### ISSUE THREAD

**Issue by katlimruiz** [garden-io/garden#1724]
Hi

So I have a question. My company has many microservices each living in their own git repo, with own pipeline definition.

How can we use Garden for this scenario? Should I create another repo for my garden environment, or this does not work and I'm forced to do mono-repo?

Thanks

**Comment by 10ko** [comment]
Hi @katlimruiz.
We at Garden prefer the mono-repo architecture but we have multiple mechanisms in place to allow your use case. :)
Specifically you can use remote sources to structure your Garden project. 
We support two types:
- **Remote source**: A repository that contains one or more Garden modules and their corresponding garden.yml config files.
- **Remote module**: The source code for a single Garden module. In this case, the garden.yml config file is stored in the main project repository while the module code itself is in the remote repository.

This should give you enough flexibility to either create a separate Garden project repo or configure it in an existing main repository, while importing all the different module/repos in.

Please take a look at the [remote sources](https://docs.garden.io/advanced/using-remote-sources) documentation and let us know if you need any more help!

Also, in case you don't know, we are in the [Kubernetes slack](https://chat.garden.io), in the #garden and #garden-dev channels, if you ever need faster response time. :)

**Comment by 10ko** [comment]
Hi @katlimruiz, I assume you managed to configure your project and I will close the issue.
Feel free to re-open if you have any more questions!
🌸
