### ISSUE TITLE
install.sh script doesn't work properly for Alpine Linux

### ISSUE THREAD

**Issue by netaskd** [garden-io/garden#1730]
## Bug
An install script has a string for detect alpine linux:
https://github.com/garden-io/garden/blob/8f6d3c25185669a8e6ece36e01933f6d78aca723/support/install.sh#L36

and tries to download https://github.com/garden-io/garden/releases/download/v0.11.9/garden-v0.11.9-alpine-amd64.tar.gz that doesn't exists on he repo.

**Comment by eysi09** [comment]
Hi @netaskd! 

Thanks for pointing this out and sorry for the late reply. This PR addresses the issue: #1750 

In the meantime, you can find the Docker image for the Alpine build here: https://hub.docker.com/repository/docker/gardendev/garden
