### ISSUE TITLE
[QUESTION] opposite of `garden dev`

### ISSUE THREAD

**Issue by wojtkowiak** [garden-io/garden#1734]
I might be confusing things or have the wrong approach so sorry it that's the case.

Is there a command that tears down the env instead of setting things up like `garden dev` does?
So I am getting into a lot weird situation where I have kubernetes errors which basically disappear when I delete everything and just set up local cluster from scratch. 
So far I've been using `garden del env` to clear things, and verify if just new `garden dev` will pass.
Is there a better way?

Also `garden del env` stopped working for me as soon I started using the `persistenvolumeclaim`, I can see during deleting `No delete service handler available for module type persistentvolumeclaim` and the PersistentVolume I have declared as k8 yml (module type `kubernetes`) just hangs indefinitely presumably because the volume is still claimed. After `kubectl delete pvc my-pvc` another try of `garden del env` passes.

**Comment by eysi09** [comment]
Hi @wojtkowiak 

You're right that `garden delete environment` is basically the opposite of `garden dev`. What Kubernetes errors are you getting? Perhaps this can be addressed at the root.

As for the `persistentvolumeclaim`,  that sounds like a bug. Would you mind filing an issue for that?

**Comment by wojtkowiak** [comment]
> You're right that garden delete environment is basically the opposite of garden dev

Thanks for answering, so good to know I was not using anything in a weird way 🙂 

> What Kubernetes errors are you getting? Perhaps this can be addressed at the root.

Well I do not want to bother you with those as it was mostly the case when I was running `garden dev` while creating new k8 ymls and those were applied automatically while I was still changing them. I just run into situations few times where kubernetes was throwing errors at me mostly about inability to update stuff so it's rather me being lame at devops ;) I won't hesitate to file a bug if I have something that I run into consistently. 
 
> As for the persistentvolumeclaim, that sounds like a bug. Would you mind filing a separate issue for that?

Will do, this issue can be closed then. Thanks once again!
