### ISSUE TITLE
Dashboard on mac produces javascript error resulting in a blank white page

### ISSUE THREAD

**Issue by terralab** [garden-io/garden#1738]
### Current Behavior

when visiting http://localhost:9777/ on mac a javascript error results in a blank white page

### Expected behavior

Dashboard should render properly without JS errors
### Reproducible example

On Mac OS Catalina 10.15.4
when visiting http://localhost:9777/ 
Firefox 74.0 produces SyntaxError: invalid regexp group
Safari 13.1 produces SyntaxError: Invalid regular expression: invalid group specifier name
Result: a blank white page

Firefox 74.0 on Windows does not have this problem

### Workaround

Use Chrome on Mac

### Your environment

garden 0.11.9
On Mac OS Catalina 10.15.4
Firefox 74.0 
Safari 13.1 
Chrome 80.0.3987.149

used command `garden dev` and `garden serve`
both have same behavior

**Comment by 10ko** [comment]
Hi @terralab, thanks for reporting this, it indeed looks like a bug.
As a temporary workaround, I'd suggest using Google Chrome if possible.
We will work on a fix asap. 

Thanks,
Emanuele.

**Comment by kdelorey** [comment]
I'll also report that this issue isn't specific to macOS. I also get it on other *nix environments (Manjaro Linux). I assume it's browser related and not OS releated.
