### ISSUE TITLE
Artifacts are not copied with "run test" command

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1739]
### Current Behavior

Garden doesn't copy artifacts when in interactive mode. This is the default for the `run test` command.

### Expected behavior

It should copy the regardless of whether or not it is in interactive mode.

### Reproducible example

Run `garden run test <module-name> <test-name>` in a project that stores artifacts and notes that they're not copied to the `.garden` dir.

### Workaround

Use `garden test` or `garden run test <module-name> <test-name> --interactive false`.

**Comment by lucas-sonnabend** [comment]
duplicate of this issue: https://github.com/garden-io/garden/issues/1475

**Comment by vvagaytsev** [comment]
Closing this. Feel free to reopen it if it's still an issue in Bonsai.
