### ISSUE TITLE
[FEATURE]: Have garden build check some remote repo first and fall back to building

### ISSUE THREAD

**Issue by arlyon** [garden-io/garden#1754]
### Background / Motivation

I am developing features on my machine. As I work, the images are being published to docker. I need some help somewhere (or my branch gets rebased onto, etc) so a colleague switches to my branch and runs `garden dev`. It would be amazing if they could just pull my prebuilt containers and keep working, rather than wait for a lengthy build process to complete.

### What should the user be able to do?

When running `garden {build,dev,deploy}` the build engine should check docker hub (or whatever repository is being used) first, avoiding expensive builds. Currently, if you run `garden publish` followed by `docker images prune -a` and then publish again, garden doesn't realise that the images are already available.

### Why do they want to do this? What problem does it solve?

Speedy rebases for other teams who depend on your containers but don't modify them (say, the frontend team) won't have to rebuild the containers that have already been built and published.

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it. We are a small team working on a rust server and the compile process takes around half an hour from scratch (if the dependencies have to be recompiled) which slows down development quite a lot.

**Comment by edvald** [comment]
Hey @arlyon! Thanks for the request, great to get all that context. Some of these concerns can actually be solved by using [in-cluster building](https://docs.garden.io/guides/in-cluster-building). Have you explored that?

Using a remote registry as a cache source for local dev setups for sure makes sense as a feature, just hasn't been prioritized since many of our users use the remote cluster setup.

**Comment by ultimatemonty** [comment]
our use case is very similar. We have a remote source with a Dockerfile that also has every master build published to our internal docker repo. Most devs would want to just run the service and using the pre-built image would speed up `garden dev` startup pretty significantly (~400s for building the module in our case).

A few devs would want to build the source (maybe using `garden link`) as they worked on the service.

Ideally there would be something under the `build` config in the remote source/module that specified if the source should be built or if it should just use the specified image instead. Something like the following would be great:

```
kind: Module
type: container
name: my-service
image: url/to/image
build:
  buildFromSource: false
services:
  - name: my-service
```
