### ISSUE TITLE
[FEATURE]: Make Stack Graph elements draggable in dashboard

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1755]
### Background / Motivation

It would be nice if I could drag around the elements of the Stack Graph in the Dashboard.
Sometimes the graph is very messy in some parts and it might get confusing to see what is linked to what.

### What should the user be able to do?

Drag the Stack Graph elements around
### Why do they want to do this? What problem does it solve?
See above

See above
### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by edvald** [comment]
I agree that it can get quite messy at times. I wonder if making nodes draggable would make sense, or rather to revisit how we do the rendering/visualization to accommodate larger and more complex graphs.
