### ISSUE TITLE
Fullscreen logger requires neo-blessed/xterm, fails

### ISSUE THREAD

**Issue by GavinRay97** [garden-io/garden#1785]
### Current Behavior

![image](https://user-images.githubusercontent.com/26604994/78831913-6db8ea80-79b8-11ea-8426-5fddf6272bfa.png)

### Your environment

Ubuntu 19.10, Microk8s, Garden v0.11.11

**Comment by edvald** [comment]
Thanks for reporting @GavinRay97. Seems this is the case on linux, not on Mac, so we had missed it. Plus this is one of the reasons we're easing into this new renderer, gotta make sure it actually works across different setups. We'll look into it.
