### ISSUE TITLE
[FEATURE]: k3s/k3d guide

### ISSUE THREAD

**Issue by GavinRay97** [garden-io/garden#1790]
Not a big deal, but I attempted to help someone set up Garden on `k3s` and ran into a few issues.

Would be cool if someone who has accomplished this before might be able to comment and then we could assemble a guide from it.

In the few hours I spent debugging, these were the two issues that seemed to break things:

- `k3s` deploys Traefik by default as a load-balancer/ingress. When `garden` attempts to deploy or dev, it fails on the NGINX step due to conflict with Traefik (ports in use). You can solve this either by:
	- Setting `setupIngressController: false` in the project-level `garden.yml` (though I don't know if this actually works to forward the service Ingress URLs, because I never got if fully running)
	- Disabling Traefik in the `k3s` server setup:
		- `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik" sh`
	- Or if already installed:
		- `k3s server --no-deploy traefik`

- After this, it will fail due to trying to pull local images from `docker.io` instead of the registry. It seems like a lot of work but possible to enable local registries in `k3s`, but in `k3d` there is a flag to enable local registry:
	- https://github.com/rancher/k3d/blob/master/docs/registries.md#using-the-k3d-registry
		- `k3d create --enable-registry`
		- edit `/etc/hosts` to include `127.0.0.1 registry.local`

It seems by default this uses port `5000`, on Microk8s my local registry is port `32000` and that's what Garden pulls from when building and deploying. I don't know if Garden gets that from the cluster, or if it needs to be `32000`.

This was as far as I got.

**Comment by eysi09** [comment]
Thanks for writing this up @GavinRay97!

This is a great starting point for a guide, and useful on its own until it's ready.

**Comment by johnlane** [comment]
Hope it's ok to "wake up" this issue! 
I'm trying to deploy garden in k3d and having similar troubles getting it to work. Any more information about how to get it to work would be great.

**Comment by johnlane** [comment]
Re the pulling local images. If you want to pull from the local docker images one way to achieve this is to run `k3s` with `--docker` so it uses the local Docker instead of its own internal containerd.
