### ISSUE TITLE
The Global Options section in the Commands docs is not correctly formatted.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1791]
### Current Behavior

The [Global Options](https://docs.garden.io/reference/commands#global-options) section in the Commands documentation doesn't render correctly, see screenshot below.
Many thanks to @lucas-sonnabend for pointing this out in our Slack channel.

![Screenshot 2020-04-15 at 13 37 28](https://user-images.githubusercontent.com/2706375/79333159-50d36880-7f1e-11ea-91c4-5927edf48bec.png)

### Your environment

`garden version`

`kubectl version`

`docker version`

**Comment by edvald** [comment]
Fixed by #1901
