### ISSUE TITLE
Filenames with brackets (e.g. [foo].bar) are not synced to garden's build folder

### ISSUE THREAD

**Issue by musyyy** [garden-io/garden#1818]
### Current Behavior

Having filenames with brackets in the name like `[foo].bar` are ignored by the `garden build` command and not synced to the `.garden/build/submodule` folder. 

### Expected behavior

Files with brackets `[foo].bar` should be synced.

### Reproducible example

It is reproducible with any garden example with project files like the [hot-reload example](https://github.com/garden-io/garden/tree/master/examples/hot-reload)

#### Steps with [hot-reload example](https://github.com/garden-io/garden/tree/master/examples/hot-reload)

1. Open the `hot-reload` example folder in your terminal
```
cd your/garden/examples/hot-reload
touch "node-service/[foo].bar"
```
2. Run `garden build` and check if the file `[foo].bar` exists in `.garden/build/node-service`
```
garden build
ls -la garden/build/node-service
```

### Workaround

I didn't find a workaround so far.

### Suggested solution(s)

I guess the sync function in

https://github.com/garden-io/garden/blob/334ae831b13caad4c5607eab645ddb529b6253a9/garden-service/src/build-dir.ts#L189

ignores filenames with brackets when executing the sync. 

### Additional context

The React framework NextJS is configured with filenames having brackets in it (e.g. `[slug].js`). When we tried to build the NextJS app with garden we ran into the error of missing files because it weren't synced to garden's build folder. 

[About NextJS](https://nextjs.org/docs/routing/dynamic-routes)

### Your environment

MacOS Catalina

`garden version`
0.11.12

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
`docker version`
19.03.8

`rsync --version`
3.1.3

**Comment by eysi09** [comment]
Hi @musyyy!

Looks like it's actually `rsync` that's not handling files with brackets. I'm not very familiar with NextJS but does this solve your issue: https://github.com/zeit/next.js/issues/8013?

I also noticed some other issues around the internet where libraries were struggling with the square bracket file names.

**Comment by musyyy** [comment]
Hi @eysi09,

https://github.com/zeit/next.js/issues/8013 is more a url problem and does not solve my problem with garden and rsync.

Do you have a reference saying that `rsync` is not handling files with brackets? Because if I run the following in my terminal

```
rsync ./\[foo\].bar dest/folder
rsync "./[foo].bar" dest/folder
```

the files get copied.
