### ISSUE TITLE
Kaniko builds that fail are treated as success

### ISSUE THREAD

**Issue by mitchfriedman** [garden-io/garden#1821]
### Current Behavior

If you run a build using kaniko and the build fails (non-zero exit code from the build itself), garden treats this build as a success.

For example, if you have a module that depends on another module for a `COPY` instruction, the second will timeout as the first build did not succeed.

### Expected behavior

The build failure should propagate as a true failure and anything depending on it should not succeed.

### Reproducible example

sorry, no example :( 

### Workaround

You wait for the timeout.

### Suggested solution(s)

Parse the output or check the exit code from kaniko.

### Additional context

Nothing else extra.

### Your environment

eks

**Comment by eysi09** [comment]
@mitchfriedman, is this still an issue?

**Comment by mitchfriedman** [comment]
> @mitchfriedman, is this still an issue?

Yeah, [here](https://github.com/garden-io/garden/pull/1938) is the fix
