### ISSUE TITLE
[FEATURE]: Support Mercurial

### ISSUE THREAD

**Issue by mnpenner** [garden-io/garden#1822]
### Background / Motivation

I use Mercurial instead of git.

### What should the user be able to do?

Be able to use garden w/out git.

### Why do they want to do this? What problem does it solve?

Allow users to use other VCSs.

### Suggested Implementation(s)

The only thing garden seems to need/want is that .gitignore file, unless maybe it's trying to use git to detect the project root? But there's already a garden.yml file it can use if it checks for `kind: Project`.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by edvald** [comment]
Hey @mnpenner. Garden relies quite a lot on version control, to resolve source files, versions, ignore files etc., so it's not just about the `.gitignore` files. There is an internal abstraction to make it feasible to support other VCSs as well, but it's not a common request so I doubt we'll get around to that anytime soon, unless some big customer comes in with that requirement :)
