### ISSUE TITLE
Don't ignore files from docker's COPY operation from .gitignore

### ISSUE THREAD

**Issue by mnpenner** [garden-io/garden#1823]
### Current Behavior

I was trying to `COPY` my PHP `vendor` directory into my container in a Dockerfile, but it kept giving errors. I think garden was somehow intercepting and skipping those files because I had `/vendor` in my `.gitignore`

### Expected behavior

I don't even know it's possible for garden to intercept such things. Isn't that all handled by Docker?

I don't want to check `vendor` and `node_modules` into version control but I don't see why that should preclude me from copying those files into my container.

### Reproducible example

Available upon request.

### Workaround

I think just adding `dotIgnoreFiles: [.gardenignore]` to your project garden.yml per [the docs](https://docs.garden.io/guides/configuration-files#ignore-files) should do it. I just deleted my .gitignore file because I'm not actually using git.

### Suggested solution(s)

Remove `.gitignore` from the defaults. I think it's unintuitive.

### Additional context

You might have to wait for the next major release to do this because it'd be BC breaking. I see you've got a `garden migrate` command in there too? Can probably use that to add `dotIgnoreFiles: [.gardenignore, .gitignore]` to people's project yaml so as to not break them.

### Your environment

`garden version` 0.11.13

`kubectl version` Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

`docker version` 19.03.8

**Comment by edvald** [comment]
Hey @mnpenner. We actually already have plans to change the default behavior in 0.12, to just look for `.gardenignore` files and not `.gitignore` files. Which is to say, we agree that it is unintuitive. A bit of a legacy design artefact that we need to shake out.
