### ISSUE TITLE
Port-forward for Helm charts only works when there is only a single K8s service with the same name as the module

### ISSUE THREAD

**Issue by petr-motejlek** [garden-io/garden#1827]
### Current Behavior

Port-forwarding for Helm charts (within `garden dev`) seems to only work when there is exactly one Kubernetes service in a chart used by a Garden Helm module. Furthermore, the exactly one Kubernetes service needs to match the name field of the Garden Helm module.

### Expected behavior

If the above is actually expected, there should be something about this in the Garden Helm docs. (Personally, I don't think it is expected, but I can see reasons why it might be the way things are written, because nobody asked to have them changed :)).

If it is indeed not expected, then this is not a documentation bug, but an actual bug in the code that should be addressed, by having Garden properly detect what services really exist in the chart and properly port-forward them.

### Reproducible example

Our situation is a bit complicated because we originally started with a Helm chart that created several deployments, services and secrets; that all work together as one solution. We shortly realized that Garden does not seem to want to support this (maybe it does and if this bug gets actually fixed, it in fact will) and instead pushes for divide and conquer, so we tried to divvy up our charts and see if we could still somehow have Garden work with them. We now have several smaller charts, each with a single deployment, service and secret (we were thinking of still creating a master chart that would use all of these as subcharts, to utilize Helm's atomicity), yet still failing to use Garden with them.

The main issue, that can be seen even with vote-helm (one of the Garden examples) is when the name field of the module is different from the name field of the Kubernetes service inside the chart. `garden dev` is able to deploy such a module, is able to detect that it is up, and it will even log out proper port-forward pairs, yet when it comes to the actual `kubectl port-forward` command, it uses the module's name instead of the service's name. Which is kinda funny, because based on the log output, it seems quite capable of parsing the Kubernetes manifests and detecting what services have what ports exposed :).

Below is an excerpt of `garden dev`'s output (I replaced references to my username with `user` and our project with `project` :)). `name` of the module is `project-postgres`, `name` of the Kubernetes service in the manifest is `project-local-postgres`. Of course, this excerpt is only from one of the modules with port-forwarding, but they all look the same: i.e. Garden seems able to detect the actual names of Kubernetes services and ports it should forward, but when it comes to the actual port-forwarding, it just uses name of the Garden module instead :(.

```
project-postgres             → Deploying version v-07b282f5f5... → Done (took 9.2 sec)
   Starting proxy to project-postgres/project-local-postgres:5432 on 127.0.0.1:5432
   → Forward: postgres://127.0.0.1:5432 → project-local-postgres:5432
Watcher: Watching paths /Volumes/Projects/project
Watcher: Starting FSWatcher
🕑  Waiting for code changes...
   Starting port forward to project-postgres/project-local-postgres:5432
   Forwarding local port 52852 to Service/project-postgres port 5432
   Spawning '/Users/user/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=docker-for-desktop --namespace=default port-forward Service/project-postgres 52852:5432' in /Users/user/.garden/tools/kubectl/b57d7033ebdf2a5a
   Error starting port forward to project-postgres/project-local-postgres:5432: Port forward exited with code 1 before establishing connection:

Error from server (NotFound): services "project-postgres" not found

   Successfully started port forward to project-postgres/project-local-postgres:5432
   Remote socket error: Socket is closed
```

I would expect for the `Service/project-postgres` part of `kubectl port-forward` to be `Service/project-local-postgres`, to correspond with the Kubernetes manifest. Why isn't it?

### Workaround

The only workaround we thought of so far, is to really give the Garden module the same name as the Kubernetes service, but this is with one major drawback: we can no longer deploy our solution into the same Kubernetes cluster & namespace, and separate the individual "deployments" by changing their names (and selectors) -- which is something that is very easy to do with Helm and its templated charts. This is on us, but unfortunately we only have the one cluster and namespace to use :).

It would be a viable workaround if one could template the name field of the Garden module, but that does not seem supported. I tried using `name: project-${environment.name}-postgres` there, but Garden complains that it is not matching the proper regex, and shows the unexpanded version of the name, which likely means, templating it is not supported.

### Suggested solution(s)

Honestly, I think Garden would just have to use the proper Kubernetes service name when setting up the port-forwards, rather than using the Garden module name instead. I took a very quick look at the code, and I am not sure if that part has access to that, though...

### Additional context

Happy to answer questions.

### Your environment

Garden+Docker Client+Kubectl run on my Mac, Docker Engine+Kubernetes in a cluster.

```
$ garden version
0.11.13
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.14
 Git commit:        afacb8b
 Built:             Thu Mar 12 02:45:41 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by edvald** [comment]
Hey @petr-motejlek. Thanks for the detailed report! So, we do actually just go by the Service resources, and not the module name. _However_ it could be, looking at the given context, that this might relate to this PR (and related issue): https://github.com/garden-io/garden/pull/1812

Could that be the case? That is, that the service name is different depending on some runtime/cluster variable in Helm? That could explain Garden getting the wrong service name for the port forward.

**Comment by petr-motejlek** [comment]
Hey,

Thanks for the quick response.

What is "a Service resource" in the context of your message? Is that the pseudo Garden service or the actual Kubernetes service?

Our Kubernetes services do not depend on a cluster variable (I am not entirely sure what that is precisely even), they are parametrized using values.yaml (and the facilities of Helm that deal with values), though. Would that be the same? (To put this differently, when I run `helm template`, I already have the Kubernetes service names populated by real data).

**Comment by edvald** [comment]
Sorry, that's indeed worth clarifying! I did mean Kubernetes Service resources, as opposed to Garden services. Here's the actual code we use to decide what to create the forwards for: https://github.com/garden-io/garden/blob/b23eeaaf391610ea8c2b9a93afdc778cadd6d020/garden-service/src/plugins/kubernetes/port-forward.ts#L197

It's possible that there is some bug that causes the wrong Kubernetes Service name to be used, and my first suspicion was that it had something to do with a mismatch in how the Helm chart template is rendered. Can you paste the section of your Helm chart that renders the Service (i.e. `kind: Service`) resource?

**Comment by petr-motejlek** [comment]
It should not be hard to write a small helm chart to reproduce this, using some open source thingie, like Postgres here. I'll try to do that. I wasn't originally sure whether we weren't simply doing something wrong, so I did not want to spend time writing that, but it seems like it would be worth it. So, I'll do that.

**Comment by petr-motejlek** [comment]
OK, here goes. I took the vote-helm example from Garden, scrubbed it, replaced it with nginx. Port forward does not work :).

https://github.com/petr-motejlek/garden/tree/garden-1827/examples/helm-nginx

```
...
   Error starting port forward to nginx-chart/helm-nginx:1234: Port forward exited with code 1 before establishing connection:

Error from server (NotFound): services "nginx-chart" not found

   Successfully started port forward to nginx-chart/helm-nginx:1234
   Remote socket error: Socket is closed
```

With this patch, however, it does:

```
diff --git a/examples/helm-nginx/nginx-chart/garden.yml b/examples/helm-nginx/nginx-chart/garden.yml
index 6c68ca72..08814a5e 100644
--- a/examples/helm-nginx/nginx-chart/garden.yml
+++ b/examples/helm-nginx/nginx-chart/garden.yml
@@ -3,3 +3,5 @@ type: helm
 name: nginx-chart
 serviceResource:
   kind: Deployment
+values:
+  name: nginx-chart
```

**Comment by petr-motejlek** [comment]
BUMP.

**Comment by edvald** [comment]
Acknowledged! We'll try and find time soon.

**Comment by petr-motejlek** [comment]
Thanks. We have worked around this using the approach I displayed above, but others are likely to run into the same issue. Fix would be good.

**Comment by edvald** [comment]
On closer inspection, it does look like the code is fine. The example you provided above just doesn't set a Service name unless you put `name: something` in the `values` block. The code just pulls the Kubernetes Service resource name from the rendered Helm chart resource (from `metadata.name` specifically). In your example that value is set to `{{ .Values.name }}`. You can replace that with a hard-coded value, and it should work fine.

**Comment by petr-motejlek** [comment]
@edvald , I think we might be missing the point here.

I either need the Garden documentation for the Helm module to state that each Helm module can only have exactly one Kubernetes service and that has to be named exactly the same as the Helm module, otherwise it breaks.

Or, you'd have to look at the manifest, and perhaps infer what are all the services in it.

---

I am not sure I mentioned that earlier, but our original Helm chart (before we began using Garden; we did not have subcharts) would deploy all of our system in one go. Switching to Garden made us split the chart into several subcharts (each with its own Garden Helm module), and each had to accept name for the Kubernetes service it creates, in order to have it the same as the name of the Garden Helm module.


Again, I don't see this requirement documented anywhere, and that's why we ran into this. Neither Helm has a best practice for when to use a big chart and when to go with subcharts, so if Garden has a rule like this, we should know about it, at least :)

**Comment by edvald** [comment]
Hey @petr-motejlek. I see, I have a better sense of this now. This isn't meant to be a requirement at all, we do actually parse Kubernetes Service resources to find which one to forward to, but looks like my quick testing was off the mark and it is an actual bug (simply using the wrong name when constructing the actual port forward—you can see the logs saying we're going to forwarding to the right name, but later in the code the wrong value is used). I'll take a closer look today to see if I can quickly fix it.

**Comment by petr-motejlek** [comment]
Yup, that's what I saw there too. I even got to reading the code, but never really understood when it gets changed :).

**Comment by petr-motejlek** [comment]
Thanks!
