### ISSUE TITLE
File permission issues

### ISSUE THREAD

**Issue by mnpenner** [garden-io/garden#1829]
### Current Behavior

I'm trying to use `hotReload` to keep my server up to date, but it's messing with the file owner:

```
-rwxrwx---  1 197609 197609 1.8K May 13 02:40 index.php
```

### Expected behavior

If you can retain the current owner, do that. If not, just expose rsync's myriad of options to the end user (me).

### Reproducible example

Available upon request. Maybe.

### Workaround

Don't know actually. I tried adding a post-sync command but that doesn't actually seem to be working.

```
hotReload:
    sync:
        -   source: ./src/public
            target: /app/public
    postSyncCommand:
        - chown -R nginx:kymark /app/public
        - chmod -R ug+rwX-s /app/public
```

### Suggested solution(s)

It took me forever to get this exactly right last time I tried rsyncing to a dev server. Need something like

```
rsync -rltzogvp --copy-unsafe-links --chmod F440,D550 --chown USER:GROUP host@name::specialtarget/path
```

Might still be missing some flags but that's roughly it. I think you should at least expose the `chmod` and `chown` options to us as additional [sync](https://docs.garden.io/reference/module-types/container#hotreload-sync) options.

Installing rsync on the server and using the `::` target syntax gives a small speed boost IIRC but that's maybe not feasible?? Unless you boot up a secret container and use it as a volume mount, which might actually be what's going on now.

### Additional context

Maybe something to do with having a Windows host makes this extra terrible..? I don't know, but hotReloading is unusable for me right now. I haven't quite confirmed it, but I think Garden is doing something funky with the chowns and chmods in my Docker files too because my files aren't coming out the way I set them either (all owned by root)

### Your environment

`garden version` 0.11.13

`kubectl version` Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

`docker version` 19.03.8

**Comment by thsig** [comment]
Thanks for the report! We'll bump this in priority.

**Comment by elepedus** [comment]
On MacOS (Catalina) with Garden 0.11.13, the synchronised files have the same user and group IDs as the user that created them on the host system. This suggests that they are at least being retained. 

However, when using production Helm charts that make use of custom security contexts, the retained IDs actually break permissions. 

The current workaround involves manually modifying the security context of the helm chart to match the local user's IDs, but this breaks portability, especially across different operating systems. Each developer would have to customise the values to match their own user and group IDs.

Ideally, the user and group IDs required by the target container could be set as configuration values under the `sync[]` key, and automatically applied using the flags @mnpenner recommended.

The config could look something like this:
```yaml
sync:
  - source: source_directory
    target: target_directory
    chown: 
      user: 1000
      group: 1000
    chmod: 0644
```

## Environment
`garden version` 0.11.13
`kubectl version` Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
`docker version` Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by eysi09** [comment]
Thanks for opening that issue. Since we've addressed this for dev mode and are deprecating the old hot reload functionality, I'll just let stale bot do its thing.

**Comment by thsig** [comment]
Since Stalebot hasn't been doing its thing recently, I'm closing this one.
