### ISSUE TITLE
Garden hangs after command prints `Done`

### ISSUE THREAD

**Issue by mitchfriedman** [garden-io/garden#1835]
### Current Behavior

Garden takes a while to complete after a command and printing `Done!`

### Expected behavior

The garden command should complete shortly after.

### Reproducible example

No reproducible example, but we have a project with >50 modules in it, so it's possible this is a part of it. I don't remember seeing this a while ago with older versions/fewer modules.

### Workaround

n/a

### Suggested solution(s)

🤷 

### Additional context

n/a

### Your environment

50 modules in the project, happens on CI or local, so independent of the environment.

**Comment by eysi09** [comment]
Hi @mitchfriedman, what version are you on? I'm wondering if this is fixed with #1810 that's in our latest release?

**Comment by mitchfriedman** [comment]
This might have been before that version. I'll report back if it's still relevant. Thanks

**Comment by edvald** [comment]
Is this still an issue @mitchfriedman?

**Comment by mitchfriedman** [comment]
I don't think so, haven't noticed it again. Should be good to close!
