### ISSUE TITLE
Run garden as a container

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#184]
I'm not really sure if or how we're gonna do this, but I thought I'd create this issue to centralize the discussion.

The idea is to run garden as a container to avoid the whole headache with the installation process.

One issue raised was that of watching the filesystem. We can (probably) do that with `docker run -v` [(link)](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems), which will affect performance though we don't know whether it'll have a negligible impact or not. (Could [this](http://docker-sync.io/) help?)

General links about containerizing tools:
- [Containerize your developer experience](https://www.youtube.com/watch?v=-CulRxABopY) (talk, 13mins)
- [Distributing Command Line Tools with Docker](https://spin.atomicobject.com/2015/11/30/command-line-tools-docker/) (article)
- [Docker Basics for Local Development](https://spin.atomicobject.com/2015/10/12/docker-for-development/) (article)

**Comment by edvald** [comment]
I'm afraid we need to close this, for two reasons:
1) File watchers would become very expensive, in terms of CPU usage and even i/o. There appears to be no sane cross-platform way to address that currently.
2) It would be very difficult for the framework to reach the parent host, where minikube etc. reside.

So we need a different approach to improving our installation process (which we absolutely do need to do). I'll make another issue with some thoughts and potential approaches.
