### ISSUE TITLE
"garden-util-daemon" not found

### ISSUE THREAD

**Issue by qeternity** [garden-io/garden#1843]
### Current Behavior

Upgraded from 0.11.12 and now I cannot deploy anything. I have done a cluster-init with the new version as well but this does not fix it.

### Expected behavior

Be able to deploy something

### Reproducible example

Upgrade to 0.11.14 from 0.11.12 and execute garden deploy

**Comment by qeternity** [comment]
So after perusing the repo, it seems the utils chart isn't being deployed during an upgrade process. I don't see anything in my logs about it however

**Comment by thsig** [comment]
Hello @qeternity—thanks for pointing this out.

What sort of error message did you get when the deploys failed?

**Comment by qeternity** [comment]
There was nothing in the logs, even at silly verbose levels. It didn't even appear that the chat was attempting to be deployed.
