### ISSUE TITLE
Allow not set `deploymentRegistry` when not building images

### ISSUE THREAD

**Issue by ryuheechul** [garden-io/garden#1845]
## Bug

I will say it's not a but technically but more of restriction.

In a case when I want to use garden to deploy things not involving building images, garden "force" me to do either of the followings in _Current Behavior_ section:

### Current Behavior

```
# 1. I guess this will install stuff in cluster to be able to build image in-cluster when `buildMode: cluster-docker`
Failed resolving provider kubernetes. Here is the output:
One or more cluster-wide system services are missing or not ready. You need to run garden --env=dev plugins kubernetes cluster-init to initialize them, or
contact a cluster admin to do so, before deploying services to this cluster.
```

```
# 2. in case `buildMode: local-docker`
Failed resolving provider kubernetes. Here is the output:
kubernetes: must specify deploymentRegistry in config if using local build mode
```

but they both have problems:
1. users shouldn't have to install extra stuff when they don't need it.
2. no registry should be required when no building is going to happen

### Expected behavior

Garden should give options for a case that doesn't require building images.

### Reproducible example

Create simple garden project that only contains a simple helm chart module and try to deploy it.

> Sorry for the poor example and let me know if you would like me to prepare a better example.

### Workaround

```
# buildMode: local-docker
deploymentRegistry: # just add this unnecessary and meaningless chunk and garden will deploy
  hostname: my.fake.reg
```

### Suggested solution(s)

Let the CLI aware of options for a case that doesn't require building images.

### Additional context

Why would I or anyone want this?
My current usage is deploying bunch of helm charts.

### Your environment

`garden version`
0.11.14
`kubectl version`
1.18.1
`docker version`
19.03.8

**Comment by thsig** [comment]
Thanks for the suggestion! We haven't given this use-case much attention so far (i.e. using Garden without building images), but for the time being, I think your workaround is the way to go.

The `cluster-docker` build mode does indeed install some Garden system services into your cluster.
