### ISSUE TITLE
[FEATURE]: Helm template

### ISSUE THREAD

**Issue by ryuheechul** [garden-io/garden#1851]
## Feature Request

A way to dry-run module deployment

### Background / Motivation

When you directly use helm, you can use `helm template` to look at what manifest is generated for debug purposes. It would be nice if garden can provide such a way (skaffold has render subcommand for that) to avoid write custom script to run template when `gardenl.yml` already has all the info. I mentioned helm because that's my use case now but it doesn't have to be only helm, if other module can benefit this kind of concept as well.

### What should the user be able to do?

dry run or see what actually is going to be delivered via kubectl/helm

### Why do they want to do this? What problem does it solve?

It will make develop/debug workflow robust and less error-prone by avoiding writing script to do this.

### Suggested Implementation(s)

An interface could look like this.
`garden template/dry-run/debug/whatever <module>`

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
Hi @ryuheechul—thanks for the suggestion! This would definitely be a useful feature.

It's not currently on our roadmap, but it's something we've been talking about adding for a while.
