### ISSUE TITLE
[FEATURE]: Module sources shouldn't sync on deletion

### ISSUE THREAD

**Issue by elliott-davis** [garden-io/garden#1870]
### Background / Motivation

We frequently tear down our environment that has a lot of small files. Syncing module sources takes anywhere from 60-120 seconds, which feels unnecessary if we're deleting the environemnt.
### What should the user be able to do?

Delete an environment or service without having to sync module sources
### Why do they want to do this? What problem does it solve?

It makes it faster to delete sources, which eliminates frustration 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
This looks like a simple fix, but I'm wondering if not syncing module sources will affect Helm modules. Thoughts @edvald?

If that's not the case I'll whip up a PR for this.

**Comment by edvald** [comment]
This is AFAICT a bit of an artifact left over from previous limitations. I think after some recent-ish changes it should be feasible.
