### ISSUE TITLE
Visual issues when running inside tmux/screen

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#190]
When running garden inside tmux/screen there's this weird issue with a few of the background colors. 

![Pic](https://i.imgur.com/iY9GPXV.png)

Left is a normal terminal, right is under tmux.

**Comment by edvald** [comment]
Hmm interesting. It appears those two terminals have a different interpretation of "bold/emphasis" (in iTerm it's actually bold, yet another way). So these are all technically correct, just different visual stylings. I wonder how best to handle that... cc @eysi09

**Comment by eysi09** [comment]
It works on my end. I wonder if it's a tmux config issue. What does `echo $TERM` inside tmux return?

**Comment by ellenkorbes** [comment]
Normal terminal:

```
➜  ~ echo $TERM
xterm-256color
```

tmux:
```
➜  ~ echo $TERM
screen
```

**Comment by drubin** [comment]
@ellenkorbes Try adding a `TERM= screen-256color` to your config

https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal

**Comment by ellenkorbes** [comment]
Hi @drubin! That one didn't work, but the other mentioned in that link, `set -g default-terminal "tmux-256color"`,  did! Thanks!

I'll document this and close the issue.
