### ISSUE TITLE
Cannot fetch pod logs from UI

### ISSUE THREAD

**Issue by mholleville** [garden-io/garden#1934]
## Bug

Hello, when I use garden on a GKE environment with Helm, I get an error when retrieving logs from pods.

### Current Behavior

This is my error when i click on the log button. 

<img width="1311" alt="Screenshot 2020-07-07 at 17 07 53" src="https://user-images.githubusercontent.com/49511757/86801716-9febee00-c074-11ea-8e9a-879b04a52cae.png">

This is my API build directory

![image](https://user-images.githubusercontent.com/49511757/86801956-d45faa00-c074-11ea-8e13-2a167c8bd726.png)

Why garden trying to use Helm 3 ?

`garden version`
0.11.3

`helm version`
Client: &version.Version{SemVer:"v2.14.0"}
Server: &version.Version{SemVer:"v2.16.0"}

**Comment by eysi09** [comment]
Hi @mholleville!

Garden uses Helm 3 but actually fetches it for you and stores under `$HOME/.garden/tools`. So it shouldn't mix with the version of Helm you have previously installed. You can run the Garden version of Helm with the `garden tools` command (on Garden v0.12 and greater).

As for the issue itself, I'm not quite sure what's happening at a glance.

Could you try updating to the latest version of Garden and see if it's still an issue? We made some small changes to how we run Helm commands in our latest version.
