### ISSUE TITLE
Link on docs not very helpful

### ISSUE THREAD

**Issue by timonbimon** [garden-io/garden#1937]
Not really a bug report at all, but just wanted to direct your attention to the fact that the links on the Garden docs (https://docs.garden.io/)
link to the GitHub Readmes, which is not very helpful.

![image](https://user-images.githubusercontent.com/14793026/87056446-f177b280-c205-11ea-8a40-639f05beea22.png)

clicking on Getting Started, you land here:

![image](https://user-images.githubusercontent.com/14793026/87056518-0c4a2700-c206-11ea-8ac7-30c1121f43ce.png)

**Comment by eysi09** [comment]
Hi @timonbimon and thanks for pointing this out!  We'll look into this ASAP.

We just did a major refactor of our docs and looks like we messed up the links along the way.
