### ISSUE TITLE
"Getting Started" tutorial doesn't pass integration test

### ISSUE THREAD

**Issue by cgorman** [garden-io/garden#1941]
Not really a bug per se, but going through the Getting Started tutorial as it is written doesn't work when you get to the test step. There are a few differences between the code in `demo-project` and `demo-project-start`. Running `garden test` from `demo-project` works, The specific failure is that `call-backend` gives a 404, which I assume is because there is no `call-backend` route in the `frontend` app. Just replacing `app.js` with the working one in `demo-project` doesn't fix it and that's as far as I felt like going. Tested on `master` and `v0.12.0` .

Also a side note, but it might be worthwhile to get a github template for documentation issues since this doesn't really fit under the "bug report" criteria IMHO. Thanks!

**Comment by eysi09** [comment]
Hi @cgorman and thanks for flagging this. We'll fix this ASAP.
