### ISSUE TITLE
Terraform map outputs break garden

### ISSUE THREAD

**Issue by ThisGuyCodes** [garden-io/garden#1947]
### Current Behavior

```
Failed getting status for service 'xyz' (from module 'xyz'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error validating getServiceStatus terraform output from provider terraform: key .outputs[terraform_outputs] must be one of [number, string, boolean]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 test task(s) failed!
```

### Expected behavior

Works.

### Reproducible example

Any terraform output that has a map:
```hcl
output "a_map" {
  value = map(
      "first", "first_value",
      "second", "second_value"
  )
}
```

### Workaround

Don't use map outputs.

### Suggested solution(s)

Output validator should consider more types valid.

### Additional context

Personally it's less important that I be able to access this value in templating (though I believe you're using the json output, so idk how hard that'd be). I'm already dumping the output to a json in an exec build.

**Comment by ThisGuyCodes** [comment]
Can this get some attention? Even just validation that I'm not doing something wrong.

This will become more problematic for us as we want our infrastructure to be more modular (specific example: every RDS instance gets a debezium kafka connect instance, which is easy if our RDS instances are a map we can loop over).

**Comment by edvald** [comment]
My apologies @ThisGuyCodes. Much of the team has been away, I'm catching up a little. Hadn't seen this before. We rely on `terraform` to output JSON, and don't make any attempt to parse the HCL. Need to see what the `terraform` CLI is actually outputting in this scenario, to see if it's something we can address.

**Comment by edvald** [comment]
Oh I see it now. It's a no-longer-needed limitation in the `outputs` schema. I can simply lift that, now that we properly support maps/arrays/etc for our templating.

**Comment by ThisGuyCodes** [comment]
@edvald you just made my day!
