### ISSUE TITLE
Getting Started error: contexts[4].context.cluster is missing 

### ISSUE THREAD

**Issue by mhn10** [garden-io/garden#1976]
## Bug
Trying out the getting started by following the examples/demo-project-start. Getting the following error when trying to do local cluster build

garden deploy
Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
contexts[4].context.cluster is missing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- local-kubernetes

### Current Behavior

Not able to build

### Expected behavior
As per tutorial, services should come up

### Reproducible example
![image](https://user-images.githubusercontent.com/31016811/89243099-0141a700-d5b8-11ea-8fd9-dba0b7fe60b4.png)

Just followed getting started, local kubernetes cluster

```yaml
kind: Project
name: demo-project
environments:
  - name: local
    providers:
      - name: local-kubernetes
        context: docker-desktop
```

### Additional context

I have docker-desktop context on Mac. I also have minikube, but I dont use it at all.

`kubectl config get-coontexts` 

*         docker-desktop             docker-desktop       docker-desktop                   

Error.log

```

[2020-08-04T01:33:44.212Z] Error: contexts[4].context.cluster is missing
    at /snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config_types.js:111:19
    at Function.map (/snapshot/project/garden-service/tmp/dist/node_modules/underscore/modules/index.js:197:22)
    at Object.newContexts (/snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config_types.js:92:14)
    at KubeConfig.loadFromString (/snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config.js:106:40)
    at /snapshot/project/garden-service/tmp/dist/build/src/plugins/kubernetes/api.js:0
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/src/plugins/kubernetes/api.js:0)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[2020-08-04T01:33:44.217Z] Error: Failed resolving one or more providers:
- local-kubernetes
    at Garden.<anonymous> (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
Error Details:
rawConfigs: []
taskResults:
  resolve-provider.exec:
    type: resolve-provider
    key: resolve-provider.exec
    name: exec
    description: resolving provider exec
    completedAt: '2020-08-04T01:33:43.239Z'
    batchId: 65a2b38f-e4c8-4766-940a-70e163f04260
    output:
      name: exec
      dependencies: {}
      moduleConfigs: []
      config:
        name: exec
        path: >-
          /Users/mhn10/Documents/Code/Garden/garden/examples/demo-project-start
      status:
        ready: true
        outputs: {}
        dashboardPages: []
        cached: true
      tools: {}
    dependencyResults: {}
    version: 0.12.1
    startedAt: '2020-08-04T01:33:43.225Z'
  resolve-provider.container:
    type: resolve-provider
    key: resolve-provider.container
    name: container
    description: resolving provider container
    completedAt: '2020-08-04T01:33:43.240Z'
    batchId: 54a35c84-08fd-423c-9826-7f0466fd66cb
    output:
      name: container
      dependencies: {}
      moduleConfigs: []
      config:
        name: container
        path: >-
          /Users/mhn10/Documents/Code/Garden/garden/examples/demo-project-start
      status:
        ready: true
        outputs: {}
        cached: true
        dashboardPages: []
      tools:
        docker:
          buildSpec:
            platform: darwin
            architecture: amd64
            url: >-
              https://download.docker.com/mac/static/stable/x86_64/docker-19.03.6.tgz
            sha256: 82d279c6a2df05c2bb628607f4xxxxxxxxxxce6d5f2a2f65643fbb6ed2f9af
            extract:
              format: tar
              targetPath: docker/docker
          lock:
            queues: {}
            domains: {}
            domainReentrant: false
            timeout: 0
            maxPending: 1000
          name: docker
          type: binary
          spec:
            name: docker
            description: The official Docker CLI.
            type: binary
            builds:
              - >-
                ~taskResults~resolve-provider.container~output~tools~docker~buildSpec
              - platform: linux
                architecture: amd64
                url: >-
                  https://download.docker.com/linux/static/stable/x86_64/docker-19.03.6.tgz
                sha256: >-
                  34ff89ce917796594cd8114xxxxxxxxxxxxxx7a796b5897052f7cc
                extract:
                  format: tar
                  targetPath: docker/docker
              - platform: windows
                architecture: amd64
                url: >-
                  https://github.com/rgl/docker-ce-windows-binaries-vagrant/releases/download/v19.03.6/docker-19.03.6.zip
                sha256: >-
                  b4591baa2b76ce3fbexxxxxxxxxxxd87363f29d63f5c
                extract:
                  format: zip
                  targetPath: docker/docker.exe
          toolPath: /Users/mhn10/.garden/tools/docker
          versionDirname: fa0336ac33b46eb5
          versionPath: /Users/mhn10/.garden/tools/docker/fa0336ac33b46eb5
          targetSubpath: docker/docker
          chmodDone: false
    dependencyResults: {}
    version: 0.12.1
    startedAt: '2020-08-04T01:33:43.227Z'
  resolve-provider.local-kubernetes:
    type: resolve-provider
    description: resolving provider local-kubernetes
    key: resolve-provider.local-kubernetes
    name: local-kubernetes
    error: {}
    startedAt: '2020-08-04T01:33:43.240Z'
    completedAt: '2020-08-04T01:33:44.176Z'
    batchId: 54a35c84-08fd-423c-9826-7f0466fd66cb
    version: 0.12.1
messages: []


```

### Your environment

`garden version`
0.12.1
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

`docker version`

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by eysi09** [comment]
Hi @mhn10 

Apologies for the late reply, but I believe this has been resolved on the latest  version of Garden. The underlying issue was that Docker for Desktop now uses a different name for its default context. You fix this by upgrading to the latest version of Garden or by explicitly setting the `providers[].context` field to `docker-desktop`. 

Please let me know if that doesn't help.
