### ISSUE TITLE
git directory unavailable

### ISSUE THREAD

**Issue by alemairebe** [garden-io/garden#1977]
### Current Behavior

builds depending on `.git` folder to provide commit-id of the artifact fails as I cannot get it synced.
I tried to `include: .git` at module level and also tried with build.dependencies[] on container module type builds with kaniko on a remote cluster, both fails.
### Expected behavior

Being able to sync .git directory to the remote kubernetes cluster so kaniko can build artifacts with git commit id

### Workaround

disable .git feature

### Your environment

```
garden version 
0.12.0
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Comment by eysi09** [comment]
Hi @alemairebe 

We actually always exclude the `.git` directory. I'm trying to recall whether its because its a sensible default or if there are other underlying reasons as well (cc @edvald).

We have been looking into exposing the commit SHA as a [module output](https://docs.garden.io/reference/module-types/container#outputs), and we'd be happy to bump the priority on that one. Would you be able to workaround this in the mean time?

**Comment by alemairebe** [comment]
Hi @eysi09 ,
I tried to work around this by using the maven-container module as that one is building artifacts outside a container but no luck in that direction either.
