### ISSUE TITLE
[FEATURE]: expand terraform support

### ISSUE THREAD

**Issue by ThisGuyCodes** [garden-io/garden#1988]
### Background / Motivation

Terraform .13 is out! But also being locked to one version of terraform is pretty limiting :(

### What should the user be able to do?

Specify versions of Terraform besides .12.26.

### Why do they want to do this? What problem does it solve?

Use new features / bug fixes in Terraform. `for_each` for modules!!

### Suggested Implementation(s)

Since the CLI interaction with Terraform is pretty stable, I think this would mostly amount to expanding [this](https://github.com/garden-io/garden/blob/a783adc02a31cd9dac89f945aa3115033f7ed488/garden-service/src/plugins/terraform/cli.ts#L27-L65) and doing integration tests. The json output had some changes in .13 but I think it's just extra fields.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by ThisGuyCodes** [comment]
I would actually be interested in contributing this! Besides [the file I linked in the issue](https://github.com/garden-io/garden/blob/a783adc02a31cd9dac89f945aa3115033f7ed488/garden-service/src/plugins/terraform/cli.ts#L27-L65) are there other changes that would be needed? And / or are there tests for me to look at / could write to validate multiple versions of Terraform?

**Comment by edvald** [comment]
That would be much appreciated! It should be as simple as adding an entry for the latest 0.13.x release, barring any unexpected changes in their CLI interface. 

I'd suggest hard-coding the default version to the 0.12.x one, in the bottom line of the file, and then we can change that when we do a breaking release.

**Comment by jeremiahlewis-vw** [comment]
What about tying this to a docker image (e.g. wrap container module instead of shell for terraform)?

**Comment by ThisGuyCodes** [comment]
@jeremiahlewis-vw I don't understand how that would solve this? I'm not using a shell for terraform here.

**Comment by jeremiahlewis-vw** [comment]
Sorry, should be more precise, what I mean is that the terraform module is (AFAIK) a wrapper on the exec module, which means dependencies need to be managed / packaged as part of the CLI. Alternately, the terraform module could be based on the container module, in which case the dependencies could be managed as just another container dependency. This is relatively easy to set up already, by using the terraform docker image and running tasks that execute various terraform commands.

https://docs.garden.io/using-garden/modules#module-types

**Comment by edvald** [comment]
It doesn't exactly wrap/extend the `exec` module, even though it does execute commands locally. I'd hesitate to require Docker for this, because many users will be unable to use it locally, and we don't want to preclude use of Terraform before a remote cluster is available.

What I think I'll do is to simply add the latest 0.13 version, as well as allow a `null` option for the Terraform version, which will direct Garden to use whichever `terraform` CLI version that's on the user's path.

**Comment by jeremiahlewis-vw** [comment]
(Will keep pushing for a container-based setup, but understand your justifications, thanks!) And thanks for the great tool. :)
