### ISSUE TITLE
SSH Port Forwarding does not work on first connection

### ISSUE THREAD

**Issue by ultimatemonty** [garden-io/garden#1995]
## Bug
Setting up SSH port forwarding using the service port definitions causes a weird SSH connection issue on the initial attempt to connect. The session terminates with the following error

```
Bad packet length 1397966893.
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
```

Trying to connect again results in a successful connection and from there after it's fine. This consistently happens each time you restart garden or restart the deployment for the service.

This also happens if you define the port forwarding as a kubernetes module with a manifest.

### Expected behavior
Connecting to the service via SSH is successful the first try.

### Reproducible example
I've created a small repo where the issue is reproducible
https://github.com/ultimatemonty/garden-ssh-forward-repro

run `garden dev` then `ssh root@127.0.0.1 -p 2222`. The first attempt will result in the MAC error. Try it again and you will be able to connect. Password is `root`

To reproduce the kubernetes module version use the [`manifest-port-forwarding`](https://github.com/ultimatemonty/garden-ssh-forward-repro/tree/manifest-port-forwarding) branch of that repo and follow the same repro steps.

### Workaround
The only way we found to work around it was to manually apply a manifest that sets up the port forwarding.

I have that setup on the [`static-manifest`](https://github.com/ultimatemonty/garden-ssh-forward-repro/tree/static-manifest) branch. Just fire up garden and then run `kubectl -n ssh-forward-repro-default apply -f container/ssh-forwarder.yml` and you'll be able to SSH in with no issues.

### Suggested solution(s)
No idea

### Additional context
SSH access is needed for application development and debugging purposes. Specifically for enabling debug sessions from IntelliJ/PHPStorm into a service.

### Your environment
Tested on:
* MacOS Catalina 10.15.4 (mid-2014 Macbook Pro for personal use, no management software)
* MacOS Catalina 10.15.6 (19G73) (2018 Macbook Pro for work use with lots of enterprise management software)

```
$ garden version
0.12.1
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
Thanks @ultimatemonty! We'll take a look. There appears to be something suspect in how we hold the connection as we initialize the proxy and port forward.

**Comment by thsig** [comment]
Closing this one for now, feel free to reopen this if it's still a problem.
