### ISSUE TITLE
Garden not picking up build directory

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [garden-io/garden#2014]
### Current Behavior

Currently I am very bewildered, because this really seems like pretty standard behavior.  Hopefully I'm just doing something wrong and this is a simple fix on my end.  I have a **very** simple kotlin app that I bundle through the gradle shadow jar plugin, and subsequently pickup and run in my container. 

```
FROM openjdk:8-jre-alpine

ENV APPLICATION_USER ktor
RUN adduser -D -g '' $APPLICATION_USER

RUN mkdir /app
RUN chown -R $APPLICATION_USER /app

USER $APPLICATION_USER

COPY build/libs/backbone-generator-0.1.0.jar /app/generator.jar
WORKDIR /app

CMD ["java", "-server", "-jar", "generator.jar"]
``` 

As you can see, the Dockerfile expects the jar to be in the `build/libs` folder.  This builds no problem with `docker build -t generator .`

However, when running `garden build` with the followin `garden.yml`

```
kind: Project
name: demo-project
environments:
  - name: default
providers:
  - name: local-kubernetes
---
kind: Module
type: container
name: backbone-generator
dockerfile: Dockerfile
services:
  - name: generator
    ports:
      - name: http
        containerPort: 8080
        servicePort: 80
    ingresses:
      - path: /generator
        port: http
```

I get a non-zero exit code complaining 

```
cp: can't stat '/app/build/libs/backbone-generator-0.1.0.jar': No such file or directory
The command '/bin/sh -c cp /app/build/libs/backbone-generator-0.1.0.jar /app/generator.jar' returned a non-zero code: 1
```

I'm curious if Garden is misinterpreting the docker file in some way, because `/app/build/libs/backbone-generator-0.1.0.jar` should most likely just be `./build/libs/backbone-generator-0.1.0.jar` unless `app` is, in this context, a path in the Garden context, not in the dockerfile context, which is possible but definitely out of my knowledge of this project so far 

My understanding is, that when no `include` is specified in a garden module, it will pick up the same path context as the Dockerfile that it is working with, so suffice to say I'm _really_ confused why this isn't working haha

### Expected behavior

Garden should pick up the `build` directory and function just as running `docker build -t generator .` would 

### Reproducible example

Really unless this is something jvm specific (which would be extra weird).  you should just be able to make an app of your choice, build it and create a dockerfile that copies the packaged build and it should produce the same result.

For reference this is my top level layout 

```
.
├── Dockerfile
├── build
|   └── ...
├── build.gradle.kts
├── garden.yml
├── gradle
│   └── ...
├── gradle.properties
├── gradlew
├── gradlew.bat
├── settings.gradle.kts
├── src
|   └── ...
```

### Workaround

TRUST ME I TRIED 😭 

### Suggested solution(s)

Like I mentioned above, the path garden is attempting to copy seems suspect, although that might just be misunderstanding how Garden is going about doing its job 

### Additional context

N/A

### Your environment

`garden version`

0.12.1

`kubectl version`

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

`docker version`

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by rgbrizzlehizzle** [comment]
Digging further this definitely appears to be some issue with Garden copying a folder named `build`.  I tried two things, first was pulling the jar into my top level directory and building from there, the second being changing `build` to `output` as my directory name, both of which worked no problem.

**Comment by edvald** [comment]
Hey @rgbrizzlehizzle . Thank you so much for the detailed report!

I think it is indeed some bug in how the include paths are inferred. You can work around it by explicitly setting an include field in the module config, but I'll try and work out why this is misbehaving.

**Comment by edvald** [comment]
One other possible explanation would be something in a .gardenignore file somewhere, but from your description I don't see you having one?

**Comment by rgbrizzlehizzle** [comment]
Nope you're absolutely right, I forgot to include it in my report because garden auto generated it, but right smack in the middle of it is a statement to ignore `build` folder 😃 a tale as old as time

**Comment by edvald** [comment]
Haha ok, so it goes sometimes :) We do have some utilities coming up for better diagnosing this sort of thing, listing files, showing which ones are included/excluded and why. Would have been useful here!
