### ISSUE TITLE
[FEATURE]: jib-container support

### ISSUE THREAD

**Issue by janario** [garden-io/garden#2015]
### Background / Motivation

[Jib](https://github.com/GoogleContainerTools/jib) is a tool used to help on building optimized docker images

We highly use it in our environments to make the process of creating new services easy and reliable

The `container` is expected to work with a Docker file and the `maven-container` is meant to build an image using jar files 

### What should the user be able to do?

Build docker images with Jib

### Why do they want to do this? What problem does it solve?

Jib is super helpful and builds consistent light images with a small effort

### Suggested Implementation(s)

A new module to integrate with Jib (maven, cli, gradle), or some support in the other modules to extends build command where the user could specify a `mvn jib:build` when needed

### How important is this feature for you/your team?

Super important, all service uses an standard Jib config

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
Hey @janario. As it happens, we've been discussing just this recently. The `maven-container` module is a little out of date, and people seem to be converging on using Jib. We'd still need to look into how exactly it'd be best to integrate with it, and how it should work with remote building, but I think your suggestion is generally how we'd like to proceed.

**Comment by janario** [comment]
@edvald Nice it was discussed :-) 

Looking forward to it

**Comment by jfernandomeyer** [comment]
This feature would be amazing @edvald. So far I've been using workflows to build images using Jib manually, but having it integrated into the build cycle would be great.

Looking forward to seeing some progress here 👍

**Comment by edvald** [comment]
Working on this right now! A little bit of figuring out to do, in terms of how it plays with the `kubernetes` provider etc., but hopefully there next release, or the one after at the latest.

**Comment by janario** [comment]
To let you know, we are using the `exec` module with `mvnw` and `GARDEN_MODULE_VERSION` (https://github.com/garden-io/garden/issues/2074#issuecomment-708385299)

So far so good, I guess we reached good support for it with those configs

```yaml
kind: Module
type: exec
name: my-app-build
local: true
include: [src/**/*, pom.xml]
build:
  command:
    - "./mvnw clean package -DskipTests && ./mvnw jib:build -Ddockerfile.tag=$GARDEN_MODULE_VERSION"
```

The only missing part as I see is to run the command at the same dir of the project, so while importing a project the `mvnw` should run from the external sources

Similar to https://github.com/garden-io/garden/issues/2078

**Comment by edvald** [comment]
This is still in progress, apologies for the delays

**Comment by tedchang77** [comment]
@edvald any update on this feature? We’re in the process of adopting Jib as well so this would be a really nice feature to have.

**Comment by edvald** [comment]
Hey @tedchang77. We ended up prioritizing the new dev mode and getting rid of NFS, but this is next up! I'm getting re-acquainted with jib as we speak. This'll be up and running within a couple of releases 🚀

**Comment by edvald** [comment]
Progress! #2511

**Comment by edvald** [comment]
@janario @tedchang77 I could actually use feedback on that PR, to see if there's something important missing from the implementation. Java dev is a touch out of my everyday knowledge, so there may be some devilish details to consider. At least the tricky bits should be largely done, but I'd not be terribly surprised if there were some config fields missing or the like.

Here are the module type reference docs in the PR: https://github.com/garden-io/garden/pull/2511/files#diff-673e5bd67f872ac65f336cd98766540b0421a9ba50df6d11e02faa507ea74382
