### ISSUE TITLE
CLI does not validate empty string parameters

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2035]
### Current Behavior

The CLI doesn't appear to be validating empty string parameters which causes errors as the command runs.

### Expected behavior

The CLI should fail with a helpful error, telling the user that a non-empty string parameter is needed for that particular option or positional argument. 

### Reproducible example

Run `garden deploy --hot` (as opposed to something like `garden deploy --hot "*"`).

### Workaround

Don't forget the string parameter!

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

`garden version`

0.12.3

**Comment by edvald** [comment]
Is this still an issue?

**Comment by thsig** [comment]
This is no longer an issue, I've just checked.
