### ISSUE TITLE
v0.12.3 broke flag parsing

### ISSUE THREAD

**Issue by ThisGuyCodes** [garden-io/garden#2039]
### Current Behavior

`garden --env=pr --logger-type=basic --log-level=debug build` prints usage information

### Expected behavior

`garden --env=pr --logger-type=basic --log-level=debug build` runs `garden build` with the given flags

### Workaround

Re-order the flags to go after the command.

### Suggested solution(s)

Flags / options should be positionally independant (or as often as possible).

### Additional context

This worked in v0.12.2.

Position-dependant flags make writing automated interactions with garden more difficult (save for things like "last one wins" which actually makes things easier!). I.e. I have a set of flags I want to be added for any command run in our CI process, so I created a wrapper for running garden commands. I now have to change this to care about the location of the flags.

I recognize position-dependance is actually practical and useful for things. However I don't believe "logger-type", "log-level", or "env" fit that description.

### Your environment

Linux, ubuntu 20.04.

`garden version`
```
0.12.3
```

**Comment by ThisGuyCodes** [comment]
perhaps even more concerning is that when this error occurs garden exits with a `0` status code. Thus my builds *said* the succeeded, and I only noticed because they were suspiciously fast.

**Comment by eysi09** [comment]
This might be the same regression as #2035

**Comment by edvald** [comment]
I'm on it.
