### ISSUE TITLE
download URLs broken :(

### ISSUE THREAD

**Issue by ThisGuyCodes** [garden-io/garden#2055]
I don't expect anything out of this, but I wanted to bring this to your attention as "a thing that creates work and makes me sad".

Up through garden 0.12.3 you put a `v` in your releases. in 0.12.4 and 0.12.5 you didn't, this broke my CI when I attempted to update the version of garden it runs. Not a ton of work to fix, but something I had to fix.

**Comment by thsig** [comment]
Hi @ThisGuyCodes—thanks for pointing this out.

In our latest release (0.12.5), we changed the version format from `vX.Y.Z` to `X.Y.Z` (removing the `v` prefix).

We forgot to mention this in the release notes and our community Slack, which was an omission on our part—my apologies.

I'll update the release notes accordingly.
