### ISSUE TITLE
The exec command doesn't work with the K8s provider

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2064]
### Current Behavior

Garden appears to hang when running something like `garden exec api /bin/sh`. The reasons is that the output from the pod that's being attached to is never rendered in the users terminal.

More precisely, the `message` events for the websocket connection here are not handled:

https://github.com/garden-io/garden/blob/master/core/src/plugins/kubernetes/api.ts#L600

It's not clear to me whether the K8s library should be doing that or whether it needs to be handled explicitly. 

### Expected behavior

Output should be visible.

### Reproducible example

Run `garden exec backend /bin/sh --env remote` in the `demo-project`. 

### Workaround

Use `kubectl` directly, for example:

```
kubectl exec <pod-name> -n <namespace-name> -it -- /bin/sh
``` 

### Your environment

Lastest `master`.

**Comment by jeremiahlewis-vw** [comment]
Glad you also noticed this, have been wondering for a week now whether it was just me. :)
