### ISSUE TITLE
[FEATURE]: Module exec should be able to refers to itself

### ISSUE THREAD

**Issue by janario** [garden-io/garden#2074]
### Background / Motivation

When using the module type `exec` it is expected to run some manual command with the values of its on

In our scenario, we are trying to have an easy way of using jib in our garden build(https://github.com/garden-io/garden/issues/2015) 

Trying to extend it to use exec module:
```
kind: Module
type: exec
name: my-jib-image
local: true
build:
  command:
    - ./mvnw clean package -DskipTests
    - ./mvnw jib:build -Ddockerfile.tag=${modules.my-jib-image.version}

$ garden build
Failed resolving module config my-jib-image. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Invalid template string ./mvnw jib:build -Ddockerfile.tag=${modules.my-jib-image.version}: Module 
my-jib-image cannot reference itself.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more modules:

my-jib-image: Invalid template string ./mvnw jib:build -Ddockerfile.tag=${modules.my-jib-image.version}: 
Module my-jib-image cannot reference itself.
```

Since the exec module is meant for an easy extension point it would be nice if it can refer to is version output at least

### What should the user be able to do?

Module type `exec` can refer to its version output

> ${modules.my-jib-image.version}

### Why do they want to do this? What problem does it solve?

Some custom modules should have a way of integrating with its version

### Suggested Implementation(s)

exec module only can refer to itself of to its version at least

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
Hi @janario—in this case, you could split your `exec` module into two modules, where the first runs `./mvnw clean package -DskipTests`, and the second refers to the module version of the first.

The thing is, a module's version is only updated after it's built, so sequencing the two commands in a single build step would result in the second step (`jib-build` here) not having access to the updated version from the first step. In Garden, each module represents a versioned build step.

Does that help?

**Comment by janario** [comment]
The suggestion might help in some cases, and at some point, jib support might be a proper fix

"version gets updated only after its built", but does it get calculated before, right? I wonder how the container module works, does it build with the version right away or retag in the end?

**Comment by edvald** [comment]
There is another approach here that should work: Use `$GARDEN_MODULE_VERSION` in the build command. The `exec` module type exposes a `GARDEN_MODULE_VERSION` environment variable when running commands.

So you command would be something like:

```
build:
  command:
    - "./mvnw clean package -DskipTests && ./mvnw jib:build -Ddockerfile.tag=$GARDEN_MODULE_VERSION"
```

The reason for this is that template strings are resolved before the version is available, but the version is in turn available at the time the command is actually run.

I think this needs to be better documented, it's a bit buried in our docs atm.

**Comment by janario** [comment]
That's perfect for my scenario

Thanks, I'll close this one :+1:
