### ISSUE TITLE
[FEATURE]: Provide outputs or modules on workflow evaluation

### ISSUE THREAD

**Issue by janario** [garden-io/garden#2078]
## Feature Request

Workflows usually are build to runs some commands based on a specific directory. e.g. `./mvwn my-project`

But when importing an external project using `sources` and trying to run an imported workflow it can fail since it executes in a different directory

# project-a
```
kind: Workflow
name: project-a-workflow
steps:
  - command: [build]
  - script: |
      ./mvnw ...
  - command: [deploy]
```

# project-b
```
$ garden run workflow project-a-workflow

stdout: 'Building image with version: v-8ba87183b1'
stderr: |-
  bash: line 3: ./mvnw: No such file or directory
Script exited with code 127

```

### Background / Motivation

Would like to reuse workflow definitions across different projects 

### What should the user be able to do?

Make it possible to execute workflows outside of where it was defined

### Why do they want to do this? What problem does it solve?

Be more flexible and reuse external definitions of other projects

### Suggested Implementation(s)

My first idea was to reuse the module [output](https://docs.garden.io/reference/module-types/exec#usd-modules-less-than-module-name-greater-than-path) from the same dir

```
${modules.my-module.path}
```

But it is not available, not sure if due to some relation to the [stack graph](https://docs.garden.io/using-garden/workflows#workflows-and-the-stack-graph):

> : Could not find key modules. Available keys: environment, local, project, secrets, steps, var and variables.

But a better approach would to provide some output of the workflow that could be reused in itself. e.g.

```
${worflows.project-a-workflow.path}/mvnw ...
```

So when using in the same project it would be the same directory, but when importing into a different project it would point to its source with the directory of the workflow

> .garden/sources/project/project-a--2016ba3c92/

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @janario and thanks for opening this issue.

I'm forwarding this one to @thsig, the person who implemented the workflows feature.
