### ISSUE TITLE
[FEATURE]: Module should not evaluate other disabled module 

### ISSUE THREAD

**Issue by janario** [garden-io/garden#2079]
## Feature Request

When using an expression that points to a module that is disabled it could evaluate to undefined or we should have an explicit way of accessing only active modules

### Background / Motivation

In our scenarios, it is common to relate container modules with helm modules

```
kind: Module
type: container
name: my-image
image: my-image
---

kind: Module
name: my-chart
type: helm
releaseName: my-chart
values:
  deployment:
    imageTag: "${ var.my-image.version }?"
```
This works great running garden build / deploy

But in our scenario, we would like to import this project as an external `source`, and at its own project `my-image` would be enabled but when importing it we would like to rely on the default image in that chart(that would be a stable version)

project-a
```
kind: Module
name: my-image
...
disabled: ${ var.my-image-disabled || "true" } # disabled by default so, when importing in project-b it would use the default chart image
---
kind: Module
name: my-chart
values:
  deployment:
    imageTag: "${ modules.my-image.version }?"
---
kind: Project
name: project-a
variables:
  my-image-disabled: "true" 

$ garden build # builds a new image
$ garden deploy # reuses the same built image
```

project-b
```
kind: Project
name: project-b
# variables:
#   my-image-disabled: "false"
sources:
  - name: project-a
    repositoryUrl: git...

$ garden build # won't do anything for the imported container module since the image was imported disabled
$ garden deploy # will use the container module version and fails, it would be expected to evaluate to undefined and uses the default in the chart since `?` was specified 
```

As a workaround, I have built an expression to check if the module is disabled

> imageTag: "${ (var.my-image-disabled || 'true') == 'true' ? undefined : modules.my-image.version }?"

### What should the user be able to do?

Evaluation for a version of the disabled module should resolve to undefined (modules.my-image.version)

### Why do they want to do this? What problem does it solve?

Composition with external modules would be more flexible

### Suggested Implementation(s)

Do not evaluate some of the values of a disabled module or provide an easy way of checking values for enabled modules only

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Thanks for the feature request and for sharing your workaround! 

I suppose setting the version of disabled modules to undefined makes sense. But I wonder what we should do about other values, such as the module path. Note also that changing this behaviour would be considered an API change so we'd have to do it as part of a breaking change release. 

It'd be useful to get some feedback from other users as well to better understand what this should look like. 

In the mean time I'll flag this a `priority:low` since there's already a workaround.

**Comment by tobias-minted** [comment]
I think this would be useful, too.
