### ISSUE TITLE
Heap error gets thrown regardless of include/exclude - Process memory threshold reached.

### ISSUE THREAD

**Issue by kyungkimsf** [garden-io/garden#2084]
### Current Behavior

I used to be on the cli version 0.12.3 and not run into any issues, but after upgrading recently to 0.12.6 I have started seeing the following error whenever I try to bring up my garden dev in local.

```
Process memory threshold reached. This most likely means there are too many files in the project, and that you need to exclude large dependency directories. Please see https://docs.garden.io/using-garden/configuration-overview#including-excluding-files-and-directories for information on how to do that.
If this keeps occurring after configuring exclusions, please file an issue at https://github.com/garden-io/garden/issues.
```

I've tried adding `include: [] ` to all my modules in the project but still seem to run into the issue. I am thinking it's probably due to the pure size of the project I am trying to bring up -- and I happen to fall in the 85%-100% range heap usage range. My project already respects the ignore files also - 
```
dotIgnoreFiles:
  - .gardenignore
  - .gitignore
```

I've tried setting an env var via `export NODE_OPTIONS=--max_old_space_size=4096` to increase node's max memory limit but that somehow break garden altogether where i can't even do `garden --version`.

### Expected behavior

- There should be an option to increase the max heap size limit in case it was ever needed. 
- The error message should be more straightforward -- more details in the Workaround section.

### Reproducible example

1. `export NODE_OPTIONS=--max_old_space_size=4096` in the shell
2. Run `garden --version`

**Expected:**
version output

**Actual:**
nothing

### Workaround

1. Downgrading manually to 0.12.3 version that did not have the heap check. (may only work if your heap usage falls between 85% but still not using up all 100%)
2. I've found out that by removing certain duplicate dependencies e.g., if my module F had dependencies like
```
dependencies:
- A
- B
- C
```
and B happened to depend on A already, and C happened to depend on B, then just depending on C seems to relieve the issue for me. Perhaps, this is the **real culprit** of the issue -- my listing out all dependencies in my project was trying to make it more apparent what the module relied on.

### Suggested solution(s)

- It seems like the heap error could possibly result from duplicated (inferred) dependencies being listed in some modules as opposed to what the error message indicates -- e.g., include/exclude files.
- Allow for increasing the max heap for the garden engine.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker

`garden version` - 0.12.6

**Comment by thsig** [comment]
@kyungkimsf Thanks for flagging this! We'll look into it.

**Comment by kyungkimsf** [comment]
I've gotten rid of sort of the 'nested dependencies' mentioned in the original ticket, but it seems I still hit the heap issue randomly so I think we do still need a way to increase max allowed heap.

**Comment by thsig** [comment]
Hi @kyungkimsf—we've been trying to reproduce this on our end, but haven't been able to so far.

Could you run a command with the highest log level (`-l 5`) and see if you notice anything there that might offer a clue to the underlying problem?

**Comment by kyungkimsf** [comment]
@thsig I had tried the `silly` log level before and it didn't quite show me anything obvious -- here's the tail end of that -- 
```
Calling git in /Users/myUser/development/myProject with args 'ls-files --ignored --exclude-per-directory .gardenignore'
Calling git in /Users/myUser/development/myProject with args 'ls-files --ignored --exclude-per-directory .gitignore'
Calling git in /Users/myUser/development/myProject with args 'ls-files --ignored --exclude-per-directory .gardenignore'
Calling git in /Users/myUser/development/myProject with args 'ls-files --ignored --exclude-per-directory .gitignore'
Calling git in /Users/myUser/development/myProject/.dev with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/.dev'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Calling git in /Users/myUser/development/myProject/.dev with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/.dev'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Calling git in /Users/myUser/development/myProject/.dev with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/.dev'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/mysql with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/mysql'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Calling git in /Users/myUser/development/myProject/redis with args 'diff-index --name-only HEAD /Users/myUser/development/myProject/redis'
Process memory threshold reached. This most likely means there are too many files in the project, and that you need to exclude large dependency directories. Please see https://docs.garden.io/using-garden/configuration-overview#including-excluding-files-and-directories for information on how to do that.
If this keeps occurring after configuring exclusions, please file an issue at https://github.com/garden-io/garden/issues.
```

for the record, the redis and mysql dirs `data` dirs that are being gitignored which should already be being ignored, I think.

**Comment by kyungkimsf** [comment]
Please let me know if there's anything additional you'd need that I could provide to debug -- many of our engineers are hitting this issue intermittently and would be great if we could find the culprit.

**Comment by kyungkimsf** [comment]
Also, just to give more info, I have one symlinked dir that is pointing to my home dir -- so technically outside of the project dir. It is however, already added to the gitignore -- but I've seen garden throw this error - 
```
(node:26054) UnhandledPromiseRejectionWarning: Error: Path /Usrs/myName/someDir/projectDir/symLinkedDir
is not in a git repository root. Garden must be run from within a git repo. Please run `git init` if you're starting a new project and repository, or move the project to an existing repository, and try again.
    at Object.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/vcs/git.js:0)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/vcs/git.js:0)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:26054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by edvald** [comment]
Ah, that could well be the problem! I've been scanning the code looking for something like that, so this is *super* helpful, thank you! We'll take a closer look. This could also be the source of some performance problems we've noticed in complex projects.

**Comment by edvald** [comment]
So to clarify, you're using git submodules in your project?

**Comment by kyungkimsf** [comment]
we are actually not using any git submodules as far as I know -- which is puzzling as to why we're hitting that code path.

**Comment by edvald** [comment]
It is expected that you'd hit that particular line, but not the line below (225). If you have no submodules this should resolve to the `else` clause below, and not recurse.

How did you spot the recursion btw? It certainly seems there is some recursion happening, just wondering if it's happening right there.

**Comment by kyungkimsf** [comment]
I believe @elliott-davis may be better fitted to answer that question as he's been the one debugging it.

**Comment by kyungkimsf** [comment]
By killing some of the transitive/chained dependencies, we're able to bring up garden without it going into too much recursion. Not the most ideal as we'd like certain services to start if XYZ services are running but it lets us workaround this issue at the moment.

**Comment by edvald** [comment]
Understood. That does give me an indication as to where the issue might lie. I'm working to reproduce on my side. @elliott-davis any additional hints would be useful, but we have a good place to start. This certainly seems like a performance _bug_ and not some design issue, so it's something we should be able to fix once we track it down.

**Comment by vrybas** [comment]
I got a similar issue with not enough memory error. It happens when there are a lot of files in a module and the module is linked to the local source code.
 
When I run `garden deploy -l 5 myservice`, _sometimes_ it fails with ENOMEM error:
```
...
...
Calling git in /path/to/my/service with args 'ls-files --ignored --exclude-per-directory .gardenignore'

Error: ENOMEM: not enough memory...
```

If I count the files in a module I get:
```
$ git ls-files | wc -l
2529
```

Garden version:
```
$ garden version
0.12.5
```

**Comment by edvald** [comment]
Hey @vrybas. Still trying to get a solid reproducible case here. Can you explain what you mean by "the module is linked to the local source code"?

**Comment by vrybas** [comment]
I mean linked with the `garden link`

![image](https://user-images.githubusercontent.com/30538/100240644-da7ef600-2f43-11eb-989b-615cb6851fd9.png)

**Comment by edvald** [comment]
Aha, I see, thanks! I think that narrows it down for sure.

**Comment by edvald** [comment]
I _think_ I've narrowed this down a little, and it has to do with setting the `dotIgnoreFiles` parameter. Setting it to multiple files takes the file scan to a (currently) much more expensive procedure than having just the default or at least a single item in the list. Any chance @vrybas @kyungkimsf @elliott-davis you could avoid using both `.gitignore` and `.gardenignore`, maybe just using the `.gardenignore`?

**Comment by vrybas** [comment]
@edvald deleting the auto-generated `.gardenignore` file from the project folder seems to be helping. The content of `.gardenignore` was
```
# Add paths here that you would like Garden to ignore when building modules and computing versions,
# using the same syntax as .gitignore files.
# For more info, see https://docs.garden.io/guides/configuration-files#including-excluding-files-and-directories
```
