### ISSUE TITLE
[FEATURE]: Make current git branch available as variable

### ISSUE THREAD

**Issue by wyrie** [garden-io/garden#2086]
## Feature Request
Make the current git branch available as a pre-defined garden variable.

### Background / Motivation
We would like to use this as part of our defaultNamespace value. Currently we either have to deploy by manually specifying the branch name with --env or ensure the branch name is available as an evironment variable. 

### What should the user be able to do?
Set, using say local.git-branch, the value of the current branch anywhere in the garden project

### Why do they want to do this? What problem does it solve?
It creates an easy and automated way to work with multiple feature branches by linking them to garden environments.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by thsig** [comment]
Hi @wyrie—we'll look into this one soon.
