### ISSUE TITLE
show-timestamp not working for json logger

### ISSUE THREAD

**Issue by lucas-sonnabend** [garden-io/garden#2095]
## Bug

No timestamps are shown for json-logger

### Current Behaviour

When I run garden with --show-timestamps and json logger I don't get any timestamps
```
$ garden deploy app-config --show-timestamps
[2020-10-06T15:57:15.560Z] Deploy 🚀
[2020-10-06T15:57:15.563Z]
[2020-10-06T15:57:15.564Z] ℹ providers                 → Getting status...
[2020-10-06T15:57:15.821Z] ✔ providers                 → Getting status... → Cached
[2020-10-06T15:57:15.821Z]    ℹ Run with --force-refresh to force a refresh of provider statuses.
```
turns into
```
$ garden deploy app-config --logger-type=json --show-timestamps
{"msg":"Deploy 🚀","metadata":{},"section":""}
{"msg":"Getting status...","metadata":{},"section":"providers"}
{"msg":"Getting status... - Cached","metadata":{},"section":"providers"}
{"msg":"Run with --force-refresh to force a refresh of provider statuses.","metadata":{},"section":""}
```
### Expected behaviour

I get a field called  `timestamp` or similar in the json logger output

### Reproducible example

See above

### Workaround

I don't know

### Suggested solution(s)

see expected behaviour

### Your environment

garden version 0.12.6

macOS

**Comment by lucas-sonnabend** [comment]
I might try my hands at this myself, how hard can this possibly be? :D

**Comment by edvald** [comment]
Looks like @thsig beat you to it .)
