### ISSUE TITLE
Non-root containers cannot retrieve artifacts

### ISSUE THREAD

**Issue by wyrie** [garden-io/garden#2106]
## Bug

When a container is running as a non-root user, or specifically one that does not have access to the root of the filesystemm, extracting artifacts will fail.

### Current Behavior

Running a test that produces an artifact in an environment mentioned above will result in an error:
TAR_BAD_ARCHIVE: Unrecognized archive format

### Expected behavior

The artifact should be extracted and stored in the designated folder

### Reproducible example

See https://github.com/wyrie/garden-example

### Workaround

N/A

### Suggested solution(s)

Change where the placeholder file is created - from the root of the filesystem to a world-readable place.

### Additional context

https://kubernetes.slack.com/archives/CKM7CP8P9/p1602519854087900

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS and docker-desktop

`garden version`
0.12.7

**Comment by thsig** [comment]
This was closed by https://github.com/garden-io/garden/pull/2105, right @wyrie?

**Comment by wyrie** [comment]
@thsig - yes it does

**Comment by tbl-harmoney** [comment]
This seems to be reoccurring on 0.12.34, could we reopen this @thsig?
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/65944949/156152262-33b45ed8-ccda-4e9b-bd92-df3ecf3e5e6e.png">
