### ISSUE TITLE
[FEATURE]: expose service account in tests

### ISSUE THREAD

**Issue by jfri3d** [garden-io/garden#2118]
## Feature Request
Expose service account in tests instead of using default.

### Background / Motivation
Using the default service account is not the best practice and is rather limiting when testing complex stacks with differing permissions...

### What should the user be able to do?
Allow setting a desired service account for tests (and possibly tasks).

### Why do they want to do this? What problem does it solve?
Isolation of service accounts with varying permissions is critical. One such example is having a test (without mocks of course) that deploys a resource in other namespaces. It should be easy to run tests with any service account.

### Suggested Implementation(s)
Expose service account when copying params for the test container.

https://github.com/garden-io/garden/blob/e2f0d8dff8c06f81502ae064f8a88183eeea164e/core/src/plugins/kubernetes/container/test.ts#L30

### How important is this feature for you/your team?
Somewhere between painful and critical.

We either add a RoleBinding to the default service account (yuck) or ignore garden tests and run "tests" inside of a kubernetes resource with an explicit service account (also yuck).

**Comment by thsig** [comment]
Thanks for submitting this, @jfri3d—we're having an internal discussion on this, and will get back to you here soon.
