### ISSUE TITLE
The VSCode Plugin 🔌

### ISSUE THREAD

**Issue by l-korbes** [garden-io/garden#212]
```
Hi! Let's discuss our VSCode Plugin!
  v
╭─╮
⌾ ⌾
│▕│
╰─╯
```

**Comment by edvald** [comment]
Some ideas I've had so far:

- Add a sidebar, similar to the Kubernetes extension, where you can browse projects, modules and deployed services.
- Each of the services could have an icon next to it indicating its deployment status (and an indicator when it's building/redeploying/testing etc).
- Easily look at logs for any running service.
- Check the latest test results - and logs - for each test run.
- Manually deploy/redeploy via context menu.
- Checkboxes to toggle automatic building, testing and deploying.
- Validation and hints for `garden.yml` files.
- View the dependency graph for a project.
- Indicate module status (deployed/tested) in the folder tree.

Architecturally, I think this will all rely on adding a `garden serve` command that exposes a websocket interface. The plugin could post commands to the socket, and logs+events could be posted back as JSON objects, and the plugin would aggregate and resolve them appropriately.

One other thing to consider is #73, which we'll need to address anyway but would be more likely to come up with this running.

**Comment by edvald** [comment]
Oh and of course, tools to make it easy to attach a debugger to a service. That depends on some other work we haven't done yet, but should definitely be possible.

**Comment by ellenkorbes** [comment]
SGTM, with the one addition that it'd be interesting to have a red/green light or an icon at the bottom indicating whether things are in progress or all done. (Without the sidebar visible I mean.)

**Comment by ellenkorbes** [comment]
FYI work on this is suspended in favour of the documentation overhaul. TBC.
