### ISSUE TITLE
Posix path validation fails in windows environments

### ISSUE THREAD

**Issue by wyrie-zz** [garden-io/garden#2120]
## Bug

When using the kubeconfig key and  hadolint provider on windows the path validation fails as it is being tested against a set of posix rules.

### Current Behavior

Setting kubeconfig in the project garden.yaml file to a relative path like `kubeconfig: kubeconfig.yaml` will produce the following error on windows:
```
Deploy
 providers                 → Getting status...
Failed resolving provider kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error validating provider configuration: key .kubeconfig must be a POSIX-style path
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- kubernetes
See error.log for detailed error message
```

This occurs on the hadolint provider as well.

### Expected behavior

A file that exists and is valid should pass.

### Reproducible example

Add `kubeconfig: kubeconfig.yaml` to project yaml and run on windows in shell of choice.

### Workaround

Remove the kubeconfig key and use KUBECONFIG environment variable. Disable hadolint provider :(

### Suggested solution(s)

Looking at the debug output, the kubeconfig key is resolved to a full windows path: `C:\somewhere\project\kubeconfig.yaml`, even when the file is relative to the project root in garden.yaml.

This could be the result of the resolve call in `core/src/plugins/kubernetes/kubernetes/kubernetes.ts`
```
if (config.kubeconfig) {
  config.kubeconfig = resolve(projectRoot, config.kubeconfig)
}
```

This would fail the validation in `PosixPathSchema`?

Could this be altered to handle windows paths. Alternatively resolving the path(s) should be posix compatible.

### Additional context

https://kubernetes.slack.com/archives/CKM7CP8P9/p1603704037191700

### Your environment

* **OS:** Windows
* **How I'm running Kubernetes:** docker-desktop, EKS 

`garden version`
0.12.9

**Comment by wyrie** [comment]
@eysi09 - I've been looking at this some more.

Would it be good to create a unified path validation schema instead of relying solely on posfix paths?

So changing `PosixPathSchema` to `FsPathSchema` and extending the rules to deal with the platform differences, like:
```
absoluteOnly: {
      method() {
        // tslint:disable-next-line: no-invalid-this
        return this.$_addRule("absoluteOnly")
      },
      validate(value, { error }) {
        if (process.platform !== "win32") {
          if (!value.startsWith("/")) {
            return error("absoluteOnly")
          }
        } else {
          if (!(/^(?<drive>[a-z]+:)?\\/ui).test(value)) {
            return error("absoluteOnly")
          }
        }

        return value
      },
    },
```

From what I can tell the scope of this change should be contained to only the validation of the values provided to the schemas as other parts rely on `utils/fs.ts`?

**Comment by ITHedgeHog** [comment]
This issue is now causing us some problems as well. It would be extremely helpful to support this on Windows.
