### ISSUE TITLE
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead

### ISSUE THREAD

**Issue by jscontreras** [garden-io/garden#2123]
### Current Behavior

Following the demo instructions using the latest Docker Desktop 2.4..0.0
````
# when I run
garden deploy
````
the error
```
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead

Here's the full output:

Sending build context to Docker daemon  13.82kB
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
```

### Expected behavior

It should build and deploy to kubernetes correctly

### Your environment

* **OS:** macOS Catalina 10.15.7
* **How I'm running Kubernetes:** Docker Desktop 2.4.0.0

`garden version`
0.12.9

**Comment by edvald** [comment]
I suspect this is a similar problem as this issue: https://github.com/rancher/k3s/issues/1708

Basically it appears they've changed their API somewhat in the latest version, so we need to look into how we can address that in a way that works across the new version and older versions as well.

**Comment by eysi09** [comment]
Hi @jscontreras 

I've been unable to reproduce this on my end. Would you mind sharing your provider configuration?

**Comment by eysi09** [comment]
Scratch that, I'm seeing this issue on my end as well now.

**Comment by jscontreras** [comment]
Oh I'm glad you are seeing it too! Thanks for looking into this. Is kind of an issue that this is happening with the official getting started documentation (maybe add a note while you guys fix it?) I lost a ton of time thinking I was doing something wrong
Thanks

**Comment by eysi09** [comment]
Yeah good point. I'm hope to be able to roll out a fix later today. But in the meantime, the following should do the trick:

1. Open Docker for Desktop preferences.
2. Click Docker Engine tab.
3. Add `"features": { "buildkit": true }` in the input field.

See also:

<img width="1250" alt="Screenshot 2020-11-06 at 17 23 25" src="https://user-images.githubusercontent.com/5373776/98389772-cfc3f600-2054-11eb-95c0-443ff5e2d1d0.png">

**Comment by eysi09** [comment]
Looks like this was an issue with Docker all along. The offending code was removed in this commit: https://github.com/docker/docker-ce/commit/95971a49f97defa51b166211fbd6d44080540a62, but it hasn't been released yet.

I'm not sure there's much we can do about this on our end except ask users to do one of the following: 

- Downgrade the Docker CE (i.e Docker for Desktop) server version (to 19.x.y, I believe), or
- upgrade the Docker CLI version (to 20.x.y, I believe), or
- apply the fix in my previous comment.

There was also a question about this on StackOverflow, here's [my answer](https://stackoverflow.com/a/64746532/5629940), in case the conversation turns up more useful information.

I'll also make sure to add an entry on this in the Troubleshooting section of our docs.
