### ISSUE TITLE
[FEATURE]: Extend the initScript from the exec provider to allow cross-platform execution without relying on bash

### ISSUE THREAD

**Issue by wyrie** [garden-io/garden#2124]
## Feature Request

The iniScript function currently relies on bash being available on the platform running the garden project. It would useful to have control over the execution environment as part of the initScript configuration.

### Background / Motivation

Discovered by some of our windows users that drive their project from powershell, which fails for them in that environment.

### What should the user be able to do?

Use initScript on any platform with any of the primarly shell environments

### Why do they want to do this? What problem does it solve?

Allows the use of initScript without the need to install bash

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
Makes sense, but I wonder how best to actually solve this. Do your developers on Windows have/use WSL? I wonder if that's ultimately the best approach here, since otherwise the actual script won't work across platforms.

**Comment by wyrie** [comment]
Some have WSL, but we've been trying to steer clear of it to avoid the extra overhead associated with running WSL. In and of itself it would be fine but we're trying to keep the door open on local cluster deployments and our stack is very heavy.

Is the same form as docker command+args viable?
```
initScript:
  command: [powershell]
  args: [/path/to/script]
```

**Comment by edvald** [comment]
Understood, makes sense. I think your suggestion could be viable, but I'll think a bit about the exact configuration schema to see how best to lay it out. We've also been considering making this feature a little more native to Garden, as opposed to buried on the exec provider, so perhaps we'll do that at the same time.
