### ISSUE TITLE
[FEATURE]: Add container module config option to disable image push

### ISSUE THREAD

**Issue by Cpcrook** [garden-io/garden#2136]
We're utilizing `garden` with a dotnet core suite of services, so our images are...hefty...to say the least.  Generally, producing an image capable of running our tests requires a dotnet SDK image of at least ~600mb, plus any additional tooling and source, leading to an image size of greater than 1GB in many cases for projects that incorporate JS (i.e. react + aspnet core).

For the `garden dev` story, it would be extremely useful to us to have the ability to build and run tests against an intermediary target dockerfile stage in a specific module, but not push that container up to our private docker registry, in order to not spend quite a while uploading a +1GB image.

Perhaps we're thinking about this wrong, but it would seemingly be helpful to have the ability for a given `container` module to disable publishing of the image produced, while still being able to report on tests.  It would greatly tighten up our testing feedback loop within the `garden dev` story.

Maybe something along the lines of:

```
  ...

  # For multi-stage Dockerfiles, specify which image to build (see
  # https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target for details).
  targetImage:

  # Push the image built to the container registry specified in project.garden.yml
  pushImage: true

  ...
```

Maintains current behavior but allows the ability to disable pushing the image.  If this is something you all are open to including, I may take a stab at implementing it.

**Comment by thsig** [comment]
Hi @Cpcrook—for running tests against an intermediate Dockerfile stage, were you thinking that the image should be run as a local Docker container?

Pushing to a registry is how we make the image available to Kubernetes, so I'm curious to hear what sort of setup/flow you had in mind here.

**Comment by Cpcrook** [comment]
Yes, I think that's ultimately what we'd ultimately want in certain situations. I understand it's a different kind of use case, but here's how we have things setup:

Our C# projects have container modules ultimately produce a final build image with only the binaries & static files required to run the services, which utilize the much-smaller dotnet runtime image -- so the final image being pushed is ~250MB vs up to 2.5GB.  These make sense to push up to the registry in order to deploy them to the cluster as they change during development.  If we want to debug any of these individual services, we utilize telepresence to swap out deployments.  That side works great.

Where it gets weird:  since those images are our final runtimes, they do not contain the infrastructure nor the code for our tests, which reside in a separate C# project in our repository (common practice).  As such, we can't run tests as part of those garden module definitions in order to have them reported in the stack graph.

Our solution was a separate container module that produces a "test" stage image, which _does_ include our test code, as well as the infrastructure to run them (e.g. utilizing the dotnet sdk base image), and does so.  We then had this as a dependency of the actually-running application module within garden.  In this case, we don't really care about the container reaching the registry or the cluster -- we only care about the test commands passing when run in the container (which could happen locally -- to be clear, these are unit and integration tests, and functional tests utilizing extensive mocking functionality provided by dotnet test harnesses like WebApplicationFactory).

I guess the alternative solution is to consider the tests run as part of the building the final image in the first place, but we were hoping for better reporting/transparency in the garden dashboard stack graph, which that doesn't accomplish.

Going forward, as we add E2E tests and API contract testing, obviously running tests within the cluster in order to hit "real" resources, more closely matches the existing use case where containers _are_ pushed to the registry and deployed to the cluster.  In that case, those tests can be separately containerized without issue since they don't rely on application code itself.
