### ISSUE TITLE
[Question] Is it possible to log output from exec build command?

### ISSUE THREAD

**Issue by ig-5g** [garden-io/garden#2139]
I have an `exec` module that looks like this

```
kind: Module
type: exec
name: setup-namespace
local: true
include: []
build:
  command:
    [
      ./setup-namespace.sh, $arg1, $arg2
    ]
``` 

`setup-namespapce.sh` echo-es diagnostic messages to the standard output. I am not able to see these messages when I run `garden deploy`. I tried bumping the log level all the way to "silly" - it does not help.

Is there any way to capture script messages in garden logs?

Thank you.

**Comment by eysi09** [comment]
Hi @ig-5g 

This will be possible by setting the log level to verbose or great once #2144 is merged.

For example: `garden build --log-level verbose` or `garden build -l 3`. 

You can also currently get the command result which includes the build logs with `--output json | -o json` option. For example: `garden build -o json`.
