### ISSUE TITLE
Dashboard: Need to refresh server to get updated test results

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2145]
### Current Behavior

If I re-run tests while the dashboard server is running, the UI still shows the previous test results.

### Expected behavior

It should show the latest results.

### Reproducible example

1. Open dashboard.
2. Run test and open results
3. Change code and re-run test so that it e.g. breaks
4. Re-open test results
5. Observe that you still see the old test results.

### Workaround

N/A

### Suggested solution(s)

Haven't really investigated but this is probably because we're not creating a new Garden instance when re-fetching.

### Additional context

N/A

### Your environment

Latest master.

**Comment by eysi09** [comment]
@edvald, do you know what the issue might be here? I'm pretty sure we fixed something very similar the other day.

**Comment by thsig** [comment]
Since we're deprecating the dashboard soon, I'm closing this one for now.
