### ISSUE TITLE
[FEATURE]: Expose `${environment.production}` in template strings

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#2149]
## Feature Request

This was suggested by a user on our community Slack.

Expose the value of the `environments[].production` field in template strings.

### Background / Motivation

The `${environment.production}` flag would be a useful shorthand for something like

```
// Container module used instead of helm chart for other environments than production and staging
disabled: ${environment.name == 'dev' || environment.name == 'ci' || ...}
```

### What should the user be able to do?

For example: `disabled: ${!environment.production}`

### Suggested Implementation(s)

This would be a simple matter of providing this variable to the relevant config contexts.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by 10ko** [comment]
Hi @arghya88 👋,
I don't think we have a bot that can act on that command. :)
Were you thinking of give this a try?

**Comment by arghya88** [comment]
@10ko yes..please assign this to me

**Comment by arghya88** [comment]
@thsig being new to this and typescript I need more clue on how to do this. How to provide this variable to the relevant config contexts? I found `EnvironmentContext` which probably exposes `environment.name` and `EnvironmentConfigContext` which exposes `environments[]` fields except `name`
