### ISSUE TITLE
Empty variable shouldn't be passed with "null" value

### ISSUE THREAD

**Issue by ArnaudRinquin** [garden-io/garden#2152]
### Current Behavior

ENV variables with empty value, like the following yaml, are passed as `FOO=null`:

```yaml
tests:
  - name: unit
     env:
        FOO: 
```

### Expected behavior

Just don't push them to the POD spec or maybe as empty string?

### Reproducible example

Should be straighforward

### Workaround

Just remove the silly declaration.

### Suggested solution(s)

Omit the ENV variable

### Additional context

`FOO=` declaration similar config is valid in docker compose (that's how it ended up in our garden config).

**Comment by eysi09** [comment]
You're right, good catch!

I think this is one of those unfortunate cases where users have come to depend on the (wrong) behaviour so we need to flag this as a breaking change and address in our next breaking release.

**Comment by vvagaytsev** [comment]
Closing this as a stale one. @ArnaudRinquin please let us know if this is still and issue.
