### ISSUE TITLE
Dashboard breaks when hostname contains a wildcard

### ISSUE THREAD

**Issue by ArnaudRinquin** [garden-io/garden#2170]
### Current Behavior

Following #2137, wildcards (`*`) are allowed in the hostnames but this seems to break the dashboard which deems them as invalid.

### Expected behavior

Not break.

### Reproducible example

Open dashboard on a config that has something like `*.whatever.garden.dev`

### Workaround

After digging the [codebase](https://github.com/garden-io/garden/blob/master/dashboard/src/util/helpers.ts#L59-L72), I figured specifying linkUrl would fix the situation.

### Suggested solution(s)

Just allow it.

### Additional context

Here is a screenshot:

![Screenshot 2020-12-15 at 10 38 09](https://user-images.githubusercontent.com/228886/102198363-95a30b00-3ec2-11eb-8628-a45f8743472a.png)

### Your environment

* **OS:** OS X Big Sur
* **How I'm running Kubernetes:** GKE

`garden version`

0.12.11

**Comment by eysi09** [comment]
Hi @ArnaudRinquin 👋 

Thanks for flagging this, I think it has to do with the library use for parsing URLs. Should be a simple fix.

**Comment by eysi09** [comment]
For those bumping into this, note that it works fine on Chrome. Looks like the Firefox, and perhaps other browser, implementations of the `url.format` function throws on hostnames that contain `*`, which, tbh, is probably what it should do.
