### ISSUE TITLE
garden test on helm module doesn't seem to run test post mounting of secret volume

### ISSUE THREAD

**Issue by zzztimbo** [garden-io/garden#2171]
I have a helm chart for a deployment that relies on a secret to be mounted in the pod. 
Whenever I run `garden test` my tests fail with an error saying my secret file does not exist. When I exec into the running pod, the tests run fine. 

Is there a way to specify that the tests should be run in the deployed container (which, for sure, has the secret mounted)?

**Comment by zzztimbo** [comment]
I see that a whole new pod is being spun up to run the test. 
```
Starting Pod test-gbo-dbt-helm-dev-data-426565 with command 'dbt --no-use-colors test'
Running with dbt=0.18.0
Found 62 models, 30 tests, 0 snapshots, 0 analyses, 155 macros, 0 operations, 0 seed files, 0 sources

Encountered an error:
[Errno 2] No such file or directory: '/var/run/secrets/cloud.google.com/service_account.json'
Test failed!
```

**Comment by eysi09** [comment]
Hi @zzztimbo 

Thanks for opening the issue. Handing this one off to @thsig who's been working on related parts of the codebase recently and probably has the most context.
