### ISSUE TITLE
[FEATURE]: Terraform 0.14 support

### ISSUE THREAD

**Issue by Pacobart** [garden-io/garden#2181]
### Background / Motivation

We'd like the ability to use the latest major release of Terraform with Garden.

### What should the user be able to do?

Install Terraform 0.14.x and use it instead of the default 0.13.3 Garden provides.

### Why do they want to do this? What problem does it solve?

Keeps us up-to-date on latest features.

### Suggested Implementation(s)

I believe the option to set a specific terraform version already exists. Allowing 0.14.x as part of the regex match is all that's needed.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Hi @Pacobart 

This is simple to add. We'll need to enable the regex and add the path to the bin. We'll look into this.

**Comment by eysi09** [comment]
I just realised there's actually one workaround.

You can explicitly set the `version` field to `null` and then Garden will pick the system version of the tool. One thing to look out for is whether the Terraform CLI interface has changed at all between the version. Garden basically shells out to Terraform and makes assumptions about the commands, options and outputs. 

It would be super helpful if you could give it a spin and see if it works on your end before we make the change.

**Comment by Pacobart** [comment]
@eysi09 I tested and validated I am able to set the terraform version to `null` and it uses my system installed version 0.14.4

**Comment by Pacobart** [comment]
Bump. We are running into issues where setting `version: null` isn't being honored by garden and is still using 0.13.3. We'd like to at least have the matching updated so we could use terraform `0.13.6`. Thoughts?

**Comment by edvald** [comment]
Hmm, curious what the issue with `null` is, need to look into that. Any pattern to how/where/when that's coming up? 
But yep, we can get on this regardless.
