### ISSUE TITLE
Dangling Kaniko pods

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2184]
### Current Behavior

Kaniko pods are not always (never?) cleaned up after builds. The `garden-system` namespace fills up with them and they need to be deleted manually. Some are in error state and some are completed.

I haven't yet confirmed whether they're never cleaned up or if it fails intermittently.

### Expected behavior

I don't need to think about Kaniko pods.

### Reproducible example

Build a project with `buildMode: kaniko`. 

### Workaround

Run the following (assuming you have awk installed) every now and then:

```console
kubectl get pods -n garden-system | awk '/kaniko-garden-system-/{print $1}' | xargs kubectl delete pod -n garden-system
```

### Suggested solution(s)

Make sure we delete the pod at the end of the build. Unless we think it's a good idea to keep them around for debugging purposes, in which case could decide to only older pods. Feels brittle though.

### Additional context

N/A

### Your environment

We've seen this for projects using EKS and GCP and across different container registries.

Kaniko version: `gcr.io/kaniko-project/executor:debug-v1.2.0`

Garden version: latest master

**Comment by eysi09** [comment]
The pods do indeed terminate in some instances. Not sure why even successful ones are sometimes left dangling. I'm assuming the process is not exiting with 0 for some reason.

**Comment by Chipcius** [comment]
To me this looks like if the garden process is interrupted on my machine the Kanko pods are not cleaned up after builds.

Example the process terminated by `CTRL+C`

**Comment by vvagaytsev** [comment]
Closing this as stale. @eysi09 @Chipcius feel free to reopen it if it's still an issue.
