### ISSUE TITLE
[FEATURE]: Helm chart to install cluster services

### ISSUE THREAD

**Issue by ghost** [garden-io/garden#2186]
## Feature Request

It seems there's no Helm chart available on https://artifacthub.io/ to deploy the cluster services. Instead, from what I could figure out from the code, it generates charts on the fly and deploy them using the CLI.

I would like to be able to install the cluster wide services from Helm charts to have more control over which version is deployed to which cluster and when.

### Background / Motivation

Our policy is to use Helm charts to deploy cluster services. It helps us test software on our test cluster, and then promote version upgrade through other environments. 

### What should the user be able to do?

Use charts hosted either on the central https://artifacthub.io/ or Garden specific charts repo.

### Why do they want to do this? What problem does it solve?

Relying on dynamically generate charts by the CLI seems prone to errors as a different version of it might generate different charts.

### Suggested Implementation(s)

Best case scenario would have the charts published to https://artifacthub.io/. Otherwise, a subcommand on the CLI that would generate charts could work as well. The charts end up in .garden in your project directory, we could always copy them, but that's a PITA.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful. Potentially a deal breaker.

**Comment by jftheroux-devolutions** [comment]
Also, by having to create a project to deploy the cluster wide services, it forces us to create a fake project, which creates empty namespaces in our clusters. Which we need to deploy after.

**Comment by edvald** [comment]
I think this is a reasonable request and we can certainly look into it. The original technical reasons for using a plugin command have been gradually chipped away, and we're actually longer-term aiming to avoid needing the cluster-wide services entirely. I'll do a quick investigation to see how easy/feasible it would be to make a Helm chart in the meantime.

**Comment by jftheroux-devolutions** [comment]
In the meantime, can I assume that version X of the CLI will always generate the same configuration? If that's the case, I can work around the issue for now. While I would still prefer to have charts.

**Comment by edvald** [comment]
That is correct. The same CLI version and same project configuration will result in a deterministic setup.

**Comment by jftheroux-devolutions** [comment]
What happens let's say I deploy version X in our clusters with our CI and a developer upgrades his CLI to Y, do both need to match?

**Comment by edvald** [comment]
If there is a material difference between what the newer CLI (or different configuration) expects, a warning may be shown, but users should not be affected. We rarely make such changes to begin with, and only make breaking changes (e.g. add a new service) in breaking Garden releases, which are quite few and far between. We have no current plans for such changes, except to remove services actually, which would not cause any issues for users.
