### ISSUE TITLE
When opening mutliple dashboards, the url in the logs contains the wrong port

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2188]
### Current Behavior

When running multiple dashboards, the info log showing the dashboard url contains the url of the first opened dashboard.
Additionally (it seems) gets updated with the latest created dashboard port. 

See below:

<img width="832" alt="Screenshot 2021-01-07 at 17 13 56" src="https://user-images.githubusercontent.com/2706375/103916536-d7fbe880-510c-11eb-8aef-94122fd0b7aa.png">

### Reproducible example

Just run the command `garden dashboard` in two separate terminals.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
Closing this as "Won't fix", see the comments in the attached PR.
