### ISSUE TITLE
git submodules with depth > 1

### ISSUE THREAD

**Issue by OliverSanftleben** [garden-io/garden#2201]
### Current Behavior

When using Remote Sources, Git submodules with depth > 1 will not be checked out. As a result, garden will hang at build (see https://github.com/garden-io/garden/issues/2119)

In the logs you can see that garden calls 'git clone --recursive --depth=1 ...'

### Expected behavior

Git submodules should be checked out with no depth limit

I'm expecting command

'git clone --recurse-submodules ...'

without depth parameter

### Reproducible example

sorry I have no

### Workaround

not known

### Suggested solution(s)

change command for git clone (or give the possibility to configure it)

### Additional context

related:
https://github.com/garden-io/garden/issues/1277
https://github.com/garden-io/garden/issues/2119

### Your environment

* **OS:** Windows 10
* **How I'm running Kubernetes:** Docker desktop

`garden version`  0.12.9

**Comment by edvald** [comment]
Thanks for flagging this @OliverSanftleben. I think you're right, we should simply skip the depth parameter, we'll take a look.

**Comment by Orzelius** [comment]
Garden will no longer hang at build after #2923. 

I'm not too sure about removing the depth parameter as you wouldn't always want to check out all submodules' submodules. You can always pull them manually though and garden will recognize them that way.
