### ISSUE TITLE
I am amble to create a project with an upercase letter in name but get error when building

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2202]
## Bug
When I am creating a new project with an uppercase project name and then build I get an error 

### Current Behavior

```
Error validating project: key .name with value "Test" fails to match the required pattern: /^(?![0-9]+$)(?!.*-$)(?!-)[a-z0-9-]{1,63}$/
```

### Expected behavior

I should not get an error

### Reproducible example

```
mkdir mytest
cd mytest
git init
garden create project --name Test
garden build
```

### Workaround

Fix the name in the `project.garden.yml` to lowercase

### Suggested solution(s)

I should get a warning or some check to tell me I am being stupid and need to have a lowercase name or garden should fix it for me

### Your environment

* **OS:** Ubuntu 20.04.1 LTS
* **How I'm running Kubernetes:** Doesn't matter as I never get that far 
* **Garden version:** 0.12.12`

**Comment by edvald** [comment]
Good catch, thanks for reporting! We should fix that with a bit of validation in the create command.
