### ISSUE TITLE
when linking a terraform module for local development, garden is complaining about initRoot missing when trying to display the plan

### ISSUE THREAD

**Issue by jftheroux-devolutions** [garden-io/garden#2221]
### Current Behavior

I'm using the following module at the moment:

~~~
kind: Module
type: terraform
name: app-service
autoApply: ${var.terraform["autoApply"]}
allowDestroy: ${var.terraform["allowDestroy"]}
root: '.'
repositoryUrl: file:///Users/jft/src/garden/garden-app-service#master
variables:
  name: ${var.appservice['name']}
  service_plan_name: ${var.appservice['servicePlan']}
  service_plan_resource_group: ${var.appservice['resourceGroup']}
  subscription_id: ${var.appservice['subscription_id']}
~~~

I've linked my module locally by running `garden link module app-service /Users/jft/src/garden/garden-app-service`

After making a change to my Terraform code, I'm running the following command to see what would be applied `garden plugins terraform plan-root`

And I get this error:

~~~
terraform provider does not have an initRoot configured
~~~

But running `garden deploy` works and applies the change.

My provider is configured like this:

~~~
providers:
      - name: terraform
        version: null
~~~

### Expected behavior

Expecting the plan to be displayed.

### Reproducible example

Shown above.

### Workaround

I can run `terraform plan` directly in the directory containing the Terraform code.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** AKS
* **Garden version:** 0.12.12

**Comment by edvald** [comment]
Hey @jftheroux-devolutions. If I'm not misunderstanding, I _think_ this might be an issue of just using the wrong plugin command. Per your example, the idea is that you'd use `garden plugins terraform plan-module app-service`, instead of the `plan-root` command. Does that work?

**Comment by jftheroux-devolutions** [comment]
Debugged on Slack with Jon. User error.
