### ISSUE TITLE
All cli commands failing.

### ISSUE THREAD

**Issue by singerxt** [garden-io/garden#2231]
### Current Behavior

All commands from the garden _cli_ failing with `Command "git rev-parse --show-toplevel" failed with code ENOENT:`

```
➜  api-service-garden git:(main) ✗ garden dashboard
Dashboard 📊


🌻  Garden dashboard running at http://localhost:9700
Command "git rev-parse --show-toplevel" failed with code ENOENT:

See error.log for detailed error message
➜  api-service-garden git:(main) ✗ garden deploy
Command "git rev-parse --show-toplevel" failed with code ENOENT:

See error.log for detailed error message
➜  api-service-garden git:(main) ✗ garden logs
Command "git rev-parse --show-toplevel" failed with code ENOENT:

See error.log for the detailed error message
```

I started experiencing this issue after doing multiple `garden link source ${project_name} ${path_to_repo}`

error.log file
```
errno: ENOENT
code: ENOENT
syscall: spawn git
path: git
spawnargs: []
originalMessage: spawn git ENOENT
shortMessage: |-
  Command failed with ENOENT: git rev-parse --show-toplevel
  spawn git ENOENT
command: git rev-parse --show-toplevel
stdout: ''
stderr: ''
all: ''
failed: true
timedOut: false
isCanceled: false
killed: false
```

my git client seems to work as expected :-)

### Expected behavior

Commands are working.

**Comment by edvald** [comment]
Hmh, never seen that one before. The ENOENT error generally means "no such file or directory", which by looking at the code, in this case could refer to either not being able to find `git` or the directory it's attempting to run it from. So my first question to rule out the basics would be: Are you _absolutely_ sure all the `${path_to_repo}`s  that you linked to point to directories that actually exist? :P

Apologies if they do but that's the first thing I'd want to double-check. Not to say we shouldn't be reporting a more helpful error if that's the case btw, or that it couldn't be something else, but that's step 1 to confirm :)

**Comment by singerxt** [comment]
Yeah, it is. However, now I cannot unlink it too. 

```
➜  api-service-garden git:(main) ✗ garden unlink source ts-ticket-demo
Command "git rev-parse --show-toplevel" failed with code ENOENT:

See error.log for detailed error message
```

**Comment by edvald** [comment]
You could try removing the `.garden` directory, which will basically reset the links, and then try linking the sources one by one to see if there's a particular source that's causing the problem (which would be my suspicion). When you find one that causes an error, it'd be handy to see what the paths are, and see if there's something we can glean from those.

**Comment by singerxt** [comment]
@edvald You were right I was pointing to a folder that does not exist. However, you might want to validate input for the `garden link` command in the future. Because I was able to broke the whole CLI because of that :-).

Thank you for all your help
