### ISSUE TITLE
Add `garden delete service` command

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#224]
It would be nice to be able to halt/remove a specific service in some scenarios. For example, I managed to confuse K8s somewhat by hopping between a GCF and an OpenFaaS implementation as I switched branches, in which case it'd be nicer to be able to just remove the affected service and not have to wipe the whole environment.

**Comment by eysi09** [comment]
Good point. Should I take this one on since I wrote the `delete env` command?

**Comment by eysi09** [comment]
How do we want to handle services that depend on the service being deleted?

**Comment by edvald** [comment]
I don't think we should handle it specifically in the command, since it's not intended to be used as part of a standard workflow. Basically missing dependencies will be resolved whenever the user runs `garden dev/deploy` next.

**Comment by eysi09** [comment]
Resolved in #240
