### ISSUE TITLE
Unable to use standard docker image with Github and deploy keys (Missing SSH)

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2261]
## Bug
When building with a private remote repository using SSH it fails as SSH is not installed on the default CI docker image `gardendev/garden:0.12.16`

### Current Behavior

```
Error: Command "git clone --recursive --depth=1 --branch=<redacted> git@github.com:<redacted> /drone/src/.garden/sources/module/<redacted>--5a347299b1" failed with code 128:

Cloning into '/drone/src/.garden/sources/module/<redacted>--5a347299b1'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

### Expected behavior

The default image should have openssh-client installed to allow for a full git clone using SSH

### Reproducible example

1. Setup a module with remote repository using the ssh remote (git@github.com:<team>/<repo>)
2. Build using the CI build image `gardendev/garden:0.12.16`

(Remember to hook up your SSH key if required for the repository)

### Workaround

Create your own image with `gardendev/garden:0.12.16` as base and install `openssh-client`

```
FROM gardendev/garden:0.12.16
RUN apk add openssh-client
```

### Suggested solution(s)

Add openssh-client package to the build image

### Your environment

* **OS:** gardendev/garden:0.12.16
* **How I'm running Kubernetes:** EKS
* **Garden version:** 0.12.16

**Comment by edvald** [comment]
Gotta love a one-line PR, just in time for today's release .)
