### ISSUE TITLE
[FEATURE]: Self update on garden cli 

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2266]
## Feature Request
It would be really nice to have a self update on the garden cli interface to simplify the update process when a new release comes out

### Background / Motivation

I have 20+ guys and gals working with Garden and telling them to use the install script for updating the garden environment every time there is a new release is going to get old really fast and people are going to lag behind. On the other hand to poke them to just run another command on the `garden` tool they run every day is not that hard

### What should the user be able to do?

I envision users pretty much running a command like shown here below to trigger the update. In the short term if this just run the install script from the website to override the current installation, that is fine by me, as long as garden gets updated

```
garden self-update
```

### Why do they want to do this? What problem does it solve?

- Simplifies updating of CLI
- Makes easier to keep developers up to date

### Suggested Implementation(s)

```
garden self-update
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
That makes a ton of sense. It's been on our radar for a bit, just needed a nudge to prioritize it .) It's conceptually pretty easy to update Garden in place, since it's really as easy as replacing the files in the installation directory. I'll have a look this week.

**Comment by ITHedgeHog** [comment]
Whilst we have a smaller team, it is one of the barriers to the adoption of garden.io to our process. It would be awesome if it came sooner rather than later.

**Comment by eysi09** [comment]
I agree, this would be a great addition!

**Comment by 10ko** [comment]
Just for posterity, the `garden self-update` command has been released in Garden [0.12.25](https://github.com/garden-io/garden/releases/tag/0.12.25).

See docs: https://docs.garden.io/reference/commands#garden-self-update
