### ISSUE TITLE
Error validating configure container output from provider local-kubernetes

### ISSUE THREAD

**Issue by langfors** [garden-io/garden#2282]
### Current Behavior

Getting this error message which I am unable to understand:

`admin-ui: Error validating configure container output from provider local-kubernetes: key .moduleConfig.include[1] must be a relative sub-path (may not contain '..' segments or be an absolute path)`

### Expected behavior

I had a nice configuration building and all of a sudden I am getting this error I can't seem to get past.

### Your environment

OSX with Docker using built-in k8

0.12.17

**Comment by langfors** [comment]
I solved this by using specific includes in the module yml

**Comment by edvald** [comment]
Ah, good catch @langfors. It could have been some inferred paths from the Dockerfile. Do you see any suspects in the Dockerfile? I'd be keen to fix that, probably something to do with the Dockerfile parsing that we do.
