### ISSUE TITLE
Allow --env with plugin commands like terraform

### ISSUE THREAD

**Issue by failshell** [garden-io/garden#2284]
### Current Behavior

--env isn't supported by garden plugin commands.

### Expected behavior

I would like to be able to specify an environment to be able to test changes.

### Reproducible example

Run something like `garden plugin terraform plan-module -- test-module --env=test`

### Workaround

Change default environment in project definition.

### Your environment

* **OS:** macOS
* **Garden version:** 0.12.17

**Comment by edvald** [comment]
This is actually supported, you just need to put the flag before the `--` flag (which is intended to separate Garden options from the plugin command options).

**Comment by failshell** [comment]
ah yes, my bad. that works.
