### ISSUE TITLE
[FEATURE]: Configurable resource requests for container type services

### ISSUE THREAD

**Issue by noizwaves** [garden-io/garden#2309]
### Background / Motivation

We are currently running into issues when deploying preview environments to an EKS cluster that I think could be solved with [configurable resource requests](https://github.com/garden-io/garden/blob/master/core/src/plugins/kubernetes/container/deployment.ts#L348-L353).

### What should the user be able to do?

Specify resource requests per service in a container module type.

### Why do they want to do this? What problem does it solve?

Our deployments consist of 10s of pods, which when started can consume hundreds (up to a thousand) of MBs of memory. Currently, when Garden creates the kubernetes manifests, it assigns each pod a fixed resource request limit. For 15 pods, that amounts to ~1.5gb (15 * 100) of memory, and these pods are allocated. However, once the pods start, they will grow to consume ~ 4.5gb (15 * ~300) of memory.

We would like to be able to capture these known memory requirements as custom resource requests, so that kubernetes can distribute our pods across nodes and also trigger cluster auto scaling (when the request resources cannot be fulfilled by existing nodes).

The current values cause our deployments to cause a significant number of OOMs and pod relocations that are disruptive to users. Being able to specify custom values would help us prevent this.

### Suggested Implementation(s)

For a container module type, a service should have configurable resource requests (just like they can for [resource limits](https://docs.garden.io/reference/module-types/container#services-limits)):

```
services:
  requests:
    cpu: 1000
    memory: 1024
```

These values would override the defaults [used here](https://github.com/garden-io/garden/blob/master/core/src/plugins/kubernetes/container/deployment.ts#L348-L353).

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @noizwaves 

You can of course work around this by using the `kubernetes` module type. And with module templates, you can prevent duplicating the config. [Here's our guide](https://docs.garden.io/using-garden/module-templates) on the topic. Do you think that would make sense for your use case?

That being said, the `container` module type is pretty popular and almost exclusively used with the K8s provider, so it's certainly tempting to expose more K8s primitives (and Docker Compose has a notion of resource reservations, so it does apply more broadly). I'll take this up with the team internally and circle back. In any case it's simple to implement.

**Comment by eysi09** [comment]
Just to follow up, we've decided to add resource requests to the container module type. Thanks for the suggestion!

**Comment by noizwaves** [comment]
Great, thanks for the update @eysi09 !

**Comment by thsig** [comment]
This was implemented in #2392, looks like we forgot to close this issue at the time.
