### ISSUE TITLE
[FEATURE]: Support targetImage flag in Test Commands

### ISSUE THREAD

**Issue by ITHedgeHog** [garden-io/garden#2312]
### Background / Motivation

As a .Net Core developer I am used to only running the test suite of my application in the build stage of my docker container, against the .Net Core SDK. When publishing the project to the final stage of the docker container the test suite is not included, as it is not required in production.

Currently I have to maintain two module definitions for every .Net Core application, one which targets the build stage and runs the unit / integration tests and a second which targets the final stage which consists of the application ready to run.

### What should the user be able to do?

When specifying the unit tests to run the user should be able to specify the build stage of the docker file too, to allow for a single module definition to cover a .Net Core Application

### Why do they want to do this? What problem does it solve?

To reduce the need for duplication of module definition, and also to increase the understandability of Garden in a .Net Core application. Current feedback from my team is that the whole process is difficult to understand, especially as it may be months in between needing to modify this part of the module definition.

### Suggested Implementation(s)

Add targetImage flag to the Unit Test Definition and have the command run in that stage of the docker image

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by ITHedgeHog** [comment]
Duplicate of  2330

**Comment by graemechristie** [comment]
@ITHedgeHog  - I'm not sure #2330 is related to this one. #2330 is around Garden not refreshing Auth Tokens.
