### ISSUE TITLE
`garden dev` doesn't deploy the same way `garden deploy` does

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#232]
See recording:

[![asciicast](https://asciinema.org/a/noyyELQc3RmMcYm0EudpoMuE2.png)](https://asciinema.org/a/noyyELQc3RmMcYm0EudpoMuE2)

**Comment by edvald** [comment]
@eysi09 reproduced this as well. I'll look into it.

**Comment by eysi09** [comment]
I was just getting started looking into this. The pod and service are running fine after doing `garden dev` and `curl http://hello-container.hello-world.local.app.garden:32000/hello` also works. It's just the `call` command that fails.

**Comment by edvald** [comment]
It appears that this has been fixed, after recent refactoring. Closing.
