### ISSUE TITLE
[FEATURE]: Support Module Type Pulumi

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2340]
### Background / Motivation

We currently use Pulumi to deploy our k8s applications and infrastructure.  Would love to use Garden but we it would need to support Pulumi.

### What should the user be able to do?

Use pulumi to deploy to k8s applications and infrastructure.

### Why do they want to do this? What problem does it solve?

Ability for devs and our CI to use Garden.

### Suggested Implementation(s)

Similar to terraform module.

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

**Comment by eysi09** [comment]
Hi @tedchang77 

That's a super interesting feature request. We've talked about Pulumi support before but haven't really found time to action it.

We're trying to keep a sensible scope on the number of plugins supported by the Garden team and there's not a lot of Pulumi expertise on the team. That being said, I think this would make perfect sense as a community supported plugin. Is that something you or someone on your team would be interested in looking into? We'd be more than happy to help you get started and provide support and direction.

**Comment by tedchang77** [comment]
Hi @eysi09,

I was able to integrate pulumi with Garden using the exec and kubernetes module. We are currently in the process of evaluating Garden and if we decide to move forward this is something that we would definitely consider.  Would it make sense for this community plugin to utilize the plugin SDK that will be published later this year?

**Comment by edvald** [comment]
Hey @tedchang77. Glad you weren't blocked on this. But yes, I think their new SDK would definitely be the way to go. It'd actually be a really nice feature and should be fairly easy to do. Once you're further along we'd be happy to dig into that with you, even do some pairing as needed.

**Comment by tedchang77** [comment]
@edvald any timelines on when the SDK will be available?

**Comment by edvald** [comment]
This is in progress!

**Comment by tedchang77** [comment]
@edvald this is very exciting! Let us know if you need any input on this feature or if you have questions about Pulumi.
