### ISSUE TITLE
git submodules with 0.12.20 (no bug with 0.12.17)

### ISSUE THREAD

**Issue by OliverSanftleben** [garden-io/garden#2365]
### Current Behavior

When git submodules have no garden.yml (and they are not excluded with .ignore) some random files for config are loaded.

![grafik](https://user-images.githubusercontent.com/15686824/116090081-c9c5de00-a6a3-11eb-804a-8f39ad4588b5.png)

### Expected behavior

Projects without garden.yml should be ignored.

### Workaround

Explicitely exclude git submodules with .gardenignore

### Suggested solution(s)

See "Expected behavior"

### Your environment

* **OS:**   Ubuntu 18.04.5 LTS 
* **How I'm running Kubernetes:**  vscode

`garden version`
0.12.20

**Comment by OliverSanftleben** [comment]
exclusion with .gardenignore seems to have no effect, so I have no workaround

with 0.12.17 I have no such problems

**Comment by eysi09** [comment]
Hi @OliverSanftleben 

Judging by the screenshot, you're using remote sources. Are these the the git submodules in the remote source?

Also could you produce a minimal repro for us? That would really speed up the debugging and fixing on our end. Thanks!
