### ISSUE TITLE
PVCs will not mount in 0.12.21

### ISSUE THREAD

**Issue by ultimatemonty** [garden-io/garden#2369]
### Current Behavior
After upgrading from `0.12.16` to `0.12.21` our PVCs are no longer mounting as expected. We are receiving the following error:
```
Failed getting status for service 'cache-volume' (from module 'cache-volume'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
persistentvolumeclaim module cache-volume doesn't specify a serviceResource in its configuration. You must specify a resource in the module config in order to use certain Garden features, such as hot
reloading, tasks and tests.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

`serviceResource` isn't mentioned in the [current PVC docs](https://docs.garden.io/reference/module-types/persistentvolumeclaim)

Unfortunately Homebrew has made it incredibly difficult to rollback to a previous version of a package.

Our current PVC config is
```
kind: Module
name: cache-volume
type: persistentvolumeclaim
include: []
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 128Mi
```

and the volume config is
```
- name: cache
  containerPath: /app/cache
  module: cache-volume
```

EDIT: the volume is used in a `container` module running in a `local-kubernetes` provider.

### Expected behavior
PVCs mount as expected OR the docs are updated to reflect the `serviceResource` config requirement.

### Reproducible example
Create a simple volume and create a PVC module for that volume without `serviceResource` specified.

### Workaround
None so far

### Suggested solution(s)
If `serviceResource` is required for PVC modules now a doc update would be sufficient. 

### Your environment
Garden 0.12.21
MacOS 11.2.3
Docker for Mac 3.3.1 (63152)
Docker Engine 20.10.5
Docker Compose 1.29.0
Kubernetes 1.19.7

```
$ garden version
0.12.21
```

**Comment by eysi09** [comment]
Hi @ultimatemonty! 

I _think_ I see where this could be happening, likely a bug that was introduced a couple of releases ago when we made some changes to how we handle module versions. That being said, our integ tests for this module type are passing and I'm having a hard time reproducing on my end. I created a PVC like the one you shared and referenced it from a container module type, but deploying and validating works just fine on my end. Anything else you can think of that might be relevant?

Also, was the PVC deployed with an older version of Garden? I suppose that could be what's causing this, although it seems highly unlikely. 

In the meanwhile, you could grab the 0.12.16 binary from here: https://github.com/garden-io/garden/releases/tag/0.12.16

Note that you might need to get via curl/wget, otherwise your Mac will complain about the binary being downloaded off the internet.

**Comment by ultimatemonty** [comment]
@eysi09 thanks for getting back to me so quickly! 

I've confirmed the PVCs work as-is with `0.12.20`. I've also tried deleting all the existing PVCs via `kubectl delete pvc --all` and then starting garden again and still see the same issue.

As a workaround we've forked the Garden homebrew formula and mirrored it to our internal tap and are enforcing 0.12.20 there.

I'm happy to help debug this further but I'm unsure of what additional information you might need. If a screenshare is the easiest thing I'm game for that as well.

Thanks!

**Comment by edvald** [comment]
@eysi09 this appears to be related to the recent changes around the new dev mode, not the module version handling.

**Comment by eysi09** [comment]
Aha, ok. We tried reproducing this on our end but came up short. Any pointers, @edvald?

And thanks for the offer @ultimatemonty, I'll definitely reach out if we find ourselves blocked, but this should be an easy enough fix.

**Comment by edvald** [comment]
I think the issue has to do either with how we convert the PVC module to a Kubernetes module internally (which is how it's ultimately deployed) or the validation that follows. I suspect the former, probably tacking on the devMode stanza where we shouldn't.

**Comment by remotezygote** [comment]
Running into this 100% reliably. I've not found a way to use persistent volumes at all with newer garden versions, which is a humongous problem. I am very much a n00b to garden, but feel like I'm doing it correctly...

Mac OSX Big Sur 11.4
garden 0.12.22
minikube v1.20.0

Example just trying to have a persistent volume for PG:
```
kind: Module
name: postgres-data
type: persistentvolumeclaim
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---

kind: Module
description: Postgres container
type: container
name: postgres
image: postgres:13
services:
  - name: postgres
    replicas: 1
    volumes:
      - name: data
        module: postgres-data
        containerPath: /db-data
    ports:
      - name: db
        containerPort: 5432
    env:
      POSTGRES_DB: ${var.pg-database}
      POSTGRES_USER: ${var.pg-user}
      POSTGRES_PASSWORD: ${var.pg-password}
      PGDATA: /db-data
    healthCheck:
      command: [
        psql,
        -w,
        -U, "${var.pg-user}",
        -d, "${var.pg-database}",
        -c, "SELECT 1",
      ]
tasks:
  - name: db-init
    command: [/bin/sh, -c]
    # The postgres health check appears to go through before the server accepts remote connections, so we need to
    # sleep for a while.
    # https://github.com/CrunchyData/crunchy-containers/issues/653
    args: [
      'sleep 15 && psql -w --host ${var.pg-host} --port 5432 -d ${var.pg-database} -c "ALTER DATABASE ${var.pg-database} SET db.initalized = 1;"'
    ]
    dependencies: [postgres]
    env: &env
      PGDATABASE: ${var.pg-database}
      PGUSER: ${var.pg-user}
      PGPASSWORD: ${var.pg-password}
  - name: db-clear
    args: [
      psql,
      -w,
      --host, "${var.pg-host}",
      --port, "5432",
      -d, "${var.pg-database}",
      -c, "TRUNCATE author",
    ]
    dependencies: [postgres]
    env:
      <<: *env
```

Error:
```
Failed getting status for service 'postgres-data' (from module 'postgres-data'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
persistentvolumeclaim module postgres-data doesn't specify a serviceResource in its configuration. You must specify a resource in the module config in order to use 
certain Garden features, such as hot reloading, tasks and tests.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by eysi09** [comment]
Awesome, thanks for the repro. This will make it a lot easier to diagnose and fix.
