### ISSUE TITLE
[FEATURE]: Add support for Kubernetes modules with exec (to open an interactive shell)

### ISSUE THREAD

**Issue by estoesto** [garden-io/garden#2373]
### Background / Motivation

I am not entirely sure this should be a feature request or a bug. When running `garden exec` against a service deployed with the kubernetes module on a remote EKS cluster, I get the following error:
```
No 'execInService' handler configured for module type 'kubernetes' in environment 'remote'. 
Are you missing a provider configuration?
```
Running `garden plugins kubernetes cluster-init` results in:
```
All services already initialized!
```

This would be extremely useful when deploying django and node applications. 

### What should the user be able to do?

Open an shell or execute a command on a running service without relying on kubectl.

### Why do they want to do this? What problem does it solve?

When working in remote development setup, this is extremely necessary for debugging purposes.

### Suggested Implementation(s)

Extend the existing Garden Exec command functionality to support services deployed with the Kubernetes module.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @estoesto 

Thanks for flagging this. You're absolutely right that this is missing, we simply hadn't gotten around to adding it yet. So yeah, not sure whether we should call it a bug or feature, I suppose it's both. 

But we'll look into this and try and ship this within our next couple of releases.
