### ISSUE TITLE
"Attempted to copy non-file" when a symlink target is a folder

### ISSUE THREAD

**Issue by orarbel** [garden-io/garden#2382]
## Bug

Building breaks when a module contains a symlink to a folder.

The offending line only checks if the target of a symlink is a file, but doesn't check if it's a folder.

https://github.com/garden-io/garden/blob/893e55b6e4932dda671509248ce2acf513eb8526/core/src/build-staging/helpers.ts#L68

### Current Behavior

An error of "Attempted to copy non-file" is raised.

### Expected behavior

The build will be successful.

### Reproducible example

Projects that contain a symlink to a folder.

### Suggested solution(s)

Add a condition that checks if the target is a folder and if so don't raise an error.

### Your environment

* **OS:** macOS BigSur 11.3
* **How I'm running Kubernetes:** Docker Desktop

`garden version`
0.12.21

**Comment by eysi09** [comment]
Thanks for the detailed report @orarbel. Should be a quick fix on our end.

**Comment by eysi09** [comment]
@edvald, could you confirm that the suggestion makes sense? If that's the case I can fix it on my end.

**Comment by edvald** [comment]
Yeah I think that does make sense, but I wanna take a quick look to make sure. Lots of little devils in the details in this stuff .)

**Comment by eysi09** [comment]
All right, I'll assign this to you then. Feel free to re-assign.

**Comment by vvagaytsev** [comment]
@jondeandres is this still a problem in `0.13`?

**Comment by abMatGit** [comment]
@vvagaytsev hey I can attest this is also a problem for me. In `0.13` this code is still checking only if it symlinks a file not a folder. 

This would be fixed if the code was: 
```typescript
if (!sourceStats.isFile() || !sourceStats.isDirectory()) { 
```

**Comment by alexkuretz** [comment]
Getting this trying to build backstage via container action with garden 0.13.39
```
✖ build.backstage           → Failed processing Build type=container name=backstage (took 10.35 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error while copying from '/home/user/work/backstage/backstage/node_modules/app' to '/home/user/work/backstage/.garden/build/backstage/node_modules/app': Source is neither a symbolic link, nor a file.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1 requested deploy action(s) aborted!
```
It is indeed a symlink:
```
user@computer:~/work/backstage/backstage$ ll node_modules/app
lrwxrwxrwx 1 user group 15 Sep  6 16:24 node_modules/app -> ../packages/app/
```

**Comment by stefreak** [comment]
@alexkuretz Hi @alexkuretz can you have a quick look at the current edge version by running `garden self-update edge-bonsai`? Does it work fine with that version? We'll also create a production release soon, but early feedback is always a good thing. Thank you 👍

**Comment by alexkuretz** [comment]
Hey, thanks, it looks like this has resolved the issue for me.
