### ISSUE TITLE
Garden hangs while trying to fetch remote sources if no authentication to repo is provided.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2388]
### Current Behavior

Whenever no authentication to the remote sources repository is set, Garden will try to fetch remote sources and hang without throwing an error.

### Expected behavior

An error is thrown when Garden encounters an authentication error while fetching remote sources.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by Orzelius** [comment]
a silly question, but how does one even authentication to a remote sources repository?
