### ISSUE TITLE
Kubernetes uninstall-garden-services fails to remove validating webhooks

### ISSUE THREAD

**Issue by qeternity** [garden-io/garden#2394]
### Current Behavior

Kubernetes `uninstall-garden-services` does not clean up `garden-nginx-ingress-nginx-admission` validating webhook.

### Expected behavior

All k8s garden resources are cleaned up, including validating webhooks.

**Comment by eysi09** [comment]
Thanks for the bug report. I'd guess this is actually an issue with Helm, since Garden install and uninstall nginx via Helm.

**Comment by edvald** [comment]
I believe this issue was down to migration between Helm chart configs for nginx, so it's not something we can action. Do let us know if you bump into something like this again though!
