### ISSUE TITLE
(Possibly) wrong link in documentation

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#2401]
### Current Behavior

On the [stack graph](https://docs.garden.io/basics/stack-graph) page of the documentation, the link to the "Getting Started" section points to [this](https://github.com/garden-io/garden/tree/c7de8544c59c47e837cada93ad140aeb73dc1b76/docs/getting-started) page, which doesn't look like intended behavior.

### Expected behavior

I guess the README.md wasn't generated properly?

### Reproducible example

Go to the [stack graph page](https://github.com/garden-io/garden/tree/c7de8544c59c47e837cada93ad140aeb73dc1b76/docs/getting-started), click "Getting Started" hyperlink.

Lots of love,

Your dutch friend.

**Comment by eysi09** [comment]
Hello my Dutch friend ❤️ 🇳🇱

Thanks for pointing this out. We'll see about prioritising this for Q4.
