### ISSUE TITLE
Automatically create port-forwards when using dev mode.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2410]
### Current Behavior

If I want Garden to create automatic port-forwards for my services while using the new `dev-mode` I need to run the command with the `--watch` flag.

### Expected behavior

I would expect the `--dev` mode to automatically create the port-forwards for all my services, same as it was with the hot-reload functionality.

### Reproducible example

```sh
# This doesn't create the port-forwards
garden deploy module-a --dev module-a

# This creates the port-forwards
garden deploy module-a --dev module-a --watch


```

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
Looks like it was fixed some time ago. Now the command `deploy` with the `dev-mode` option enables port-forwards. Closing this.
