### ISSUE TITLE
[FEATURE]: terraform plugin support for destroy action

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#2414]
### Background / Motivation

The terraform garden plugin supports planning and applying a terraform stack, but not destroying it.

### What should the user be able to do?

Be able to destroy a terraform stack deployed with garden analogue to planning and applying it.

### Why do they want to do this? What problem does it solve?

There should be an option to clean up infrastructure deployed with gardens terraform plugin. 

### Suggested Implementation(s)

```
garden --env=example plugins terraform destroy-root
garden --env=example plugins terraform destroy-module
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
>  Not having this feature makes using Garden painful

Ouch, we don't want that. Perhaps we could find time to pair on this, since you probably but have a good feel for what the UX should be like.
