### ISSUE TITLE
[FEATURE]: Respect the terminal color themes

### ISSUE THREAD

**Issue by glennsarti** [garden-io/garden#2420]
### Background / Motivation

Currently there doesn't appear to be a way to disable colourised output besides using a JSON/YAML output format. This can cause issues with terminals that don't fully support colourisation or font change e.g. italics.  An example below

![image](https://user-images.githubusercontent.com/5819622/120133033-f8ccf380-c1fd-11eb-8e21-c008f81350a2.png)

Admittedly the funny looking font is my terminal configuration (Default Windows Terminal with Cascadia Code Italics) but I cannot disable this "feature" in garden

It also causes issues in CI logging tools and spews out ANSI codes in log output.

### What should the user be able to do?

There already exists a `--log-level` command line argument.  I would like a `--no-color` argument as well to disable any fancy colouristation of output.  Or perhaps an additional log-level of  `no-color` which behave like `basic` but also have no colour.

This would also disable the ability to move the cursor easily using ANSI sequences so I'd expect this is an opt in setting.

### Why do they want to do this? What problem does it solve?

If my terminal renders the "fancy" text incorrectly, I can quickly disable it so I can read the output of Garden

### Suggested Implementation(s)

As above.  either add `--no-color`   or   `--log-level no-color`

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

The rendered text is more difficult to read with a default install of Windows Terminal

**Comment by eysi09** [comment]
Hi @glennsarti 

That's a very good point and should be simple to fix. We'll look into this right away.

**Comment by edvald** [comment]
There is actually an undocumented way to do this with an environment variable: `FORCE_COLOR=0`. But the feature request is still definitely legit, we should have a canonical + documented way to do this.

**Comment by rogpeppe** [comment]
One standard way to do this is `TERM=dumb`. It would be great if that setting disabled all ANSI tty output.

**Comment by spenczar** [comment]
This remains an issue. Here's a screenshot of my very first time using `garden`:
<img width="874" alt="Screen Shot 2023-01-17 at 10 36 49 AM" src="https://user-images.githubusercontent.com/880413/212983042-4721c7ac-9487-4abc-92cd-6aeb3b022415.png">

Pretty bad for a first-time user experience!

I would like to be able to set `NO_COLOR=1` and get `garden` to use monochromatic output. See https://no-color.org/. The `--no-color` output or any of the other suggestions are fine too.

**Comment by eysi09** [comment]
I'm terribly sorry for the way overdue reply. 

Garden does indeed support the `NO_COLOR` environment variable (or rather the underlying library we use for rendering colors). 

Is that not working for you?

(We also added a note on this in our FAQ, pending a merge.)
