### ISSUE TITLE
[FEATURE]: Allow a Task or Test to receive traffic from other pods in garden cluster

### ISSUE THREAD

**Issue by WBrettDavis** [garden-io/garden#2423]
### Background / Motivation

Our API test container hosts mock implementations of APIs which are started up during the test run. As a result, we'd like to be able to have our test container receive traffic during the lifetime of its execution within the garden cluster. Currently, tests and tasks do not support configuration of a "ports" setting which would allow this traffic from other pods within the cluster.

### What should the user be able to do?

A user should be able to provide a "ports" configuration section in the same way that this setting is configured for "service" modules.

### Why do they want to do this? What problem does it solve?

This will allow us to run our API test container as a "test" module, which supports exporting of artifacts, while also allowing us to use the API mocking features provided by our tests.

### Suggested Implementation(s)

After discussing this briefly with @edvald - his suggested implementation was "... to add a Service resource for the test pod during its execution."

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Thanks for the feature request @WBrettDavis.

We can look into this, should be a simple addition.

Just FYI, you can "run" services with the `garden run service my-service` command. So you could imagine adding your test container to the module's service spec, and then running it. That will create a K8s Service object for the pod and it will run the entrypoint command, in interactive mode by default. But of course that doesn't give you the same primitives as using the proper test command.

**Comment by WBrettDavis** [comment]
Hi all - I was just wanting to see if there was any chance of reconsidering this feature as we are still facing this issue and have yet to find an effective work around.

**Comment by edvald** [comment]
Hey @WBrettDavis! We have been working out a feature that might help with this, which is to allow running tests/tasks in an existing service deployment, instead of running ad-hoc Pods. That was originally meant more as a performance optimization but I wonder if that would cover your use-case here?

**Comment by WBrettDavis** [comment]
@edvald thanks for the response! I think this would work as long as these tests work similarly in the way that they expose their artifacts.

**Comment by edvald** [comment]
Ok cool! And that would be the case, yes. Basically mostly the same flow, except running from an existing Pod instead of a new one.

**Comment by Orzelius** [comment]
Hello, with the Bonsai release this is now possible either via `kubernetes-exec` or `kubernetes-pod` action types.
