### ISSUE TITLE
Garden breaks when using git version 2.32.0

### ISSUE THREAD

**Issue by jeremiahpslewis** [garden-io/garden#2426]
### Current Behavior

<img width="1161" alt="Screen Shot 2021-06-06 at 22 20 53" src="https://user-images.githubusercontent.com/4462211/120938907-83898300-c715-11eb-9382-9fac1e6c0137.png">

### Expected behavior

No error.

### Reproducible example

Run anything...

### Workaround

Don't update git to 2.32

### Suggested solution(s)

Amend uses of git ls-files so that either `-o` or `-c` is specified. Looks like 3 instances, should be a minor fix: https://github.com/garden-io/garden/search?q=ls-files&type=

### Additional context

See the change described in this commit: https://github.com/git/git/commit/b338e9f668737e08201c990450b8c3d744f63162

### Your environment

In this case, irrelevant, but garden version 0.12.22

**Comment by eysi09** [comment]
Looks like this has to do with a breaking change in a git minor release. We're working on this.
