### ISSUE TITLE
"Error: Command "git rev-parse --show-toplevel" failed with code ENOENT" in watch mode

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2430]
### Current Behavior

I see this error every time I run `npm install` while in watch mode:

```
(node:51854) UnhandledPromiseRejectionWarning: Error: Command "git rev-parse --show-toplevel" failed with code ENOENT:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:51854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 70)
(node:51854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproducible example

Run Garden in watch mode in some demo project and run, say, `npm install is-odd`. 

### Workaround

None that I know of.

**Comment by danhawkins** [comment]
This is also happening to me, only on one of my projects, the other one is working fine. Also this project was working ok before, not sure what changed

**Comment by eysi09** [comment]
Interesting, we haven't seen that before. Usually it only happens on `npm install` or similar while the watch command is running. Essentially something changes in the file system while Garden is running a git command internally.

Is there a local task or similar in your Garden config that might mess with the file system while Garden is starting up?

**Comment by edvald** [comment]
I think we're mainly missing some error handling in our git handler. We should handle these types of things gracefully.

**Comment by danhawkins** [comment]
> Interesting, we haven't seen that before. Usually it only happens on `npm install` or similar while the watch command is running. Essentially something changes in the file system while Garden is running a git command internally.
> 
> Is there a local task or similar in your Garden config that might mess with the file system while Garden is starting up?

I don't think so

**Comment by danhawkins** [comment]
I also just tried `garden validate`

<img width="724" alt="Screenshot 2021-07-24 at 23 34 08" src="https://user-images.githubusercontent.com/108635/126879388-87c56373-6990-4abd-8115-84e79cc9d0f2.png">

**Comment by danhawkins** [comment]
OK in my case it was my bad, I had a submodule listed in gitmodules that I was not using

**Comment by hqm42** [comment]
This also ocrures when you move or rename the folder of a linked module. Adjusting the module path in *.garden/local-config.yml* fixed it for me.
