### ISSUE TITLE
[FEATURE]: allow to optionally specify which project garden.yml file to use

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2432]
### What should the user be able to do?

Run `garden deploy --project=<path to directory or file>` to use the project configuration specified at `<path to directory or file>`.

### Why do they want to do this? What problem does it solve?

A user might want to re-use the same module for different projects and right now there is no way of specifying different project configurations.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by OOPMan** [comment]
I agree, I think this would be a great feature

**Comment by eysi09** [comment]
I think this should be easy enough to add, unless there are some gotchas around file scanning and module resolution. Thoughts, @edvald?

**Comment by edvald** [comment]
It's not quite clear what the suggested behavior is. It's easy to allow picking a project config by name, for example, but it gets a little thornier if we're talking about overriding where we scan for modules relative to where the project config is.

More specific examples of a use case would be useful, then we can see what could make sense.
