### ISSUE TITLE
[FEATURE]: Allow Remote Sources/Modules to use CLI, project variables and env file variables to construct repositoryUrl

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2436]
### Background / Motivation

We need to construct the repositoryUrl property when using remote sources/modules based on values provided at runtime. Garden currently only reads in variables set using environment variables. it would be nice to set these variables using the CLI or from a file.

### What should the user be able to do?

set variables using either project variables, env file, or CLI to set and have them available in  repositoryUrl

### Why do they want to do this? What problem does it solve?

The need to create variables using environment variables.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
This will be fixed with #2438
