### ISSUE TITLE
[FEATURE]: Allow garden variables to be defined at the module wide and module-environment specific level

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2437]
### Background / Motivation

We have hierarchal configurations that are shared by a product (group of services) and services which can also be specific to an environment.  We currently merge these configurations ourselves but since Garden already has support for hierarchical values at the project and environment level, it would be nice if they supported variables at the module wide and module-env specific levels.

### What should the user be able to do?

be able set variables module wide and at the module-env that could be consumed in the template strings. these variables would have higher priority that variables set at the project and environment level.

### Why do they want to do this? What problem does it solve?

We would not longer need to build custom scripts/config files to merge these variables ourselves and could leverage the garden framework.

### Suggested Implementation(s)

add module and module-env variables to Garden modules 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
That's a great point. We've been discussing this internally for awhile. Just need to find some time to git'er done.

As a side note, we should use the chance to add utility commands that show how variables will be resolved (we could mask secrets or skip resolving them).

**Comment by eysi09** [comment]
This was addressed with #2454
