### ISSUE TITLE
[FEATURE]: add skipRendering flag to generateFiles in ModuleTemplates

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2447]
### Background / Motivation

When using ModuleTemplates the generateFiles fails since it tries to render some of the content and fails with the following error:

Invalid template string (import * as pulumi from "@pulumi/p…): Unable to parse as valid template string. 

### What should the user be able to do?

set a skipRendering flag to true (default is false) to so that it won't look for template string. see below:

generateFiles:
      - sourcePath: index.ts
        targetPath: index.ts
        skipRendering: true

### Why do they want to do this? What problem does it solve?

Currently resorting to creating additional modules that contain the code we want to copy and then using build dependencies on that module and copying.  

### Suggested Implementation(s)
set the skipRendering flag:
generateFiles:
      - sourcePath: Pulumi.yaml
        targetPath: pulumi/Pulumi.yaml
        skipRendering: true

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Thanks for opening the feature request @tedchang77. We'll look into this.

**Comment by tedchang77** [comment]
Or maybe instead of adding a skipRendering flag you can introduce a copyFiles at the same level of generateFiles. it might be more clear.

**Comment by edvald** [comment]
This is slated for next release!

**Comment by edvald** [comment]
This exact feature has been deprecated in favor of a different approach in Garden 0.13+, so I'm closing the issue. Basically this will be best handled with `exec` Run actions going forward, and we may introduce specific action types to support further if the need arises.
