### ISSUE TITLE
Missing ingresses list in Dashboard

### ISSUE THREAD

**Issue by jondeandres** [garden-io/garden#2455]
### Current Behavior

We can't see the list of `ingresses` for `kubernetes` modules that deploy `Ingress` k8s resources but we can see the ingresses deployed by a `container` module when using the `services` section.

### Expected behavior

We'd expect to see the list of ingresses when a `kubernetes` module deploy `Ingress` resources.

### Reproducible example

Running `examples/hot-reload-k8s` is enough to see this behavior.

### Suggested solution(s)

We can see a `detail.remoteResources` entry in the `/api` response that has the detailed deployed objects in k8s so it seems the backend is aware of the existence of those `Ingress` objects. Maybe making use of that knowledge to return the `ingresses` entry it'd be enough.

### Your environment

Running garden locally using minkube in an Ubuntu laptop

garden version: 0.12.23

----
Thanks!

**Comment by thsig** [comment]
Thanks for reporting this! Should be a relatively simple fix.

We'll need to add the `ingresses` key to the output from the `kubernetes` module type's `getServiceStatus` handler.

**Comment by eysi09** [comment]
Yes, this has been a known issue for awhile. Similarly, we don't print the ingress URL in the command line after deploying a K8s or Helm module. Would be great to get this fixed. We'd essentially need to parse the manifests / charts and construct the URL.

**Comment by jondeandres** [comment]
is there any workaround for this? Do you think these kind of information should be part of the output of the module or there could be a way to register outputs?
