### ISSUE TITLE
[FEATURE]: ConfigMap modules

### ISSUE THREAD

**Issue by jondeandres** [garden-io/garden#2456]
## Feature Request

I am not sure this is doable so I am opening this feature request: define a kind of `configmap` module that can be referenced in `services.volumes` or allow to reference a  `kubernetes` module that deploys a `ConfigMap` resource.

### Background / Motivation

I don't have idea of what's the good practice re: injecting configuration files into the container

**Comment by thsig** [comment]
Hi @jondeandres—thanks for the suggestion! We'll give this a bit of thought on our end. A similar approach to how we implemented `persistentvolumeclaim` modules might make sense here.

**Comment by edvald** [comment]
Just pushed #2501
