### ISSUE TITLE
Dashboard logs fails when built subset of services

### ISSUE THREAD

**Issue by maciejgwizdala** [garden-io/garden#2460]
### Current Behavior

Logs in dashboard is not working correctly, when only selected subset of services are built and deployed with garden.
Services (modules, type helm):
- service-a
- service-b
- service-c

`garden deploy service-b`

Error in dashboard:
> Whoops, something went wrong.
> ❌ Request failed with status code 500
> 
> Please look at the terminal logs displayed by the dashboard server for details.
> 
> 💡 You can get more detailed logs by running the server with --log-level=debug.

`garden dashboard --log-level debug` output:

> API server request failed with status 404: Command ".garden/tools/helm/6d4b7a51cf3dcb28/linux-amd64/helm --kube-context aks-cluster --namespace user install service-a .garden/build/service-a --dry-run --namespace user --output json --timeout 300s --values .garden/build/service-a/garden-values.yml" failed with code 1:
> Error: Chart.yaml file is missing
> Error: Chart.yaml file is missing

> API server request failed with status 404: Command ".garden/tools/helm/6d4b7a51cf3dcb28/linux-amd64/helm --kube-context aks-cluster --namespace user install service-c .garden/build/service-c --dry-run --namespace user --output json --timeout 300s --values .garden/build/service-c/garden-values.yml" failed with code 1:
> Error: Chart.yaml file is missing
> Error: Chart.yaml file is missing

### Expected behavior

Only subset of deployed services with depedencies should be tracked, so not all services have to be built for viewing logs in dashboard.

### Reproducible example

1. Project with several modules:
- type helm, using base-helm like in example
- not dependent on each other, separate ones
2. Run `garden deploy service-b`
3. Run `garden dashboard --log-level debug`

### Workaround

not available (?)

### Suggested solution(s)

Possibility to run `garden dashboard` with specified service(s) like `garden build` or `garden deploy` commands can do.

### Your environment

* **OS:** macOS, Ubuntu Linux, Windows 10
* **How I'm running Kubernetes:** AKS
* `garden version`: 0.12.23

**Comment by thsig** [comment]
Hi @maciejgwizdala—thanks for reporting this! I'm not quite sure how to reproduce this on my end.

Does `service-b` reference a base module (like here https://docs.garden.io/guides/using-helm-charts#re-using-charts)?

**Comment by maciejgwizdala** [comment]
Hello,
Yes, all services references same base module, as `base: base-chart`

**Comment by eysi09** [comment]
Sorry for the delayed response. But just to narrow this down, do you see the same issue if just call the `garden logs` command directly?

**Comment by maciejgwizdala** [comment]
Hello,
It's same behaviour, when using `garden logs`.

**Comment by eysi09** [comment]
Ok that's useful to know. So I suppose it's not an issue with the dashboard per se, but rather the logs command. And just to confirm that it's not an issue with the project config, does this work as expected if you actually build or deploy the "offending" module before running the logs command?

**Comment by maciejgwizdala** [comment]
Yes, when running build / deploy for all modules within project, logs / dashboard is working correctly.

**Comment by eysi09** [comment]
Gotcha, thanks for the feedback. We'll look into this.

**Comment by vvagaytsev** [comment]
The local dashboard was removed in 0.13. Feel free to try out the new Cloud dashboard. Closing this.
