### ISSUE TITLE
insecure installation instructions

### ISSUE THREAD

**Issue by jdstrand** [garden-io/garden#2462]
## Bug
Looking at https://docs.garden.io/getting-started/1-installation, the non-brew installation instructions say to run curl and pipe that into bash. There is a manual install section that avoids running bash, but there are no published checksums (ie, sha256 or sha512) for current and past binary versions to verify the download. This is insecure since it allows for supply chain attacks.

At a minimum, the site should publish checksums (ie, sha256 or sha512) for current and past binary versions with instructions on how to verify the download in the manual install section.

Since you have an installer script, you might want to consider modifying it to verify the checksum of the downloaded file. In this manner, you can publish an additional checksum for your installer, then users can curl it, verify the installer's checksum then run it.

**Comment by thsig** [comment]
Hi @jdstrand—thanks for pointing this out! We'll have a look at this.

I'll tentatively assign this to @eysi09 for now.

**Comment by edvald** [comment]
We've now added checksums to the installation script and release process: #2473 

We should perhaps mention that in the installation docs as well.
