### ISSUE TITLE
[FEATURE]: command completion 

### ISSUE THREAD

**Issue by exocode** [garden-io/garden#2463]
### Background / Motivation

I am one of that guy, hitting the "tab"-button a lot.

### What should the user be able to do?

write `garden`+ press `tab` to complete and suggest commands

### Why do they want to do this? What problem does it solve?

devs are lazy and wont read manuals, so they should get suggestions of the current possible commands.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by thsig** [comment]
Yeah, this would be really great! We've been discussing this internally recently, hopefully we'll get around to implementing something of the sort soon.

**Comment by eysi09** [comment]
Closing as a duplicate of #2344.
