### ISSUE TITLE
[FEATURE]: Allow configuring ephemeral-storage request and limit for kaniko pods

### ISSUE THREAD

**Issue by zyulyaev** [garden-io/garden#2469]
### Background / Motivation

When I was trying to configure kaniko build mode for a remote kubertenes on GKE autopilot, I hit the ephemeral storage limit which is only 1Gi there:
```
{
  "message": "Pod ephemeral local storage usage exceeds the total limit of containers 1Gi. ",
  "phase": "Failed",
  "reason": "Evicted",
  "startTime": "2021-07-07T13:34:26.000Z"
}
```

### What should the user be able to do?

I think you should be able to specify ephemeral-storage request and limit for the kaniko pod created by garden:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

### Why do they want to do this? What problem does it solve?

This will allow you to calibrate the ephemeral storage size for larger docker images.

### Suggested Implementation(s)

I think one should be able to specify `ephemeralStorage` just like `cpu` and `memory` for the [requests](https://docs.garden.io/reference/providers/kubernetes#providers-resources-builder-requests) and [limits](https://docs.garden.io/reference/providers/kubernetes#providers-resources-builder-limits).

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
This is a good idea, and relatively easy to do. cc @thsig

**Comment by thsig** [comment]
Quick question: Do we want to add this only to the builder config for Kaniko/BuildKit, or also to `container` services in general?

Or would that be bringing too many k8s-specifics into the `container` module type?

**Comment by edvald** [comment]
I'd say just for Kaniko/BuildKit to start.

**Comment by zyulyaev** [comment]
I think it is more important for Kaniko/BuildKit since there is no workaround, while for containers you can use kubernetes or helm module to have better control of the resources.
