### ISSUE TITLE
Cannot install garden with install script

### ISSUE THREAD

**Issue by zyulyaev** [garden-io/garden#2475]
### Current Behavior

The `curl -sL https://get.garden.io/install.sh | bash` command results in "Checksum validation failed." error.
<img width="688" alt="Screenshot 2021-07-09 at 21 35 08" src="https://user-images.githubusercontent.com/9340671/125122187-b6041280-e0fd-11eb-8ed0-79014140f252.png">

### Expected behavior

Installation completes successfuly.

### Reproducible example

```
curl -sL https://get.garden.io/install.sh | bash
```

### Workaround

You can still install garden manually as described in the [docs](https://docs.garden.io/getting-started/1-installation)

### Suggested solution(s)

As far as I understand, this was introduced while added checksums for the release artifacts. Current install script requires the latest release to have a checksum file, which is not the case for the current latest release.
Revert the latest install script change, or make checksum files optional until next release.

**Comment by zyulyaev** [comment]
Found another workaround:
```
curl -sL https://raw.githubusercontent.com/garden-io/garden/v0.12.3/support/install.sh | bash
```

**Comment by edvald** [comment]
Ach! Good catch. I'll just add those checksum files to the latest released version
