### ISSUE TITLE
 Error from helper function uuidv4: Cannot read property 'v4' of undefined

### ISSUE THREAD

**Issue by OOPMan** [garden-io/garden#2487]
### Current Behavior

Current the uuidv4 helper function seems to be broken...

![image](https://user-images.githubusercontent.com/248980/125662061-a9d58132-f78a-4a75-837e-8968e59ec55f.png)
![image](https://user-images.githubusercontent.com/248980/125662412-93608f08-ad78-487b-9c97-06c1a078c0bc.png)

### Expected behavior

Expected the `uuidv4()` function to work

### Reproducible example

![image](https://user-images.githubusercontent.com/248980/125663444-f1b46ffb-1481-4437-9266-d9a3b85644e4.png)

### Workaround

N/A

### Suggested solution(s)

Unsure

### Additional context

From some googling it seems like the function may have been renamed to `v4()` in the source library?

### Your environment

* **OS:** Linux
* **How I'm running Kubernetes:** Minikube

``` AJorgensen@AJ-X1CARBONG2  /tmp/t   master  garden version
0.12.24
```

**Comment by edvald** [comment]
Huh. That's strange, no clue how this might have passed through tests, but should be a quick fix! Thanks for the heads up :)

**Comment by OOPMan** [comment]
@edvald Glad to have helped find something. Thanks for the awesome tool BTW!
