### ISSUE TITLE
garden dev: spinner doesn't stop for task when it fails

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#249]
To reproduce, make a build fail and observe the spinner going after the error is printed.

**Comment by eysi09** [comment]
I haven't been able to reproduce. At least not by intentionally throwing errors from `buildModule` plugin actions.

**Comment by edvald** [comment]
Hmm interesting. The way it came up for me, was when using `garden dev` specifically, and having the go-service build failing (same error you came across the other day, unused import).
