### ISSUE TITLE
devMode ignores modified files on initial sync

### ISSUE THREAD

**Issue by davidbrowning** [garden-io/garden#2505]
### Current Behavior

``` 
garden link module (name) (path)
# modify existing files in local repo
garden dev
# from local repo
git status
# shows modified file(s)
# from inside container
git status
# no modified files
```
As soon as I revert my local changes and make them again, garden picks it up and correctly syncs to remote 

### Expected behavior

git status should be identical in both the local and remote git repo

### Reproducible example

Will be contributing an example using devMode next week and will report it back here. For now, I'm using outside code I can't share. As soon as the example exists, I'll attempt to reproduce. 

### Workaround

Prior to running garden dev, ensure no files have been modified (e.g. start development and garden dev simultaneously rather than working on code *then* spinning up the remote environment)

### Suggested solution(s)

First, we need to identify whether this is perhaps an issue in mutagen and fix it there. 

### Additional context

App is elixir, but I expect similar behavior in other stacks

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS 

`garden version`
0.12.24

**Comment by davidbrowning** [comment]
I believe we've found the correct way to use this workflow. Use one-way-replica as the devMode sync mode. 

```
devMode:
  sync:
    - target: (directory)
      mode: one-way-replica
```

**Comment by thsig** [comment]
Hi @davidbrowning—thanks for reporting this! Do you think this is something that should be fixed/changed on our end, or that we should update our documentation accordingly?
