### ISSUE TITLE
System limit for number of file watchers reached

### ISSUE THREAD

**Issue by tbl-harmoney** [garden-io/garden#2518]
### Current Behavior

Linux command line is flooded by errors logs because the file watcher is not excluding folders like `node_modules` although added in `.gitignore`.
```
(node:305615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 43258)
(node:305615) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/<redacted>/front-end/node_modules/@ts-morph/common/node_modules/.bin/tsserver'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1415:11)
    at createFsWatchInstance (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/node_modules/chokidar/lib/nodefs-handler.js:629:21)
```

`.gitignore` at project root:
```
# dependencies
node_modules
```

`.gitignore` at same level as `node_modules` folder:
```
node_modules/
```

Not encountered with same code base on MacOS.
Also encountered when running `garden dev <module>` where `<module>` is another module than the one with the watched `node_modules`.
Same behaviour when using `--hot-reload=<module>`.

### Expected behavior

Garden CLI should not watch ignored folders. 
An indication on how many files Garden is watching (e.g. in case more than 1000 files are being watched) could also be useful as people might forget some directories are not ignored, causing performance decrease of Garden, possibly without notice.

### Workaround

Removing folders like `node_modules` and `dist` when running in watch mode. Only works when working on another module of course which doesn't rely on these folders.

### Your environment

* **OS:** Ubuntu 20.04
* **How I'm running Kubernetes:** occurs on both minikube and remote GKE
* **garden version:** 0.12.24

**Comment by edvald** [comment]
Hey @tbl-harmoney. Garden currently doesn't use .gitignores by default, but rather `.gardenignore` files. However, the most direct way to exclude files from watching right now is with `modules.exclude[]` in your project configuration.

That said, I'm looking into making Garden a bit smarter about this, especially on Linux where file/directory watching is inherently a lot more expensive than on Mac.

**Comment by tbl-harmoney** [comment]
Can confirm this approach fixes the problem: https://github.com/garden-io/garden/issues/2547#issuecomment-907263482
