### ISSUE TITLE
[FEATURE]: Set correct permissions on files synced with devMode.sync

### ISSUE THREAD

**Issue by bbaga** [garden-io/garden#2519]
### Background / Motivation

The synced files will be owned by the container's user with read and write permissions only `-rw-------`.
In our case, this doesn't work well for development. We are working with PHP/FPM and FPM (www) doesn't have permission to read the synced files (now owned by root). We can run the containers with the www user, but that introduces some pain as we lose the ability to make quick experimental changes in the container without having to rebuild it.

This wasn't an issue with docker volumes.

### What should the user be able to do?

I couldn't find a way to execute postSync commands when using devMode.sync, that could work as a workaround, otherwise, configurable permissions and owner on source/target pair basis would be pretty neat.

### Why do they want to do this? What problem does it solve?

This would make the synced files accessible for processes that are running with a user different from the container's main user. 

### Suggested Implementation(s)

I'd leave this to the professionals.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

(inconvenient would be a better word)

**Comment by bbaga** [comment]
I see that Mutagen has[ options for configuring permissions on the files](https://mutagen.io/documentation/synchronization/permissions), is it possible to set these in a `garden.yaml`? I made some blind attempts, but the yaml validation failed.

**Comment by edvald** [comment]
Not yet @bbaga, but I'm actually working on adding those fields as we speak :) Just trying to decide on the field names etc. but it's pretty straightforward to pass along these parameters.

**Comment by edvald** [comment]
Added a commit to address this on top of #2491. We should have that merged and released next week. Some folks here on holiday, so there's a backlog of PRs to get through :P

**Comment by HologramInterview** [comment]
Thanks for working on this, we need these options as well.  When do you think this will be released?

**Comment by ozymandias547** [comment]
Thanks for working on this, we need these options as well. When do you think this will be released?
