### ISSUE TITLE
[FEATURE]: For project configuration, add environments[].modules.include[] and environments[].modules.exclude[] keys

### ISSUE THREAD

**Issue by OOPMan** [garden-io/garden#2524]
### Background / Motivation

It would be very useful for different project environments to use different module files. My reasoning for this is to have a module file for development that builds images locally and another module file for staging that uses images built in our CI and push to a container registry

### What should the user be able to do?

The user should be able to declare `environments[].modules.include[]` and `environments[].modules.excludes[]` items that
are currently only permitted at the project configuration root-level.

### Why do they want to do this? What problem does it solve?

This will allow the user to specify per-environment module files

### Suggested Implementation(s)

I'm not sure what would be involved. I did test and see if I could use a templated string in the project level `modules` section but that did not seem to work. 

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by edvald** [comment]
Hey @OOPMan. Have you looked at using the `disabled` field on individual modules? You can use template strings to conditionally disable modules with that. Example: `disabled: ${environment.name != 'prod'}`

**Comment by OOPMan** [comment]
> Hey @OOPMan. Have you looked at using the `disabled` field on individual modules? You can use template strings to conditionally disable modules with that. Example: `disabled: ${environment.name != 'prod'}`

I have thought about that but I feel like filling my module files with a lot of conditional logic like this is a little ugly.

I can definitely make use of that approach, I just feel that having per-environment module includes/excludes would be a cleaner approach.

I forked the source so I may fiddle a bit and see if I can get a PR together...
