### ISSUE TITLE
kubernetes-helm bucket seems to have removed binaries < v2.16 

### ISSUE THREAD

**Issue by MarkMurphy** [garden-io/garden#2528]
## Bug

```
ℹ providers                 → Getting status...
   ℹ Fetching kubectl...
   ✔ Fetched kubectl
   ℹ Fetching helm2...
✖ providers                 → Failed fetching https://storage.googleapis.com/kubernetes-helm/helm-v2.14.1-linux-amd64.tar.gz
```

This was working up until today and if you check [the bucket](https://storage.googleapis.com/kubernetes-helm) you can see that there's no trace of anything below v2.16.

We're using garden v0.11.14 (in the process of upgrading) and nothing in the codebase of garden v0.11.14 looks like it specifies helm version 2, it defaults to 3: https://github.com/garden-io/garden/blob/v0.11.14/garden-service/src/plugins/kubernetes/helm/helm-cli.ts#L112 😕 

Not exactly sure how to work around this one.

**Comment by edvald** [comment]
Hey @MarkMurphy. This might be a little tricky to work around without updating the Garden CLI. The reason for still having Helm 2.x in there is to ensure older releases have been migrated. This has since been removed. 

You're quite a lot of versions behind—are there specific reasons to staying on a version that old?

**Comment by MarkMurphy** [comment]
We were mostly avoiding the garden upgrade up to this point because of the breaking changes and tight timelines. We have though as of last week been in the process of upgrading. We've been working though some issues that have come up during the upgrade (which is why you've seen me so much lately 😄). We have a lot of terraform configuration we have to upgrade as well so it wasn't super trivial to make the switch. 

I posted an issue with the helm community as well. Understandably, that version was intentionally removed but you can still access it via github releases as noted in the issue: https://github.com/helm/helm/issues/10005#issuecomment-894517793

I'm not sure there's anything for you guys to do here now, other than maybe create a patch release for v0.11 that points to github for the download instead of the bucket so users who haven't upgraded yet don't have their deployments broken...but then again, maybe that's just us
