### ISSUE TITLE
Is there a way to use variables in module names or apply prefixes?

### ISSUE THREAD

**Issue by bbaga** [garden-io/garden#2533]
**Scenario:**
I have two garden projects, both need to run a `http` service so the relevant modules are called `http`. When I try to use project A as the dependency of project B, I run into module name collision.

**Current solution:**
The workaround I found is trivial, just renamed the modules. Called them `project-a-http` and `project-b-http`.
Although this isn't that nice since every project has to prefix every module to avoid future conflicts.

From the documentation it is clear that we can use variables for various values, such as the service names, but when I tried to use variables for the module name I got the following error:

```
Error validating module (app.garden.yaml): key .name with value "${project.name}-http" fails to match the required
pattern: /^(?!garden)(?=.{1,63}$)[a-z][a-z0-9]*(-[a-z0-9]+)*$/
```

Is there any other way to apply a prefix modules and services in the projects?

**Comment by edvald** [comment]
Hey @bbaga. This is a current limitation, that is mentioned in docs (but admittedly easy to miss). It's something we might consider allowing though, to a limited degree. I think allowing `${project.name}` is pretty reasonable, for example, so I think this is valid as a feature request 👍

**Comment by bbaga** [comment]
Uh, sorry for that, I tried to read through the docs before posting the question, but clearly didn't pay enough attention. I'll likely to post a feature request, but using `${project.name}` might not be what I really need as it seems to bleed through  to the dependency project with the top-level project's name (I'm not sure of that is a feature or a bug).

**Comment by edvald** [comment]
> seems to bleed through to the dependency project with the top-level project's name

I suppose neither feature nor bug, just an effect of how it's implemented currently. There isn't (yet) an explicit notion of project dependencies, and modules are simply treated as being part of the project you're running at any point. That is, if you reference, say, a repo with another project in a project, the project configuration in that repo will be ignored.

It's something we've been exploring for a bit, how to explicitly define project dependencies, but it's a non-trivial design challenge so we haven't committed to an approach yet.

**Comment by bbaga** [comment]
My question was answered, I'm closing this issue. Thanks.
