### ISSUE TITLE
Sub-directory detection for hotReload seems to be faulty

### ISSUE THREAD

**Issue by OOPMan** [garden-io/garden#2534]
### Current Behavior

I have an application with the following directory structure:
![image](https://user-images.githubusercontent.com/248980/128888074-d99e832a-cb04-41fe-bab3-0c6f71fb6013.png)

I have configure hot reload as follows:
![image](https://user-images.githubusercontent.com/248980/128888169-11e6db80-2e85-42b1-b155-170bce0379f6.png)

When I run `garden deploy` I get the following output:
![image](https://user-images.githubusercontent.com/248980/128888339-449abdd1-3722-46be-acf9-bf4599249450.png)

### Expected behavior

I should be able to deploy. The `/home/derms/derms_api` directory is not a sub-directory of `/home/derms/derms` (It's not symlinked in any way either...)

### Reproducible example

Will attempt to provide later

### Workaround

Will attempt to provide later

### Suggested solution(s)

Uncertain

### Additional context

N/A

### Your environment

* **OS:** Linux (Kubuntu 20.10)
* **How I'm running Kubernetes:** minikube

`0.12.24`

**Comment by edvald** [comment]
@thsig not sure if the actual issue here is easy to fix or not? Does this stuff ring a bell?

**Comment by thsig** [comment]
This is an issue, and an easy fix—I'm having a look at it now, actually.

**Comment by OOPMan** [comment]
@edvald Thanks, I was actually testing out the hot reload because people on my team were complaining that the newer dev mode feature isn't fast enough and takes too long. I might want to hit the forums on that topic, it seems like in our experience with dev mode that it is actually rebuilding images rather than hot syncing files?!?!?! Maybe it's a configuration issue on our side, I know dev mode is supposed to use mutagen...

**Comment by edvald** [comment]
Oh interesting. I'm pretty sure that's some configuration/usage matter, happy to help with that! I certainly wouldn't suggest switching to the much-slower and soon to be deprecated hot reload mechanism :)

**Comment by OOPMan** [comment]
@edvald Should I posted a topic on the forum or open a new ticket?

**Comment by edvald** [comment]
Either works, but the forum seems like the spot for this one :)

**Comment by OOPMan** [comment]
@edvald Sure, I'll try and post something tomorrow then :-)

**Comment by OOPMan** [comment]
@edvald Okay, no need for me to post, I worked out my problem. I was using `garden deploy --dev-mode --watch` when I should have been doing `garden deploy --dev-mode='*'

**Comment by edvald** [comment]
Ahaa I see. I'm actually going to make a change to make that command equivalent, seems like the expected behavior.
