### ISSUE TITLE
Better docs for dev mode

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2549]
Our [documentation for dev mode](https://docs.garden.io/guides/hot-reload) is a little sparse, it's still flagged as experimental, and the old hot reloading functionality is still at the top of the doc. 

We should address these issues and also the one mentioned in this [comment](https://github.com/garden-io/garden/issues/2520#issuecomment-892789636).

**Comment by thsig** [comment]
Since this was opened, we've significantly expanded our dev mode guide, so I think we're good on that front (for now, at least).
