### ISSUE TITLE
Deprecate cert-manager integration

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2551]
### Current Behavior

The current `cert-manager` version supported in the Garden integration is way too old (`v0.11.0`) and needs an update.

### Expected behavior

As a user I want to be able to generate certificates using the latest version of `cert-manager`
### Reproducible example

N/A

### Workaround

You could potentially install `cert-manager` manually and use it to manage tlsCertificates but we haven't tested with the latest `cert-manager` version.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by ohookins** [comment]
Maybe a first step on the path to deprecation would be to fix this:

```
Failed resolving provider kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error validating provider configuration: key .certManager.email is required
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- kubernetes
```

This happens when you set `certManager.install: false`

**Comment by ohookins** [comment]
Probably not worth solving if certmanager is going to be removed anyway. Stalebot can close it.

**Comment by Walther** [comment]
Deprecated in #3517 
Fully deleted in #4085
Closing this issue as completed.
