### ISSUE TITLE
Make installation process smoother

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#256]
Currently, installation on both Linux and Windows is quite tedious. The installation flow on macOS is straightforward in comparison, but even then it has somewhat heavy dependencies, and the reliance on npm has been known to cause headaches.

Another issue is that we don't currently offer any automated version checking or management for the framework, which is likely to cause frustration over time. One of the main benefits of Garden should be to limit the "works on my machine" class of problems, so it's something we should tackle well.

I've explored a few different ways to address the issue, some of which are not mutually exclusive. Once we pick an overall strategy, we may make this a project and break up into separate issues.

### 1 - Set up CI for installation and smoke test on each major platform

This is kind of a given, we should definitely do this no matter how the installation is actually performed.

### 2 - Make proper system-level packages for Windows and Linux

This could be the most straightforward initial improvement, and cover a lot of the pains on those platforms. We'd use `chocolatey` on Windows, and make at least a `deb` package for Linux, possibly an `rpm` as well.

### 3 - Make an Electron app

This is an interesting thought, so I dug a little into it. It seems to align in some respects, since we could use electronforge.io to automate the making of cross-platform installers. We might even at some point want some desktop UI features as well. Automatic updates could also be nice.

However, it doesn't automate creating a CLI command that's on the user's path, so we'd still have that step. It's also non-idiomatic for dev tools in general, and just feels a bit overkill in some respects. So I'd suggest we put a pin in that one for now.

### 4 - Bundle releases with nexe

https://github.com/nexe/nexe is a pretty nice way to bundle the framework as a single binary. I'm willing to bet it would be non-trivial to get it working properly, but this would be a nice improvement, as it basically folds all the npm stuff into a single binary which is faster to install and start. Plus it removes a bunch of potential native extension issues etc.

This would depend on 1) to be done (because you currently need to compile on each platform we want to support). I regard this as a good optimization to make at some point.

### 5 - Remove annoying dependencies

By "annoying" I mean native dependencies or not-easily-automatable dependencies that we could possibly get rid of or bootstrap at runtime. For example, we could maybe remove the `x509` package which has an OpenSSL dependency that's known to cause problems, and we could call some CLI commands that we use via containers. We'll need to investigate each of these independently, but it's overall something we should keep in mind when adding features (is the dependency native, does it need system-level installation, etc.).

### 6 - Make garden-cli a shim and manage the installation ourselves

This would add some complexity on our side, but I rather like this notion. The idea is that the `garden` CLI command would be a very thin layer, that first checks if the actual library is installed, installs it if not using whatever method is appropriate on the platform (and does it in user-space, notably), and hands off the execution.

The benefit we'd get would be more control, and in particular we could actually pin projects to a specific Garden version. This may become very important actually - we for sure don't want our users to find out after hours of debugging that they're using different garden versions.

## The Plan / Discussion

So. I'd say we definitely start with 1) and 2). These are clear improvements that can work nicely with any of the other things. We can also do 5) somewhat easily, or at least partially.

4) and 6) warrant some more consideration imo. Both would be good improvements, but will need to be spiked and prioritised.

Thoughts?

**Comment by edvald** [comment]
It appears both will be challenging to implement. Main consideration I think will be native dependencies, which are a little tricky in `pkg`, but in turn we'd need to actually build `nexe` executables on each respective platform. We can't avoid native modules entirely, so we need to figure out which ends up working better.

**Comment by oddur** [comment]
+1

To roll this out to all out devs, we need the installation to be as easy as possible. Zero effort would be best.

**Comment by edvald** [comment]
Closing this, superseded by more specific tasks (many of which are complete).
