### ISSUE TITLE
[FEATURE]: Support conditional deploys so that downstream dependencies are not automatically redeployed

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2568]
### Background / Motivation

There are two distinct use cases for deploying our infrastructure: complete vs incremental deploys.  For a complete deploy, the stack generated from the dependency graph is ideal as each module will be only be deployed after it's upstream has been deployed.  Similarly for incremental deploys of a module, the stack graph results in all downstream modules being re-deployed, even if this is not necessary. This increases the blast radius and performance of garden. We should be able to distinguish between these two use cases so that when we do an incremental deploy, the dependent services are only deployed when it makes sense. 

### What should the user be able to do?

Downstream services should not be redeployed when a module is deployed unless the module references an output that has changed.

### Why do they want to do this? What problem does it solve?

Making a change to an upstream module service results in all downstream module services being redeployed, which increases blast radius and the time it takes for a garden command to complete.

### Suggested Implementation(s)

Include the outputs of a module in it's garden version hash.  If a service specifies the upstream module as a dependency, only deploy the service if it references an output which changes.  This will also handle the full deploy case as the previous values of the outputs will be null.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @tedchang77 

Thanks for writing this up. This sounds very reasonable and something we've been meaning to look into. We expect to start work on this soon and we'll keep you posted.

**Comment by 10ko** [comment]
This behaviour has changed with actions on `0.13.x`, closing this.
