### ISSUE TITLE
Getting an error while executing garden login from cli

### ISSUE THREAD

**Issue by neeraj00890** [garden-io/garden#2578]
**Error:**   Looks like your session token is invalid. If you were previously logged into a different instance
of Garden Enterprise, log out first before logging in

Please assist me there.

**Comment by eysi09** [comment]
Hi @neeraj00890 

Logging out and back in should do the trick, as per the error message. That is, run `garden logout` and then `garden login`.

And we'd be happy to further assist you on your dedicated support Slack channel. Would you mind pinging us there?
