### ISSUE TITLE
Linux/Minikube integration tests

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#260]
We should have another stab at an integration test, using https://github.com/gavinzhou/ci-minikube as a guide to get minikube set up in CI.

We'll want the test to:
1) Test the packaging of `garden-cli`
2) Complete the whole installation flow for linux (so instead of just running garden from the repo directory, we actually do an `npm install -g <package archive>` to make sure the distribution works.
3) Run our integration tests (`npm run integ`) except have them use the installed `garden` binary and not the in-repo build.

cc @drubin

**Comment by edvald** [comment]
Mentioned this on Slack, but I suggest we give Azure Pipelines a spin for this, since they support all three of our supported platforms. Also, its free for OSS, and has some K8s specific niceties. 

Microsoft ain't messin' around these days .)

**Comment by ellenkorbes** [comment]
![theysurearent](https://user-images.githubusercontent.com/25550091/45420937-cf558d80-b68b-11e8-98d2-8965fea31166.jpg)

**Comment by eysi09** [comment]
I wrote about my experience with Azure in #321.

**Comment by edvald** [comment]
Closing in favor of #552
