### ISSUE TITLE
[FEATURE]: .git directory inclusion in container module

### ISSUE THREAD

**Issue by kszymans** [garden-io/garden#2623]
### Background / Motivation

My application requires .git directory for compilation thus I wanted to include it to my docker image.

### What should the user be able to do?

Include .git directory to container module

### Why do they want to do this? What problem does it solve?

Services which needs .git directory

### Suggested Implementation(s)

.git directory shouldn't be treated specially, but as standard directories/files

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

Current walkaround is to use exec module with dependency to container one:

```
kind: Module
type: exec
name: git-copy
description: Copy local repository
local: true
build:
  command: ["cp", "-r", ".git", ".git_garden", "&&", "chmod", "-R", "+w", ".git_garden" ]
include:
  - .git
```

**Comment by thsig** [comment]
Hi @kszymans! I think your workaround makes sense—is it slowing down your build process?

**Comment by kszymans** [comment]
It does not slow down, but complicates build process.
