### ISSUE TITLE
Test command shows different behaviors when using artifacts

### ISSUE THREAD

**Issue by anna-yn** [garden-io/garden#2634]
### Current Behavior

I have some jest tests in my repo and I noticed that running with `artifacts` makes jest behave differently. Without `artifacts`, when I run tests with this config:
```
tests:
  - name: modules
    command: ['yarn']
    args:
      - jest
      - --silent
```
Jest would print out something like this for each file it ran:
```
PASS src/something.spec.ts
```
But when I add an artifacts block (which copies over the right artifacts just fine):
```
    artifacts:
      - source: /frontend/junit-jest-modules.xml
        target: modules-result
```
Jest would run without those outputs, even ignoring options like `--verbose`. 

### Expected behavior

Jest should behave the same way with or without the `artifacts` block specified in tests.

### Reproducible example

I might try come up with a short example later. I'm using:
yarn: 1.12.3
jest: ^26.6.3

### Workaround

I haven't found a workaround for this yet. Right now I'd need to choose between seeing the test results in console log in each job or only see aggregated results produced with the artifacts.
### Your environment

* **OS:**  linux 
* **How I'm running Kubernetes:** AKS  

`garden version`
0.12.28

**Comment by vvagaytsev** [comment]
This was fixed a while ago. Closing this. Feel free to reopen if it's still and issue in the latest Garden versions.
