### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tbl-harmoney** [garden-io/garden#2655]
## Bug
Although no garden CLI commands are hanging, multiple processes are causing high CPU usage.
![image](https://user-images.githubusercontent.com/65944949/140931510-36c35a12-c72a-4a86-a3df-4d4547eb7cf3.png)

No `garden dev` commands were executed, only `garden deploy` using the `kubernetes` provider (cluster on GKE). 
`.gardenignore` files are also used to ignore folders like `node_modules`. Is there a way to check how many/which files are watched, as this might be the cause of the high CPU usage?

Some `garden deploy` executions seem to be stuck in the beginning on the provider step, before starting the deployment. After canceling the command, the process probably keeps on running.

### Your environment

* **OS:** MacOS Big Sur 11.6
* **How I'm running Kubernetes:** GKE

`garden version` 0.12.29

**Comment by thsig** [comment]
Hi @tbl-harmoney!

If you run e.g. `garden deploy --watch -l 4` (i.e. with the `debug` log level) you'll see something like this early in the log output:
```
Scanning project root at /Users/ths/src/garden/examples/demo-project
→ Includes: **/*garden.y*ml
→ Excludes: .garden/**/*,.git,.gitmodules,.garden/**/*,debug-info*/**
```
Currently, the watcher watches everything in the project that's not excluded in the project-level `modules.exclude` configuration. So in your case, it might be watching `node_modules` too (unless you've added that to the project-level  `modules.exclude`). See https://docs.garden.io/reference/project-config#modules.exclude for more details.

Do you also get this high resource usage when running a command that's not in watch mode, e.g. `garden build` or `garden deploy` without the `-w/--watch` flag? Just making sure we're looking in the right place for the cause of the high resource usage.

Happy to help diagnose this further!

**Comment by tbl-harmoney** [comment]
Hi @thsig, 

The following configuration is already present in `project.garden.yml`:
```
modules:
  exclude:
    - node_modules/**/*
    - target/**/*
```

Anyway, the `garden deploy` commands which were hanging and causing high CPU usage were _not_ run with the `-w` watch flag, so it might be unrelated to ignoring files. I'll keep running with the debug flag to diagnose further as it doesn't occur often that the deploy is stuck at the provider step.

**Comment by edvald** [comment]
Is this specific to macOS? Generally only the file watching is done in a distinctly different manner across platforms, so I wonder if it's more to do with some performance bug in module resolution etc.

Also, how big is the project? Thinking both in terms of module count and repo size.

**Comment by tbl-harmoney** [comment]
> Is this specific to macOS? Generally only the file watching is done in a distinctly different manner across platforms, so I wonder if it's more to do with some performance bug in module resolution etc.
> 
> Also, how big is the project? Thinking both in terms of module count and repo size.

Hi @edvald, this might indeed be a cross platform issue. I cannot confirm this for Windows/Linux yet. 
I would categorize the repo as large. ~50k commits and 3 application components which result in 10 garden modules:
* 3 container modules to build the application components.
* 3 helm modules to deploy the application components.
* 2 k8s modules for external components (database & document storage).
* 2 e2e test modules (build + deploy module) as we need a separate container image for the e2e tests.

Will also take a process dump if it happens again.

**Comment by tbl-harmoney** [comment]
Happened again, stuck at:
![image](https://user-images.githubusercontent.com/65944949/141806192-4cdb5c5f-458a-4bd8-a5d6-8c073b8024f4.png)

Took a snapshot and spindump of the process, will send it in private.

**Comment by tbl-harmoney** [comment]
Hi @edvald @thsig, some new info:

We've started to test our Garden setup with some of our developers using a Windows machine. It seems the same behaviour occurs, the `deploy`, `dev` but even `logs` command is stuck after completing the provider step. 

After cancelling the command and re-executing, it just works.

**Comment by tbl-harmoney** [comment]
Caught an execution in debug mode.
Just stops after scanning all modules.

<img width="1915" alt="Schermafbeelding 2021-12-07 om 09 28 17" src="https://user-images.githubusercontent.com/65944949/144994944-d27474a1-a85c-4a59-b6f3-aa1158a639e4.png">

**Comment by tbl-harmoney** [comment]
Sent a PM with a log trace after using `garden deploy -l=silly` on a Windows machine which seems to be stuck about 1 out of 2 executions.

**Comment by tbl-harmoney** [comment]
We've built a custom version of Garden with extra logging and came to the following conclusion:

Our project.garden.yaml file contained the following config:
```
dotIgnoreFiles:
  - .gitignore
  - .gardenignore
```
We started with `.gitignore` but needed some extra excludes as we also have sub (module) `.gitignore` files. We added some of these more specific ignores to a `.gardenignore` file.

However, this causes the function `getFiles()` in `core/src/vcs/git.ts` to behave differently, due to this if-condition:
https://github.com/garden-io/garden/blob/master/core/src/vcs/git.ts#L272
```TypeScript
if (this.ignoreFiles.length > 1) {
```

Some "intersection" logic is executed, calling a comparison function:
https://github.com/garden-io/garden/blob/master/core/src/vcs/git.ts#L294
```TypeScript
// Note: The comparison function needs to account for git first returning untracked files, so we prefix with
// a zero or one to indicate whether it's a tracked file or not, and then do a simple string comparison
const intersection = new SortedStreamIntersection(
  streams.map(({ output }) => output),
  (a: VcsFile, b: VcsFile) => {
    log.debug(`HARMONEY ${identifier}: comparing ${a.path} and ${b.path}`) // added custom log to debug
    const cmpA = (a.hash ? "1" : "0") + a.path
    const cmpB = (b.hash ? "1" : "0") + b.path
    return <any>(cmpA > cmpB) - <any>(cmpA < cmpB)
  }
)
```

When adding logs, an infinite loop seemed to be present:
```
HARMONEY 152: comparing .DS_Store and .dockerignore
HARMONEY 152: comparing .dockerignore and .dockerignore
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing undefined and undefined
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing .dockerignore and .dockerignore
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing undefined and undefined
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing .dockerignore and .dockerignore
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing undefined and undefined
HARMONEY 152: comparing .dockerignore and .DS_Store
HARMONEY 152: comparing .dockerignore and .dockerignore
...
```

As multiple ignore files in the garden config clearly complicate the execution, we just eliminated the `.gardenignore` file again:
```
dotIgnoreFiles:
  - .gitignore
```

FYI, contents of the deleted `.gardenignore` file were:
```
dist
node_modules
target
acceptance/reports
```
Which explains why `.dockerignore` and `.DS_Store` files were listed in the logs, although our `.gitignore` file does ignore them. This "multiple ignore file" and intersection logic can be tricky for an end user. It feels like adding an extra ignore file should just be an extra safety, whereas an extra ignore file with only few ignored lines can cause a heavy comparison.

As a conclusion: we have a valid workaround by just specifying 1 ignore file. However, the infinite loop could still be solved to improve the "multiple ignore file" setup.
