### ISSUE TITLE
file permissions are lost when files are copied/generated in generateFiles of moduleTemplates

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2674]
### Current Behavior

When files are copied and/or generated the file permission is lost. This causes an issue because we copy executable scripts and they can no longer be run.

### Expected behavior
The file permissions should be copied from the source to the target.

### Suggested solution(s)

the execution bit should be retained.

**Comment by 10ko** [comment]
We deprecated the `generateFiles` field, so closing this.
