### ISSUE TITLE
[FEATURE]: Require custom tag property in container module to tag the image with custom tagging

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#2680]
### Background / Motivation
The current behavior of garden build for container module to build the image and tag with garden module version. Developer do not have option to tag the image with custom tag as per their CI/CD policy. 

### What should the user be able to do?
run garden build which will create and publish the image with custom tag.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by tedchang77** [comment]
Garden should also be able to push the custom tag(s) to the docker registry.

**Comment by carolinapc** [comment]
Hi!
That's a nice feature to have, as we need to add customized tags without generating new images every time we pass a different one in extraFlags property.
