### ISSUE TITLE
[FEATURE]: Allow Automatic Environment cleanup to call garden workflows

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2686]
### Background / Motivation

The current implementation deletes the namespaces associated with an environment. For customers that are using Infrastructure as code tools like pulumi and terraform this leaves their state files in an inconsistent state.  Allowing the cleanup script to call a workflow would give you an audit trail as well as keep the state file synchronized. 

### What should the user be able to do?

enter garden workflow or command to call or maybe call default cleanup workflow that needs to be implemented by team.

### Why do they want to do this? What problem does it solve?
consistent way of handling resources in k8s cluster.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
Thanks @tedchang77. This is on the roadmap already, but happy to nudge it.

**Comment by tedchang77** [comment]
@edvald we have a workaround for this.. we can refresh the statefile/backend so it's synched with what's actually deployed so this can wait. just wanted to capture it so we don't forget.
