### ISSUE TITLE
[FEATURE]: Add few useful variables

### ISSUE THREAD

**Issue by kszymans** [garden-io/garden#2688]
### Background / Motivation

Hello 👋 
I am trying to setup clean up policy mechanism of preview envs deployed by garden and I noticed lack of two potentially useful features:
- `${git.ref}` or at least `${git.repository}` variable - in order to delete the preview env with garden from central place you have to be aware location of garden config, so repository is essential here. I overcome this by naming project name with the repo name
- `date` helper function or variable which will contain deployed date based on which you can decide whether it's time to clean up the env. This could help in order to check when the preview environment has been last time deployed with garden. I overcome this by using "creationTimestamp" from k8s namespace metadata.

### What should the user be able to do?

☝️ 

### Why do they want to do this? What problem does it solve?

☝️ 

### Suggested Implementation(s)

☝️ 

### How important is this feature for you/your team?

Something between these two:
🌵 Not having this feature makes using Garden painful
🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Hi @kszymans 

It makes perfect sense to add `ref` and `repository` to the `git` template context. We already have `${git.branch}`. 

When you say `repository` though, are you thinking the URL of the remote?

A `date` function is a bit more tricky. The Garden CLI doesn't really store any state, so I'm not quite sure how feasible it would be to implement this. In any case the CLI would need to "call" a given provider to get this information which we can't really do when template strings are resolved. 

My gut reaction to that would be to write some script around this that you can call from a Garden task or a Garden workflow.

**Comment by kszymans** [comment]
1. Yes, I meant to keep in `${git.repository}` variable return value of `git config --get remote.origin.url` your current repository
2. I may not follow you especially in terms of providers, but is there any problem to implement returning date mechanism under `${date}` variable or helper function with this: https://www.javatpoint.com/typescript-date-object?

**Comment by eysi09** [comment]
Ah, I may have misread your text. Do you just need the current date? If that's the case, it would be easy to add and we should definitely do that, along with some different formatting options.

**Comment by kszymans** [comment]
Yes, that's exactly what I need and I guess will be useful for others.
