### ISSUE TITLE
[FEATURE]:   generateFiles field on each module in a template should allow the use the path of module instead of just the path of the template

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2703]
### Background / Motivation

When using generateFiles in a template we need to use files that are located in the module itself and this is currently not possible as the path of the template is used.  The location of the modules is not in a subdirectory of the template location so we can't reach specify the files in the modules.

### What should the user be able to do?

Be able to use the path of the module for the generateFiles.sourcePath field.
We should also continue to support a generateFiles at the template level if there are files we want to generate that are not specific to a module.

### Why do they want to do this? What problem does it solve?

Need to generate files that are specific to a module. For example configuration data specific to a module.

### Suggested Implementation(s)

generateFiles field on each module in a template is taken to be relative to that module (as opposed to the template path), and to instead add a generateFiles field top-level on the ModuleTemplate resource itself.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by 10ko** [comment]
We deprecated the generateFiles field, so closing this.
