### ISSUE TITLE
`garden dev --hote=vote` errors: "not configured for hot-reloading" (despite readme)

### ISSUE THREAD

**Issue by Venryx** [garden-io/garden#2709]
### Current Behavior

Following instructions for trying the `vote` example causes an error -- specifically, when I try `garden dev --hot=vote`, I get: `The following requested services are not configured for hot reloading: vote`

### Expected behavior

I expect the example to start, with hot-reloading working.

### Reproducible example

Sequence of commands run:
1) `garden dev`
* Result: I got the error for ingress-controller: `DaemonSet/garden-nginx-ingress-nginx-controller: 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.` Presumably this is because I already had an ingress controller set up in my local Kubernetes cluster.
2) ctrl+c to cancel
3) Changed `vote/garden.yaml`'s `services[0].ports[0].containerPort` from `8080` to `8081`. (as quick test to see if that was the cause of the error above)
4) `garden dev`
* This time the ingress-controller error did not occur, but this time the `vote` deployment errored, with: `Deployment/vote: Readiness probe failed: Get "http://10.1.4.25:8081/": dial tcp 10.1.4.25:8081: connect: connection refused`)
5) ctrl+c to cancel
6) Changed the port above back to `8080`.
7) `garden dev --hot=vote`
* Result: the error mentioned above: `The following requested services are not configured for hot reloading: vote`)

### Additional context

I guess just the fact I already had a Kubernetes cluster set up, in Docker for Desktop?

### Your environment

* **OS:** Windows 10 Pro
* **How I'm running Kubernetes:** Docker for Desktop

`garden version`: 0.12.33

**Comment by edvald** [comment]
Hi @Venryx. It appears our docs for the vote example are out of date. We have deprecated the older "hot reloading" feature for the new _dev mode_. See the guide here: https://docs.garden.io/guides/code-synchronization-dev-mode

Basically the example should be run without the `--hot` flag now. I'll leave this issue open until we've updated the docs and possibly other examples along the way.
