### ISSUE TITLE
[FEATURE]: tilt

### ISSUE THREAD

**Issue by SurbhiSGupta** [garden-io/garden#2718]
### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

🌵 Not having this feature makes using Garden painful

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by thsig** [comment]
Haha. Hello there : )

**Comment by 10ko** [comment]
I think it might be a bit challenging to port Tilt from Go to Typescript but maybe @thsig you could take a look? 😆

**Comment by edvald** [comment]
Tempting as it is to... I guess I don't know, _tilt_ Garden? I'll go ahead and close :P

**Comment by SurbhiSGupta** [comment]
Oh my goodness, how completely embarrassing!

I was poking around and didn’t realize it would post the issue 🤦🏾‍♀️

As part of the design exploration, I’ve been looking at different ways of getting more user feedback from the Tilt itself, and appreciated seeing the elegant way you executed in your docs. Anyway! Hiding in a corner now. 😅
