### ISSUE TITLE
Garden won't build if minikube isn't up

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#272]
I get the sense that you *should* be able to build stuff without the server running, and that it would only be required for deploying. But I get errors whenever I'm trying to build things without minikube running. Not sure whether it's a bug or a feature (and the conversation on Slack didn't quite clarify it for me) so here's the issue so we can discuss.

```
➜  hello-world git:(master) garden build
Unexpected error when loading plugin "local-kubernetes": Error: Command failed: minikube ip
E0911 11:42:19.542508    2882 ip.go:48] Error getting IP:  Host is not running
See error.log for detailed error message

➜  hello-world git:(master) minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

➜  hello-world git:(master) garden build
Build 🔨
✔ openfaas--openfaas-build… → Building → Done (took 9.9 sec)
✔ hello-npm-package         → Building → Done (took 0 sec)
✔ hello-container           → Building hello-container:v21b6af98d9... → Done (took 6.9 sec)
✔ hello-function            → Building → Done (took 28.8 sec)

Done! ✔️
```

**Comment by edvald** [comment]
Ah, I thought you meant that Garden itself wasn't building. 

I wonder if this is something we want to address. We'd need to complicate the local-kubernetes plugin a bit, and the ability to build isn't super useful on its own. If you really need to build without minikube running, you could add an environment to the project config that doesn't include the local-kubernetes plugin.

I'll close this, but please re-open if I'm missing a use case here.
