### ISSUE TITLE
[FEATURE]: devMode file syncing from linked repository against remote module

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2736]
### Background / Motivation

Using devMode with code directly in the repo I'm using for Garden works (I'm using a git submodule) but there's a desire to move from git submodules to remote modules, and then link the module to a locally checked-out directory elsewhere in the filesystem. Now the subdirectory in my garden repo contains just the `garden.yml` and the linked code is elsewhere, but running `garden dev` starts up mutagen syncing from the directory containing the `garden.yml` and **not** the linked module directory that the code is being built from.

### What should the user be able to do?

DevMode should alter the local directory which is acting as the Mutagen source to be the linked module path, when a remote module is linked.

### Why do they want to do this? What problem does it solve?

We have numerous microservices and there are several options for us when working on parts of our stack with Garden:
- Pre-built images - doesn't allow us to do any live coding or change any of the code.
- Cluster-built images using git submodules in the garden parent repo - requires pulling down every single service's code and dealing with git submodule issues which scale up as our stack grows.
- Cluster-built images using remote modules - still requires pulling down every service's code but without dealing with git submodules, but also moves the code outside of the working tree and into `.garden` where it is harder to change.
- Remote modules with linking to local directories outside of the garden tree for working on specific codebases.

This last option seems to give us the most flexibility but unfortunately then can't be used with dev mode live syncing which is a critical aspect of the workflow.

### Suggested Implementation(s)

No user interface changes would be necessary, it's an internal-only change to local path resolution when the Mutagen sync configuration is being set up. We would require at least the kubernetes and container modules to work with this.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

I haven't yet unleashed this on our wider dev team but I can see that the git submodule approach in order to use devMode will likely come with a lot of friction for our team - one that I'm hoping to avoid in order to gain buy-in.

**Comment by edvald** [comment]
Filing this as a bug actually. Syncing from the linked directory is the sane behavior imo, and I think this is just an oversight.

**Comment by ohookins** [comment]
I believe this is working, seems like it was a permissions issue in the destination container. Unfortunately mutagen and garden are completely silent on this so it would still be good to get more observability on problems, but I think we can close this particular issue.
