### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#274]
[This is out of date as we're now using Airtable to keep track.]

### Index

* Basics `PENDING`
  * Installation `REVIEW`
  * Quick Start `REVIEW`
  * Concepts `REVIEW`
* Using Garden `PENDING`
  * Features and usage `WRITE`
  * Configuration files `REWRITE`
  * Providers `WRITE`
* Example projects `PENDING`
  * Hello world `WRITE`
  * Simple project `REWRITE`
  * TLS project `PENDING`
  * Socks shop or Coolstore set-up `PENDING`
  * Something heavy on serverless `PENDING`
* Guides `PENDING`
  * Projects with multiple remote and local repos `WRITE`
  * Configuring hot reload `WRITE`
  * Setting up TLS `PENDING`
  * How to "gardenify" an existing project `WRITE`
  * Migration guide from Docker Compose to Garden `WRITE`
  * Getting started with Kubernetes using the Garden framework `WRITE`
* Contributing to Garden `REWRITE`
* Reference `PENDING`
  * Glossary `REWRITE`
  * Commands Reference `REWRITE`
  * Config Files Reference `REWRITE`
  * Provider Configurations `PENDING`
    * Container `WRITE`
    * Kubernetes `WRITE`
    * OpenFaaS `WRITE`
    * Local Kubernetes `WRITE`
    * Google Cloud Functions `WRITE`
  * Module Configurations `PENDING`
    * Container `WRITE`
    * OpenFaaS `WRITE`
    * Google Cloud Functions `WRITE`
* FAQs `REWRITE`

Tags:

`WRITE` - Yet to be written.
`REWRITE` - Needs significant changes.
`PENDING` - Not to be worked on at the moment.
`REVIEW` - Ready to be reviewed by a colleague.
`done` - File is in its final version.

Related: #257.

**Comment by eysi09** [comment]
A few notes:

* _Motivation_ feels a little out of place. Perhaps move it to the bottom?
* I think we should also have a _Features_ chapter.

**Comment by ellenkorbes** [comment]
Thanks. Made some adjustments.
