### ISSUE TITLE
[FEATURE]: Allow a task to be running based on a different image than the parent container module

### ISSUE THREAD

**Issue by jgeigerOnline** [garden-io/garden#2744]
### Background / Motivation

Currently tasks are restricted to the image of the parent container module. Now, in my case I have a Java container (A) that requires a message queue container (B) to be set up in a very specific way that is only known to A and is therefore not supposed to be moved to B. Tasks would be ideal for this as A could then have a task that would set up B with knowledge local to A but as A does not have the same tooling as B it is not solvable via a task currently.

### What should the user be able to do?

Specify an image for a task that is different from the parent container.
For example: A Java image contains a task that is based on a message queue image containing message queue tooling usually not known to a Java image.

### Why do they want to do this? What problem does it solve?

Having to create a separate container module whose only purpose is to set up an environment instead of combining this with the container using the results of the setup.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
Hi @jgeigerOnline—thanks for writing this up! This is a great idea, we'll have a look.
