### ISSUE TITLE
[FEATURE]: conditionally deploy services that have a dependency on another service when it is deployed

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2759]
### Background / Motivation

we have service-b that has a dependencies on service-a and also consumes an output from service a.. for example a dns entry. when we change service-a's outputs and re-deploy service-a, service-b has stale values causing it to not be able to connect to service-a. we need to then redeploy service-b to pick up the new output values.

### What should the user be able to do?
automatically deploy services that have a dependency on the service that is being deployed. should be able to specify if you only want to deploy if the dependent service is already running or deploy if its missing.

### Why do they want to do this? What problem does it solve?
not having to redeploy dependent services yourself

### Suggested Implementation(s)
a couple of options added to the deploy command: --with-dependants and --update-only, the rormer willatter indicating that missing services should not be deployed.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by Orzelius** [comment]
@tedchang77 sorry for taking so long with this, but it has been implemented via https://github.com/garden-io/garden/pull/4786.

For the `--update-only` flag could you perhaps create a separate issue if you still feel the need for it.
