### ISSUE TITLE
[FEATURE]: Add flag to generateFiles property

### ISSUE THREAD

**Issue by carolinapc** [garden-io/garden#2775]
## Feature Request

Add flag to **generateFiles** property

### Background / Motivation

Currently **generateFiles** property is throwing error if the source file is not found. 

### What should the user be able to do?

Add optional files to the **generatedFiles** property and garden will ignore errors if they do not exist.

### Why do they want to do this? What problem does it solve?

When deploying a module that uses a template that has **generateFiles** property, not all modules that uses this template have the files in the list to be copied. With this feature, we would not be forced to create an empty file just to avoid the error, instead we would set not required files as optional and the error wouldn't be thrown.

### Suggested Implementation(s)

Set a flag (called _optional_ or _required_), which value would be true or false. 
Once it is set as optional (e.g: _optional=true_ or _required=false_) garden will not thrown error if the source file does not exist.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
Will this still be an issue in 0.13, or will module templates be changing significantly there? @edvald

**Comment by 10ko** [comment]
We deprecated the generateFiles field, so closing this.
