### ISSUE TITLE
[FEATURE]: Prompt to proceed when running commands like garden delete

### ISSUE THREAD

**Issue by carolinapc** [garden-io/garden#2781]
### Background / Motivation

`garden delete` command runs without confirmation to proceed. That means we can accidentally destroy all deployments.

### What should the user be able to do?

When running the command, a prompt should ask if the user likes to proceed.
Also add an optional flag (-y)  so we can run without prompt when running automatically inside custom commands for instance, like Pulumi does with the command `pulumi cancel -y`.

### Why do they want to do this? What problem does it solve?

Commands needs to be failsafe so we can avoid accidental mistakes.

### Suggested Implementation(s)

Add a prompt confirmation when running garden commands like delete, build, deploy.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
Thanks for the request @carolinapc! This looks like a nice feature, but it would be a breaking change. We'll consider including this in the next minor release `0.13`.
