### ISSUE TITLE
Inconsistent emoji rendering across terminals

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#279]
The emoji look great on macOS, but they're often rendered as � and □ on e.g. PowerShell (Windows) and Konsole (Linux/KDE).

I propose we add some sort of check and only attempt to use emoji in terminals where we've tested that it works.

Thoughts?

**Comment by edvald** [comment]
Good catch. I wonder how we might be able to detect it... _(goes Googling)_

https://www.npmjs.com/package/detect-emoji-support

Lemon squeezy.

**Comment by eysi09** [comment]
Closed in #308.
