### ISSUE TITLE
[FEATURE]: add ability to filter the stack graph on additional fields

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2807]
### Background / Motivation

The stack graph currently allows you to filter on build, deploy, task and test. We currently have a large dependency graph with many dependencies that makes the graph very busy and hard to see all the relationships. it would be nice to be able to have labels and selectors similar to k8s: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ I don't think we need to support the full matchExpressions and matchLabels may be a good start. 

### What should the user be able to do?

from the UI generate list of keys and values that are in the stack graph that you can choose from. for example:

action=deploy # this key and value is automatically created based on the kind
type=frontend
owner=team1
serviceExposure=external

### Why do they want to do this? What problem does it solve?

allow you to focus on certain parts of the stack graph

### Suggested Implementation(s)

add metadata to module definitions:
metadata: 
   labels:
     key1 : value1
     key2 : value2
  
autocomplete labels (keys and values) based on stack graph. start with simple match and then add additional capability to add expressions if their is demand for this.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
That's a great idea. 

We'll be making a lot UI/UX improvements in the coming weeks and this is great feedback to feed into that conversation. 

We're also planning to add a notion of tags at the framework level which would allow you to do just that.

**Comment by vvagaytsev** [comment]
@tedchang77 we have a major refactoring related to the Stack Graph in progress now. We can get back to this request once the Stack Graph changes are released. The tentative release date is the end of the summer.
