### ISSUE TITLE
Command names not displaying in garden --help in PowerShell

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#281]
No idea why, but it seems the color we use for the command names in our help message don't display in PowerShell:

https://www.dropbox.com/s/nxcr92o7zfnwcrf/Screenshot%202018-09-16%2016.45.56.png?dl=0

Side-note: I'm not sure the single letter aliases make much sense for top-level commands, and some of them are clearly wrong, `r` is an alias in more than one place. We should check and fix those.

**Comment by eysi09** [comment]
Closed in #346

**Comment by eysi09** [comment]
Actually this is still a problem.

**Comment by eysi09** [comment]
This appears to be no longer an issue.
