### ISSUE TITLE
[FEATURE]: Be able to add more than one garden command in the custom commands

### ISSUE THREAD

**Issue by carolinapc** [garden-io/garden#2819]
### Background / Motivation

I'm trying to create a custom command where I need to run two garden commands at once. 

So first I'm generating a file from the result of this command: 
```garden get modules -o=json > garden-modules.json``` 

Then I need to call this workflow to run the steps I need with the file generated:
```garden run workflow my-workflow```

### What should the user be able to do?

Instead of passing only one **gardenCommand** in the **Command** module, we could be able to pass as many as we wish to call.

### Why do they want to do this? What problem does it solve?

I would like to be able to run one command (custom command) to execute one or more garden commands.

### Suggested Implementation(s)

Improve the gardenCommand property to allow more than one command. Currently we can only mount one.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
Hey @carolinapc. Feature request accepted :) But there are actually a couple of ways you could do this already:

1. Run both commands in an exec step with e.g. an external script or with `command: [sh, -c,  "garden get modules -o=json > garden-modules.json; garden run workflow my-workflow"]` (nothing to prevent calling the garden CLI from exec commands, even multiple times); and
2. Run the first command as an exec step and then the workflow with `gardenCommand`.

Both will functionally do the same thing. There may also be a way to make that first command a part of the workflow you've defined, but I'd need to dig into that specific workflow to see.

Hope that helps!

**Comment by carolinapc** [comment]
Hi @edvald, thank you for accepting the request. 
I've implemented second option you suggested as a workaround, but I really prefer the first option cause I just want that to ran once, and I think the workflow is running for each module (please let me know if I'm wrong).

So using the first option, I implemented like that
```
exec:
  command: 
    - sh
    - -c
    - ./deployment-common/workflow-scripts/installNodeModules.sh
    - " | garden get modules -o=json --var generateDependencies=true > garden-modules.json"
```
Working pretty :) thank you!

**Comment by edvald** [comment]
The first option should work fine, but I'd suggest doing it something like this:

```yaml
exec:
  command: 
    - sh
    - -c
    - |
      ./deployment-common/workflow-scripts/installNodeModules.sh
      garden get modules -o=json --var generateDependencies=true > garden-modules.json
      garden run workflow my-workflow"
```

The workflow will only run once, to be clear. Hope that does the job :)

**Comment by carolinapc** [comment]
That's what I was doing before but I got errors, and I thought that could be something that garden were preventing me to do! Maybe I mistyped it though. I'll try again. Thanks!

**Comment by carolinapc** [comment]
> The first option should work fine, but I'd suggest doing it something like this:
> 
> ```yaml
> exec:
>   command: 
>     - sh
>     - -c
>     - |
>       ./deployment-common/workflow-scripts/installNodeModules.sh
>       garden get modules -o=json --var generateDependencies=true > garden-modules.json
>       garden run workflow my-workflow"
> ```
> 
> The workflow will only run once, to be clear. Hope that does the job :)

I tried again this approach but I got these errors:
```
sh: 2: ./deployment-common/workflow-scripts/installMavenPlugin.sh: Permission denied
internal/modules/cjs/loader.js:967
  throw err;
  ^

Error: Cannot find module '/home/x227191/thxcs-shared-services/get'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

So the way it worked was this one:
```
exec:
  command: 
    - sh
    - -c
    - ./deployment-common/workflow-scripts/installNodeModules.sh
    - "| garden get modules -o=json --var generateDependencies=true > garden-modules.json"
 ```
