### ISSUE TITLE
`garden test` reporting error although command succeeded

### ISSUE THREAD

**Issue by tbl-harmoney** [garden-io/garden#2822]
### Current Behavior

Occasionally, running tests through `garden test` result in a non-zero exit code although the underlying executed command returns exit code 0. 
Artifacts are not collected as well, is it possible the transfer of artifacts fails and returns the error code?
<img width="860" alt="image" src="https://user-images.githubusercontent.com/65944949/155537882-c4583870-6ec8-4ada-a95c-c31778fe4750.png">
"1 test task(s) failed"
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/65944949/155538683-aa59d9b8-00fa-41ed-a7f8-b3c0114b2a7a.png">

### Expected behavior

`garden test` succeeds or gives more info about the error.

### Your environment

* **OS:** Linux, docker, ubuntu-20.04
* **How I'm running Kubernetes:** GKE

`garden version` 0.12.34

**Comment by thsig** [comment]
Hi @tbl-harmoney! It does indeed look like the error in the artifact handling logic is what's causing the error here.

Should we simply log the error but return a zero (successful) exit code when the test suite itself succeeds but there's an error in the artifacts logic, @edvald?

That would be a simple change, but I just wanted to verify that we'd be OK with those semantics.

**Comment by tbl-harmoney** [comment]
Closing because of https://github.com/garden-io/garden/issues/2816#issuecomment-1074903565
