### ISSUE TITLE
[FEATURE]: Cleanup PersistentVolumeClaims on `garden delete service`

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2836]
### Background / Motivation

I just got PVCs working to back some of our in-stack databases and noticed that when I `garden delete service`, the PVCs are left in place. There doesn't appear to be another command to run that would clean them up, which is a bit inconsistent with the behaviour of the CLI in general.

### What should the user be able to do?

Be able to clean up all Garden-provisioned resources including PVCs with the Garden CLI itself.

### Why do they want to do this? What problem does it solve?

PVCs in cloud environments come with a cost-associated component (e.g. EBS volumes left dangling) which can only be removed by cleaning up the namespace (which is also not something Garden does, as far as I'm aware). While I have plans to automatically clean up namespaces periodically, PVCs seem like an obvious choice to prevent runaway resource utilisation and expenditure.

Additionally, if developers want to reset their stack to a clean state, this is the only way to do it without resorting to kubectl commands.

### Suggested Implementation(s)

Either an additional command like `garden delete volumes` or an additional flag to `garden delete service` like `--delete-volumes`. I'd prefer the latter so we can keep deletion of the resources to one command I can give to developers.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

Aside from the cost and resources element, moving our backing stores to PVs means that resetting Garden stacks to a clean state can no longer be achieved with the Garden CLI alone.

**Comment by ohookins** [comment]
@eysi09 would still like this to be solved, as `garden delete environment` means we have to trash our letsencrypt private key, and I'm still worried about hitting rate limits there. The other thing that would be helpful would be for the task output secrets to also be cleaned up, which would mean being able to re-provision a stack from a relatively clean state without the full nuclear option of destroying the namespace.

**Comment by 10ko** [comment]
Hi, we are planning to remove specific PVC related action types and won't be supporting this use case in the future.

**Comment by ohookins** [comment]
What will be the replacement? Is it expected that PVCs are just implemented
using kubernetes actions?
