### ISSUE TITLE
[FEATURE]: List multiple containers for devMode within a Helm module

### ISSUE THREAD

**Issue by agates4** [garden-io/garden#2886]
### Background / Motivation

We have multiple deployments with our Helm chart. We need to hot reload each deployment, and sometimes sync the file directories in different ways.

Rather than busting up the Helm chart with multiple Helm charts, one for each deployment, I'd like to specify a list of containers to use with devMode.

This devMode ought to be a list, rather than allowing only one container name:
https://docs.garden.io/reference/module-types/helm#devmode.containername

### What should the user be able to do?

Specify multiple containers for devMode within a Helm module.

### Why do they want to do this? What problem does it solve?

This helps elliminate the need for multiple Helm modules, one per deployment.

Also, because dynamic module templating is not yet available, this means that we could have just 1 Helm module, instead of trying to figure out how to support N number of Helm modules per team.

### Suggested Implementation(s)

For these deployments:
```
λ kubectl -n my-microservice get pods                                              
NAME                                     READY   STATUS    RESTARTS   AGE
sample-api-64679bcc49-rmmqr        3/3     Running   0          20d
sample-consumer-79796b7466-c69hv   3/3     Running   0          20d
```

Allow this devMode configuration:
```
devMode:
  - containerName: sample-api
    args: []
    command: []
    sync: []
  - containerName: sample-consumer
    args: []
    command: []
    sync: []
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
+ No parity with our staging/prod deployments.

**Comment by thsig** [comment]
Note: This has been implemented in 0.13 (which is still under active development).
