### ISSUE TITLE
Workflow steps producing empty logs with structured output (-o=json / -o=yaml)

### ISSUE THREAD

**Issue by RixTmobilender** [garden-io/garden#2898]
### Current Behavior
Running a workflow with the output flag set to either JSON or YAML produces an empty log key:
![image](https://user-images.githubusercontent.com/87778732/162537918-9d00bd73-fe0d-4909-bfff-6f169a32b6f3.png)

Perhaps related to https://github.com/garden-io/garden/issues/2883
### Expected behavior
The log key should be populated with the jsonstring output of my workflow step, the same way tasks do

### Reproducible example
```
kind: Workflow
name: reproducible-example
steps:
- script: |
    echo "[\"my_json_string\"]"
```
`garden run workflow reproducible-example -o=json`
### Your environment

* **OS:** Ubuntu 22.04 on WSL2
**Garden version**: `0.12.39`

**Comment by Orzelius** [comment]
@RixTmobilender thank you for the issue, I wouldn't have noticed the bug if you hadn't pointed it out. Is fixed via https://github.com/garden-io/garden/pull/2972
