### ISSUE TITLE
Garden crashes if default dashboard port is taken

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2924]
### Current Behavior

If I run Garden in persistent mode in a given project, it starts the dashboard server at port 9777. 

When I run Garden in persistent mode (for a different project, probably not relevant) in another process it crashes because the dashboard port is taken:

```
✔ garden-enterprise         → Authorizing... → Done
   ℹ Visit project at https://eysi.dev.enterprise.garden.io/projects/1

Error: listen EADDRINUSE: address already in use 127.0.0.1:9777
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at GetAddrInfoReqWrap.doListen (net.js:1516:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8)
```

### Expected behavior

It should pick another random port.

### Reproducible example

See above.

### Workaround

Manually set the dashboard port via env var when starting the second process. E.g.: `GARDEN_SERVER_PORT=9778 garden dev`. 

### Suggested solution(s)

I'm wondering if this broke with #2891. Maybe start by seeing whether there's something fishy in that commit.

**Comment by vvagaytsev** [comment]
There is a breaking change in [v.6.0.0](https://github.com/sindresorhus/get-port/releases/tag/v6.0.0), the package became [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
