### ISSUE TITLE
[FEATURE]: Allow custom annotations for image builders so that IRSA can be used

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2931]
### Background / Motivation

According to the [AWS EKS Best Practices Guide](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node), when using IRSA you should set the instance metadata service to IMDSv2 and the hop count to 1. This means that pods will no longer be able to talk to the regular instance metadata endpoint and inherit the role of the node.

Under normal conditions, kaniko or cluster-buildkit will just use the default Service Account, and not have any specific IAM role that grants it ECR push permissions, so it will rely on the instance role and ECR push permissions associated with it. If we want to enforce the above security settings, any ECR pushes will fail. Since there's no opportunity to add annotations to these pods, we can't tell IRSA which IAM role the builder should assume, and hence can't give it the right permissions. This will break effectively all modules using in-cluster built images.

### What should the user be able to do?

Add a configuration in the Garden project configuration associated with the chosen builder service, that adds the K8s annotation to the builder's service account. This probably also means that a build service account needs to be created by Garden.

### Why do they want to do this? What problem does it solve?

See the description above.

### Suggested Implementation(s)

This could just be added to the existing configuration map that you pass for the builder in the project configuration. I'm not sure how things like for GKE or AKS works with respect to pod roles, so I guess it would be good to have a solution that works equally well for those platforms (although I'm not using them).

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

It's a non-functional requirement as far as the day to day developer experience goes, but not having this means that any Garden pod can assume the instance IAM role, and use any permissions a given EKS node can use. This is not great for security.

**Comment by thsig** [comment]
Hi @ohookins! Thanks for the detailed suggestion here.

Would you be interested in implementing this functionality and submitting a PR?

We'd be happy to hop on a call and do some pair-programming on this, and to point you to the right places in the codebase to get started (and answer any questions that may come up).

**Comment by stefreak** [comment]
Just so nobody else duplicates the effort: I am actively working on this :)

**Comment by stefreak** [comment]
One thing I noticed during the investigation is that a service account would also be useful for the tasks.

First implementation will only target in-cluster-building, but I will at least create another feature request issue for allowing for IRSA (or injecting credentials through service accounts in general) also for tasks.

**Comment by stefreak** [comment]
We should make sure, when implementing this, that it also can be used to enable using GCP's workload identity: https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

**Comment by stefreak** [comment]
IRSA for Runs is already possible in Garden 0.13 via the [kubernetes-pod](https://docs.garden.io/reference/action-types/run/kubernetes-pod) `Run` type.
