### ISSUE TITLE
Rsync error : `rsync: failed to connect to localhost`

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#2944]
## Bug

While deploying on our Cluster from a GitHub action worfklow we encountered a `rsync` error. It worked after retrying the action manually. Maybe it should retry by itself or wait for the connection to be ready?
 
### Current Behavior

Failed building app. Here is the output:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command "rsync --recursive --links --perms --times --compress --relative --delete --temp-dir /tmp /home/runner/work/slite/REDACTED/.garden/build/./app/ rsync://localhost:33883/volume/d019468f-f347-49ac-b38f-70ea95590283/" failed with code 10:

rsync: failed to connect to localhost (::1): Connection refused ([111](https://github.com/slite/REDACTED/runs/6385791447?check_suite_focus=true#step:7:111))
rsync: failed to connect to localhost (127.0.0.1): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [sender=3.1.3]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```

### Expected behavior

It should not fail :D 

### Workaround

Retry

### Suggested solution(s)

Have a retry included or wait for connection to be ready?

### Your environment

* OS: Ubuntu20.04.4
* Cluster: GKE
* Buildkit
* Garden version: 0.12.40

**Comment by vvagaytsev** [comment]
@antoinelyset could you try the [edge release](https://app.circleci.com/pipelines/github/garden-io/garden/11837/workflows/0e917b86-54e8-43bb-b6c4-1ed189af5a10/jobs/188162/artifacts), please?

I increased the number of retries and the time intervals between attempts. This might fix the issue.

**Comment by antoinelyset** [comment]
We implemented a retry at our level too. I will still see if it happens again.

**Comment by vvagaytsev** [comment]
Ok, thank you @antoinelyset! Please let me know if this fix does not work. This fix will be released in Garden `0.12.41`, it's coming soon.

**Comment by vvagaytsev** [comment]
@antoinelyset sorry for the very late reply. Yes, I think you can try it. Please let us know if it helps.

We have got other issues with `rsync` reported in #3332. Have you ever seen the same problem?

**Comment by stefreak** [comment]
@antoinelyset good to hear, we're actually planning to release a new version pretty soon.
