### ISSUE TITLE
Logging issues when tasks fail

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#295]
https://www.dropbox.com/s/ctikvvqcfh2x05q/Screenshot%202018-09-22%2019.57.48.png?dl=0

Something off in how we log print out task errors.

**Comment by eysi09** [comment]
Another case of feeding callback functions blindly to the `map` function.

```javascript
arr.map(callback) // bad, because map passes both the array element, the index and the original array to the callback
arr.map(el => callback(el)) // good
```
Fixed in #305.
