### ISSUE TITLE
Windows installation script no longer activates Hyper-V?

### ISSUE THREAD

**Issue by mbaeuerle** [garden-io/garden#2958]
Hi!

I was checking the installation for the garden CLI [here](https://docs.garden.io/getting-started/1-installation#windows) and saw that it mentions that it will activate Hyper-V and optionally install Docker during the installation process.

As we only intended to use Garden remotely and with in-cluster building both are not necessary and I wondered if there is a way to skip these steps.

Then I checked the actual PS script and it seems like the virtualization and Docker steps [were already removed since then](https://github.com/garden-io/garden/commit/97d49fe783af4288d9489a0654ca5d7b21e0b463) and just the docs may need to be updated accordingly, is that correct?

Best regards!
Marian

**Comment by vvagaytsev** [comment]
Thanks @mbaeuerle! Yes, you're right, these steps were intentionally removed in !97d49fe7. I'll update the documentation soon.
