### ISSUE TITLE
[FEATURE]: `garden run task` and `garden test` should (optionally) output incremental log output in real-time 

### ISSUE THREAD

**Issue by isaacpz** [garden-io/garden#2970]
### Background / Motivation

`garden run task` and `garden test`  both show a “Running” spinner while the task is running. No log output is printed to the console until the task/test is complete.

### What should the user be able to do?

A user should be able to see incremental logs as a task runs. Optionally, this behavior could be hidden behind a flag.

### Why do they want to do this? What problem does it solve?

Biggest pain point is around using Garden to power CI workflows. Currently, when using `garden test` or `garden run task` in CI, the logs are very hard to use because:

- hung/spinning tasks never output anything at all, and are thus impossible to debug
- we don’t get timestamps from our CI provider when all logs are dumped at the same time
- hard for engineers to know what stage the CI is at if the task takes a long time to run

### Suggested Implementation(s)

Something like `garden run task --incremental-logs` would suffice! 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
For context: This comes out of a conversation we had on our community Slack.

In short, we'd be happy to implement this at the same time we rework our CLI logging (which we're hoping to do soon).

We already have all the incremental log streaming machinery functioning, so this would mostly be a matter of logging.

**Comment by 10ko** [comment]
This is now available in `0.13.x` if you set the log level to verbose.
We don't have plans to support what @salotz has mentioned in their comment, at least not in this fashion.
