### ISSUE TITLE
[FEATURE]: Diff / Preview / Dry-Run mode for Deploy

### ISSUE THREAD

**Issue by jamesmeneghello** [garden-io/garden#2973]
### Background / Motivation

We often have manual approval steps as part of deployments, for somebody to glance over and double-check that nothing is changing that will break things.

### What should the user be able to do?

It's nice to be able to have some kind of visual report on what's changing to display as part of a CI approval step or some such. Some ability to do a dry-run of deploy and produce a report would be excellent.

### Why do they want to do this? What problem does it solve?

So that you can understand at-a-glance what a deploy is going to do.

### Suggested Implementation(s)

Something akin to Pulumi preview would be great.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by Orzelius** [comment]
Yeah this makes a lot of sense to have. Currently you could compare the `garden get modules` command output to the `GARDEN_VERSION` env value in containers in k8s but that's quite annoying to do.

**Comment by jamesmeneghello** [comment]
Is that only for container modules? The ones I deploy using Kubernetes modules don't seem to have it.

**Comment by thsig** [comment]
We've been planning to implement this functionality for a while, but we're currently in the middle of a huge refactor and refresh of our config syntax.

We'll have a look at this once that's done (which will hopefully be by the end of June).

**Comment by vvagaytsev** [comment]
Closing in favor of #4658
