### ISSUE TITLE
[FEATURE]: Don't force Helm dependency updates

### ISSUE THREAD

**Issue by jamesmeneghello** [garden-io/garden#3000]
### Background / Motivation

Bitnami's repositories are falling apart at the seams, and about 1 in every 5 helm calls to their registry fails. Unfortunately, this means that even caching the charts locally and using `chartPath` doesn't work, because they have a dependency on a common chart. Garden (helpfully) automatically checks this dependency for updates, but this then sometimes fails. 

End result: about 1 in 5 `garden deploy`s are failing.

### What should the user be able to do?

It'd be great to make the dependency update checks optional?

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

**Comment by vvagaytsev** [comment]
Thanks for reporting this! We'll take a look soon. We think we can add a retry for this.

**Comment by vvagaytsev** [comment]
@jamesmeneghello is this still a problem?
