### ISSUE TITLE
Garden 0.12.43 fetch-tools fails on Alpine 3.15.0

### ISSUE THREAD

**Issue by jamesmeneghello** [garden-io/garden#3061]
### Current Behavior

```
/garden/static # GARDEN_DISABLE_ANALYTICS=true GARDEN_DISABLE_VERSION_CHECK=true garden util fetch-tools --all --garden-image-build --logger-type=basic
Error relocating /garden/better_sqlite3.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
```
### Reproducible example

`docker run --rm -it alpine:3.15.0 ash`

```
apk add bash curl docker-cli git openssl rsync ca-certificates tar gzip openssh-client libstdc++
mkdir /garden
cd /garden
export GARDEN_VERSION=0.12.43
curl -L -o garden.tar.gz https://github.com/garden-io/garden/releases/download/$GARDEN_VERSION/garden-$GARDEN_VERSION-alpine-amd64.tar.gz
tar -zxvf garden.tar.gz
mv alpine-amd64/* .
chmod +x garden
ln -s /garden/garden /usr/bin/garden
chmod +x /usr/bin/garden
cd /garden/static
GARDEN_DISABLE_ANALYTICS=true GARDEN_DISABLE_VERSION_CHECK=true garden util fetch-tools --all --garden-image-build --logger-type=basic
```

### Workaround

Works fine for Garden 0.12.42

### Your environment

* **OS:** Alpine 3.15.0 amd64

`garden version`: `0.12.43`

**Comment by jamesmeneghello** [comment]
Fix (specifically for this image):

```
apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/main libstdc++
rm /usr/lib/libstdc++.so.6 && ln -s /usr/lib/libstdc++.so.6.0.29 /usr/lib/libstdc++.so.6
```

**Comment by vvagaytsev** [comment]
Thanks for reporting this @jamesmeneghello! We'll try to address this issue in the next patch release.

**Comment by vvagaytsev** [comment]
@jamesmeneghello it looks like the wrong version of `stdlibc++` is getting installed -- `6.0.28`, while it should be `6.0.29`.

Have you tried to use the `--no-cache` flag in the `apk add bash curl docker-cli git openssl rsync ca-certificates tar gzip openssh-client libstdc++` command from the reproducible example? Could you try that to check if it helps? We use that flag to build a Garden image for Alpine, see [`alpine.Dockerfile`](https://github.com/garden-io/garden/blob/master/support/alpine.Dockerfile).

By the way, does the same issue happen with [this Garden build](https://output.circle-artifacts.com/output/job/89f1fbea-e32c-4fef-ab56-fdf0a3d780e9/artifacts/0/dist/garden-0.12.43-alpine-amd64.tar.gz)?

**Comment by thsig** [comment]
Reopening this for now, feel free to close it if this has ben resolved in the meantime.
