### ISSUE TITLE
Garden logging doesn't work as expected with large amounts kubernetes logs

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#3062]
### Expected behavior

see https://github.com/garden-io/garden/compare/0.13...jest-artifacts-repro-2 for reproducible example

the `garden test frontend` log output should match the one from just running `npm run test` in the frontend direcotry

`npm run test` produces about 1.3k log lines in the correct order and so should running garden.

### Reproducible example

see https://github.com/garden-io/garden/compare/master...jest-artifacts-repro-2 for reproducible example

* the test just via npm produces about 1.1k lines every time (we want this)
``` sh
GARDEN_LOGGER_TYPE=basic gdev run test frontend no-artifacts --env=local 2>&1 >/dev/null | wc -l
# 1106
```
* running the same test via garden with or without artifacts and with or without fancy logger produces 5-15k lines of logs, which seem to be duplicated and repeated a whole bunch
``` sh
GARDEN_LOGGER_TYPE=basic gdev run test frontend no-artifacts --env=local 2>&1 >/dev/null | wc -l
# 12713
GARDEN_LOGGER_TYPE=basic gdev run test frontend with-artifacts --env=local 2>&1 >/dev/null | wc -l
# 9708
```
* running both tests together produces correct(ish) amount of logs, but they're still out of order and look corrupted
```
GARDEN_LOGGER_TYPE=basic gdev test frontend --env=local 2>&1 >/dev/null | wc -l
# 2266
```

Things that change behavior of logs (for worse or better):
* how many garden tests are run
* logging behavior of the tests themselves
  * how much is logged at once
  * how much is logged to stdout/stderr
* with or without artifacts
* kubernetes (local seems to be worse??)
* logger type
* the amount that is logged by the test
* stderr seems to make things worse
* using jest

### Workaround

Play around with things mentioned above and it might fix the issue for you. The example I provided seems to be unfixable without modifying the tests themselves.

The easiest fix is to reduce the amount of logs. Running tests one by one instead of all of them also fixed the issue sometimes.

### Suggested solution(s)

Rewrite garden logging logic (planned this year) and implement more tests that test logging output

**Comment by stefreak** [comment]
@Orzelius i'm curious, you wrote

> local seems to be worse

How can you run the test locally? Did you try that using the exec plugin?

**Comment by Orzelius** [comment]
> @Orzelius i'm curious, you wrote
> 
> > local seems to be worse
> 
> How can you run the test locally? Did you try that using the exec plugin?

I think I meant local kubernetes there. I faintly remember testing with both minikube and microk8s
