### ISSUE TITLE
garden dev: modifying upstream dependency of tests doesn't correctly trigger new tests

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#307]
Noticed this earlier, unsure if it's caused by the flow in the `garden dev` command action, or if the dependency list or versioning is off in the `TestTask`. 

Either way, you can reproduce by 
1) starting `garden dev` in the simple-project example
2) modifying `services/go-service/webserver/main.go`, changing "Hello from Go!" to "Hello from foo!"

Observe that both unit and integ tests for `node-service` run instantly, without waiting for the updated `go-service` to deploy.

Breaking the test `test/integ.js` in `node-service` directly produces the expected result however.

@thsig can you dig into this?

**Comment by thsig** [comment]
Will do.
