### ISSUE TITLE
Cloud command palette does not work with the `serve` command

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3081]
### Current Behavior

When I run `garden dev`, I am able to use the Cloud command palette as expected.

If I instead run `garden serve`, it doesn't appear to respond to the command palette. 

I think the gif below pretty much sums it up.

![Kapture 2022-07-29 at 12 38 04](https://user-images.githubusercontent.com/5373776/181742444-da8349b4-3356-4998-8c3f-91d9dbc6f025.gif)

### Workaround

Always use the `dev` command.

### Environment

Using latest versions of Core and Cloud.

**Comment by Orzelius** [comment]
closing as I presume it works now
