### ISSUE TITLE
[FEATURE]: local.arch template variable

### ISSUE THREAD

**Issue by KoduIsGreat** [garden-io/garden#3086]
## Feature Request
provide access to a `local.arch` template variable similar to [platform](https://docs.garden.io/reference/template-strings/modules#usd-local.platform)
### Background / Motivation
for local development environments there are some images that are specifically needed (i.e developing on M1's vs intels).
providing access to this would allow templated garden modules to swap out container ids based on  arch during development

### What should the user be able to do?
ideally it should beable to be used the same way as `local.platform` or any other provided local variable simple example

### Why do they want to do this? What problem does it solve?
currently without this feature we're having developers just manage this external to garden with bash scripts and if statements to setup operators with the correct images before running our garden workflow

### Suggested Implementation(s)
similar to `local.platform`

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
@KoduIsGreat thanks for reporting this! The feature will be available in the next release.
