### ISSUE TITLE
cli: add support for runtime config files and env vars

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#309]
We should support per user and per project CLI runtime configuration files.

User settings could be at `$Home/.gardenrc` and project settings at `/path/to/project/.gardenrc`. Among other things, the config files could contain settings for CLI arguments and options. [Here's](https://yarnpkg.com/lang/en/docs/yarnrc/#toc-cli-arguments) how yarn does it. Other settings could also be added there as applicable.

This would also be a good chance to improve how we handle env variables, it's pretty ad hoc at the moment.

I'm guessing the order of precedence should be:
```
project settings < user settings  < env vars < cli args 
```
where `cli args` has the highest precedence.

**Comment by eysi09** [comment]
@edvald, was the conclusion to implement this in Go?

**Comment by edvald** [comment]
That would make sense, since it'll affect behavior at that level.

**Comment by eysi09** [comment]
See also #668.

**Comment by eysi09** [comment]
Closing in favour of #1523.
