### ISSUE TITLE
[FEATURE]: add ability to specify dependent services, which should be deployed on build stage for container/module

### ISSUE THREAD

**Issue by modsen-hedgehog** [garden-io/garden#3112]
### Background / Motivation

I'm working on mono-repository project and I have a gateway service, which needs dependent services to be deployed to generate some graphql schemas on build stage. This gateway service just takes so called graphql introspection and combines them. But as I understand right now there is no solution to configure such behavior.

### What should the user be able to do?

User should be able to configure dependent services, which should be already deployed on build stage for some module/container

### Why do they want to do this? What problem does it solve?

It helps to make request for some configurations

### Suggested Implementation(s)

It could work the same as it works for specifying dependent services, which should be BUILT on build stage for some module/container

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
@modsen-hedgehog thanks for reporting this.

The problem should be solvable in Garden `0.13`, but in `0.12.x` it's quite tricky. Now we're actively working on `0.13`, the plan is to get it finished in mid-September.

**Comment by Orzelius** [comment]
This is now possible in 0.13, thanks for the issue and sorry for the wait!!1
