### ISSUE TITLE
[FEATURE]: Fetch dependencies of a dependency

### ISSUE THREAD

**Issue by idoshamun** [garden-io/garden#3124]
### Background / Motivation

I was working on my first garden project, which includes a few services, databases, and an application.
The application relies on two services, and the services rely on different dependencies such as redis, postgres, etc.

### What should the user be able to do?

I think as a garden user, I should be able to define the dependencies of my module. When one of my other garden references this module, its dependencies should automatically be fetched. Right now, I have to hardcode the dependencies of my dependencies in the project file.

### Why do they want to do this? What problem does it solve?

It helps us abstract away implementation details of other services.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
Thanks for reporting this @idoshamun! We'll take a look after the `0.13` release.

**Comment by vvagaytsev** [comment]
This should be fixed in Garden 0.13. Please let us know if it's still an issue.
