### ISSUE TITLE
[FEATURE]: Modules contributing values to a project level variable

### ISSUE THREAD

**Issue by idoshamun** [garden-io/garden#3125]
### Background / Motivation

My dev setup contains a single postgres instance that serves many services. 
This postgres instance supports initializing multiple databases via a comma-separated environment variable.

### What should the user be able to do?

As a garden user, I'd like to define on a module level a variable with a single database name and then aggregate this variable from all my other modules into a single comma-separated string that I can provide to my postgres instance.

### Why do they want to do this? What problem does it solve?

It abstracts away implementation details of remote modules that I shouldn't care about

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by Orzelius** [comment]
Hello, sorry for getting back to this so late but what you describe can be done via terraform provider [`initRoot`](https://github.com/garden-io/garden/blob/main/docs/reference/providers/terraform.md#providersinitroot) field and the provider level outputs can be later used in modules/actions.
