### ISSUE TITLE
Custom exec commands are executed from current directory instead of project root

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3151]
### Current Behavior

As per the title: Custom Commands that have type `exec` are executed in the directory that the command is called from. 

### Expected behavior

The command is always executed from project root _or_ the directory where it's defined. 

I think we only support placing custom commands in the project root anyway so it's kind of a moot point.

But if we imagine we'll support placing custom commands in nested dirs, e.g. next to the module that the commands are relevant for, they should be executed from that dir (imo).

### Reproducible example

1. Create a Garden project with two dirs: `scripts` and `foo`.
2. Add a file called `./scripts/echo-ok.sh` that contains `echo ok`.
3. Add the following config to the project root:

```
kind: Command
name: echo
description:
  short: Echo.
exec:
  command: ["/bin/sh", "-c", "./scripts/echo-ok.sh"]
```

4. cd into `foo` and run `garden echo` and observe it fail because it can't find the file. 

### Workaround

Always shell into the root before executing a custom command.

### Suggested solution(s)

Set the `cwd` in the exec function to the correct path. 

### Your environment

Lastest master as of writing.

**Comment by Orzelius** [comment]
@eysi09 Thank you for the detailed issue and a nice repro, could you check the pr to fix it #3171 and give feedback on if requiring a garden project for custom commands makes sense
