### ISSUE TITLE
[FEATURE]: Use native tools on ARM64 mac

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3166]
## Feature Request

Garden should download and use ARM64 native tools on M1 mac.

### Background / Motivation

I am hitting a terraform problem in conjunction with rosetta, where terraform apply fails randomly on M1 macs. [This can be fixed by installing ARM64 native terraform](https://github.com/hashicorp/terraform-provider-aws/issues/22582#issuecomment-1015302978). But with garden, I do not have control to do that.

Because of that I get errors like this, making terraform completely unusable:
```
Error: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.


Command "/Users/steffen/.garden/tools/terraform-0-14-7/5bca2f75c0636f7a/terraform apply -var-file /Users/steffen/work/github/garden-platform/cloud/customers/terraform/garden.tfvars.json" failed with code 1:
```

There might be similar rosetta incompatibilities with other tools.

### What should the user be able to do?

When on M1 mac, garden should simply use the appropriate ARM64 tools where available.

### Why do they want to do this? What problem does it solve?

For example, terraform does not work with rosetta, but it works fine natively. There might be other tools with issues like that.

### Suggested Implementation(s)

I am not sure. This might be related to https://github.com/garden-io/garden/issues/2333

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

... it's very, very painful. I wrote a bash script that runs garden in a docker container to work around this issue, and it's very slow, and it was not easy to make it work in the first place.

**Comment by vvagaytsev** [comment]
Thanks for raising this @stefreak! Looks related to https://github.com/garden-io/garden/issues/2333 We can reconsider both issues after the Garden `0.13` release. I also use an Apple machine with an M1 chip :)
