### ISSUE TITLE
BUG: Disabled module builds on code change in dev-mode

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3203]
### Current Behavior
When I run dev mode, an exec module will suddenly try to build (But it's disabled in the local-kubernetes env in my project)

### Expected behavior
I expect disabled modules not to do anything when I change code in dev mode

### Reproducible example
It's not a minimal example, but it is reproducable.
Commit to check out to reproduce this: https://github.com/garden-io-testing/hono-garden/commit/c762fdfa6484e0989c0df350fd64f41bc37d14fc

1. `git clone https://github.com/garden-io-testing/hono-garden.git`
1. `cd hono-garden`
1. `git checkout c762fdfa6484e0989c0df350fd64f41bc37d14fc`
1. run `garden dev`
1. change the file hello/src/index.ts (e.g. add a comma in the hello world response)

dev output:

```
% garden dev
Dev ⌨️

━━━━━━━━━━━━━━━━━━━━━━━━
🌍  Running in namespace default.local-kubernetes
━━━━━━━━━━━━━━━━━━━━━━━━

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ graph                     → Resolving 4 modules... → Done
deno-hello-k8s            → Deploying in dev mode
ℹ deno-hello-k8s            → Syncing . to / in Deployment/deno-hello-k8s (one-way)
✔ deno-hello-k8s            → Connected to sync target / in Deployment/deno-hello-k8s
✔ hello                     → Building version v-a174a3700b... → Done (took 0 sec)
✔ deno-k8s                  → unit tests → Already passed
✔ deno-k8s                  → Getting build status for v-97c03cf348... → Already built
✔ deno-hello-k8s            → Deploying version v-3ca92f1bd9... → Already deployed
   → Ingress: http://hono-garden.local.app.garden
   → Forward: http://localhost:8000 → deno-hello-k8s:8000 (http)

🌻  Garden dashboard running at http://localhost:9777?key=XXX

🕑  Waiting for code changes...

✔ graph                     → Resolving 4 modules... → Done
✔ hello                     → Building version v-b7ca4b234e... → Done (took 0 sec)
✔ deno-k8s                  → unit tests → Already passed
✔ deno                      → Building version v-4f85b255ad... → Done (took 0.2 sec)
✖ hello-cloudflare          → Building version v-b812de89b0...
✔ deno                      → Running unit tests → Success (took 0.2 sec)

Failed building hello-cloudflare. Here is the output:
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Command "wrangler publish --dry-run --outdir=build" failed with code 1:
...
```

### Workaround
Unknown to me

### Suggested solution(s)
There seem to be some code paths, where the `disabled` flag is not checked. This should be fixed.

### Additional context
Some modules only work in a certain environment, so they are disabled when not needed.

### Your environment

* **OS:** M1 mac
* **How I'm running Kubernetes:** Docker desktop

```
% gdev version # latest master
0.12.44
% garden version
0.12.42
```

**Comment by vvagaytsev** [comment]
Thanks for reporting this @stefreak! We'll take a look soon.

**Comment by vvagaytsev** [comment]
Unfortunately, I have no access to https://github.com/garden-io-testing/hono-garden/commit/c762fdfa6484e0989c0df350fd64f41bc37d14fc. Can you grant me permission, please?

**Comment by stefreak** [comment]
on it :)

**Comment by vvagaytsev** [comment]
This might be related to the old FileSystem watcher. We need to reproduce it with 0.13.
