### ISSUE TITLE
Connection lost when running garden exec

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#3208]
### Current Behavior

When running `garden exec <module-name> --interactive /bin/bash` the connection often gets lost after a little while, resulting in the freezing of the terminal (in my case `zsh`).

### Expected behavior

The same behaviour as in local-mode (restoring in case of lost connection).

### Workaround

Currently I have to kill the terminal and restart the command.

### Additional context

Might be related to #3149

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
Closing this as stale.
