### ISSUE TITLE
BUG: no error with two garden projects in the same directory

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3210]
### Current Behavior
If you have two`kind: project` definitions in different files there is no error message

### Expected behavior
I expect an error, otherwise it can be very confusing if user edits the "wrong" file (that garden does not use)

### Reproducible example
```
mkdir repro
cd repro
git init
garden create project
mv garden.project.yml garden.yml
garden create project
garden deploy
```

### Workaround
Unknown

### Suggested solution(s)
Garden should validate project definitions. There should be only one. Otherwise the user needs to be warned

### Additional context
Just had this issue and it was very confusing, until I actually found out there was accidentally two project definitions in the same dir.

### Your environment

* **OS:** macos
* **How I'm running Kubernetes:** irrelevant

`garden version`
0.12.42

**Comment by vvagaytsev** [comment]
Thanks for reporting this @stefreak! We'll take a look soon.
