### ISSUE TITLE
[FEATURE]:  --skip-dependencies should work on sync mode

### ISSUE THREAD

**Issue by mowings** [garden-io/garden#3234]
### Background / Motivation
We have a lot of services to run in a single project, and dependency checking can be slow, but can also sometimes redeploy things that are unchanged (some of this could be our project configuration).

While `--skip-dependencies` works fine with a normal service deploy, it does not work when a service is being deployed with the `--dev` flag:

```
# Given a service named "foo"
garden deploy foo --skip-dependencies. # Works
garden deploy --dev foo --skip-dependencies # Does not work
```

The latter case fails with:

```
No service names were provided as CLI arguments, but the --skip-dependencies option was used. Please provide a list of service names when using the --skip-dependencies option.
```

### What should the user be able to do?
`--skip-dependencies` should work  with a service deployed via the `--dev` flag. Ideally, it would also work for services deployed with the `--local` flag.

### Suggested Implementation(s)
At least in the case of the `--dev` flag, this looks like a simple validation error. The two use-cases above (regular deploy, versus `--dev` deploy should be treated the same way, as a service has been specified in both cases.

### How important is this feature for you/your team?
:cactus: Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
Huge thanks for reporting this, @mowings! We'll take a loon soon!
