### ISSUE TITLE
[FEATURE]:  deploymentStrategy. should be available in container module

### ISSUE THREAD

**Issue by mowings** [garden-io/garden#3237]
### Background / Motivation

We have a one single-replica container that we deploy via the garden container module that has attached PVCs.  We would like this  deployed with the `recreate` strategy to minimize reattachment delays when we redeploy it. While most other deployments in our project use helm, we still have a few that we would like to simply use rolling update to minimize downtime.  

Garden allows deploymentStrategy to be specified at the project level, but not at the module level, where it arguably makes more sense. Thus ALL of our garden container modules end up having to use the `recreate` strategy

### What should the user be able to do?

Specify a deployment strategy under the container/service section. For example:

```
services:
  - name: postgres
    replicas: 1
    deploymentStrategy: recreate
```

### Why do they want to do this? What problem does it solve?

Keeps us from using recreate as the default deployment strategy.

### Suggested Implementation(s)

See above

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

We can work around this by using helm or k8s manifests for deployment,  but we *do* like using container modules for simple deploys.

**Comment by vvagaytsev** [comment]
Thanks for reporting this, @mowings! We'll take a look soon.
