### ISSUE TITLE
BUG: docs generator outputs docs including the escape character for `\$` when using backtick-strings

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3245]
## Bug

Example: 
https://docs.garden.io/reference/module-types/configmap#disabled

If a user copies the example `disabled: \${environment.name == "prod"}` from the docs with the backslash, it won't work, because the dollar is escaped.

This is a bug in our docs generator: if you escape a `$` in a backtick-string (`` `\${something}` ``) it shouldn't end up escaped in the resulting docs.

Search for `\$` in all `.md` files in the garden repository. There are ca. 116 instances of this problem in our docs. 

### Reproducible example

A config like this yields docs with a bug

````
cache: joi
          .array()
          .description(
            dedent`
            Lorem Ipsum
            \`\`\`
            cache:
              tag: _buildcache-\${camelCase(git.branch)}
            \`\`\`
          ),
````

### Current Behavior

This yields the docs like that (with escaped `\$`)

````
Lorem Ipsum
```
cache:
  tag: _buildcache-\${camelCase(git.branch)}
```
````

### Expected behavior

It should yield docs like this (without escaping `$`):
````
Lorem Ipsum
```
cache:
  tag: _buildcache-${camelCase(git.branch)}
```
````

### Workaround

- [extracting the env-var-like string](https://github.com/garden-io/garden/blob/master/plugins/jib/index.ts#L39) `${...}` as a constant and [using it](https://github.com/garden-io/garden/blob/master/plugins/jib/index.ts#L99) in the target template string. (thanks @vvagaytsev)

### Suggested solution(s)

I tried to understand the docs generator and fix this bug myself, but I got stuck. need help to find a solution.

### Your environment

* **OS:** macos

**Comment by Orzelius** [comment]
I wonder how no one has pointed this out before. Either way, good catch!

**Comment by vvagaytsev** [comment]
Thanks, @stefreak! Actually, that's not the only place. In https://docs.garden.io/reference/module-types/configmap#varfile you can see `varfile: "my-module.\$\{environment.name\}.env`.

I faced the same issue in #3184 and solved it by [extracting the env-var-like string](https://github.com/garden-io/garden/blob/master/plugins/jib/index.ts#L39) `"${...}"` as a constant and [using it](https://github.com/garden-io/garden/blob/master/plugins/jib/index.ts#L99) in the target template string.

There are a few other places where we have the same issue.

**Comment by stefreak** [comment]
> Search for `\$` in all `.md` files in the garden repository. There are ca. 116 instances of this problem in our docs.

@vvagaytsev yes exactly, this was only an example. Good point with the work around, will add it to the main bug ticket 👍
