### ISSUE TITLE
Ingress does not work with GCE ingress controller on GKE

### ISSUE THREAD

**Issue by MarkMurphy** [garden-io/garden#3249]
Error during sync: error running backend syncing routine: googleapi: Error 400: Invalid value for field 'resource.timeoutSec': '5'. TimeoutSec should be less than checkIntervalSec., invalid

`timeoutSeconds` cannot be greater than `periodSeconds`

See https://cloud.google.com/load-balancing/docs/health-checks and https://github.com/kubernetes/ingress-gce/blob/master/docs/faq/gce.md#can-i-configure-gce-health-checks-through-the-ingress

Unfortunately values for checking interval (periodSeconds) and check timeout (timeoutSeconds) are hardcoded here https://github.com/garden-io/garden/blob/master/core/src/plugins/kubernetes/container/deployment.ts#L730-L739 and there is no way to fix this without forking.

Can we make these values configurable?

**Comment by vvagaytsev** [comment]
Thanks for reporting this @MarkMurphy! We'll take a look soon.

**Comment by vvagaytsev** [comment]
This might be related to #3072.

**Comment by 10ko** [comment]
We are not going to work on this, please use the kubernetes action type if you encounter errors.
