### ISSUE TITLE
How do environment variables work?

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#325]
Here are two snippets from the `hello-world` example, in the `hello-container` module:

– [garden.yml](https://github.com/garden-io/garden/blob/master/examples/hello-world/services/hello-container/garden.yml#L21):
```yaml
FUNCTION_ENDPOINT: ${services.hello-function.outputs.endpoint}
```

– [app.js](https://github.com/garden-io/garden/blob/master/examples/hello-world/services/hello-container/app.js#L7):
```js
const functionEndpoint = process.env.GARDEN_SERVICES_HELLO_FUNCTION_ENDPOINT
```

I understand that they're connected, you're declaring the variable in one place and using it in the other. But how does the whole syntax work there?

**Comment by edvald** [comment]
Oops, forgot about this one. Actually, the example could be updated thusly: `const functionEndpoint = process.env.FUNCTION_ENDPOINT`. The framework injects some env vars automatically (all the ones prefixed with `GARDEN_` but it's better practice to define them explicitly instead, as in the `FUNCTION_ENDPOINT` variable. Those are then exposed directly when running the service.

**Comment by eysi09** [comment]
We've updated the `hello-world` example to reflect this (#390). We should also add documentation for the plugins where we document things like service outputs. But that belongs in a separate issue so I'm closing this one for now.
