### ISSUE TITLE
`garden cloud` subcommands show the higher-level help text

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#3256]
### Current Behavior

Running the command `garden cloud` gives you the list of available subcommands, `garden cloud groups`, `garden cloud secrets`, and `garden cloud users`. Running any of those suggested subcommands gives you the same help message of the `garden cloud` command, instead of showing the relevant help for the specific subcommand(s) and their available sub-subcommands / options.

![Screenshot 2022-09-26 at 15 16 07](https://user-images.githubusercontent.com/2943750/192273944-e7234239-7e6a-4ee0-8fcd-cc654a8b42b2.png)

### Expected behavior

The CLI should show the specific help for the subcommand issued, listing the available nested subcommands / options for the subcommand in question.

### Your environment

- macOS Monterey 12.6
- `garden version` 0.12.44

**Comment by vvagaytsev** [comment]
Thanks for reporting this @Walther! It should be an easy fix.
