### ISSUE TITLE
[BUG] update-remote sources command is missing --parallel flag

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3269]
### Current Behavior

In v0.12.45, the `--parallel` flag was added to `garden update-remote all` and `garden update-remote modules`.
However it is missing from `garden update-remote sources`.
Note that `garden update-remote all` still updates all declared sources in parallel.

### Expected behavior

`garden update-remote sources` should have the `--parallel` flag as well.

### Workaround

If you need to update remote sources in paralllel, use `garden update-remote all` for now.

`garden version`
0.12.45

**Comment by vvagaytsev** [comment]
Thanks for reporting this @hnicke! That should be an easy fix, I'll take a look soon.
