### ISSUE TITLE
[BUG] multiple local ports for localMode breaks backwards-compatibility

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3271]
### Current Behavior
Since v0.12.45, [multiple port forwards](https://github.com/garden-io/garden/commit/a98af5363) are allowed for `localMode`.
The new configuration syntax is:
```yaml
localMode:
  ports:
    - local:
      remote: 
```
The old syntax (<=v0.12.44) was:
```yaml
localMode:
  localPort:
```

The problem is that v0.12.45 does not support the old syntax, and neither does v0.12.44 support the new syntax.
This forces us to atomically upgrade our stack to v0.12.45.
This is painful since our stack lives in multiple repositories (we use remote sources).

This breaking change was not documented in the [release announcement](https://github.com/garden-io/garden/releases/tag/0.12.45).
However, the [responsible commit](https://github.com/garden-io/garden/commit/a98af5363) clearly states it is a breaking change.

### Expected behavior
Breaking changes are especially frustrating in a tool like garden which execution can span multiple repositories (when using remote sources).
I wish there would have been an upgrade path: Support both syntaxes in v0.12.45 and remove the old syntax in - let's say - v0.12.46.

I just saw that the `localMode` feature is still considered experimental (`garden deploy --help`) and thus it might have been my fault to use it in our stack in the first place.
However, neither the [localMode guide](https://docs.garden.io/guides/running-service-in-local-mode) nor the module reference contains a similar hint which suggests that this feature is "stable".
However I'd at least expect that the release changelog contains a word or two about this breaking change.

**Comment by vvagaytsev** [comment]
Hi @hnicke! Thanks for reporting this! Sorry, that's my fault, I forgot to mention it in the release notes. Now the [release notes](https://github.com/garden-io/garden/releases/tag/0.12.45) are up-to-date.

[improvement(local-mode): allow multiple port-forwards](https://github.com/garden-io/garden/commit/a98af5363) caused incompatibility. But the local mode is still an **experimental** feature. It means that some incompatible changes could be done until the first non-experimental release.

Sorry for the inconvenience.
