### ISSUE TITLE
failed to solve: error writing manifest blob: failed commit on Garden v0.12.45

### ISSUE THREAD

**Issue by ajtran** [garden-io/garden#3279]
### Current Behavior

When running `garden deploy --env=dev`, the deploy fails trying to commit:
```
#20 exporting cache
#20 preparing build cache for export done
#20 writing layer sha256:109c04bbea473dcd39bfc58fe8612c1db408f94e9aaf614e32f703efa258ee42 0.1s done
#20 writing layer sha256:4d990e80d602f070b3258e9062eeda704e6cba7d1b38718a5e9ece2e82b4ed67
#20 writing layer sha256:4d990e80d602f070b3258e9062eeda704e6cba7d1b38718a5e9ece2e82b4ed67 0.1s done
#20 writing layer sha256:530afca65e2ea04227630ae746e0c85b2bd1a179379cbf2b6501b49c4cab2ccc
#20 writing layer sha256:530afca65e2ea04227630ae746e0c85b2bd1a179379cbf2b6501b49c4cab2ccc 0.1s done
#20 writing layer sha256:5b4b56e6b99464c54d3f129e00bd20b617c458db956feb2970245abc431fe85f
#20 writing layer sha256:5b4b56e6b99464c54d3f129e00bd20b617c458db956feb2970245abc431fe85f 0.1s done
#20 writing layer sha256:5cd4df23d1df20205bb8b136bfad8be74ae68a81ba829994bfa6735d23675441 0.1s done
#20 writing layer sha256:7685f6245a25ce74c09455867bb2d273d515a64df78a633837809dcca004c85b
#20 writing layer sha256:7685f6245a25ce74c09455867bb2d273d515a64df78a633837809dcca004c85b 0.1s done
#20 writing layer sha256:8162171ecb65551f90de8eb79be7a98850c0b4fa7af6e31150ad932d3ea3fb32
#20 writing layer sha256:8162171ecb65551f90de8eb79be7a98850c0b4fa7af6e31150ad932d3ea3fb32 0.1s done
#20 writing layer sha256:c49fb0f1c5aafb11b2258d5015e910ea395233e3f7347ec14e182db93fdfd493
#20 writing layer sha256:c49fb0f1c5aafb11b2258d5015e910ea395233e3f7347ec14e182db93fdfd493 0.1s done
#20 writing layer sha256:d450d4da0343091dd049727bcf8ccaae8c22b9b11cbb26823c403343ca9faa1c
#20 writing layer sha256:d450d4da0343091dd049727bcf8ccaae8c22b9b11cbb26823c403343ca9faa1c 0.1s done
#20 writing layer sha256:ff63b82a42d3d44071011eb2a1262a77c15520b940511c05ebd7a7c3019fdff6
#20 writing layer sha256:ff63b82a42d3d44071011eb2a1262a77c15520b940511c05ebd7a7c3019fdff6 0.1s done
#20 writing config sha256:0f835856accabfaef0764d02e067f1164f40e750aa14308d780424bcd74f24d6
#20 writing config sha256:0f835856accabfaef0764d02e067f1164f40e750aa14308d780424bcd74f24d6 0.9s done
#20 writing manifest sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c
#20 writing manifest sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c 0.7s done
#20 ERROR: error writing manifest blob: failed commit on ref "sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c": unexpected status: 404
 Not Found
------
 > importing cache manifest from registry.com/some-repository/conversations:_buildcache:
------
------
 > exporting cache:
------
error: failed to solve: error writing manifest blob: failed commit on ref "sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c":
unexpected status: 404 Not Found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy action(s) failed!
```

It seems the default behavior in v0.12.45, sets
```
clusterBuildkit:
  cache:
    - type: registry
      mode: max
```
however, in our version of harbor, this isn't yet supported as outlined in this https://github.com/goharbor/harbor/issues/14774

### Expected behavior

I expect the deploy to go through without any errors.

### Reproducible example

garden version: v0.12.45
harbor version: v2.5.3-797c3536
kubernetes(eks) version: v1.21.14-eks-18ef993

command: `garden deploy --env=dev`

### Workaround

Downgrade to v0.12.44.
or run `garden deploy --env=dev` twice.

or on v0.12.45, specify:
```
clusterBuildkit:
  cache:
    - type: registry
      mode: inline
```

### Suggested solution(s)

we could default the mode to `inline`, rather than `max`.

### Additional context

tried clearing local garden directory, cleared running garden pods, reproduced failing environment on engineers machine on v0.12.45, and working environment on v0.12.44.

The only resolution found (without rerunning commands) was to downgrade garden from v0.12.45 to v0.12.44

### Your environment

macOS: Monterey v12.5.1
harbor version: v2.5.3-797c3536
kubernetes(eks) version: v1.21.14-eks-18ef993
garden version: v0.12.45

edit: add more context to what went wrong, linked an issue, and suggested a possible solution.

**Comment by justinharringa** [comment]
Looks like this feature changed the default behavior 😞 https://github.com/garden-io/garden/pull/3239

**Comment by vvagaytsev** [comment]
Thanks for reporting this @ajtran! We'll take a look soon.

**Comment by vvagaytsev** [comment]
@justinharringa thanks for finding the breaking change!

**Comment by vvagaytsev** [comment]
@stefreak can you take a look?

**Comment by stefreak** [comment]
@vvagaytsev yes, I will. Sorry for breaking your deploys @justinharringa @ajtran

Indeed, changing the default back to inline would solve this problem. Probably we'll do that.

I assumed that all self-hosted docker registries support `mode=max` as the reference registry implementation does support it. But I didn't have Harbor on the radar. That means we'd need to change the default back to inline, or implement a feature detection mechanism 🤔

**Comment by vvagaytsev** [comment]
@stefreak I think changing the default back to `inline` should be ok for now. This will ensure compatibility. A feature detection mechanism can be implemented later as a separate feature/improvement.

**Comment by justinharringa** [comment]
Awesome! Thanks @stefreak !
