### ISSUE TITLE
Support .gardenignore in subdirectories

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#328]
`.gardenignore` files should have broadly the same semantics as `.gitignore` files. Currently we only support one file in the project root directory. We should scan for `.gardenignore` files in subdirectories and include those when filtering files to include in builds etc.

**Comment by edvald** [comment]
Actually, we may also need to do this for our internal handling of `.gitignore` files, might wanna look into that along the way.

**Comment by drubin** [comment]
Does Garden already honour .dockerignore files?

**Comment by edvald** [comment]
We use docker for building containers, so yes, by extension.

**Comment by drubin** [comment]
@edvald I meant in deciding when to trigger a rebuild.

**Comment by edvald** [comment]
I see - no we don't refer to the .dockerignore file for that. I'm not sure how we'd implement that at the framework level, since the framework doesn't know what a `.dockerignore` file is.
