### ISSUE TITLE
command: [workflow-a] terminates flow while command: [run, workflow, workflow-a] doesn't

### ISSUE THREAD

**Issue by jrnxf** [garden-io/garden#3288]
### Current Behavior
My workflows look like this

reset workflow (outer-most):

```
  ...
  - description: Run refresh workflow
    command: [run, workflow, refresh]
  - description: Run the data orchestrator task
    command: [run, task, data-orchestrator]
```

refresh workflow:

```
  ...
  - description: Run codegen
    command: [run, workflow, codegen]
```

codegen workflow:

```
  - description: Generate Prisma Client and NestJS types locally
    script: pnpm run --dir backend generate
  - description: Generate GraphQL schema
    script: pnpm run --dir backend generate:schema
  - description: Mirror schema between frontend and backend
    script: cp backend/schema.graphql frontend/schema.graphql && echo "Done! ✅" || true # || true prevents the workflow from failing if the backend has never run
  - description: Run GraphQL Code Generator for frontend
    script: pnpm run --dir frontend graphql-codegen
```

The problem is that if I use `command: [codegen]` I never make it back to my outer workflow. Garden simply hands (even though the codegen was successful, and then after 20 seconds or so finishes having never run my final task. I am forced to use `command: [run, workflow, codegen]`

### Expected behavior

Either should work

### Workaround

explained above 

### Your environment

* **OS:** MacOS 12.6 M1 Pro 2021 
* **How I'm running Kubernetes:** Docker Desktop  

`garden version` 0.12.44

**Comment by vvagaytsev** [comment]
Thanks for raising this @thatvegandev! We'll take a look.

**Comment by vvagaytsev** [comment]
An update on this. Sorry for coming back so late.

We'll probably re-examine the workflows within the next year. We do not recommend running workflows inside other workflows. Thanks for trying that scenario :)

We can recommend using Garden custom commands as a workaround. Closing as not planned.
