### ISSUE TITLE
[FEATURE]: kustomize with helm charts

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3289]
### Background / Motivation
I'm integrating a 3rd party helm chart into our garden stack.
Its resulting manifests however have a minor flaw and don't suite our needs 100%.
In general I would have three options to address this:

* supply patch upstream and hope they will incorporate it soon & release a new chart version
* fork the chart
* use kustomize

Supplying a patch upstream takes a lot of time and is not guaranteed to be accepted: Some charts stopped accepting PRs to add 'yet another flag'.

Forking a chart has a high maintenance cost and should be considered as last resort only.

It seems to me that at this point in time, the preferred way of solving this is using kustomize:
`render helm chart -> run through kustomize -> apply to cluster`

### What should the user be able to do?
I'd like to use a kustomize overlay for the helm chart module / action.

### Why do they want to do this? What problem does it solve?
If I could customize helm  charts with garden, I would not neither have to beg upstream to include yet another flag nor take the burden of maintaining a fork if the chart.

### Suggested Implementation(s)
I haven't used the kustomize integration of the kubernetes module but I think it could be similar.

### How important is this feature for you/your team?
:cactus: Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
Thanks for reporting this @hnicke! This looks like an advanced use case. Now we're busy with a more urgent project https://github.com/garden-io/garden/issues/3278, so we'll definitely take a look a bit later.

**Comment by shumailxyz** [comment]
More info in #3459

**Comment by worldofgeese** [comment]
The most important takeaway from #3459 is 
> In Helm version [3.9.0](https://github.com/helm/helm/releases/tag/v3.9.0), Helm adds “a --post-renderer-args flag to support arguments being passed to the post renderer”.

More information on Post Rendering available at [Helm's official docs](https://helm.sh/docs/topics/advanced/#post-rendering). Post rendering implements native manipulation of Helm charts.

**Comment by 10ko** [comment]
We don't plan to support this, sorry.
