### ISSUE TITLE
[FEATURE]: Allow envFrom usage in modules/task

### ISSUE THREAD

**Issue by Dunemask** [garden-io/garden#3292]
## Feature Request
Add `envFrom` as a drop in addition/replacement for the `env` specifications in modules/tasks.

### Background / Motivation
Unfortunately i'm not super active in development right now so this is more of a backburner kick-starter idea. Potentially this is a very niche use-case, but I figured someone out there might also find it useful. It simply removes unnecessary data redundancy between garden modules and raw kubernetes modules.

### What should the user be able to do?
A user should be able to create a configmap/secret and reference it for use as environment variables in modules/tasks.

### Why do they want to do this? What problem does it solve?
The overall incentive for this particular feature is to allow containers to use environment variables from configmaps to remove unnecessary replication of data when both configmaps and container envars exist. A user could create a single configmap/secret containing environment variables which can be shared between kubernetes and garden modules alike. This removes any

### Suggested Implementation(s)
I'm not familiar enough with Garden's codebase to suggest implimentation on that level, but I do know that a user should be able to add a `envFrom` spec to their modules/tasks and reference a configmap/secret to specify the variables to use.

### How important is this feature for you/your team?
:cactus: Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
Thanks for reporting this @Dunemask! Yes, that looks like a niche use case. Would you be interested in submitting a PR for this feature? We are happy to give you the necessary guidelines.

**Comment by Dunemask** [comment]
Haha 😂, it certainly is pretty niche! Due to work circumstances I can't commit enough time to submit a PR right now. However, once work settles down I'll definitely reopen this and take a crack at this!

Thank you so much for helping developers have consistency between environments. I'm very lucky to have found Garden when I did, it's been such a huge blessing! 🙂

**Comment by vvagaytsev** [comment]
Thank you @Dunemask! Let's keep it open :) Now we're quite busy with a bigger project -- https://github.com/garden-io/garden/issues/3278, and some urgent bugs and feature requests.

Anyway, we'll be happy to support you in implementing this later! :)

**Comment by vvagaytsev** [comment]
Closing this as stale now. Feel free to reopen if you have time to work on this. We'll be happy to support you with your PR :)

**Comment by vvagaytsev** [comment]
We have another issue that can address this feature request, please see #4729.
