### ISSUE TITLE
[FEATURE]: More intelligence around running Garden commands against "dev mode namespaces"

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3298]
### Background / Motivation
Let's say I run `garden dev` in one process and start my services in dev mode. I write some code and then I want to test my changes.

Now, I run `garden test` in a separate process. 

What's going to happen is that Garden will re-build and re-deploy services and may thereby disable dev mode for some of them. After all, Garden is all about guaranteeing that the right version if you code is tested and the dev mode services may be "dirty". 

So in a way, this makes sense, but it can still be annoying and cause confusion when dev mode is all of a sudden no longer working. 

### Suggestion
When running a Garden command that has a "runtime effect", check if another Garden process is already in watch mode for that same namespace. 

If it is, we could make it interactive and give the user the following choices:

* Redeploy services as needed
* Pick a different namespace
* Continue but don't re-deploy any service that is already in dev mode

This is just a suggestion and I'd love to hear more thoughts on the topic. 

Beyond that, we should of course also log changes to the dev mode status in the original process so that users are aware of it being disabled. 

We could also display this in Garden Cloud and allows users to toggle dev mode for a given service via the command palette.

### How important is this feature for you/your team?
:rose: It’s a nice to have, but nice things are nice :slightly_smiling_face:

**Comment by vvagaytsev** [comment]
Closing this. This is no longer applicable to the new dev mode implementation in 0.13.
