### ISSUE TITLE
Validate links in docs

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#330]
Our docs contain a lot of links and these tend to break. Perhaps someone re-names an example project and forgets to change the corresponding links to it. 

We should have some way of automatically testing all the links in docs to ensure they stay valid.

**Comment by eysi09** [comment]
This seems to work: https://github.com/stevenvachon/broken-link-checker

**Comment by ellenkorbes** [comment]
LGTM

**Comment by drubin** [comment]
It would be great if we find a tool that is able to parse markdown to do this type of validation before its actually released. 

It seems that tool only works against published websites?

**Comment by drubin** [comment]
I think something like this could also work (never used it before) https://www.npmjs.com/package/markdown-link-check

**Comment by drubin** [comment]
I think something like this could also work (never used it before) https://www.npmjs.com/package/markdown-link-check

**Comment by drubin** [comment]
Might not be related to links but I did find a markdown validator that validates the nested yaml.

https://github.com/felicianotech/md-proofer from [circleci blog post](https://circleci.com/blog/markdown-proofer/)
