### ISSUE TITLE
When running a test, if the command ends or the pod gets evicted, the logs are not displayed

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#3331]
### Current Behavior
When running tests, if the process running the tests gets interrupted, Garden fails to print the full logs from the pod running the tests.

### Expected behavior
Garden should either stream logs as they appear during test runs or make sure to collect all the logs printed to stdout before the pod gets evicted.

### Workaround
Sometimes it's helpful to increase the resources/limits for the pod running the tests.

### Suggested solution(s)
We should stream logs as opposed to collecting them at the end of the pod lifecycle and printing them with Garden.
If this is what we already do, it's possible this is some strange behavior with the test runners (which might only print output at the very end of the execution of the test suite). We should investigate if this might be the case and offer a guide or tutorial on how to configure the test runner to stream output as it becomes available, on stdout.

### Additional context
This is unfortunately difficult to reproduce and very intermittent. It has been reported by some of our users using Jest.

**Comment by thsig** [comment]
We've already got the machinery in place for incrementally streaming test/task pod logs line-by-line, so we could simply use that (instead of asking the k8s API for all the pod logs at the end of execution, which seems to be problematic in these edge cases).

What do you think, @edvald @eysi09?

**Comment by Orzelius** [comment]
@thsig I think that makes sense, but it will probably be a bit problematic if there's tons of logs

**Comment by thsig** [comment]
Yeah. We'd need to implement some simple logic for only keeping the last N lines of output (and also make sure that the output doesn't grow beyond a certain kilobyte count).

**Comment by vvagaytsev** [comment]
Yes, we can collect the tailing logs in a buffer with the FIFO eviction policy, and print the buffer contents on the error/exit. Th buffer size can be configurable.

**Comment by stefreak** [comment]
For an OOM event, Garden prints the logs of the Pod:

```
[2023-01-16T14:05:56.575Z] Error: Pod container was OOMKilled. Here are the logs until the out-of-memory event occurred:

> frontend@1.0.0 integ /app
> node_modules/mocha/bin/mocha test/integ.js
```

Reproduced this by changing `example/demo-project/tests/integ.js` to include a `while (true)` loop that fills an array with garbage data.

**Comment by stefreak** [comment]
If one deletes the test Pod while the tests are running, garden does not display the logs.

Changed the `example/demo-project/tests/integ.js` like this to reproduce:

```
describe('GET /call-backend', async () => {
  let foo = 0
  while (true) {
    await new Promise(resolve => setTimeout(resolve, 1000))
    foo += 1
    console.log(`Foo ${foo}`)
  }
```

Then I went on and deleted the Pod of the running test.

Resulting error message:

```
✖ frontend                  → Running integ tests → Failed! (took 71.8 sec)

Failed running integ tests in module frontend. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to start command execution. Failed to initiate a runner pod with error:
Got error from Kubernetes API (readNamespacedPodStatus) - pods "test-frontend-integ-192868" not found

Please check the cluster health and network connectivity.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 test action(s) failed!

See .garden/error.log for detailed error message
```

Unfortunately all the stack trace information gets lost in the way garden processes this error so it is hard to find the code that needs to be changed.

**Comment by stefreak** [comment]
[5b8f433](https://github.com/garden-io/garden/commit/5b8f43390118207d38053e4d99aa2407a0d571fb) is a prototype of a way to get more information. With that commit it looks like this now:

```
✖ frontend                  → Running integ tests → Failed! (took 10.1 sec)

Failed running integ tests in module frontend. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error: Pod could not be found. It might have been evicted or deleted.
    at PodRunner.awaitRunningPod (/Users/steffen/work/github/garden/core/src/plugins/kubernetes/run.ts:870:19)
    at PodRunner.runAndWait (/Users/steffen/work/github/garden/core/src/plugins/kubernetes/run.ts:825:24)
    at runWithoutArtifacts (/Users/steffen/work/github/garden/core/src/plugins/kubernetes/run.ts:406:17)
    at AsyncFunction.testContainerModule (/Users/steffen/work/github/garden/core/src/plugins/kubernetes/container/test.ts:40:18)
    at Object.assign.actionType.actionType (/Users/steffen/work/github/garden/core/src/actions.ts:1303:24)
    at ActionRouter.testModule (/Users/steffen/work/github/garden/core/src/actions.ts:476:22)
    at wrapped.process (/Users/steffen/work/github/garden/core/src/tasks/test.ts:179:16)
    at TaskNode.process (/Users/steffen/work/github/garden/core/src/task-graph.ts:801:20)
    at wrapped.processNode (/Users/steffen/work/github/garden/core/src/task-graph.ts:436:18)

Logs: [Could not retrieve previous logs for deleted pod test-frontend-integ-ebd680: Got error from Kubernetes API (readNamespacedPodLog) - pods "test-frontend-integ-ebd680" not found]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 test action(s) failed!
```

Unfortunately the logs are not available anymore, after the Pod has been deleted. So we should stream the logs, as @10ko suggested initially.

**Comment by stefreak** [comment]
The `runAndWait` function in `core/src/plugins/kubernetes/run.ts` already sets up a `logsFollower` – maybe we just need to find a way to extract the logs from there, instead of fetching the logs from Kubernetes when there was a 404 error.

**Comment by stefreak** [comment]
I think what a user actually would like to see in this case is not the logs of the interrupted test, but a clear and actionable error message like this:

```
Failed running integ tests in module frontend. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find Pod test-frontend-integ-a197a5 – it might have been deleted or evicted.

Please read this FAQ for hints how to prevent Pods from being evicted mid-run: garden.io/xyz

Latest Pod events:

LAST SEEN   TYPE     REASON      OBJECT                           MESSAGE
10m         Normal   Scheduled   pod/test-frontend-integ-559e1a   Successfully assigned demo-project-default/test-frontend-integ-559e1a to docker-desktop
10m         Normal   Pulled      pod/test-frontend-integ-559e1a   Container image "frontend:v-fa43cc8321" already present on machine
10m         Normal   Created     pod/test-frontend-integ-559e1a   Created container main
10m         Normal   Started     pod/test-frontend-integ-559e1a   Started container main
10m         Normal   Killing     pod/test-frontend-integ-559e1a   Stopping container main
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by eysi09** [comment]
Big plus one on hints! 

The idea was always to implement it with this https://github.com/garden-io/garden/issues/3254, after we release v0.13. 

I suppose we could start creating a proper "hint database" already and just link to it "manually" for now. 

With #3254 we can make it a lot more consistent.

**Comment by stefreak** [comment]
In the proposed implementation (PR #3537) we are displaying Pod events as part of the error message, and we stream the log events to the CLI to make them visible when using verbose log level (`-l3`).
