### ISSUE TITLE
Problems with syncing code before building

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#3332]
### Current Behavior
Some of our users are encountering issues when running `garden dev` where the initial syncing of the code gets stuck and the deployment fails. Note: this happens before even starting the build.

### Expected behavior
The code gets synced and built successfully. If any issue arises, Garden should terminate with an exit code.

### Reproducible example
This is unfortunately very difficult to reproduce but we'll try to create a repo.

### Workaround
Kill the Garden process and restart it.

### Suggested solution(s)
This needs further investigation, but I had a chat with Orzelius and we thought that this issue could be related to rsync issues when uploading the code in the build container.
We were wondering if it would be a nice idea to implement the code syncing using mutagen and expose this syncing mode under a project-level option, defaulting to the current behaviour.

**Comment by vvagaytsev** [comment]
If we could get verbose- or debug-level logs from a dev machine, that would be very helpful.

**Comment by eysi09** [comment]
Just in case this has to do with Mutagen and not rsync: We added more logs around Mutagen syncing in #3560 which may help debug sync issues. 

We also added a `garden plugins kubernetes sync-status` helper command which prints the Mutagen sync status. 

This can also be useful for debugging.

**Comment by vvagaytsev** [comment]
Closing this as stale.
