### ISSUE TITLE
[FEATURE]: Add the ability to create configmaps from files in the configmap module

### ISSUE THREAD

**Issue by marklester** [garden-io/garden#3335]
### Background / Motivation
I have a use case where I need to create many configmaps to mount to a service/task. It would be nice to be able to have a folder of files and have the module either put them into one configmap or make a configmap per.
This is common enough that that kubectl has it built it:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files

### What should the user be able to do?
* Create a configmap module and have an key that says what files/dirs will be turned into configmaps
* if the files are too big die early with a clear error

### Why do they want to do this? What problem does it solve?
* simplifies the process of making configmap from files
* makes it easy to have syntax highlighting to files that will be turned into configmaps

### How important is this feature for you/your team?

:cactus: Not having this feature makes using Garden painful

**Comment by 10ko** [comment]
We'll be deprecating the `ConfigMap` action type, please use the `kubernetes` one.
