### ISSUE TITLE
Namespace and helm release names can become too long

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#334]
We need to rethink how we generate namespace names and release names. The current approach is simple but can fall apart when deploying to nested namespaces (e.g. the openfaas plugin dependencies).

It should remain deterministic, and ideally we should avoid having lookup tables somewhere. So we should consider how we might have a length-limited prefix that's user readable, and a hash suffix that makes it unique across users, projects etc.

We should limit the overall length based on Kubernetes identifier limitations, and the max length of Helm release names (which may be the same).

**Comment by drubin** [comment]
References #262 

I am going to mention this again.

**Comment by edvald** [comment]
Well yes, it does refer to the same problem, sort of. Just a question of what approach to take. We still need to make sure namespaces and release names are unique and deterministic, because adding some sort of a lookup table or using labels will make things much more tricky to manage for the framework.

**Comment by drubin** [comment]
Yes I think we are going to have to bite the bullet and start managing state some how or assume single user cluster (and move multi user functionality into the hosted version which would have to maintain this any way).

**Comment by edvald** [comment]
Just came across this - https://rimusz.net/tillerless-helm/

This would be a viable solution to having to scope release names by namespace, but perhaps hacky in terms of implementation (having to start a tiller subprocess for every garden invocation, or doing some annoying process management).

The alternative is to simply wait for Helm 3, but we have no idea when that'll be released.

**Comment by drubin** [comment]
@edvald Why don't we just use the `module's name` as the release name? we are already putting them in the project's namespace? Feels a bit pointless duplicating that.

Same way we do deployments we set them to the name of the module, I think this maps more closely to expected behaviour (albeit a little bit of duplication, it will some times create `psql-psql` but i think that would happen with or with out garden)

**Comment by drubin** [comment]
https://github.com/helm/helm/issues/2060#issuecomment-306847365 
> We do not plan on fully supporting multi-namespaced releases until Helm 3.0 because doing so will break backwards compatibility and require a major refactoring of much of Helm/Tiller's Kubernetes code.

I really thought helm scoped release names to namespaces. 

But then it brings me back to #262 of us at least generating much friendlier namespaces.
