### ISSUE TITLE
wercker/stern repo no longer exists causing a 404 error on util fetch-tools --all

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3347]
### Current Behavior

Relevant code block:

https://github.com/garden-io/garden/blob/7e86f3eaeec92c0801d9c61dd8e1cd867f1b4d51/core/src/plugins/kubernetes/logs.ts#L522

There is a fork of the project here: https://github.com/stern/stern

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
Thanks for reporting this @ashwiren! We'll take a look.
