### ISSUE TITLE
In-cluster builds on EKS: credentials not found in native keychain

### ISSUE THREAD

**Issue by theoribeiro** [garden-io/garden#3368]
### Current Behavior

In-cluster builds (both Kaniko and cluster-buildkit) are failing on EKS using ECR when trying to build an image running `garden build` with the following error:
```
[2022-11-17T15:24:37.385Z] Error: Unable to query registry for image status: time="2022-11-17T15:24:37Z" level=fatal msg="Error parsing image name \"docker://***********.dkr.ecr.us-east-1.amazonaws.com/****/repo/test:v-36b8e5e856\": getting username and password: 1 error occurred:\n\t* credentials not found in native keychain\n\n"

    at skopeoBuildStatus (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/container/build/common.ts:263:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1303:24
    at ActionRouter.getBuildStatus (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:359:20)
    at wrapped.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/build.ts:132:22)
    at TaskNode.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:801:20)
    at wrapped.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:436:18)

Error Details:

command:
  - skopeo
  - '--command-timeout=30s'
  - inspect
  - '--raw'
  - '--authfile'
  - /.docker/config.json
  - >-
    docker://***********.dkr.ecr.us-east-1.amazonaws.com/****/repo/test:v-36b8e5e856
output: >
  time="2022-11-17T15:24:37Z" level=fatal msg="Error parsing image name
  \"docker://***********.dkr.ecr.us-east-1.amazonaws.com/****/repo/test:v-36b8e5e856\":
  getting username and password: 1 error occurred:\n\t* credentials not found in
  native keychain\n\n"


[2022-11-17T15:24:37.400Z] Error: 1 build action(s) failed!
    at handleProcessResults (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/commands/base.ts:532:19)
    at BuildCommand.action (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/commands/build.ts:148:32)
    at GardenCli.runCommand (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:508:20)
    at GardenCli.run (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:667:26)
    at Object.runCli (/snapshot/project/tmp/pkg/cli/src/cli.ts:41:14)

Error Details:

results:
  build.test-image:
    type: build
    description: building test-image
    key: build.test-image
    name: test-image
    error:
      detail:
        command:
          - skopeo
          - '--command-timeout=30s'
          - inspect
          - '--raw'
          - '--authfile'
          - /.docker/config.json
          - >-
            docker://***********.dkr.ecr.us-east-1.amazonaws.com/****/repo/test:v-36b8e5e856
        output: >
          time="2022-11-17T15:24:37Z" level=fatal msg="Error parsing image name
          \"docker://***********.dkr.ecr.us-east-1.amazonaws.com/****/repo/test:v-36b8e5e856\":
          getting username and password: 1 error occurred:\n\t* credentials not
          found in native keychain\n\n"
      type: runtime
    startedAt: '2022-11-17T15:24:35.473Z'
    completedAt: '2022-11-17T15:24:37.326Z'
    batchId: b84dedc4-5292-47e7-ab98-a26b0a8fc485
    version: v-36b8e5e856
```

My pod has IAM permissions to access ECR as it is being run on an instance that has the correct IAM role, and imagePullSecrets are set up according to instructions. 

After some investigation, I found out that the error is being thrown by skopeo on the garden-utils pod, which is currently running a version of amazon-ecr-credential-helper (v0.4.0) that, for some reason, can't load the instance credentials. I logged in as root into the garden-utils pod and updated amazon-ecr-credential-helper to 0.6.0 and skopeo now works as expected.

### Expected behavior

The in-cluster build would work without errors.

### Reproducible example

You can use the kaniko example setting it up on EKS using an ECR registry.

### Workaround

There are no known workarounds.

### Suggested solution(s)

Update garden-util's (gardendev/k8s-util) image to use the latest version of amazon-ecr-credential-helper (0.6.0) so that it can load the credentials from the instance's attached IAM role.

### Your environment

* **OS:** macOS Ventura 13.0
* **How I'm running Kubernetes:** EKS running Kubernetes 1.23

`garden version`
0.12.46

**Comment by stefreak** [comment]
@theoribeiro thank you for taking the time to  this bug report!

As I am currently working on enabling IRSA for in-cluster builders (#2931) I am already looking into the relevant code paths. So I'll look into this issue.

**Comment by stefreak** [comment]
@theoribeiro I noticed that version `0.5.0` introduced support for [EC2 IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html). Is it possible that your EC2 instances have IMDSv1 disabled? See also the AWS docs on [configuring instance metadata options](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html)

**Comment by theoribeiro** [comment]
@stefreak You nailed it! We're using EKS Managed Node Groups for our nodes and I just checked and they're indeed using IMDSv2. Since we're using Terraform to deploy our cluster, I believe the modules are now configured to disable IMDSv1 by default as per an AWS recommendation to conform to security best practices.

**Comment by stefreak** [comment]
@theoribeiro cool thank you very much for confirming this, we'll fix this with high priority

**Comment by stefreak** [comment]
@theoribeiro can you try again after `garden self-update edge`?

We'll release this next week but I want to be sure that this change actually fixed your problem :)

**Comment by theoribeiro** [comment]
@stefreak the edge version is getting stuck getting the provider status. 0.12.46 gets pass that step but edge does not. Any ideas why?
```
providers                 → Getting status...
```

**Comment by stefreak** [comment]
@theoribeiro thanks for that piece of information, can you check where it gets stuck by running the command with silly-log enabled? (`-l5`)

**Comment by theoribeiro** [comment]
@stefreak it stops at:
```
GET https://*****.gr7.us-east-1.eks.amazonaws.com:5555/version
```

Normal version gets past that
```
GET https://*****.gr7.us-east-1.eks.amazonaws.com:5555/version
   Kubernetes: Getting API resource info for group networking.k8s.io/v1
   GET https://*****.gr7.us-east-1.eks.amazonaws.com:5555/apis/networking.k8s.io/v1
   kubernetes status: ready
   Caching provider status for kubernetes at /Users/theoribeiro/Dev/***/***/.garden/cache/provider-statuses/kubernetes.dev.json
```

**Comment by stefreak** [comment]
@Orzelius might this be a regression introduced with the new kubernetes client library version https://github.com/garden-io/garden/pull/3374 ?

**Comment by stefreak** [comment]
@theoribeiro is it possible that HTTP_PROXY or HTTPS_PROXY env vars are set?

**Comment by theoribeiro** [comment]
We are using an SSH tunnel to connect to the Kubernetes cluster, could that be the problem?

**Comment by stefreak** [comment]
@theoribeiro ah ok, can you kindly explain how the tunnel works? Are you using the ssh SOCKS proxy (`-D`)?

It would be amazing if you could take the time to create a new issue with information about your set up, so we can try to reproduce the behaviour.

Thank you again for the time spent, and really sorry there's another regression in the way 🙇

**Comment by theoribeiro** [comment]
We're using a simple port forward over ssh with `-fN -L 5555:$CLUSTER:443` and setting up `/etc/hosts` to point $CLUSTER to 127.0.0.1. 

That setup works for us for all kubectl commands. We tried using a SOCKS proxy for that but could never get it working properly with kubectl

**Comment by srihas-g** [comment]
@theoribeiro could you share the `cluster` config from your kube-context?

**Comment by theoribeiro** [comment]
Hey @srihas-g. Here's the configuration we got, omitting sensitive data:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ******* <omitted-base64-certificate-data>
    server: https://**********.gr7.us-east-1.eks.amazonaws.com:5555
  name: arn:aws:eks:us-east-1:***********:cluster/<cluster-name>
```

**Comment by Orzelius** [comment]
> @Orzelius might this be a regression introduced with the new kubernetes client library version https://github.com/garden-io/garden/pull/3374 ?

yes, it might

**Comment by Walther** [comment]
The provider status getting stuck could indeed be related to the regression introduced in #3374.
This should be fixed with #3389 - please try with the latest `edge` release to see if it helps!

**Comment by stefreak** [comment]
@theoribeiro We now actually reproduced the regression you faced with port-forwarding. @Walther fixed it in the latest edge release (https://github.com/garden-io/garden/pull/3389) –

could you run `garden self-update edge` again, and see if your issues are fixed now? 

Thank you

**Comment by theoribeiro** [comment]
@Walther @stefreak all working now! Just had the first build using Kaniko with no issues! 

Thank you for your efforts in making this work. Happy to collaborate with this great tool in any other way you guys need.

**Comment by stefreak** [comment]
@theoribeiro awesome :) Thanks for the offer, any collaboration+feedback is always appreciated! Feel free to reach out on our discord server if you have any ideas https://discord.gg/gxeuDgp6Xt

I'm working on a [more secure IAM setup using IRSA for in-cluster-building](https://github.com/garden-io/garden/issues/2931), if you want I can share the docs with you once it's merged, would be very happy if you can try it out and give feedback. Hope I finish it within the next 7 days.
