### ISSUE TITLE
Documentation has fixed max page width

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3371]
### Current Behavior
![image](https://user-images.githubusercontent.com/117711531/203464517-d688f93c-29de-4abb-9df4-9cf0b70d658a.png)

### Expected behavior
At the very least it should allow the embedded code blocks to display their full width.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by Orzelius** [comment]
We agree this is extremely annoying, but unfortunately it comes down to the doc provider we're using: gitbook.
In general we've been extremely unhappy with gitbook and plan to migrate to docusaurus in 0.13. This and many other issues will be solved in doing so.

**Comment by vvagaytsev** [comment]
Closing this as stale. It seems to be a GitBook issue.
