### ISSUE TITLE
localPort in services is ignored unless run in dev mode.

### ISSUE THREAD

**Issue by ralphv** [garden-io/garden#3382]
## Bug

[localPort](https://docs.garden.io/reference/module-types/container#services-.ports-.localport) is ignored unless it is run in dev mode or watch mode

### Current Behavior

when a service port specifies localPort, is it not being mapped correctly. Note this is different than the [portForwards](https://docs.garden.io/reference/module-types/kubernetes#portforwards) which is supposed to only run under dev/watch mode.

### Expected behavior

map the port locally so that the localhost:xxx can hit the service port as needed. In our use case this is required for normal operation and not just for debugging/dev mode purposes. 

### Reproducible example

Any service that has the localPort on ports is being ignored
### Workaround

Explicitly deploying the service in dev mode like

`garden deploy --dev=XXXX`

With this, the localPorts of the service XXX correctly map locally.

### Suggested solution(s)

According to the documentation, localPort should work always I don't see something to say that it is intended only for dev mode.

### Additional context

Sample yaml

kind: Module
name: service-ui
description: Service ui
type: container
dockerfile: docker/Dockerfile
services:
  - name: service-ui
    ports:
      - name: http
        containerPort: 8380
      - name: forward
        localPort: 8889 # this is ignored, this is the issue.
        containerPort: 8380
    ingresses:
      - path: /
        port: http
        hostname: kube-ep-${var.envId}-service-ui.${var.gardenHost}
        annotations:
          kubernetes.io/ingress.class: "nginx"

### Your environment

* **OS:** macOS
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217

* **How I'm running Kubernetes:** GCP

`garden version`
0.12.31

**Comment by ralphv** [comment]
Great to know. Thank you for the response. `--forward` will come in handy.

**Comment by vvagaytsev** [comment]
Thanks, @ralphv! Let's close this issue then :) Feel free to report a new issue if you get any troubles with the `--forward` flag.
