### ISSUE TITLE
isEmpty() computes wrong value with null values

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3398]
### Current Behavior
With a variable defined as null...

```
variables:
  my-value: null
```

...the following template...

```
${isEmpty(var.my-value)}
```

...evaluates to false.

The following snippet in the context of a kubernets manifest of a kubernetes module...

```
${isEmpty(null)}
```

causes this exception:

```
Failed deploying service 'tls-cert' (from module 'tls-cert'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Invalid template string (apiVersion: cert-manager.io/v1
kin…): Cannot read property '_error' of null
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy action(s) failed!
```

I find this slightly disturbing.

### Expected behavior
As documented here: https://docs.garden.io/reference/template-strings/functions#isempty

### Your environment

* **OS:** arch linux

`garden version`
0.12.46

**Comment by vvagaytsev** [comment]
Thanks for reporting this @hnicke! We'll take a look.
