### ISSUE TITLE
garden deploy: deployments are not being scaled up to 1 replica

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3438]
### Current Behavior
Since v0.12.47 we see a new behaviour:
A k8s deployment belonging to a garden kubernetes module with `spec.replicas: 1` which got manually scaled to `0` is not being scaled up when deploy via `garden deploy`.
The output is: `Already deployed`.

### Expected behavior
`garden deploy` should scale up the deployment to the specified replica count.
This was the behavior before 0.12.47.

### Reproducible example
* use garden v0.12.47
* use any k8s module with a k8s deployment
* deploy it using `garden deploy`
* scale it down manually: `kubectl scale deploy ... --replicas 0`
* deploy again using `garden deploy`.
  The output will say: `Already deployed`.
* we still have 0 pods.

#### != 0.13.7
Upon scaling down the deployment, overwrite its `garden.io/manifest-hash` annotation:

```
kubectl annotate --overwrite deploy ... garden.io/manifest-hash=scaleddown
```

Full example for a `scale-down` task:

```
kind: Module
type: exec
name: scale-down
description: |
  The 'scale-down' task completely scales down a system.
  After the task completed, there should be no running pods in the system.
tasks:
  - name: scale-down
    command:
      - bash
      - -c
      - |
        'set -eu
        kubectl="kubectl --context ${providers.kubernetes.config.context} --namespace '${providers.kubernetes.outputs.app-namespace}'"
        for resource_type in deployment statefulset; do
          if [ $($kubectl get $resource_type --no-headers | wc -l) -gt 0 ]; then
            $kubectl scale $resource_type --all --replicas 0
            # see https://github.com/garden-io/garden/issues/3438#issuecomment-1349264690
            $kubectl annotate $resource_type --overwrite --all garden.io/manifest-hash=scaledown
          fi
        done
        echo Successfully scaled down system'
```

#### == 0.13.7
Upon scaling down the deployment, delete the related garden-meta configmap:
```
kubectl delete configmap garden-meta-<garden-deploy-name>
```

Full example for a `scale-down` task:

```
kind: Module
type: exec
name: scale-down
description: |
  The 'scale-down' task completely scales down a system.
  After the task completed, there should be no running pods in the system.
tasks:
  - name: scale-down
    command:
      - bash
      - -c
      - |
        'set -eu
        kubectl="kubectl --context ${providers.kubernetes.config.context} --namespace '${providers.kubernetes.outputs.app-namespace}'"
        for resource_type in deployment statefulset; do
          if [ $($kubectl get $resource_type --no-headers | wc -l) -gt 0 ]; then
            $kubectl scale $resource_type --all --replicas 0
          fi
        done
        
        # ensure the deployment gets properly scaled up when running `garden deploy` for the next time
        # see https://github.com/garden-io/garden/issues/3438
        garden_meta_configmaps="$($kubectl get configmap --no-headers | awk "{ print \$1 }" | { grep "^garden-meta-deploy-" || true; })"
        [ -n "$garden_meta_configmaps" ] && $kubectl delete configmap $garden_meta_configmaps
        
        echo Successfully scaled down system'
```
        

### Suggested solution(s)
https://github.com/garden-io/garden/commit/66f74e8be seems to have caused this.

### Additional context
Scaling replicasets down is part of our core workflow for managing dev systems:

* In the evening we automatically scale all deployments / statefulsets down.
* when running `garden deploy` again the system used to automatically spin up again
While we could alter this workflow to not scale down but delete  the deployments, this further complicates automated upscaling (kubectl scale vs garden deploy).

### Your environment

* **OS:** linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.47

**Comment by stefreak** [comment]
Thanks for reporting this @hnicke, we'll look into this.

**Comment by hnicke** [comment]
Thank you for the provided workaround! Works like a charm.

**Comment by stefreak** [comment]
Great to hear that! We are planning to rework the logic (but after 0.13 landed) and I hope that we can then eliminate the need for that workaround

**Comment by hnicke** [comment]
version 0.13.7 shipped #4516 which in turn invalidated the [current workaround](https://github.com/garden-io/garden/issues/3438#issuecomment-1349264690).
@stefreak  has already [pointed out](https://github.com/garden-io/garden/pull/4516#pullrequestreview-1457055962) that #4516 would have implications on 'cleanup mechanisms in the wild'.

I have figured out that the new workaround for >= 0.13.7 is to delete the related `garde-meta-<deploy-name>` kubernetes configmap when scaling down the kubernetes deployment, just like @stefreak has already [assumed](https://github.com/garden-io/garden/pull/4516#discussion_r1214604254).

**Comment by hnicke** [comment]
I have updated the workarounds - now they contain full example for a `scale-down` task.

**Comment by stefreak** [comment]
Thank you for letting us know @hnicke !

**Comment by hnicke** [comment]
It looks like bonsai broke our scale-down workaround.
In  `0.13.7` I was able to remove the `garden-meta-*` configmap  as a workaround due to #4516.
Since #4516 got (partially) reverted, this workaround does not work in `0.13.8`.
However, our previous workaround (manipulate the `garden.io/manifest-hash` annotation) doesn't seem to work in bonsai anymore, at all. I tested with `0.13.6` and `0.13.8.`.
The `garden.io/manifest-hash` label is not being written by `garden deploy` anymore in the first place.
How does the garden deploy cache work in bonsai? Is it using local cache in `.garden`..?

**Comment by stefreak** [comment]
@hnicke We are currently working on this again in https://github.com/garden-io/garden/pull/5122, if you want to share your feedback with us.
Currently we plan to make sure that the work around mentioned in https://github.com/garden-io/garden/issues/3438#issuecomment-1349264690 continues to work, and we also plan to make sure that `deploy -f` is another workaround (We noticed that the deployment stays scaled to 0 with `deploy --force`, and that is not behaviour we desire– with `--force` it should be scaled up even without updating the version hash).

**Comment by hnicke** [comment]
I love the idea of being able to use `deploy -f` in this case!
However I'd appreciate if it would still be possible to scale up without the force flag, e.g. using above workaround.

On a side note, I resigned from my job and hence don't manage that garden stack anymore. @marcusLockenvitz is taking over responsibility for our stack for now.

**Comment by stefreak** [comment]
@hnicke Thank you for the feedback. Hi @marcusLockenvitz 👋  All the best for you @hnicke
