### ISSUE TITLE
Faster module resolution

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3452]
Users that have hundreds of modules in their Garden project, are running into performance issues. Starting most Garden commands takes a long time, because Garden is currently running multiple `git ls-files` calls for each module.

# Technical background
Garden relies heavily on Git for scanning module/action source trees, to determine the scope of build contexts and versions of each node in the Stack Graph.

Right now the tree scanning is done in a fairly naive way, basically calling out (even multiple times) to the `git ls-files` CLI command for _each_ module in a project, with limited optimizations made when different modules/actions share a directory, overlap etc.

# Proposed solution
1. Instead of a single instance of `VcsHandler` attached to the `Garden` instance, we create a handler for the context of each scan, i.e. when resolving actions/modules and pass it along. This allows the handler to hold state and caches during that context and then be freed.
1. When calling `GitHandler.getTreeVersion()` for a given action/path, instead of scanning the targeted path directly via `git ls-files` calls, we 
  1. Ensure that the _repo_ that the given path belongs to has been scanned and that the tree is in-memory.
    1. This should respect the `dotIgnoreFile(s)` and `modules.*` (to be renamed to `scan.*`) fields in the project config.
    1. Effectively this should be what currently happens in `VcsHandler.getFiles()` except that it streams into a tree structure instead of a list.
    1. A simple data structure would be a basic trie, organized by path components instead of string character. This would be a good place to start at least, and we can see how that scales.
  1. Extract the subtree for the given path.
  1. Apply any filters, i.e. include/exclude on the module/action.
  1. Return the list of files.
1. Initially roll this mechanism out via feature flag, e.g. `GARDEN_GIT_SCANNER=repo`.
  1. This can basically toggle whether we use the current `GitHandler` or the new class which houses the new implementation.

## Benefits of the approach
1. The only required changes outside of `VcsHandler` and `GitHandler` are to pass an instance of the handler around during use, instead of using `garden.vcs`. This limits the blast radius of the changes dramatically and **avoids major conflict with graph V2 changes**.
1. We basically drop the number of `git ls-files` calls from up-to-hundreds to a handful on each project scan.

## Potential concerns
1. We may in certain cases be indexing a _lot_ of files in memory, so we might need aggressive optimizations on that front. We need to stress test this and see.
  1. One potential highly scalable approach, since we already bundle it, is using an in-memory sqlite instance, single table per repo, b-tree index on the path. Might be too heavy, not quite sure.
  1. Another approach could be making a WebWorker for the scanning, written in Rust or Go and compiled to WASM, and querying that.
1. This will need quite a bit of testing, both automated and in practical use.

# Alternative approaches
1. We could instead employ more limited caching improvements, e.g. caching file lists per scanned directory (pre-filtered). In that case we would still implement step #1 in the above solution.
  1. This would be a much more marginal improvement, but still likely drop `git` CLI calls.
1. We might also go for a different flow, essentially pre-optimizing calls by gathering upfront which filesystem queries need to be run and planning accordingly.
  1. This is likely a more complex approach ultimately, and would certainly have a far bigger blast radius in terms of code modules affected.
1. ?

**Comment by mdragilev** [comment]
Hi.  Are there any plans for implementing this or anything else for speeding up resolution of hundreds of modules. We are running into the performance issues as well.

**Comment by vvagaytsev** [comment]
@mdragilev we're working on the next big release now - `0.13`. We plan do revisit this after `0.13`.

**Comment by mdragilev** [comment]
@vvagaytsev Thank you Vladimir.  Is there a place to track when 0.13 will come out?

**Comment by vvagaytsev** [comment]
@mdragilev yes, the 0.13 project GH board is https://github.com/orgs/garden-io/projects/5

The goal is to release it in Q1 2023.

**Comment by vvagaytsev** [comment]
@tedchang77 we're planning to do a pre-release for public testing by the end of March. The production release is planned for Q2 2023.

**Comment by tedchang77** [comment]
We're planning on migrating to 0.13. Is there a timeline for when this will be implemented?

**Comment by edvald** [comment]
We're working on this right now @tedchang77! Can't quite commit to a timeline until we've tested it a bit but expect no more than a couple of weeks.

**Comment by edvald** [comment]
We've only partially addressed this, so leaving it open still.

**Comment by vvagaytsev** [comment]
@eysi09 @edvald should we split it into a few more particular issues?

**Comment by eysi09** [comment]
Yeah I think this needs to be revisited now that we have a partial implementation. 

We may want to open a new issue that's more specific.

**Comment by TimBeyer** [comment]
Can we close this now that `0.13.20` is released with the new scan mode as default and with the tree based performance optimization?
