### ISSUE TITLE
[FEATURE]: support kustomize in helm module

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3459]
## Feature Request
Garden's kubernetes module supports Kustomize. Let's port this support to Garden's helm module using Helm's [post rendering](https://helm.sh/docs/topics/advanced/) feature.

### Background / Motivation
I was writing an article for Garden's blog on Helm charts and thought wow one of Helm's most powerful features, post rendering, would be a huge win in our push to catering to DevOps Engineers and platform teams that work with Kubernetes every day.

### What should the user be able to do?
At first, anything users of the kubernetes module can do with its support for kustomize. Later, pass to Helm "any executable that accepts rendered Kubernetes manifests on STDIN and returns valid Kubernetes manifests on STDOUT"[^1]. 
[^1]: https://helm.sh/docs/topics/advanced/#usage

### Why do they want to do this? What problem does it solve?
This feature would help bring feature parity to both kubernetes and helm modules and eliminate cases of, "we support Helm but..."  and other gotchas when SREs, DevOps Engineers, and Platform Engineers turn to use these tools. Increasing coverage of support for the underlying technologies behind these modules reduces frustration and works as a user expects. Users typically expect everything works when support is advertised: see CockroachDB's continued march toward syntax-parity with Postgres for an example.

### Suggested Implementation(s)
Expose functionality exactly as the kubernetes module. The backend would call Kustomize as its post-render executable. Allows arguments as the kubernetes module.

### How important is this feature for you/your team?
:rose: It’s a nice to have, but nice things are nice :slightly_smiling_face:

**Comment by worldofgeese** [comment]
In Helm version [3.9.0](https://github.com/helm/helm/releases/tag/v3.9.0), Helm adds “a --post-renderer-args flag to support arguments being passed to the post renderer”.

**Comment by hnicke** [comment]
See also #3289.

**Comment by vvagaytsev** [comment]
This duplicates #3289.
