### ISSUE TITLE
SGv2: Some trivial fixes in error message assertions

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3506]
Some error message assertions should be fixed:

* [x] base.ts
* [x] common.ts
* [x] module-template.ts
* [x] project.ts

Let's use fuzzy-matching comparison like in  https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/config/base.ts#L170 instead of `expect(stripAnsi(err.message)).to.equal("...")`

**Comment by Walther** [comment]
Fixed in https://github.com/garden-io/garden/pull/3527 (not sure why this wasn't auto-closed)
