### ISSUE TITLE
Make persistent volumes the default for cluster buildkit pods

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3514]
Make persistent volumes the default for cluster buildkit pods.

We no longer need to sync code to garden-util when using buildkit. Buildkit can take care of caching build contexts.

See also #3235.

**Comment by stefreak** [comment]
@vvagaytsev Looking at #3235 this does not need to be the default. We first need to implement PVC support for in-cluster-builder build context storage (not only buildkit). We can still decide on the new default after we gathered experience with some users running it with the PVC mode in 0.14. Right now it is just not possible to configure in-cluster-builder to use PVCs and that is simply a missing feature that can be added after initial 0.13 release.
