### ISSUE TITLE
Don't (or at least optionally) include dependants when running `garden test <module name>`

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3518]
See https://github.com/garden-io/garden/blob/844126e6b8ec2eecf7124f5180333fb70716a7c6/core/src/commands/test.ts#L120

* We added a `--skip-dependants` option to the `test` command in https://github.com/garden-io/garden/pull/2363
* We might consider making this behaviour the default, while replacing the `--skip-dependants` option with a `--with-dependants` option.

**Comment by edvald** [comment]
This is already the default behavior in 0.13.
