### ISSUE TITLE
Create a new example for certificate generation and management

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#3521]
We need a new example for certificate generation and management, as the automatic cert-manager integration is deprecated and deleted in 0.13.

Related to:

* https://github.com/garden-io/garden/issues/2551
* https://github.com/garden-io/garden/pull/3517/

**Comment by ShankyJS** [comment]
Hey @Walther please assign me this one

**Comment by worldofgeese** [comment]
@ShankyJS and I are working on a doc [here](https://youngest-kite-tan-preview.motif.land/cert-manager-install-draft). It's just the commands for now. Exposition to come.
