### ISSUE TITLE
Garden attempts to get status of K8s service before environment is prepared 

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#353]
Running some Garden commands (e.g. `deploy` and `init`) when the `garden-system` hasn't been initialised throws `Got error from Kubernetes API - services "garden-system--ingress-controller-nginx-ingress-controller" not found`. 

This is because:

1. The commands above trigger a call to `prepareEnvironment` in (`src/actions.ts`).
2. The `prepareEnvironment` function calls `getEnvironmentStatus` before invoking the `prepareEnvironment` handler for the relevant plugins.
3. That eventually results in the `Helm` plugin calling `checkObjectStatus` (`kuberntetes/status.ts`) for `garden-system` K8s objects.
4. Calling `checkObjectStatus` throws a 404 error for missing service objects (they haven't been prepared cf. 1. above). 

At first glance, `getEnvironmentStatus` should be called after the `prepareEnvironment` handlers are invoked. However, the handlers depend on the return value from `getEnvironmentStatus`. So this one requires a bit more thought.

**Comment by eysi09** [comment]
This issue can be worked around for now with #354.

**Comment by edvald** [comment]
I actually think #354 addresses this correctly. Closing.
