### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#355]
When running Garden on the Mac I use for development and the Windows machine I use for testing I regularly run into some DNS issues. E.g. when running `garden call my-service/` I get the following:

`getaddrinfo ENOTFOUND project-name.local.app.garden project-name.local.app.garden:80`

This is resolved when I add `127.0.0.1 project-name.local.app.garden` to the hosts file (both on Windows and osX).

However, as far as I know, other users have not had to edit their hosts file to get Garden working. What gives?

**Comment by thsig** [comment]
I haven't encountered this myself, but I seem to recall you running into network problems on your machine in the past. Could this have something to do with your particular setup?

**Comment by edvald** [comment]
This doesn't appear to be Garden-specific at all, but perhaps something to do with this DNS "hack" of having a wildcard entry point to 127.0.0.1. It wasn't meant as a permanent solution when I set it up, but I also don't quite understand what may be causing this for you - and noone else.

**Comment by drubin** [comment]
What DNS hack? How do we get wildcard entries to point to 127.0.0.1 I tried for ages to figure out if this was possible but short of running a DNS server I couldn't figure it out.

**Comment by drubin** [comment]
This since this was a miss configuration on our router.

 If we figure out what causes it to not pass the DNS through we can revisit it or if its a real common problem we can update our FAQ/setup instructions.
