### ISSUE TITLE
Garden fails deploying helm chart after stateful set was deleted

### ISSUE THREAD

**Issue by TimBeyer** [garden-io/garden#3625]
### Current Behavior

I had a `vault` deployment which comes from a helm chart.
During debugging another issue, I deleted its `StatefulSet` from the cluster manually.
Now when I want to deploy, I receive the following error message from Garden:

```
Failed deploying service 'vault' (from module 'vault'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
StatusCodeError from Kubernetes API (/apis/apps/v1/namespaces/ge-tim/statefulsets/vault) - 404 - 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"statefulsets.apps \"vault\" not 
found","reason":"NotFound","details":{"name":"vault","group":"apps","kind":"statefulsets"},"code":404}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

I ran both `garden delete service vault` and deleted the `.garden` directory, but it would still fail.

Only when deleting the release in `helm` directly - in my case using Lens for that - vault can be deployed again.

### Expected behavior

I would expect `garden delete service vault` to fully delete the helm release so I can redeploy.
I'd also expect `garden deploy vault --force` to ensure that in case of an error like this, it would force delete and redeploy the chart.
I might also expect that I receive some sort of helpful guidance in case of this error that points me in the direction of resolving this.

### Reproducible example

Create a module of type helm that relies on a stateful set (for example picking the official helm chart).  
Delete its stateful set.  
Try to deploy it.

### Workaround

Directly delete the helm release.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` 0.12.48

**Comment by stefreak** [comment]
Thank you for reporting this @TimBeyer 👍

**Comment by 10ko** [comment]
Resources created by Helm should only be deleted (or "uninstalled") using Helm or Garden, if a user deletes a resource manually, the status of the Helm release will be inconsistent and Garden cannot know if it should re-deploy said resource or not. We are closing this, feel free to re-open if you have a way we could implement this.
