### ISSUE TITLE
`examples/jib-container` Gradle hot reload doesn't work

### ISSUE THREAD

**Issue by iirekm** [garden-io/garden#3674]
I switched the spring boot app example from Maven to Gradle. The only way to force it to hot reload is changing something in `spring-boot.garden.yml`. Changing java code, or `./gradlew classes` or `./gradlew assemble` or `./gradlew jibDockerBuild` - nothing forces garden to reload it.

**Comment by Orzelius** [comment]
Hello @iirekm, the jib-container example does not have hot reloading or dev mode configured. Jib module type is just for building container modules. If you wish to improve developer experience when working on the code you can configure [dev mode](https://docs.garden.io/guides/code-synchronization-dev-mode) like usual or perhaps utilize garden's [local mode functionality](https://docs.garden.io/guides/running-service-in-local-mode).

Can this issue be closed?

**Comment by vvagaytsev** [comment]
Closing this or stale.
