### ISSUE TITLE
[FEATURE]: Helm version >= v3.8.0 / Use local helm installation

### ISSUE THREAD

**Issue by djfinnoy** [garden-io/garden#3753]
### Background / Motivation
Garden is currently shipped with Helm v3.7.2. This is problematic for those of us who use OCI registries (eg. Google Artifact Registry).

Can we please upgrade the bundled Helm binary?

We are using Google Artifact Registry for containers and helm charts. In later versions of Helm, its possible to re-use Docker's credential configuration (`gcloud` credential helper) for these registries. Since Garden runs Helm v3.7.2, I'm unable to authenticate via Helm modules. Container modules work fine for the same registry.

### What should the user be able to do?

Users should be able to use Google Artifact Registries for both containers and helm charts, with authentication handled by the `gcloud` credential helper in the local Docker config.

### Why do they want to do this? What problem does it solve?

It allows full usage for Google Artifact Registries for containers and helm charts; providing a private registry with a simple authentication mechanism.

### Suggested Implementation(s)

Bump the bundled Helm binary to v3.11.1

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

**Comment by jondeandres** [comment]
I experienced same issue installing bitnami OCI charts. I fixed the problem temporary linking the `helm` binary in `~/.garden/` to my system one

**Comment by stefreak** [comment]
@garden-io/core I added this to your core weekly as Candidate, because using a helm version that does not support OCI becomes more and more "breaking" over time for everyone who depend on Helm charts whose latest versions are released on OCI.

**Comment by chrispsplash** [comment]
i have confirmed this works on garden 0.13.2 🎉 .  NOTE: The OCI charts are referred to by a single URI so we don't need the `repo` field any more.

# Example
Here's how you deploy the Bitnami Contour helm chart version 12.1.0
```
kind: Deploy
type: helm
name: contour

spec:
  chart:
    name: oci://registry-1.docker.io/bitnamicharts/contour
    version: "12.1.0"

  namespace: contour
```
