### ISSUE TITLE
[FEATURE]: Add server-side apply option to kubernetes action

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3839]
### Background / Motivation

When applying manifests using `kubectl apply`, theres a limitation of 256kb because of how annotations work.

If you use `kubectl apply --server-side` then it doesn't suffer from this limitation, however there may be added complications with resolving conflicts.

https://kubernetes.io/docs/reference/using-api/server-side-apply/

### What should the user be able to do?

For a given kubenetes module you should be able to enable the `--server-side` switch when garden executes `kubectl apply`

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

🌵 Not having this feature makes using Garden painful

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by 24601** [comment]
Given server-side apply is required for anything over 200k or so, I'd say this is actually quite important for many people (like OLM's CRDs, they must be SSA'ed).

**Comment by ManAnRuck** [comment]
I've a similar issue with adding CRDs from TiDB.
Maybe it make sense to add something like this
```yaml
spec:
  apply:
    extraArgs:
      - "--server-side=true"
```
or
```yaml
spec:
  apply:
    serverSide: true
```

---

Just for testing, adding 
```ts
  args.push("--server-side=true")
```
after line 122 in https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/kubectl.ts#L122 is working for me :sweat_smile:

**Comment by ManAnRuck** [comment]
Do you maybe have a hint for me, how i should get and pass the spec.XY arg from config to the apply function?
Just started to open a PR ;)
https://github.com/garden-io/garden/pull/6107
