### ISSUE TITLE
Configure support for depending on pure ESM packages

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#3841]
A lot of packages in the Node ecosystem have moved to being pure ECMAScript modules (ESM)
Our current build configurations and scripts do not support depending on ESM.
This is blocking us from updating a lot of our dependencies.

Blocked by `pkg` https://github.com/vercel/pkg/issues/1291

**Comment by Walther** [comment]
@stefreak i have a list of examples mentioned here: https://github.com/garden-io/garden/pull/3838

**Comment by stefreak** [comment]
Still causing issues for us, see also #5182
