### ISSUE TITLE
Dependency relation not transitive?

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#386]
If `service-a` depends on `service-b`, and `service-b` depends on` service-c`, `service-a` does not appear to depend on `service-c`.

I noticed this when trying out the _[sock-shop-mono](https://github.com/garden-io/sock-shop-mono/commits/master)_ example where `front-end` depends on `orders` and `orders` depends on `shipping`, at the service level.

Now, when I run `garden dev` and then change the `shipping` service, `front-end` will deploy before `shipping`. Whereas I'd expect `shipping` to deploy, then `orders`, then `front-end`. (Note that on the current _sock-shop-mono_ `master` branch, `shipping` is a dependency of `front-end` so that should be removed to see issue.)

If the dependency relation is not supposed to be transitive we should probably document that because I think that's what people would assume.

[Here's a digram](https://github.com/microservices-demo/microservices-demo.github.io/blob/HEAD/assets/Architecture.png) of the sock-shop service dependencies.

**Comment by edvald** [comment]
This is simply a bug, likely introduced recently. @thsig can you investigate?

**Comment by edvald** [comment]
Or well at least it sounds like a bug from the description, but looking at it again there are some possible explanations, depending on the exact configuration and state (not 100% clear to me reading the description). In any case this needs to be inspected - and I'd suggest tests to be written to validate.

**Comment by thsig** [comment]
I'll look into this (and write tests as appropriate).
