### ISSUE TITLE
Running garden get status in `project + module` in same directory causes services to be hot reloaded

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#387]
Calling `garden get status` in `gatsby-hot-reload` causes the some file changes that triggers a reload.

(Same thing happens with out hotreload enabled)

I assume this has to do with our calculation of "dirty" state and the module's directory is in the same directory as the `.garden` folder? 

### Start garden

```sh
garden dev --hot-reload=website

Good morning! Let's get your environment wired up...

✔ website                   → Building website:2c12317af0... → Done (took 36.2 sec)
✔ website                   → Deploying → Ready
```
### Run 

`garden get status`

## Output 

```sh
✔ website                   → Hot reloading → Done (took 316 ms)
✔ website                   → Building website:2c12317af0... → Done (took 0.7 sec)
✔ website                   → Hot reloading → Done (took 144 ms)
✔ website                   → Building website:2c12317af0... → Done (took 0.4 sec)
✔ website                   → Hot reloading → Done (took 132 ms)
✔ website                   → Building website:2c12317af0... → Done (took 0.4 sec)
```

**Comment by edvald** [comment]
@thsig This came up again while @drubin was working on a particular example project. Might be worth bumping in priority. David can give more details on the issue.

**Comment by edvald** [comment]
Does adding those files to `.gitignore` help? Not to say we shouldn't fix it on our side, just wondering if that works.

**Comment by drubin** [comment]
@edvald  They were in `. gitignore`   https://github.com/drubin/cote-workshop/blob/garden/.gitignore#L5 `*.log`

**Comment by edvald** [comment]
Ah ok. The `.gitignore` should be respected, so it may be a different issue then, but we'll find out.

**Comment by edvald** [comment]
@thsig This does still appear to be an issue, FYI. Not a high priority one, but possibly indicative of some other larger issue.
