### ISSUE TITLE
Task template resolution breaks module deploy (even when task has its own dependencies)

### ISSUE THREAD

**Issue by sundbp** [garden-io/garden#3895]
### Current Behavior

I have a task on module A looking like:
```yaml
tasks:
  - name: vault-configure
    dependencies:
      - name: vault-read-root-token
    command: [/bin/configure-vault.sh, "${runtime.tasks.vault-read-root-token.outputs.log}"]
```

So this task command depends on the output of the dependent task.

If I try to apply this module it fails with:
`Invalid template string (${runtime.tasks.vault-read-root-to…): Could not find key vault-read-root-token under runtime.tasks.`

It suggests that resolving the overall module depends on resolving this task template, which isn't relevant for deploying the task at hand.

### Expected behavior

I expect that deploying the module should not fail as it is not using this task for deployment in any way, nor does it use the template outside of the specific task.

### Workaround

I am not aware of one.

### Suggested solution(s)

Do not attempt to resolve the tasks section, which is irrelevant, when a module is deployed.

### Additional context

In my case I have a vault module and a vault-init module. The vault-init module does automatic vault initialization and unseal, storing away the vault root token. It has a task vault-read-root-token to fetch this token. Then the vault module has a configure-vault task which depends on this token to run a script to setup policies etc in vault.

I thought by making only the configure-vault task depend on the read root token task things would work, but at garden deplioy time the configure-vault task seems to be resolved and it breaks (as the task hasn't been run, and can't be run at this time either as vault isn't yet unsealed).

### Your environment

* **OS:** Arch Linux
* **How I'm running Kubernetes:** KinD 

`garden version`
0.12.52

**Comment by stefreak** [comment]
@sundbp thank you for reporting this; Can I ask you to create a small / minimal example for us that reproduces this problem (e.g. as a gist)

That would be super helpful 🙏

**Comment by vvagaytsev** [comment]
Closing this a stale. Feel free to reopen if it's still an issue in 0.13.
