### ISSUE TITLE
Logs command fails with "no such file or directory" if a given K8s service hasn't been staged to the build dir

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3900]
### Current Behavior

If a given service belongs to a K8s module and it hasn't been built and thereby is not in the `.garden/build` directory, the `garden logs` command will fail with:

```sh
ENOENT: no such file or directory, open '/path/to/.garden/build/my-servicre/my-service.yml'
```

### Reproducible example

1. Change into the `kubernetes-module` example project.
2. Run `rm -rf ./.garden/build`
3. Run `garden logs`. 

### Workaround

Run `garden build` or `garden deploy` before running the logs command.

### Suggested solution(s)

Either we read the manifest required to find the logs from the src dir or ensure that we stage it before getting the logs.

### Your environment

Only tested on Garden 0.12 but AFAICT is broken on 0.13 as well.

**Comment by Walther** [comment]
potentially related https://github.com/garden-io/garden/pull/4516 ?

**Comment by 10ko** [comment]
This should be fixed, please re-open if that's not the case.
