### ISSUE TITLE
BUG: SSL verification fails when connecting to GKE cluster using the internal IP

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3918]
### Current Behavior

1. Get cluster credentials of GKE cluster using `gcloud container clusters get-credentials <cluster-name> --internal-ip --region=<cluster>`. Notice the `--internal-ip` flag.
2. Run a garden command from a computer that has a route to the internal IP of the Kubernetes API (e.g. through a VPN or from a virtual machine that is connected with the internal network).
3. Garden will complain with this error: `Error: unable to verify the first certificate` While `kubectl` commands work fine.

### Expected behavior

Garden should trust the certificate defined in the .kube/config, just like `kubectl` does. The garden command should also work with the internal IP, without the certificate verification error message.

### Reproducible example

Can be reproduced with any remote kubernetes example; the internal IP of the GKE needs to be made reachable from the computer that runs the garden command.

### Workaround

One workaround is 

```
export NODE_TLS_REJECT_UNAUTHORIZED='0'
```

But that is not a sustainable solution, as it degrades security significantly.

### Suggested solution(s)

This is likely an issue with the upstream library [kubernetes-client/javascript](https://github.com/kubernetes-client/javascript).

### Your environment

* **OS:** unknown
* **How I'm running Kubernetes:** GKE

`garden version` unknown

**Comment by 10ko** [comment]
This should be fixed, please re-open if that's not the case.
