### ISSUE TITLE
Get rid of Sywac CLI framework

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#393]
Sywac isn't maintained much and is poorly documented, and I feel like mapping our commands to it is uglier than just switching to a simpler arg parser (e.g. https://github.com/sindresorhus/meow). 

nb. We also looked a bit into oclif.io as well, but it doesn't appear to fit easily with our needs, even though it seems like a nice framework.

Not a high priority task, but maybe a nice first issue for someone, would clean up our code a bit.

**Comment by davidkjackson54** [comment]
It appears that sywac may have died a death. Doesn't seem to have been touched in 6 months. 
Seems to have gone the same way as yargonaut by the same author.   Started but then seemingly dropped.
Would like to see a public statement by the author as to the status. I wouldn't want to waste a lot of time converting without a clear path.

**Comment by edvald** [comment]
That seems to be the case. Thankfully we're not tightly coupled to it. Most of our related code is glue between Sywac and our underlying `Command` abstraction (which we created to avoid this type of coupling, and to allow other methods of using the commands such as HTTP API calls).

**Comment by eysi09** [comment]
This doesn't feel relevant. Lets revisit when we need to.
