### ISSUE TITLE
0.13: [Bug]: Reference docs on Action types are missing context; config keys not alphabetically sorted

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4056]
### Current Behavior

Garden's Action Types reference page is missing context: it is unclear which Action (Build, Deploy, Run, Test) each `kind`  block sits under.

![image](https://user-images.githubusercontent.com/59834693/230126545-5f61d7ae-436b-433b-a31d-c82ee6cbd16c.png)

Additionally, config keys in the sidebar of each kind's action are not alphabetically sorted. If this is by design, please disregard.

![image](https://user-images.githubusercontent.com/59834693/230127748-9168da2a-6bb9-42dc-a3f3-3066d7e8a411.png)

This bug is submitted on behalf of @pepov and has been validated by @worldofgeese. @pepov may have addditional context to share.

**Comment by vvagaytsev** [comment]
The action kind rendering has been fixed in #4057. I've also checked the docs generated from the `main` branch. It looks like we have not sorted the TOC alphabetically. That can be addressed in a separate PR if we'd like to.

**Comment by worldofgeese** [comment]
Thanks @vvagaytsev!
