### ISSUE TITLE
[FEATURE]: `asdf` plugin to support multiple concurrent versions of `garden`

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4059]
### Background / Motivation

Testing community preview releases like Bonsai could be a lot easier with an asdf plugin, which allows multiple versions of a given program to co-exist inside a user's development environment.

### What should the user be able to do?

Community testers should be able to take advantage of preview releases easily without sacrificing the convenience of a stable Garden version.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

This looks simple enough for me to take a crack at. Tagging @pepov who first asked for this feature.

**Comment by vvagaytsev** [comment]
Closing this as not planned. We have improved `garden self-update` command. Now it allows going back and forth between the stable and edge releases.

**Comment by worldofgeese** [comment]
@pepov has created one already at https://github.com/pepov/asdf-garden. Would there still be a use-case for your plugin if garden can freely move between releases?

**Comment by pepov** [comment]
Yes, I prefer managing all the various tools with asdf. It's nice that garden can do that alone, but that's not a standard thing, so I can't expect it from other tools. But I'm happy with my plugin, it was an hour or so to set it up and it doesn't need any maintenance so all good.
