### ISSUE TITLE
0.13: [Bug]: garden deploy --sync not syncing.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4068]
### Current Behavior

Sync seems to start properly, but nothing gets synced

### Expected behavior

The changes on my local machine to be synced in the remote container.

### Reproducible example

- Run `garden deploy --sync` in the Cloud project.
- Make a change in the source code.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
Cannot reproduce this. Feel free to reopen if the issue occurs again.
