### ISSUE TITLE
Cluster buildkit with buildarg is empty string ''

### ISSUE THREAD

**Issue by fabianboerner** [garden-io/garden#4081]
In case a build arg is empty string '' incluster build with cluster buildkit fails

MY_ARG=''

invalid opt: invalid value build-arg:MY_ARG

because its forwards as build-arg:MY_ARG and expects build-arg:MY_ARG='' 

and i did not found any way to work around this since the argument on our side is sometimes an empty string, setting it to null has other drawbacks because some languages convert that into string

**Comment by vvagaytsev** [comment]
Thanks for reporting this @fabianboerner! We'll take a look.

We might also need to check if the same issue is valid for `kaniko`. cc @Walther
