### ISSUE TITLE
0.13 TODOs

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#4086]
Feel free to assign to yourself or convert to proper issues if you feel the need.

- [x] [actions/base.ts](https://github.com/garden-io/garden/blob/0.13/core/src/actions/base.ts#L400) - "is ported from another function but the logic seems a little suspect to me... - JE"
- [x] [cli/cli.ts](https://github.com/garden-io/garden/blob/0.13/core/src/cli/cli.ts#L256) - edit alpha warning for the proper 0.13 release (but keep the message and a link to where to report issues) @shumailxyz 
- [x] [config/template-contexts/actions.ts](https://github.com/garden-io/garden/blob/0.13/core/src/config/template-contexts/actions.ts#L206) - rename to template context to `actions` (to allow using `action` singular in certain contexts + match the modules field) @vvagaytsev -> #4194 
- [x] [graph/actions.ts](https://github.com/garden-io/garden/blob/0.13/core/src/graph/actions.ts#L466) - handle remote sources 

---

## Waiting for answers

- [ ] [plugin/base.ts](https://github.com/garden-io/garden/blob/0.13/core/src/plugin/base.ts#LL120C45-L120C45) - update `RunResult` schema @edvald what exactly has to be updated?
- [ ] #4543
- [x] [server/server.ts](https://github.com/garden-io/garden/blob/0.13/core/src/server/server.ts#L559) - Get rid of ClientRouter entirely @eysi09 How important is this?
- [x] [commands/deploy.ts](https://github.com/garden-io/garden/blob/0.13/core/src/commands/deploy.ts#L158) - make `monitor` and `forward` explicit options (wait for rfc)
- [ ] #4544

--- 

## a bit lower prio (will do only if the above is done)
- [x] [graph/config-graph.ts](https://github.com/garden-io/garden/blob/0.13/core/src/graph/config-graph.ts#L134) - checks for circular dependencies (circular deps already detected by toposort)
- [ ] [vcs/vcs.ts](https://github.com/garden-io/garden/blob/0.13/core/src/vcs/vcs.ts#L192) - Emit large number of files warning only once
- [ ] [plugins/kubernetes/local-mode.ts](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/kubernetes/local-mode.ts#L430) - allow multiple manifests configuration in local mode
- [ ] [plugins/kubernetes/kubernetes-type/handlers.ts](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/kubernetes/kubernetes-type/handlers.ts#L303) - Support multiple processes+targets for local mode
- [ ] [graph/common.ts](https://github.com/garden-io/garden/blob/0.13/core/src/graph/common.ts#L145) - use JSON merge for variables (also see https://github.com/garden-io/garden/issues/3592)
- [ ] [plugins/container/config.ts](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/config.ts#L599) - swap out volume acton reference with raw k8s reference
- [x] [commands/get/get-runs.ts](https://github.com/garden-io/garden/blob/0.13/core/src/commands/get/get-runs.ts#L33) - add output schema
- [x] [commands/get/get-tests.ts](https://github.com/garden-io/garden/blob/0.13/core/src/commands/get/get-tests.ts#L32) - add output schema

**Comment by vvagaytsev** [comment]
The most important tasks have been completed. The rest will be done in the `0.13.x` patch releases.

**Comment by Orzelius** [comment]
Converted to separate issues, no longer relavant
