### ISSUE TITLE
0.13: update the apiVersion and make it mandatory

### ISSUE THREAD

**Issue by mkhq** [garden-io/garden#4089]
### Background

Currently the project configuration schema has an `apiVersion`-field. This field is not mandatory in 0.12 and is available on both the project and module-level.  In order to provide users of garden a migration path, we propose to make the `apiVersion`-field mandatory at the root of the project configuration and to make that the only place where it is used. Further, for 0.13, we suggest to increase the version to `garden.io/v1`, to clearly indicate a schema breaking change. This will make it possible to fail the garden CLI in a safe way including instructions on how to upgrade for the end-user and simplify the detection of the correct garden runtime in an automation pipeline.

### Changes

Limit the `apiVersion`-field to the project config root, make it mandatory and increase the version to `garden.io/v0.13`.  The value of the version-field is a string ending with `v<major.minor version string>`. Until version 1.0, we will increment the minor version on schema changes. The field will be mandatory for the garden `0.13` CLI runtime and optional in `0.12`.

**Comment by edvald** [comment]
This is an important topic, but I have a few notes which may affect the choices here:

1. The `Project` configuration schema itself has zero breaking changes in 0.13, as far I can tell. Even the fields and features we've removed only cause a warning. (If that is not the case, we should just fix that).
2. I believe the same goes for `Module` configs, across the board.
3. The new action kinds should be _ignored_ by Garden 0.12. They are new config kinds and don't exactly need a required `apiVersion`, but we _could_ choose to require the field specifically on those new kinds, since they need to be created fresh anyway.
4. It is _very_ likely that many teams will run a mix of 0.12.x and 0.13.x clients during transition.
5. The point about choosing which runtime to use (or require) is I feel a bit disconnected from the config schema version.

We've gone to substantial lengths to make sure user configs are compatible with 0.13, and I really don't want to create unnecessary issues in that transition, if we can avoid it.

A potential low-friction approach could be:

1. Introduce a `gardenVersion` field in Project configs (or something to that effect), allowing for a range. This could inform Cloud Workflows etc. which version to use, and either warn or error when users attempt to use a different version. We've actually thought about this for a while anyway.
2. Set the default `apiVersion` in Garden 0.13.x to `garden.io/v0.13`.
3. Require the `apiVersion` field in 0.14+, warn if not explicitly set in 0.13.x.
4. Update all non-module config examples to include the `apiVersion` field.

**Comment by mkhq** [comment]
> 1. The Project configuration schema itself has zero breaking changes in 0.13, as far I can tell. Even the fields and features we've removed only cause a warning. (If that is not the case, we should just fix that).
> 2. I believe the same goes for Module configs, across the board.

There are still some inconsistencies, for example, `livenessProbe` fails in a kubernetes module when used by 0.13. But let's assume we can solve all backwards compatibility issues for 0.13. This would enable a mix of 0.12 and 0.13 clients to work seamlessly with a 0.12 schema and have equivalent execution semantics. One possible migration path is then to inform users to update to 0.13 and put a cut-off date when 0.13 specific config will be introduced, effectively breaking 0.12 clients. 

> 3. The new action kinds should be ignored by Garden 0.12. They are new config kinds and don't exactly need a required apiVersion, but we could choose to require the field specifically on those new kinds, since they need to be created fresh anyway.
> (low-friction approach) 1. Introduce a gardenVersion field in Project configs (or something to that effect), allowing for a range. This could inform Cloud Workflows etc. which version to use (always choosing the latest applicable one), and either warn or error when users attempt to use a different version. We've actually thought about this for a while anyway.

The 0.12 schema parser is strict and does not seem to allow any fields outside of the defined schema. E.g. If I add a `gardenVersion` at the top-level the execution fails. It even validates the values so `apiVersion` can only be `garden.io/v0`. The error returned is `Error validating project: key "gardenVersion" is not allowed at path [gardenVersion]`, and it seems to be the same for new Kinds. We could introduce a 0.12 release with new fields and a less strict validation, but that would make for a potentially awkward migration path in larger orgs with multiple patch releases of 0.12 in active use.

> 2. Set the default apiVersion in Garden 0.13.x to garden.io/v0.13.
> 3. Require the apiVersion field in 0.14+, warn if not explicitly set in 0.13.x.

Agree, lets do this.

**Comment by mkhq** [comment]
@edvald slept on this and had another round of discussion with @TimBeyer. We would still like to argue for making the `apiVersion`-field mandatory in 0.13. This would mean a 0.13 client running against a config without this field would fail-stop with an error message indicating that the field is missing (breaking change). I'll go into the reasoning and a versioning/migration proposal below.

**Strategy for schema protocol and runtime compatibility**

1. Schema versions (`v0`, `v1`, ...) are increased when we introduce a breaking change in the garden schemas. E.g. changing the semantics/type of an existing field or removing deprecated fields.
2. An increment of the schema version should always lead to a new major version of garden or in this case minor until we have done our first major release. The reverse is not necessary though, so we can increase the runtime to 0.14 without bumping the version.
3. The CLI runtime is always backwards compatible with the current schema and one older version. In this case Garden 0.12 is `v0`, then 0.13 would parse and run against `v0` and `v1` and 0.14 would support `v1` and `v2` and so on.

**Possible migration path for users sharing configurations**

1. Mixed environments will be possible with the current (0.12) and next version (0.13) of the runtime. If there is a gap of two larger versions, e.g. 0.12, 0.13 and 0.14, then there is no guarantee that 0.14 will work since 0.14 might not be compatible with the v0 schema.
2. To run in a mixed environment, the users would keep the lower schema version in their configuration. 0.12 is compatible with `apiVersion: garden.io/v0` and 0.13 with `v0` and `v1`. 
3. Users can test 0.13 changes in a separate branch by increasing the apiVersion to `v1`. This will break the 0.12 runtime since it doesnt know about `v1`.
4. Inform all users that they should upgrade their runtime client and set a cut-off date.
5. When the "0.13" branch is merged in, all users will be forced to upgrade since 0.12 will not work with the 0.13 schema version.
6. CI usage and pipelines can be updated to use the 0.13 runtime assuming the apiVersion is set. This can be tested in a separate branch and would not need to impact production usage.

**Discussion**

- We fully rely on 0.13 to be backwards compatible with the `v0` schema currently used by 0.12.
- Even if we are fully backwards compatible, by enforcing the switch from v0 to v1 in the apiVersion, we make it clear for end users when they need to update to 0.13 and a garden admin can enforce it by bumping the version. If some incompatibility is found during the rollout, its possible to decrease the version to v0 to allow for 0.12 usage again.
- We do already have breaking changes when moving to 0.13 (https://docs.garden.io/v/bonsai-release/tutorials/migrating-to-bonsai#breaking-changes-first). This would only be a single line change in the project config and would still allow for mixed environments since 0.12 validates fine with `apiVersion: garden.io/v0`.
- Instead of pushing this change one version into the future (0.14), we can add the same warning in 0.12 as suggested above.
- Pipelines/CI can be conservative and use the 0.12 runtime while developers are upgrading to the 0.13 runtime.

**Comment by mkhq** [comment]
After further discussions with @stefreak @10ko and @TimBeyer, we arrived at a slightly more conservative solution towards users upgrading from 0.12 to 0.13. The proposal above is amended to the following:

- Only make `apiVersion` a mandatory field if the configuration contains the new action kinds introduced in 0.13. If we would force the `apiVersion` field immediately it could happen that some users getting 0.13 from a brew update would end up with a "broken" config.
- Only allow `apiVersion: garden.io/v0` when the config does not contain the new action kinds. This means that as soon as new action kinds are used, the version needs to be changed to `apiVersion: garden.io/v1`. As an outcome, all users on 0.12 that tries to read the config will get an error (fail-stop) since it doesnt recognize `v1`.

As a result of these changes, we will allow for a mixed 0.12 and 0.13 environment until the point where the new action kind configs are introduced. 0.13 is backwards compatible with 0.12 (`v0`) configuration and a user upgrading will be able to take advantage of the improvements in 0.13 from the start without any breaking issues. The owner of the garden project can experiment with the new configuration in a separate branch and roll out when all users are ready.
