### ISSUE TITLE
Update `garden migrate` command

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4125]
Include the following changes into the `migrate` command:
* #3512
* #3069
* Check workflows
* ... ?

**Comment by vvagaytsev** [comment]
@thsig @eysi09 @Orzelius @Walther let's discuss and collect the list of the changes that must be done in the `migrate` command.

**Comment by trymbill** [comment]
Looks like the description of the command also needs to be updated. It mentions `version 0.12` a couple of times, which I'm assuming is just from when it was used for migrating to `0.12`.

**Comment by Orzelius** [comment]
will not be doing as a bit too tricky and questionable value
