### ISSUE TITLE
[FEATURE]: Upgrade to Node 20

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4158]
### Background / Motivation

Node 20 has been released. It is the "current" release and will be upgraded to LTS status later this year.

### What should the user be able to do?

Run `garden` that has been built with the Node version 20.

### Why do they want to do this? What problem does it solve?

This has the potential to directly solve some issues present on older runtime versions.

### Suggested Implementation(s)

Read the release notes of both Node 19 and 20 for breaking changes, and then attempt the upgrade in a branch. Note to also update the necessary base images.

We should probably do this for the `0.13` branch / Bonsai release, as the `0.12` branch and release is already feature-frozen.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
Remember about #4467.
