### ISSUE TITLE
Changed sources not being picked up in `dev` command

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#4167]
## Problem statement

If I:
* start the `dev` command
* run `deploy`
* change sources for one of the deploys
* run `deploy` again

then the changed sources aren't picked up (Garden thinks the builds are up to date).

## Probable cause & suggested fix

We're probably not handling changed sources properly in the FS watcher in Bonsai (when the changed source isn't a Garden config).

Again, this is only relevant for interactive commands.

**Comment by vvagaytsev** [comment]
Fixed in #4169
