### ISSUE TITLE
[FEATURE]: Catch config mismatch for `clusterIP`

### ISSUE THREAD

**Issue by hph** [garden-io/garden#4170]
## Feature Request

Delete and re-create a service when required due to a config mismatch for `clusterIPs`.

cc @eysi09 

### Background / Motivation

While redeploying a `postgres` service to be stateful, I received this error:

```
The Service "postgres" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not
 change once set
```

It would be nice if garden could catch it when a service is deployed with a different configuration for the `clusterIP` if it can't be redeployed, and possibly delete and redeploy the service (at least when not in production).

### What should the user be able to do?

Deploy a service where `clusterIPs` changes without having to manually delete and redeploy.

### Why do they want to do this? What problem does it solve?

Having to manually delete the service and redeploying. The error may be cryptic, and it might not be the first thing that people think of doing.

### Suggested Implementation(s)

The user does not get an error, but may get feedback that the service is re-created.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
Closing this as stale. @hph please feel free to reopen if it's still an issue in 0.13.
