### ISSUE TITLE
The `--tail` and `--since` flags don't work for the `garden logs` command (hi-pri)

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4173]
Like it says in the title, the `--tail` and `--since` flags don't appear to be respected and Garden just dumps all the logs. 

Obviously this breaks the logs command but also the logs viewer in Cloud. 

It also makes it hard to use 0.13 for developing Cloud. 

Because all of the above, I'd argue this is high pri.

**Comment by eysi09** [comment]
I can take this one, overlaps with what I'm currently working on.
