### ISSUE TITLE
MaxListenersExceededWarning when using the Cloud logs viewer

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4186]
Here's the full error:

`(node:23396) MaxListenersExceededWarning: (node) warning: possible EventEmitter memory leak detected. 1001 listeners added. Use emitter.setMaxListeners() to increase limit.`

This happens when running the Garden serve command and connecting via Cloud. 

Might be due to this: https://discord.com/channels/817392104711651328/1102901553544822885

**Comment by vvagaytsev** [comment]
@eysi09 is this still reproducible?

**Comment by eysi09** [comment]
Found the issue and have a repro:

When requesting a command via ws, a bunch of listeners subscribe to the Garden event bus that are never cleaned up. 

So simply by using the Clouds logs viewer or command palette, the subscribers pile up until they eventually exceed the limit. 

So the solution is to figure out a way to unsubscribe the subscribers that got created during the command run for the requested command, but not others, which may still be needed.

**Comment by eysi09** [comment]
Thank @ShankyJS!

And a brief update after some more investigation:

- The `PluginEventBroker` does not unsubscribe from events, this is probably the leading cause of "listener overflow" and needs to be addressed. 
- Commands executed via websocket requests also don't clean up after themselves but the volume is a lot lower and this will most likely resolve itself when we introduce "instance manager". So I don't think we need to worry about that for now. 

Re-assigning to @thsig who's been looking into the former cause.

**Comment by thsig** [comment]
Closed by #4258.
