### ISSUE TITLE
Typing `exit` does not kill the dev command for me

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#4209]
Reported by @eysi09.

"I get the outro messages but then command just hangs until I CTRL+C it."

**Comment by thsig** [comment]
@eysi09 I haven't been able to repro this one, does this happen reliably on your end or only under certain circumstances?

**Comment by eysi09** [comment]
This happens every time. 

I don't see any logs either, even at a silly level. It just hangs like this until I ctrl+c:

<img width="775" alt="Screenshot 2023-05-09 at 12 54 20" src="https://github.com/garden-io/garden/assets/5373776/50e000a0-0bbc-44d8-a170-31c83e162375">

Tested both on Kitty (my main terminal) and the default macOS terminal.

**Comment by thsig** [comment]
Hmm, I see. I haven't been able to reproduce this on my end at all.

**Comment by Orzelius** [comment]
I also fail to reproduce but this pr might fix it for you https://github.com/garden-io/garden/pull/4221

**Comment by eysi09** [comment]
I thought I had fixed this with #4262 but just noticed this again on my end. 

Don't have a reliable repro at the moment but we need to investigate.

**Comment by thsig** [comment]
In the absence of a reliable repro, this should be a decent general-purpose safety measure:

https://github.com/garden-io/garden/pull/4288/commits/767199cc60db997da04a54457b6683b11743c14b

**Comment by vvagaytsev** [comment]
Closing this an non-reproducible. Feel free to reopen if it still happens.
