### ISSUE TITLE
0.13: [Bug]: Changing ingress configuration in a Deploy action from dev mode does not update ingress on fresh `deploy`

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4213]
### Current Behavior

Changing the ingress configuration for a Deploy action inside dev mode doesn’t get picked up: `garden` doesn’t update the service on a new `deploy`. 

E.g. change `/hello` to `/` while `garden dev` is running. Please see Empathy Session doc (restricted to employees of garden.io) for full context starting from 40:00 in.

![image](https://github.com/garden-io/garden/assets/59834693/841706f5-b475-4cf7-8cef-784b4040d32e)

![image](https://github.com/garden-io/garden/assets/59834693/7671eb7f-56d1-46b6-bea8-9bce3a73471f)

### Expected behavior

Dev mode should automatically update the ingress.

### Reproducible example

https://github.com/shumailxyz/nestjs-typeorm-auth-starter/tree/gardenify

### Workaround

To work around, @shumailxyz  killed `garden dev` then ran `garden deploy`.

### Your environment

* **OS:** macOS Ventura
* **How I'm running Kubernetes:** Docker Desktop

`garden version` Bonsai latest as of May the 8th.

**Comment by vvagaytsev** [comment]
Also, changing the ingress in the `backend.garden.yml` requires the deployment of a new Resource to the kubernetes cluster.

AFAIK, we remove the old watching mode in `0.13`. So now we do not rebuild and redeploy the project on the local FS changes.

**Comment by vvagaytsev** [comment]
Sorry, pls ignore my previous (deleted) comments. I think I've misread the description. Need to watch video to grab the full context.

**Comment by worldofgeese** [comment]
If users are expecting different behavior, is there an argument to be made to change the behavior? As a user, I'd expect ingress to update on a new `deploy`.

**Comment by Orzelius** [comment]
closed via https://github.com/garden-io/garden/pull/4256
