### ISSUE TITLE
0.13: [Feature]: Make new dashboard more discoverable

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4214]
### Current Behavior

0.12's dashboard has been deprecated such that it is no longer obvious that

- a dashboard exists
- how the dashboard is accessible

We encountered this in two empathy sessions with @shumailxyz and @Lagoja.

The old docs specify `garden deploy --dev` as the go-to command for new users. If users  continue to use `garden deploy --dev` in Bonsai, reference to an available dashboard has been omitted. Users must use the new `garden dev` command to see a message alerting them to old dashboard's deprecation.

![image](https://github.com/garden-io/garden/assets/59834693/ae9e2b70-3054-494e-987b-1f900744d3e2)

The message isn't very obvious and easy to miss. In my GNOME Terminal example using stock colors, the message appears in a de-emphasized brown. Compare this to `Good evening!...` which is bright and bold.

Worse, the message indicates users should log in first but no utility or command is offered.

### Expected behavior

As a user, I'd expect old commands carried over from 0.12 to offer replacement functionality or a redirect. As a brand new user, I'd want more visual emphasis on the Cloud Dashboard and suggest the command used to log in to Garden Cloud Dashboard.

### Suggested solution(s)

1. Brightly colorize the new Dashboard alert.
2. Include new Dashboard alert when using other `garden` commands such as `garden deploy --dev`.
3. Move Dashboard message alert to the top of the message stream.
4. Gutsy: automatically open the web browser pointed to the new Dashboard when a user launches `garden dev` with an option to disable this behavior with e.g. `garden util no-dashboard-auto`.

**Comment by shumailxyz** [comment]
@worldofgeese `garden deploy --dev` and other similar commands should already show the warning to user now as `garden deploy --dev` would first take user to REPL (user sees this warning there) and then run deploy.
