### ISSUE TITLE
Buildkit error "Unable to query registry for image status: Pod has been killed or evicted."

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4216]
### Current Behavior

Getting buildkit error on a healthy buildkit Pod, because it has been killed in the past as a liveness probe failed.

Error:

```Unable to query registry for image status: Pod has been killed or evicted.```

### Expected behavior

Garden should ignore old events in the event history.

### Reproducible example

Hard to reproduce; liveness probe needs to fail.

### Suggested solution(s)

Look at the events before PodRunner executes a command in a Pod, and ignore the old events when looking for a killed event after the command finished (see `throwIfPodKilled` in the `PodRunner`) 

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
A possible solution can be borrowed from #4222, see the [test code](https://github.com/garden-io/garden/pull/4222/files#diff-ed6bde026575909b313be47a2cb89b9094efa6cd60e3ba9d3862be14eb9b12e2R1111-R1114).

**Comment by stefreak** [comment]
Ah great! This looks like it has been fixed by #4222 – was a dupe apparently
