### ISSUE TITLE
Figure out the story for persistent exec services

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#4255]
There's some open questions around running persistent exec services on Bonsai that I'm listing here.

This is a mix of an issue and a discussion. 

1. If I'm using modules, how do I start a persistent local process? 

Previously I would've done this with `garden deploy my-local-svc --dev`. This used to work, Garden would manage the process and stream logs. 

Presumably now it's `garden deploy my-local-svc --sync` which doesn't really make sense naming wise. Also, I don't even know if that works.

To make the naming more intuitive, we could introduce the `--monitor` flag here.

That begs the question though what this looks like if I have two services, one that's remote and has a sync spec and one that's local. Would I need to run `garden deploy --sync --monitor`,  one flag for each?

That's not very nice and we need a flag that captures both (kind of like `--dev` did before). 

2. If I'm using actions, how do I start a persistent local process?

I would've thought it would be the same but @thsig thought differently, in any case we need to need clarify. 

3. How do I start it from within the dev command. 

Presumably it's the same, just want to flag and make sure it works as expected.

**Comment by thsig** [comment]
Thanks for writing this up!

I'm going to close this one, but answer each of the questions you posed in turn.

> 1. If I'm using modules, how do I start a persistent local process?

You deploy with `--sync my-exec-service-name`. That deploys the service with `persistent: true`, and uses `devMode.command`/ `devMode.statusCommand` as the `deployCommand` / `statusCommand` of the generated Deploy.

Why does this work? If you use `devMode.command` / `devMode.statusCommand` in an `exec` Module's service config, it will get converted into a template conditional, where `this.mode` for the converted Deploy action is used to set `persistent`, `command` and `statusCommand`.

Here's the relevant snippet from the source code: https://github.com/garden-io/garden/blob/bcb6f11de6d9166d256408a426a065c3c6a3ebb5/core/src/plugins/exec/convert.ts#L76-L94

I do think this is a little awkward, but it's sort of the best we can do for the conversion. The story for new-style `exec` Deploys (i.e. written as action configs, not converted from modules) is more straightforward.

> 2. If I'm using actions, how do I start a persistent local process?
> 3. How do I start it from within the dev command.

You configure the `exec` Deploy to have `persistent: true`, and run `garden deploy`. I.e. there's no sync mode for `exec` deploys—just `persistent: true | false` to indicate whether it should keep running in the background after the Garden command terminates.
