### ISSUE TITLE
0.13 update for `using-garden/workflows.md` guide

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4292]
See [using-garden/workflows.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/workflows.md)

**Comment by vvagaytsev** [comment]
@stefreak @twelvemo could help with updating the workflow guides, please?

**Comment by twelvemo** [comment]
On it!

**Comment by vvagaytsev** [comment]
Done in #4310
