### ISSUE TITLE
[FEATURE]: Show a shortlink for cloud project URL instead of long links

### ISSUE THREAD

**Issue by shumailxyz** [garden-io/garden#4295]
## Feature Request
When a user connects to cloud using `garden login`, the cloud project link that's provided to user is quite long at the moment and doesn't fit the cli aesthetics. Currently the link looks like this

```
https://app.garden.io/projects/4fc1331d-7742-43a4-9f16-acf90481c68a?sessionId=4fc1331d-7742-43a4-9f16-acf90481c68a&userId=4fc1331d-7742-43a4-9f16-acf90481c68a
```

Would be great aesthetically if a shortlink is provided instead of massive url.

### Background / Motivation

The massive url doesn't look nice, and goes on multiple lines on small window cli atm. A shortlink instead could be much smaller and would fit better aesthetically.

### Suggested Implementation(s)

Once session is registered to cloud, core should receive a short link in response from cloud that it shows to the user. The short link could look like: 

```
https://app.garden.io/go/9w5j
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by Orzelius** [comment]
completed

**Comment by Orzelius** [comment]
or actually I'm not sure

**Comment by shumailxyz** [comment]
Not done atm. The shortlink was only for bonsai issues report.
