### ISSUE TITLE
Sync events being logged when nothing is happening

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#4348]
Reported by @eysi09:
> AFAICT there's nothing that should be triggering sync events but Garden still logs the events at an interval of a few seconds.

![Image](https://user-images.githubusercontent.com/5373776/239770197-b1a62336-3272-4a78-a216-1fea786aa468.png)

> Assigning to @thsig because you have some context here, but feel free to re-assign.

**Comment by thsig** [comment]
I've been poking at this a bit, and I'm only getting these log lines after I change files (and a sync takes place).

That said, we could totally consider lowering the verbosity / frequency of these log lines. However, users may prefer to get this visual post-sync confirmation even if it's rather versbose.

One variable to consider here: Was your editor or one of the dev tools you were using performing periodic autosaves on a sync source in the background? If so, then that would explain this.

**Comment by vvagaytsev** [comment]
Closing as non-reproducible.
