### ISSUE TITLE
Fine grained control over when and how tests run

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#438]
From the FAQ:

> In `garden dev` mode, all tests for a given service are run when a file watch event is triggered. To disable these you'd have to comment them out from the `garden.yml` file.

> More fine grained control over when and how tests run could be a feature for the future.

**Comment by eysi09** [comment]
This has been somewhat remedied by the `--skip-tests` and `--test-names` flags. There's also a #1163 which addresses this for both tests and tasks.
