### ISSUE TITLE
feat: allow garden deploy skip-dependencies without specifying a deploy action

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#4417]
For larger stacks with many deploys that depend on each other it doesn't always make sense to wait for each deploy to be complete before moving on to the next one in the dependency tree.

For test environments just deploying the most vital infra and then all of the Deploys at once will most likely suffice. All garden has to do is wait for all the deploys to be ready and them mark the command complete. Of course this means the Deploys have to be configured in a way where they don't go into crashloop if a dependency is not yet up.

Deploys with output dependencies will of course have to wait, but most of these are infra related anyways.

This would greatly increase the startup times of environments that get deployed from the zero point but has the downside of making the api more confusing and people misusing the feature for production.

**Comment by mtdoughty** [comment]
Thank you for starting this discussion.   Having a soft dependencies option would be really useful.

Where you say: 

> All garden has to do is wait for all the deploys to be ready and them mark the command complete. Of course this means the Deploys have to be configured in a way where they don't go into crashloop if a dependency is not yet up.

It would be good to clarify this.   If there is a dependency still missing most of our services will sit there waiting for it to become available.    It wouldn't pass health checks though until those dependencies are available (so wouldn't be shown as "ready" until then).    If it took long enough for the dependencies to become available they might eventually get killed and crashloop.    Is there a reason why your calling that out as something we couldn't let happen?

**Comment by Orzelius** [comment]
>  It wouldn't pass health checks though until those dependencies are available

That seems like a slightly unusual way to set up probes. Usually liveness probes are configured such that they reflect the status of the service at hand and do not depend on the surrounding services. With your configuration it sounds like the entire stack would drop only if one dependency is not functioning which I imagine is not the desired behavior.

**Comment by mtdoughty** [comment]
> That seems like a slightly unusual way to set up probes. Usually liveness probes are configured such that they reflect the status of the service at hand and do not depend on the surrounding services. With your configuration it sounds like the entire stack would drop only if one dependency is not functioning which I imagine is not the desired behavior.

This is more about the startup behaviour though.   Several of our services would require the database  or rabbitmq to be available to startup for example. 

Either way if garden could deploy the whole lot concurrently, wait until all services are ready and when deploy and test containers it would dramatically speed up our pipelines.

**Comment by Orzelius** [comment]
#4735 will allow to use the `--skip-dependencies` flag with all actions.

You can then set up your test suite something like this:
1. Build everything
2. deploy your infra
3. run the needed runs/tasks
4. Deploy services that everything else depends on
5. Deploy everything else via `--skip-dependencies`
6. (optional) use a run that tests if your stack is functional. Kinda like an e2e readiness probe. Usually it's some kind of request that triggers the use of most services in a project and if completed successfully it means the project should be ready for further testing.
7. run tests
