### ISSUE TITLE
Generate provider reference docs automatically

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#442]
## Feature Request

We currently don't generate docs for `providers` in our `garden.yml` configs currently the only reference for configuration options are exposed via our example projects and in the source code.

We should expose them on https://docs.garden.io/reference/config

**Comment by edvald** [comment]
I had started work on this, been wanting to do this for a while. I'll take it on.

**Comment by eysi09** [comment]
Did you guys have a specific design in mind?

My idea was to put each provider in it's own file, like: `https://docs.garden.io/reference/config/kubernetes`, and use markdown along with the YAML so that we can link to individual keys.

**Comment by drubin** [comment]
I would suggest explicitly add a path of `providers` / `plugins` 

`https://docs.garden.io/reference/config/providers/kubernetes` maybe? Yes really like that idea of markdown and the YAML.

**Comment by drubin** [comment]
I just wanted to explicitly show they are configured on the provider under the project level vs in each module.

**Comment by eysi09** [comment]
Yes, makes sense.

**Comment by eysi09** [comment]
I removed the milestone since this is independent of the 0.9 release.
