### ISSUE TITLE
chore: investigate new binary packaging options

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4428]
Currently, we use vercel's `pkg` tool https://github.com/vercel/pkg/
- It does not currently support Node 20, the latest version of Node.
- It also does not support ES modules.
- We have also had various other issues with it.

We should experiment with some alternatives:
- https://github.com/leafac/caxa
- https://nodejs.org/dist/latest-v20.x/docs/api/single-executable-applications.html
- others?

This is a blocker on 
- https://github.com/garden-io/garden/issues/4158
- https://github.com/garden-io/garden/issues/3841

**Comment by stefreak** [comment]
Fixed with #5233 

We now implemented [garden-sea](https://github.com/garden-io/garden/tree/main/garden-sea)

**Comment by Walther** [comment]
Fantastic work, love to see it ❤️ 🎉
