### ISSUE TITLE
[FEATURE]: Allow installing arbitrary versions of Terraform

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4429]
### Background / Motivation

Now we maintain a hard-coded set of supported versions of Terraform (and of the other tools).
Every time we need to add a new version we have to do some routine changes to the code, basically because of the binary checksums.

### What should the user be able to do?

The user should be able to use an arbitrary version of Terraform in the provider configuration.

### Why do they want to do this? What problem does it solve?

It improves the user experience and simplifies Garden development and maintenance.

### Suggested Implementation(s)

Automate the binary checksum verification process. See:
* https://www.greenreedtech.com/hashicorp-terraform-checksum-verification/
* https://developer.hashicorp.com/terraform/tutorials/cli/verify-archive

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by stefreak** [comment]
When working on this, finishing up #4381 as well (or integrating it to the changes) would be good, as we currently run terraform tests with a very old version. What we should do is run the terraform plugin tests with multiple versions of terraform, some older and some more recent, and amend the tests every time terraform has breaking changes with garden.

**Comment by stefreak** [comment]
This library looks like it provides the functionality that is needed to implement this: https://www.npmjs.com/package//openpgp#sign-and-verify-cleartext-messages
