### ISSUE TITLE
[FEATURE]: Add GCP provider so developer logged in can be tied to their GCP account

### ISSUE THREAD

**Issue by jonsjava** [garden-io/garden#4437]
## Feature Request

Right now, we use the local username to define our sub-domain and K8S namespace.  This works until it doesn't, with users that have names that in no way tie back to a person that we are aware of.

I would like to be able to call a provider to populate the user in a fashion that is similar to the output of this command:

```bash
gcloud config list account --format "value(core.account)"|head -1
```

which returns the e-mail address logged in.  Using this, I can easily strip out the `@` and domain, leaving a user I can easily track back to a user in GCP

### Background / Motivation

Looking through namespaces trying to figure out who some of them were, this became a major issue, with multiple developers with names that didn't align to anything related to their name or GCP login.

### What should the user be able to do?

we would be able to call the provider to receive outputs like this:

```yaml
user-name: ${providers[gcp].outputs.username}
user-email: ${providers[gcp].outputs.email}
```

### Why do they want to do this? What problem does it solve?

This feature would ensure that our namespaces, sub-domains, and other resources that are keyed off a given user can easily be tied to the user, rather than relying on local values that may not be tied to any meaningful data.

### Suggested Implementation(s)

See example above

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by stefreak** [comment]
Can also be solved by implementing a more general solution like #3998

**Comment by Orzelius** [comment]
Hello, exec provider has been blessed with initscript outputs so you can use it run any script you need for authentication. We will be closing this for now, but a cloud provider specific provider is still on the board as there are plenty other use cases for it.

Thank you for bringing attention to this!
