### ISSUE TITLE
[FEATURE]: Add outputs to exec provider initScript

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4440]
### What should the user be able to do?

Using the `exec` provider's `initScript`, users can run scripts at initialization time. Users should also be able to use the results of those init scripts for other actions, via output variables

### Why do they want to do this? What problem does it solve?

Can be used to solve e.g. this issue https://github.com/garden-io/garden/issues/4437

### Suggested Implementation(s)

Add `outputs` for the `initScript` on `exec` provider

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by twelvemo** [comment]
I have often wished for this too!

**Comment by stefreak** [comment]
👍 Yes I think this would be big

I already created an issue for this in the past: #3998 

@Walther Shall we close one of them?

**Comment by Walther** [comment]
Closing as a duplicate of https://github.com/garden-io/garden/issues/3998
