### ISSUE TITLE
log.getChildLogEntries() does not return child log entries

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4457]
Bug report for `garden` internals, not directly user-facing but could affect some log-related behaviors externally too.

On the `log` class, the `getChildLogEntries()` method only returns `this.entries`, which contains the entries of the current log instance only:
https://github.com/garden-io/garden/blob/08f0ef2681234446110dce85dcd4932d2405119a/core/src/logger/log-entry.ts#L404-L406

In order to actually get entries from possible child logs, you need to use `getAllLogEntries()` which fetches the entries from the `root` log.

Found when working on https://github.com/garden-io/garden/pull/4381, as the provider initialization logs did not appear in `getLogMessages(garden.log)`, because the provider initialization code creates its own sub-log, and the sub-log is not correctly fetched within the `getChildLogEntries()` method called from `getLogMessages()`

**Comment by eysi09** [comment]
This is actually the intended behaviour. 

`getAllLogEntries`,  as the name suggests, gets all log entries for that logger. 

`getChildLogEntries`, gets the entries that belong to that specific log context. I.e., its "child" entries. The nomenclature comes from the time when the logger was a proper graph structure you could traverse. 

I thought the name was clear enough so I intentionally didn't change it, but we can of course do so if this causes confusion. I think we do need to fix that `getLogMessages` function though and have it use `getAllLogEntries()`.

**Comment by Walther** [comment]
Gotcha, thanks!
Would you mind if I do the following:
- make all these relevant edits in the PR https://github.com/garden-io/garden/pull/4381 where these were needed - even if _technically_ this kind of changes could/should be done as a separate PR
- remove the `getRootLogMessages` function I added in that PR to work around the issue
- edit `getLogMessages` to use `getAllLogEntries` instead of `getChildLogEntries`, even if this means various test cases might get more logs back than before
- rename `getChildLogEntries` to `getLogEntries`, as it only gets entries from the current log context you are calling the method on (as there is no graph anymore, and therefore no child logs to fetch messages from)

**Comment by Walther** [comment]
The following changes were made in this PR https://github.com/garden-io/garden/pull/4381
- clarify the docstring on `getLogMessages()` and mention it only gets messages from the given context
- add a separate `getRootLogMessages()` function which gets all log messages via the root log
- rename `getChildLogEntries` to `getLogEntries` and add a docstring describing its behavior, in similar wording as the other functions around it
