### ISSUE TITLE
0.13: [Bug]: `garden login` does not work in VMs

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4459]
### Current Behavior

`garden login` fails to open a browser tab for authentication in headless or VM sessions like Cloud Shell

```console
tao@cloudshell:~/cloudshell_open/quicks
tart-example$ garden login
Login 

Thanks for installing Garden! We work hard to provide you with the best experience we can. We collect some anonymized usage data while you use Garden. If you'd like to know more about what we collect or if you'd like to opt out of telemetry, please read more at https://github.com/garden-io/garden/tree/0.13.0/docs/misc/telemetry.md
Logging in to https://app.garden.io...
/snapshot/project/tmp/pkg/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'https://app.garden.io/clilogin/39687' ]
}

Node.js v18.1.0
```

### Expected behavior

`garden login` should provide an alternative URL in the example of  `gcloud auth login` or `gh auth login`, that the user can copy and paste to their own web browser tab for authentication. 

### Reproducible example

[![Open in Cloud Shell](https://gstatic.com/cloudssh/images/open-btn.svg)](https://shell.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fgarden-io%2Fquickstart-example.git&cloudshell_git_branch=feature%2Fce-33%2Fcloudshell-quickstart&cloudshell_open_in_editor=project.garden.yml&cloudshell_tutorial=tutorial.md&show=ide&ephemeral=true)

### Workaround

Use personal access tokens (Can be created in user settings).

Export the personal access token like so, and then subsequent garden commands are logged in:
```
export GARDEN_AUTH_TOKEN=<auth-token-value>
```

### Your environment

Latest production Bonsai.

cc @mkhq @10ko

**Comment by stefreak** [comment]
A workaround is actually available: You can use personal access tokens (see user settings):

<img width="414" alt="Screenshot 2023-05-26 at 16 01 46" src="https://github.com/garden-io/garden/assets/139624/d1773463-6874-4c66-9db2-6a680756c026">

**Comment by worldofgeese** [comment]
> A workaround is actually available: You can use personal access tokens (see user settings). @worldofgeese I edited the issue above to reflect that.

Oh, that's great and does allow us to add the optional Dashboard login step back into the Cloud Shell tutorial 😀. Thank you!

**Comment by vvagaytsev** [comment]
We recommend to use the current workaround. Feel free to reopen this as soon as we have different auth methods that can help. For now it's not possible to implement this.
