### ISSUE TITLE
0.13: [Bug]: Helm module: fails when version is not set

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4461]
## Garden Bonsai (0.13) Bug

Module conversion breaks with helm modules, when `version` is not defined (It's not required).

### Current Behavior

In 0.13.0:
```
$ garden deploy
[...]
✖ deploy.mailhog       → Failed processing resolve Deploy type=helm name=mailhog (from module mailhog) (took 0.04 sec). Here is the output:

────────────────────────────────────────────────────────────────────────────────
Error validating spec for Deploy type=helm name=mailhog (from module mailhog): "name" must be specified with "version". Available keys: namespace, portForwards, releaseName, timeout, values, valueFiles, atomic, chart, defaultTarget, sync, localMode)
────────────────────────────────────────────────────────────────────────────────
1 deploy action(s) failed!
```

In 0.12.56:
```
$ garden deploy
[...]
✔ deploy.mailhog       → Done (took 5.8 sec)
[...]
```

### Expected behavior

As it was not mentioned as a breaking change in the changelog, I expect it to succeed in 0.13.0 as it does in 0.12.56:
```
$ garden deploy
[...]
✔ deploy.mailhog       → Done (took 5.8 sec)
[...]
```

### Reproducible example

```
kind: Project
apiVersion: garden.io/v0
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes

---

kind: Module
description: mailhog service
type: helm
name: mailhog
repo: https://codecentric.github.io/helm-charts
chart: mailhog
```

### Workaround

1. As a workaround, you can specify a specific version in the module definition, for example

```
version: 5.2.3
```

2. Alternatively, you can keep using Garden 0.12

### Suggested solution(s)

Not familiar with the code, but as helm installation succeds without version in 0.12 I don't see a reason for breaking the behaviour in 0.13– or am I missing something?

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** Docker desktop

`garden version` 0.13.0

**Comment by Walther** [comment]
The issue is originating from here: https://github.com/garden-io/garden/blob/60b60872874d8675f0a43e3417dafad35c5dccc7/core/src/plugins/kubernetes/helm/config.ts#L156C23-L166

The text description makes it sound like this is an intentional requirement. However, as noted above, this is a breaking change.

Which way do we want to fix this:
- make `version` optional even if `name` is specified, keeping backwards compatibility
- keep the breaking change, add mentions of this to the breaking change lists and migration guides

**Comment by stefreak** [comment]
Adding the bug label as well, until we are sure wether this is a bug or intentional change.

**Comment by edvald** [comment]
I don't believe this is intentional, we should fix it.
