### ISSUE TITLE
Confusing log line about garden cloud on exit

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#4481]
I noticed that we run the through the Garden Cloud init logic on exit. See:

![Image](https://user-images.githubusercontent.com/5373776/239770477-07d51223-38b4-4bf5-8b01-7dba71d8f4a4.png)

This was caused by the `quit` (`exit`) command.

Probably also related to: https://github.com/garden-io/garden/issues/4435

**Comment by vvagaytsev** [comment]
Closing in favor of #4435.
