### ISSUE TITLE
0.13: [Bug]: All commands fail inside `garden dev` when `terraform` provider enabled

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4529]
### Current Behavior

In the release version of Garden Bonsai, all commands fail inside `garden dev` when the `terraform` provider is enabled. 

### Expected behavior

Commands should run fungibly between the dev console and imperative. 

### Reproducible example

https://github.com/worldofgeese/fastapi-mongodb-garden-example/blob/main/garden.yml

### Workaround

Use the imperative forms of Garden commands.

### Additional context

Interestingly, if the latest `edge-bonsai` release is updated to or installed, Garden will produce a new and different error:

```console
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ Running validate... ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
ℹ providers            → Getting status...


Configured provider 'terraform' has not been registered.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

────────────────────────────────────────────────────────── 🌼 🌸 🌷 🌺 🌻  ──────────────────────────────────────────────────────────
```

However, an imperative form of the same command continues to function correctly.

```console
❯ garden validate --force-refresh
Validate 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment default.default
ℹ providers            → Getting status...
✔ providers            → Done (took 3.5 sec)
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 1.8 sec)
ℹ deploy.my-terraform  → Running plan...
```

Deleting the `.garden` directory does not change behavior.

### Your environment

* **OS:** Clear Linux
* **How I'm running Kubernetes:** minikube

`garden version` 0.13.0-edge-bonsai-e0f0238ab and 0.13.0

**Comment by worldofgeese** [comment]
[2023-06-04_18-27-04.webm](https://github.com/garden-io/garden/assets/59834693/4bf471cd-4c09-40e5-a20e-c8c2c9c856fc)

**Comment by worldofgeese** [comment]
Experiments recorded at https://clipchamp.com/watch/HtesT8wotbw

**Comment by Walther** [comment]
Potentially related to https://github.com/garden-io/garden/pull/4526 ?

**Comment by worldofgeese** [comment]
@Walther this is still a problem after #4526 was merged and released in 13.1: I'm getting `Configured provider 'terraform' has not been registered.`

**Comment by Orzelius** [comment]
@worldofgeese could I have access to the repro repo please

**Comment by worldofgeese** [comment]
@Orzelius wasn't intended to be private! Have made public now.
