### ISSUE TITLE
Hot reload stopped working

### ISSUE THREAD

**Issue by fabianboerner** [garden-io/garden#4540]
### Current Behavior

Filewatcher does not start to sync changes

### Reproducible example
Even with minimal setup it stopped working for me
https://github.com/fabianboerner/garden-hotreload

### Your environment

* **OS:** Ubuntu 20.04
* **How I'm running Kubernetes:** Digitalocan

`garden version` 0.12.56

**Comment by fabianboerner** [comment]
Seems related that to much files are watched.

**Comment by Orzelius** [comment]
@fabianboerner Hello, thank you for submitting the issue.

The hot-reload functionality is deprecated in 0.12 and has been completely dropped in Bonsai (0.13).

Please use the newer, faster and vastly superior sync mode instead
* [0.12 documentation (was called dev mode)](https://docs.garden.io/v/acorn-0.12/guides/code-synchronization-dev-mode)
* [Bonsai documentation](https://docs.garden.io/guides/code-synchronization)

Is it alright that we close this as we're no longer maintaining hot reload as of 0.13?

**Comment by vvagaytsev** [comment]
Closing this as stale. Feel free to reopen if it's still an issue in 0.13.
