### ISSUE TITLE
[FEATURE]: Kubernetes deploy does should wait for kubernetes jobs

### ISSUE THREAD

**Issue by pepov** [garden-io/garden#4557]
### Current Behavior

Garden deploy does not wait for kubernetes jobs defined in a kubernetes deploy action.

### Expected behavior

I would expect that garden would wait for long running jobs (ideally could would be configurable to wait or not) and also fail the whole deploy if the job fails. 

### Reproducible example

There is a reproducible example for `0.13.1` (`master` branch) and `0.12.57` (`0.12` branch):
https://github.com/pepov/garden-wait

Note: I've used my [asdf plugin](https://github.com/pepov/asdf-garden) to install the correct version of garden

Run `garden deploy` from the repo root on a local kubernetes cluster and check kubernetes pods after garden deploy finished: one of those should be running, the other should have failed.

### Workaround

I'm adding local exec actions to wait for completion, see: https://github.com/pepov/kcp-playground/blob/main/modules.garden.yml#L103-L117

### Suggested solution(s)

According to the garden source code, the way helm implements this should be the example to follow and I agree:
https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/status/status.ts#L70
https://github.com/helm/helm/blob/main/pkg/kube/ready.go#LL225C7-L225C7

### Your environment

* **OS:** Mac OS Ventura 13.4
* **How I'm running Kubernetes:** `minikube start`

```
> garden deploy
Deploy 🚀

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment default.default
ℹ cloud-dashboard      → 🌸  Connected to Cloud Dashboard. View logs and command results at:

https://app.garden.io/projects/8b43eb2d-e347-420f-8777-0c563a3c4d82?sessionId=20c8d28e-553f-44a2-b446-9cd6c46906c6&userId=72cd8adc-fd35-4651-9d9e-1a2b6e15479a

ℹ providers            → Getting status...
✔ providers            → Cached (took 3.6 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.1 sec)
ℹ deploy.job-long      → missing
ℹ deploy.job-long      → Deploying version v-ec2bc758d7...
ℹ deploy.job-wrong     → missing
ℹ deploy.job-wrong     → Deploying version v-493f14fe03...
ℹ deploy.job-wrong     → Waiting for resources to be ready...
ℹ deploy.job-long      → Waiting for resources to be ready...
ℹ deploy.job-wrong     → Resources ready
ℹ deploy.job-long      → Resources ready
✔ deploy.job-wrong     → Done (took 2.6 sec)
✔ deploy.job-long      → Done (took 2.6 sec)

Done! ✔️

> kgp
NAME          READY   STATUS              RESTARTS     AGE
long-d9sl8    1/1     Running             0            9s
wrong-77v2l   0/1     RunContainerError   0 (7s ago)   9s
```

**Comment by Orzelius** [comment]
@pepov Thank you for reporting this. As it's a relatively easy fix and will be valuable to many users we'll try to prioritize it and maybe have it done on the coming weeks.

**Comment by shumailxyz** [comment]
This is not a bug per se as `jobs` are not managed by garden. A job can create one more more pods and continue to retry execution of the Pods until a specified number of them successfully terminate or the desired number of pods can't be started after specified retries. 

Making garden wait for the completion of jobs doesn't seem ideal as the nature of job could range from short-lived, parallel, or sequential batch tasks within the cluster to tasks like background data processing etc. 

I would argue that if you need to wait for a deploy in your pipeline, `job` isn't the right resource and shouldn't be used. `exec` or `pod` would be more suitable.

Further discussion on discord: 

https://discord.com/channels/817392104711651328/1118148475788472403/1118148481392050186
