### ISSUE TITLE
edge-acorn is not displayed in the list of available versions displayed when running self-update

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4563]
### Current Behavior

We allow users to install `edge-acorn` and `edge-bonsai` through the `self-update` command.
I tried to install the `acorn-edge` by mistake and the `edge-acorn` version wasn't listed in the suggestions. See screenshot below:

![Screenshot 2023-06-07 at 17 21 15](https://github.com/garden-io/garden/assets/2706375/4faf8b41-371b-4cd5-aa2c-ed6a8d644e27)

### Expected behavior

Both `edge-acorn` and `edge-bosnai` should be displayed in the list of available versions.

### Reproducible example

Just run: `garden self-update not-existing-version`.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by vvagaytsev** [comment]
@10ko that version name should be `edge-acorn`, not `acorn-edge`. I've just tried it and it worked fine.
The list of the latest available versions must be corrected, I'll file a PR today.

**Comment by vvagaytsev** [comment]
I my bad, missed that detail in the description, sorry :)
