### ISSUE TITLE
Process memory threshold reached is seen when bring up the garden env

### ISSUE THREAD

**Issue by guomimm** [garden-io/garden#4566]
### Additional context

Running tests
 
Using environment default.remote
 
ℹ Detected WfGarden Vars, Configuring...
ℹ providers                 → Getting status...
Updating annotations and labels on namespace ephemeral-bk-9eb1b26137a9a047
Updating annotations and labels on namespace garden-system
✔ providers                 → Getting status... → Done
Updating annotations and labels on namespace garden-system
 
Process memory threshold reached. This most likely means there are too many files in the project, and that you need to exclude large dependency directories. Please see https://docs.garden.io/using-garden/configuration-overview#including-excluding-files-and-directories for information on how to do that.
 
If this keeps occurring after configuring exclusions, please file an issue at https://github.com/garden-io/garden/issues.

### Your environment

* **OS:** 
* **How I'm running Kubernetes: GKE

`garden version`
 garden version
0.12.31

**Comment by guomimm** [comment]
Please let me know what is the maximum of the file count of one garden env.

**Comment by stefreak** [comment]
@guomimm did you try updating Garden to the latest versions 0.12.57 or 0.13.1, and does the error keep occuring there?

**Comment by vvagaytsev** [comment]
Closing this as stale.
