### ISSUE TITLE
Bug: --major flag in self-update command does not have an effect

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4570]
### Current Behavior

```
% garden self-update --major
Update Garden 🗞️

Checking for target and latest versions...
Installation directory: /opt/homebrew/Cellar/garden-cli/0.12.53/libexec
Current Garden version: 0.12.58
Target Garden version to be installed: 0.12.58
Latest release version: 0.12.58

The desired version and the current version are the same. Nothing to do. Specify --force if you'd like to re-install the same version.
```

### Expected behavior

I expect that the 0.13.1 (latest stable release) is installed.

### Reproducible example

Just run `garden self-update --major` with 0.12 versions currently installed

### Workaround

Specify the exact version number, e.g.

```
% garden self-update 0.13.1
Update Garden 🗞️

Checking for target and latest versions...
Installation directory: /opt/homebrew/Cellar/garden-cli/0.12.53/libexec
Current Garden version: 0.12.58
Target Garden version to be installed: 0.13.1
Latest release version: 0.12.58

Downloading version 0.13.1 from https://download.garden.io/core/0.13.1/garden-0.13.1-macos-amd64.tar.gz...
Backing up prior installation to /opt/homebrew/Cellar/garden-cli/0.12.53/libexec/.backup/0.12.58...
Extracting to installation directory /opt/homebrew/Cellar/garden-cli/0.12.53/libexec...

Done!
```

### Suggested solution(s)

–

### Additional context

–

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker desktop

`garden version` 0.12.58

**Comment by stefreak** [comment]
@vvagaytsev I saw you made changes to self-update recently – does this also happen for you?

**Comment by vvagaytsev** [comment]
@stefreak those changes were related to other issues. For this one there is another PR that you have already approved :) Sorry about the late reply here)
