### ISSUE TITLE
Bug: Incompatiblity of latest Helm version update in 0.12.57 and the AWS CLI version we ship in 0.12

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4571]
## Bug

There seems to be an incompatibility with the latest Helm version and the AWS CLI version we ship in the workflow-runner image. (See also https://github.com/helm/helm/issues/10975)

### Current Behavior

When using the 0.12 garden container images starting with 0.12.57 together with AWS  you get the error `Error: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "[client.authentication.k8s.io/v1alpha1](http://client.authentication.k8s.io/v1alpha1)"`

### Expected behavior

No error, it should work

### Reproducible example

We can reproduce this internally

### Workaround

Not really available for users; They can't easily upgrade the AWS CLI to v2 within the container, and they can't choose the helm version in Garden 

### Suggested solution(s)

Either we downgrade helm in 0.12 to 3.8 or we update the AWS CLI. I feel like preferring the latter even though it also has the potential to be breaking for some users. But the list of breaking changes in AWS CLI v1=>v2 is very small and we did not have trouble with it internally at all.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** AWS EKS

`garden version` 0.12.57

**Comment by vvagaytsev** [comment]
Fixed via #4574

**Comment by vvagaytsev** [comment]
Fixed via #4574
