### ISSUE TITLE
[FEATURE]: 0.12: Also support config fields like `scan` and `gitIgnoreFile` that have been renamed in 0.13 in latest 0.12 version

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4572]
## Feature Request

For use cases where 0.12 and 0.13 versions are mixed for a while, or I need to go revert to 0.12 because of an issue, it would be nice if the config fields that have been renamed in 0.13 can be supported in 0.12 as well.

### Background / Motivation

Make it easier to use 0.12 and 0.13 at the same time (for reverting when hitting a bug, testing it with parts of the team, etc)

### What should the user be able to do?

Use the config field `scan` instead of `modules` also in 0.12, and use `gitIgnoreFile` instead of `gitIgnroeFiles` in 0.12 as well.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
It's nice to have, but we don't have the resources to address it soon. Closing this as not planned.
