### ISSUE TITLE
0.13: [Bug]: helm chart base not resolved from modules

### ISSUE THREAD

**Issue by to266** [garden-io/garden#4580]
### Current Behavior

When a `helm` module has the [`base`](https://docs.garden.io/reference/module-types/helm#base) keyword to reference another module, the templates are not resolved with 0.13, thus deploying a completely empty helm release.

### Expected behavior

Backwards-compatibility with 0.12

### Your environment

* **OS:** any
* **How I'm running Kubernetes:** AKS

`garden version` 0.13.13

**Comment by Orzelius** [comment]
@to266 Thank you for reporting this. Definitely a miss on our part in the module conversion logic. We'll fix it shortly.

**Comment by to266** [comment]
@Orzelius Sorry for taking so long checking this out again - but the PR did not fix this. With 0.13.13 I still get a helm deployment without any manifests
