### ISSUE TITLE
Docs: rework terraform and pulumi plugin docs

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#4581]
* The example given in the https://github.com/garden-io/garden/blob/main/docs/terraform-plugin/configure-deploy-actions.md doc is plain wrong
* move [terraform-plugin](https://github.com/garden-io/garden/tree/main/docs/terraform-plugin) and [pulumi-plugin](https://github.com/garden-io/garden/tree/main/docs/pulumi-plugin) dirs to [other-plugins](https://github.com/garden-io/garden/tree/main/docs/other-plugins)
  * fix links from the move
  * add [redirects](https://github.com/garden-io/garden/blob/main/.gitbook.yaml#L7) to old old paths
* move doc [tf action reference](https://github.com/garden-io/garden/blob/main/docs/reference/action-types/Deploy/terraform.md) and [pulumi action reference](https://github.com/garden-io/garden/blob/main/docs/reference/action-types/Deploy/pulumi.md) to the guides. In the action reference link to the guide.
* I personally think the docs should be a single file/page, but I'm open to other opinions

**Comment by 10ko** [comment]
We reworked the docs and separated the two providers into their own sections.
