### ISSUE TITLE
Bug: Cloud shell link in the README leads to clone error

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4587]
### Current Behavior

When I click on the cloud shell link in the README.md (https://go.garden.io/cloudshell) I receive an error from Google Cloud shell:

```
2023/06/09 14:32:20 Cloning https://github.com/garden-io/quickstart-example.git into /home/steffen/cloudshell_open/quickstart-example
Cloning into '/home/steffen/cloudshell_open/quickstart-example'...
fatal: Remote branch feature/ce-33/cloudshell-quickstart not found in upstream origin
2023/06/09 14:32:21 failed to resolve path '/home/steffen/cloudshell_open/quickstart-example': No such file or directory
Error occured
```

### Expected behavior

No error

### Reproducible example

Click on https://go.garden.io/cloudshell

### Workaround

Maybe cloning the main branch into the directory? didn't try that

### Suggested solution(s)

–
### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** GKE

`garden version`

**Comment by stefreak** [comment]
@worldofgeese @ShankyJS does this happen for you too? Do you know how to fix that?

**Comment by worldofgeese** [comment]
@stefreak, this has been fixed: the link previously pointed to a deleted branch. Thanks for reporting!
