### ISSUE TITLE
Killercoda environment starts with an old Garden version

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4588]
### Current Behavior

1. Start the killercoda environment at https://killercoda.com/garden-io/scenario/getting-started
2. Run garden --version 
Output:
```
0.13.0
```

### Expected behavior

At the time of writing I would expect Garden `0.13.2` which is the latest version. Can we make sure to install the latest version in every new killercoda environment?

### Reproducible example

Start the killercoda environment at https://killercoda.com/garden-io/scenario/getting-started

### Workaround

Run `garden self-update`

### Suggested solution(s)

Auto-update Garden on startup of the environment

### Your environment

* **OS:** Linux
* **How I'm running Kubernetes:** Killercoda

`garden version`

**Comment by stefreak** [comment]
@worldofgeese @ShankyJS just noticed this, but I have no idea where I could start to fix it

**Comment by shumailxyz** [comment]
@stefreak I think it's defined here: https://github.com/garden-io/garden-interactive-environments/blob/main/getting-started/background-ubuntu.sh#L7

Should be updated to use latest version.

**Comment by stefreak** [comment]
Reopening because the change has been undone & it is hardcoded now to the currently latest version.

**Comment by ShankyJS** [comment]
Going to work on this this week @stefreak

**Comment by ShankyJS** [comment]
Hey @stefreak fixed this by implementing these two lines to my script:

````
https://github.com/garden-io/garden-interactive-environments/blob/c8300bb4bd6630e24112a5991ee31a27ab039155/getting-started/background-ubuntu.sh#L7-L8C2
````
