### ISSUE TITLE
Create a new example / documentation for type: kubernetes actions

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4593]
Create an example / docs for using a `type: kubernetes` Deploy action with a `type: container` Build action.
This could be useful for bridging the gap for users who need more functionality than the `container` Deploy action can provide alone.

**Comment by Orzelius** [comment]
as the most frequent reason given against the use of kubernetes actions is the fear of boilerplate I think the example should also use action templates

**Comment by shumailxyz** [comment]
Slightly related: there's a similar example here for `helm deploy` with `container build`. Would be good to revisit this as well.

https://docs.garden.io/kubernetes-plugins/action-types/kubernetes#linking-container-builds-and-kubernetes-deploy-actions

**Comment by eysi09** [comment]
Assigning this to myself. Already have a draft PR up for a K8s Deploy action and will also update our existing action template example as well.

**Comment by 10ko** [comment]
We updated the docs to include more specific examples for Kubernetes actions.
