### ISSUE TITLE
[FEATURE]: interactive command to create 0.13 actions

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4598]
## Feature Request

We have `garden create module` but `garden create action` is missing

### Background / Motivation

I'd like to have a simple and quick way to create actions, with help of auto-detect features based on what is in my current directory, similar as `create module` does.

### What should the user be able to do?

Run `garden create action`

### Why do they want to do this? What problem does it solve?

Speed up gardenification. Help guide how to use garden

### Suggested Implementation(s)

e.g. it could be `garden create actions` – and then it suggests action kinds and types based on the directory content. For example, if there is a Dockerfile, it will suggest a container build and a container deploy.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment]
We had an early attempt to implement this in #4124. At some point, we can revisit that closed PR.

**Comment by vvagaytsev** [comment]
Closing this as not planned. [Garden seeds](https://docs.garden.io/garden-seeds/about) can be used instead. That project is under active development and will cover more and more use-cases soon.
