### ISSUE TITLE
Add support for custom ingress controllers

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#462]
Currently, we automatically install/enable nginx when using the `local-kubernetes` provider (the `kubernetes` provider does not do that).
The provider also implements support for `container` modules with the assumption of nginx as the ingress controller.

We need to make which ingress controller is installed automatically (if any) configurable in the provider config, and make sure nothing assumes the particular nginx controller and cannot be configured otherwise.

**Comment by edvald** [comment]
I'd recommend making an example project that uses Traefik, and using that to validate that the implementation works as expected.

**Comment by eysi09** [comment]
I'll close this one create a new issue for the Traefik example.
