### ISSUE TITLE
[FEATURE]: Allow installing arbitrary versions of Pulumi

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4644]
### Background / Motivation

See #4429.

### What should the user be able to do?

The user should be able to use an arbitrary version of Pulumi in the provider configuration.

### Why do they want to do this? What problem does it solve?

It improves the user experience and simplifies Garden development and maintenance.

### Suggested Implementation(s)

Automate the binary checksum verification process.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
The basic machinery for checksum verification will be introduced in #4429.

**Comment by stefreak** [comment]
This library looks like it provides the functionality that is needed to implement this: https://www.npmjs.com/package//openpgp#sign-and-verify-cleartext-messages
