### ISSUE TITLE
0.13: [Bug]: The `sync status` command still returns the wrong statuses

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#4704]
### Current Behavior

The `sync status` command returns "active" sync statuses after they have been stopped.

As before, this information is displayed in the web dashboard so fixing this high priority. 

### Reproducible example

- Run `garden dev` in your example of choice
- Run `sync start`
- Run `sync stop`
- Run `sync status` and notice how it's still flagged as active.

The syncing does indeed stop, I've verified that. It's just that the status reported is wrong.

### Workaround

None known.

**Comment by vvagaytsev** [comment]
Done via #4720.
