### ISSUE TITLE
0.13: [Bug]: stack graph resolution performance degradation

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#4763]
### Current Behavior

I'm about to upgrade our stack to bonsai.
We are seeing a drastic performance degradation in the module / action resolution step.

On v12, `garden validate` takes ~6 seconds.
On v13, `garden validate` takes ~51 seconds.

At first I was suspecting that the module-to-action conversion takes so much longer, but according to the logs this conversion only takes ~3 seconds.
However, it takes about ~44 seconds to perform the module scanning.
Please do note that the number of `Found xx files` in the logs are the same in v12 and v13.

PS: After further debugging I found out that the `exclude` action / module configuration is extremely slow in v0.13.
After migrating to `.gardenignore` files the performance issue is gone.

### Expected behavior

I'd expect `garden validate` to take <10 seconds.

### Workaround

Use `.gardenignore` files instead of `exclude` in action / module config.

### Additional context

FYI, most of our modules reside in remote sources.

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.61
0.13.6

**Comment by edvald** [comment]
You're definitely running into some sort of a performance bug here. Typically it's quite the opposite when moving over. It might be best if we troubleshoot this over in our discord where you could perhaps send detailed logs with timestamps. Would you mind posting there? Someone on our team (even myself) will then help out. Whatever we find we'll then post back here for posterity.

**Comment by hnicke** [comment]
Great, thank you! discord thread: https://discord.com/channels/817392104711651328/1126473787693604884

**Comment by vvagaytsev** [comment]
@hnicke the fix has been released in [0.13.9](https://github.com/garden-io/garden/releases/tag/0.13.9), please try it out.
