### ISSUE TITLE
Version docs and update Github links to point to the appropriate version tag

### ISSUE THREAD

**Issue by adamdavis40208** [garden-io/garden#479]
https://docs.garden.io/basics/quick-start
## Bug

The quick start doesn't behave correctly. 

### Current Behavior

```
garden get status

Error validating module go-service: key "servicePort" is not allowed at path .services[0][ports][0][servicePort], key .services[0][ports] does not contain 1 required value(s)

See error.log for detailed error message
```

### Expected behavior

I should be able to get through the quick start guide without errors

### Reproducible example

Walk through the quick start guide, at least on mac

### Suggested solution(s)

Automated tests that follow the steps in the quick-start

### Additional context

```
Error Details:
value:
  services:
    - name: go-service
      ports:
        - name: http
          containerPort: 8080
          servicePort: 80
      ingresses:
        - path: /hello-go
          port: http
context: module go-service
error-description: "key \"servicePort\" is not allowed at path \e[4m.services[0][ports][0][servicePort]\e[24m, key \e[4m.services[0][ports]\e[24m does not contain 1 required value(s)"
error-details:
```

### Your environment

`garden version`

It seems like it is `garden -v`, it doesn't obey `garden version`

`0.8.1`

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
`docker version`

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by adamdavis40208** [comment]
I wound up deleting the servicePort from the .yml, and things still worked:

```
curl http://simple-project.192.168.99.100.nip.io/hello-go
Hello from Go!
```

**Comment by eysi09** [comment]
Thanks for pointing this out @adamdavis40208!

The issue is that the examples have been updated on the master branch and are no longer compatible with the latest release.

I think the best solution is to start versioning the documentation and have links to examples point to the respective version tag. I'll re-name the issue accordingly. 

[Here's a link](https://github.com/garden-io/garden/tree/v0.8.1/examples) to the examples directory for version 0.8.1.

**Comment by eysi09** [comment]
We now point the example links to a particular version tag. The links get update automatically every time we release a new minor version. 

So e.g., a link on master should point to `https://github.com/garden-io/garden/tree/v0.10/examples` if `0.10` is the latest version. For particular tags the links then point to the examples for that tag.
