### ISSUE TITLE
0.13: [Bug]: local-docker build fails with ENOENT

### ISSUE THREAD

**Issue by chrispsplash** [garden-io/garden#4815]
### Current Behavior

The build bails out immediately with an `ENOENT` error (below)

`Unable to run docker command: An error occurred while trying to run '/Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker' (spawn /Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker ENOENT). Please make sure '/Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker' is installed and in the $PATH.`

### Expected behavior

Build runs as normal

### Reproducible example

1. Clone this example repo https://github.com/chrispsplash/example-bonsai-local-docker-build-issue
2. Set the env var `KUBE_CONTEXT` to a valid kube context
3. Run `garden build`

<details>
<summary>Sample output</summary>

```
❯ KUBE_CONTEXT=amer-dev garden build
Build 🔨

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment default.default
ℹ providers            → Getting status...
✔ providers            → Done (took 2.1 sec)
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.1 sec)
✖ build.pgbuckle       → Failed resolving status for Build type=container name=pgbuckle (took 0.09 sec). Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────
Unable to run docker command: An error occurred while trying to run '/Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker' (spawn /Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker ENOENT). Please make sure '/Users/chrisprzybycien/.garden/tools/docker/ade15f5895b17266/docker/docker' is installed and in the $PATH.
────────────────────────────────────────────────────────────────────────────────────────────────


1 build action(s) failed!

See .garden/error.log for detailed error message

 ~/Projects/chrispsplash/bonsai-local-docker-build-issue  main                         10s 
❯
```
</details>

### Workaround

Use `buildAtSource: true`.  Yep, that's all.  You can try it in the sample repo just uncomment that one line 🤷 

### Suggested solution(s)

I'm gonna guess the build dir isn't being created for `local-docker` builds.  This would explain the `docker` commands failing with ENOENT (they have their cwd set to the nonexistent build dir) and also why `buildAtSource` is a workaround.

### Additional context

It's way too hot outside 🥵 

### Your environment

* **OS:** macOS 13.4.1 (22F82)
* **How I'm running Kubernetes:** EKS

```
❯ garden version
garden version: 0.13.7
```

**Comment by vvagaytsev** [comment]
The root cause was not in the missing docker binary, it was in the incorrect `cwd` for the `docker` command.

By the way, removing the `providers.deploymentRegistry` also makes it work. That helped me to find the difference in the code paths and dig to the place where `docker`'s `cwd` was defined :)

**Comment by chrispsplash** [comment]
Confirmed, thanks!!
