### ISSUE TITLE
[FEATURE]: Make builds aware of deploy mode

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#4819]
### Background / Motivation

While working on a project, I encountered a situation where I wanted to have a different `targetStage` depending on the sync mode of actions (`actions.deploy.xx.mode`). However, I found that this was not possible as it creates a circular dependency between the build module and the deploy.

### What should the user be able to do?

The user should be able to set a different `targetStage` depending on the sync mode of actions without creating a circular dependency between the build module and the deploy.

### Why do they want to do this? What problem does it solve?

To have different Docker builds depending on the sync mode (no need for watcher or other things if we are not in sync mode).

### Suggested Implementation(s)

Have a way to know if we are in sync mode. Right now we do things like:

```
  sync-mode: ${command.params contains 'sync' && (command.params.sync contains 'api' || isEmpty(command.params.sync))}
```

But if we have multiple deploys depending on this build, it gets very complicated very fast

```
command.params contains 'sync' && (command.params.sync contains 'api' || command.params.sync contains 'api-worker' || command.params.sync contains 'api-subscriptions' ...
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful.

**Comment by Orzelius** [comment]
@antoinelyset This can be achieved via having two separate builds and changing which to use based on the action mode.

You can have a base build to reduce duplication.

Maybe it's worth creating an example for this configuration style?

**Comment by antoinelyset** [comment]
Oh really interesting indeed! Maybe an example in the documentation would be cool if there isn't. Thanks a lot!

**Comment by vvagaytsev** [comment]
We have a PR in the `quickstart-example` repo: https://github.com/garden-io/quickstart-example/pull/9/files. There you can find 2 builds (`limiter-sync` and `limiter-prod`) for the limiter service. The Deploy action picks the build depending on the action mode.

**Comment by Walther** [comment]
Closing this as not planned. Configuration examples linked above.
