### ISSUE TITLE
0.13: [Bug?]: Task caching behavior changes

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#4890]
### Current Behavior

I've noticed that starting with v0.13, the task caching  behavior changed quite a bit.
When directly running a task in v0.12 (`garden run task <task-name>`), the task will never hit the cache and hence would always run.
In contrast when directly running a task in v0.13 (`garden run <task-name>`), the task can hit the cache (`Already complete`).

This change of behavior broke most of our garden workflows.
I'm aware of the fact that I can disable the cache with the `--force` flag, which will be my workaround.

Worth mentioning is that we're still haven't migrated to actions yet - all tasks stem from modules.

Is this a bug or a feature?
If it's a feature, I suggest mentioning this breaking change in the migration guide (https://docs.garden.io/tutorials/migrating-to-bonsai).

### Expected behavior
I'd expect that the task caching behaves just as in v0.12.

### Workaround
Use `--force` flag:

`garden run --force <task-name>`

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** KE

`garden version`
0.13.9

**Comment by vvagaytsev** [comment]
Thanks for reporting this, @hnicke! Good catch!

This seems to be the expected behaviour, as the [Run action docs](https://docs.garden.io/using-garden/runs) says:

> Garden caches Run results and re-runs the Runs if its dependencies have changed. It is therefore recommended that you make sure your Runs are idempotent (i.e. can safely be run multiple times). This behaviour can be disabled via the `spec.cacheResult` field on Runs.

So it's definitely a breaking change in 0.13. I'll create a PR to update the migration guide.

**Comment by stefreak** [comment]
This was possibly not intentional / possibly an oversight during the 0.13 release.

We are evaluating this internally; Re-opening this issue in the mean time.

**Comment by 10ko** [comment]
This has been the default behaviour for `0.13.x` for a while, if that's undesirable please use the `spec.cacheResult` field.
