### ISSUE TITLE
[FEATURE]: Add possibility to make Garden ignore k8s resources status/events on deploy

### ISSUE THREAD

**Issue by xdvpser** [garden-io/garden#4897]
## Feature Request

Initially question was posted in Discord [channel](https://discord.com/channels/817392104711651328/1134084196906831892/1134084196906831892)

### Background / Motivation

I am using garden in a CI platform in my shell scripts and it is extremely inconvenient when Kubernetes objects were successfully created, but Garden CLI is returning non-zero exit code as some resources failed to start for some time.

### What should the user be able to do?

Deploy k8s resources without waiting for them to be up and running.

### Why do they want to do this? What problem does it solve?

As Garden is heavily used for deployments to Kubernetes, and IMO it should have the same behavior as other industry standard tools.
- `kubectl apply -f example_manifest.yaml` just creates k8s objects and that's it. Separately, `kubectl get <resource_type> --watch` can be used to monitor deployed resources.
- `helm install/upgrade ...` also just creates k8s objects. There is a special flag (`--wait`) to make it wait for k8s resources to be up and running.

The pain point here is that I cannot make Garden just create k8s objects.

### Suggested Implementation(s)

IMO it should be the default behavior for `garden deploy <something>`. Alternatively, additional flag can be provided - `--no-wait` or `--skip-wait`.

With this new flag, it should fail if garden couldn't install helm release or apply k8s manifests for some reason (for example, template error or k8s object already exists). But if **Kubernetes objects were successfully created**, I want garden deploy command to return 0 exit code, even if deployed services (i.e pods) fail to start or crashlooping.

When deploying services with `--sync`/`--dev` flag, `--no-wait` should be ignored.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by 10ko** [comment]
Thank you for your proposal, we think it's a good idea but a lot of the internals around testing and syncing of the tool rely on checking resource statuses and implementing this flag would mean a large refactoring and it would open up a lot of caveats and edge cases.
Unfortunately, we don't see us implementing this at this time.
