### ISSUE TITLE
0.13: [Bug]: deploy with local mode errors: `Invalid count value`

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#4912]
### Current Behavior

When running `garden deploy --local ...` and the terminal width is <90 characters, garden crashes:
```
$ garden deploy --local bex-os

───────────── 🌳  garden dev 🌳  ─────────────

Good morning! Welcome to the Garden interactive development console.

Here, you can build, deploy, test and run anything in your project, start code syncing, stream live logs and more.

Use the command line below to enter Garden commands. Type help to get a full list of commands.
Use up/down arrow keys to scroll through your command history.

Scanning repository at /home/xxx/bex/bex-umbrella
Scanning repository at /home/xxxx/bex/bex-umbrella/.garden/sources/project/bexapp--accbe12695
Scanning repository at /home/xxx/bex/bex-umbrella/.garden/sources/project/bom-app--fc03d112c9
Scanning repository at /home/xxxx/bex/bex-umbrella/.garden/sources/project/bom--493b1ac2ed
Scanning repository at /home/xxxx/bex/bex-umbrella/.garden/sources/project/bex-os--9ce2e4e449
🌿 Explore logs, past commands, and your dependency graph in the Garden web App. Log in with garden login.
→ Run garden util hide-warning web-app to disable this warning.


Invalid count value

────────────── 🌼 🌸 🌷 🌺 🌻  ──────────────
 🌷  Thanks for stopping by, love you! ❤️

  ✔︎  Dev console is ready to go! 🚀
```

It doesn't matter which log level is being used (normal / debug/ silly).
The problem only occurs when deploying with local mode.

### Workaround

Adjust your terminal to be >=90 chars in width.
Alternatively, launch the dev console first: `garden dev`. Then, from within the dev console, run `deploy --local ...`

### Suggested solution(s)

The error is most probably caused by a [RangeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Resulting_string_too_large), which in turn is thrown by a `String.prototype.repeat()` function, most probably in one of these places:
```
$ git grep '.repeat(' | grep logger  
core/src/logger/renderers.ts:  return diff <= 0 ? section : section + repeat(" ", diff)
core/src/logger/util.ts:  const titleString = title ? `${pad.repeat(titlePadding) + title + pad.repeat(titlePadding)}` : ""
core/src/logger/util.ts:  const dividerSideString = color(char.repeat(numberOfCharsPerSide))
core/src/logger/util.ts:  const paddingString = pad.repeat(padding)
```

### Your environment

* **OS:** arch linux, OSX

`garden version`
0.13.9

**Comment by hnicke** [comment]
@vvagaytsev you're welcome! The error happens with normal log level, with `-l debug`  and as well with `-l silly`.

**Comment by edvald** [comment]
I suspect the issue is that `--local` makes the deploy command persistent and thus puts you into the dev console. So it's probably something generally affecting the dev console.

**Comment by hnicke** [comment]
The problem does not occur when running `garden dev` in a narrow terminal.
The dev console spins up properly.
Interestingly enough, even running `deploy --local ...` in the garden dev console works without issue.
