### ISSUE TITLE
Show spinner (or similar) when running commands in dev console

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#4934]
### Current Behavior

If I run `garden deploy --sync`, it's not very clear what command is running and when it actually finishes. 

### Expected behavior

Garden should show a spinner or some informative text letting the user know the command is still running in case no logs are being output.

Same should apply if the command is started within the console, that is, I run `garden dev` and the `deploy --sync`.

The difference though is that in the latter case, Garden does print a success message when the command finishes running which is not the case at all for commands like `garden deploy --sync` which looks like a straight up bug.

Either way, it needs to be clear when a command is actively running and we need to handle the case when multiple commands are running at the same time. It could be as simple as a string saying something like `Currently running commands build, deploy` or similar.

This is currently handled correctly in the web dashboard. 

### Reproducible example

Run some Garden commands as described above and observe the output.

### Workaround

The live page on the web dashboard does print this information. 

### Additional context

The fact that there can be long periods of time where Garden outputs absolutely nothing even if it's doing a ton of things suggests that the default log level is not verbose enough. 

This is not really a problem if the commands are run with `-l3` because there's typically log output from build and deploy logs. 

### Your environment

Latest main.

**Comment by TimBeyer** [comment]
Resolved in https://github.com/garden-io/garden/pull/4945
