### ISSUE TITLE
0.13: [Bug]: Get Actions errors out if any action is disabled

### ISSUE THREAD

**Issue by mattpolzin** [garden-io/garden#4937]
### Current Behavior

Create a set of circumstances where one of the actions in a project will resolve to `disabled: true` and then run `garden get actions --detail`. The result will be an error like
```shell
me: ~/staging/repo (garden-bonsai) $ garden get actions --detail --env dns
Get Actions 📖 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev
ℹ providers            → Getting status...
✔ providers            → Cached (took 1.9 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 39.4 sec)


Deploy type=container name=something-or-other is disabled.
```

### Expected behavior

I expect `garden get actions --detail` to retrieve details about all actions, or at least all enabled actions, without erroring out because it discovers some actions are disabled.

### Workaround

Make sure every single action is enabled I guess?

### Your environment

* **OS:** macOS `13.4.1 (c)`
* **How I'm running Kubernetes:** AKS (Azure)

`garden version: 0.13.10-edge-bonsai-a65f2c49d`

**Comment by shumailxyz** [comment]
I think this is likely coming from 

https://github.com/garden-io/garden/blob/main/core/src/graph/config-graph.ts#L191-L196

To add some more context, `--detail` flag also goes through each action to list down the dependents of each action which in return calls `getActionByKind` and there it fails if an action is disabled.
