### ISSUE TITLE
0.13: [Bug]: Cached Action state is not cleared when expected

### ISSUE THREAD

**Issue by mattpolzin** [garden-io/garden#4942]
### Current Behavior

Given a Run Action `(a)` that depends on a Run Action `(b)` that depends on a Deploy Action; run all of these actions with a fresh deploy, then delete the resource for the Deploy Action and redeploy it, then explicitly run Action `(a)` -- You will be told Action `(a)` has already run. Then force Action `(a)` to run and it will determine that Action `(b)` has already run which will result in Action `(a)` failing (assuming it really does require something that Action `(a)` does).

### Expected behavior

I would expect the deletion and redeploy of the Deploy Action that both Actions `(a)` and `(b)` depend on to reset the cached status of those Actions so that they would run again when requested.

### Reproducible example

I have not had time to recreate a minimal reproduction of this yet, but if needed I can create one in the next few days  and update the ticket.

### Workaround

The workaround is to run all actions explicitly in-order with the `--force` flag.

### Suggested solution(s)

I think invalidating the cached state of actions when they depend on a resource that has been deleted makes sense to me. This must be roughly what happened in Garden Acorn because my organization doesn't see the bug tracked in this ticket when running Garden `0.12.x`.

### Your environment

* **OS:** macOS 13.4.1 (c) 
* **How I'm running Kubernetes:** AKS (Azure)

`garden version: 0.13.10-edge-bonsai-a65f2c49d`

**Comment by vvagaytsev** [comment]
@mattpolzin thanks for reporting this! The Run (a.k.a. task) caching default behavior was changed in `0.13 `. Unfortunately, we missed that in the very first version of the Bonsai migration guide.

Later, we got #4890 which was fixed in #4901. Now it's on the list of the [breaking changes in Bonsai](https://docs.garden.io/tutorials/migrating-to-bonsai#breaking-changes-first):
> Now Garden caches Run results and re-runs the Runs if its dependencies have changed. It is therefore recommended that you make sure your Runs are idempotent (i.e. can safely be run multiple times). This behaviour can be disabled via the `spec.cacheResult` field on Runs.

Would `spec.cacheResult: false` solve the problem? It should be a more precise and fine-grained option than the `--force` flag.

**Comment by mattpolzin** [comment]
I'll have to think on that. Would `spec.cacheResult: false` be fully the same as the old behavior or would it mean even more execution than used to occur in Acorn?

Ideally what I want is a different sort of dependency. "As long as this has run since its dependency's k8s resources were last created we can skip it." But I think I understand how the caching in its current state is supposed to work now.

**Comment by mattpolzin** [comment]
I'm going to close this issue. It seems I partially misunderstood the intended behavior and I hope that I can constantly work with what I've got by forcing things to run for all steps of most workflows.
