### ISSUE TITLE
Cannot Book Demo

### ISSUE THREAD

**Issue by 24601** [garden-io/garden#4956]
## Bug
Not an application "bug", but we're looking at becoming an enterprise customer and the calendly link on the site is broken, and there's no real other credible way to contact, so sorry for the bug pollution, but we want to give you money, but you are making it hard :).

https://capture.dropbox.com/tj2shD3KstlNU2Hh

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by edvald** [comment]
Hey @24601! Thanks for reporting this. I've sent this over to the web team, but in the meantime, here's a working Calendly link: [https://calendly.com/andrewgarden/30min](https://calendly.com/andrewgarden/30min?month=2023-08)

We look forward to chatting with you :)
