### ISSUE TITLE
Allow multiple modules in same `garden.yml`

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#501]
This has come up on a few occasions, such as when using multiple Dockerfiles in the same source directory. Shouldn't be hard to support, e.g. by adding a `modules` key (but still allowing the singular key as a shorthand).

**Comment by adnaan** [comment]
This would be quite useful. A use case for such a feature would be multiple Dockerfiles for production, development, integration etc.

**Comment by eysi09** [comment]
This was closed with #535
