### ISSUE TITLE
Print service endpoints on `garden deploy`

### ISSUE THREAD

**Issue by adnaan** [garden-io/garden#502]
### Current Behavior

After deploying a service:

```
 garden deploy mydocs --watch --hot-reload=mydocs
Deploy 🚀

✔ slate                     → Building slate:68568aa64b-1549007790... → Done (took 253.4 sec)
✔ mydocs                   → Deploying version 68568aa64b-1549007790... → Done (took 10.7 sec)
```

You would need to find the service endpoint from the yml or run `garden call mydocs`

### Expected behavior

I would expect the `garden deploy` to print the service endpoint. 

```
 garden deploy mydocs --watch --hot-reload=mydocs
Deploy 🚀

✔ slate                     → Building slate:68568aa64b-1549007790... → Done (took 253.4 sec)
✔ mydocs                   → Deploying version 68568aa64b-1549007790... → Done (took 10.7 sec)
                                    → hostname: mydocs.local.app.garden
```

`garden version`
0.8.1

**Comment by edvald** [comment]
Good idea! And shouldn't be at all hard to do, since the relevant information is already around when completing deployments.

**Comment by eysi09** [comment]
Changing the milestone since we have some bug fixes that we need to release ASAP.
