### ISSUE TITLE
garden self-update painful on windows

### ISSUE THREAD

**Issue by kroher** [garden-io/garden#5030]
### Current Behavior

When I run garden self-update in windows(usually running with a version), the next time i run garden it complains/errors 

`Path C:\Users\usrdir\.garden\bin\static is not in a git repository root. Garden must be run from within a git repo. Please run `git init` if you're starting a new project and repository, or move the project to an existing repository, and try again.`

after i go into the directory and run git init garden works fine.

doesnt do this on macOs

### Expected behavior

i shouldnt have to manually run git init in the user/.garden directory at all to start garden

### Reproducible example

clean install of garden via installer on windows
garden dev and things stand up fine on vote
garden self-update 0.13.12
garden dev
error message

### Your environment

windows 11
gke

0.12.63, 0.12.64, 0.13.12, 0.13.13

**Comment by vvagaytsev** [comment]
Thanks for reposting this @kroher!
This might have the same root cause as #2614.

We have a draft PR #4047 to solve the issue.
