### ISSUE TITLE
0.13: [Bug]: `garden deploy --sync` fails with an error

### ISSUE THREAD

**Issue by bulliana** [garden-io/garden#5053]
### Current Behavior
`deploy --sync` fails with the following error:

```
Command "/Users/ulianasirotina/.garden/tools/mutagen/85054cb3eb04c4f0/mutagen sync create /Users/ulianasirotina/garden/garden-platform/api exec:'/Users/ulianasirotina/.garden/tools/kubectl/f8a39834529cd1ed/kubectl exec -i --context=eks_garden-ci-k8s-cfb88b38 --kubeconfig=/Users/ulianasirotina/garden/garden-platform/infra/dev-infrastructure/ci/kubeconfig_garden-ci-k8s-cfb88b38 --namespace=ge-ulianasirotina --container api Deployment/api -- /.garden/mutagen-agent synchronizer':/app/api --name k-8-s-dev-ge-ulianasirotina-api-deployment-api-api-app-api --sync-mode one-way-replica -i /**/*.git -i **/*.garden -i dist -i node_modules -i tmp --default-file-mode 0644 --default-directory-mode 0755" failed with code 1:

Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: server magic number incorrect (error output: command terminated with exit code 126)

Here's the full output:

Connecting to agent (POSIX)...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: server magic number incorrect (error output: command terminated with exit code 126)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


2 deploy action(s) failed!
```

### Expected behavior

`deploy --sync` works without errors

### Reproducible example

none

### Workaround

`garden delete environment`, and start from scratch

### Suggested solution(s)

Updating Mutagen could be a possible solution

### Your environment

* **OS:** Ventura 13.5.1
* **How I'm running Kubernetes:** 🤷‍♀️

`garden version`: 0.13.13

**Comment by eysi09** [comment]
I've seen this on my end as well and most often it works to run `deploy --sync` again instead of deleting the environment. 

If that doesn't work, it should be enough to run `cleanup deploy <name-of-deploy-that-can't-sync>` instead of deleting the entire namespace. 

That being said, we obviously need to wrap up the Mutagen work ASAP and see if that fixes it.

**Comment by psimondk** [comment]
I just ran into the same - clean install of the quickstart for evaluation purposes:

![image](https://github.com/garden-io/garden/assets/2089533/9f531bd2-8e09-45cb-8c52-4d1d2314972d)

**Comment by eysi09** [comment]
Thanks for sharing @psimondk! 

We'll be including an updated version of Mutagen in our next release that we hope fixes this issue but we'll feature flag it to begin with and then make it the default in a subsequent release. 

We've been using our own fork of Mutagen for some time and we want to make sure the transition is smooth for users.
