### ISSUE TITLE
0.13: [Bug]: Unable to parse modules key

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#5083]
### Current Behavior
When using `garden plugins pulumi preview` command, garden is unable to parse `${modules["${parent.name}-publish-image"].version}` 

`An error occurred while reading pulumi varfiles for action spring-boot-service: Unable to load varfile at '/home/workstation/thx/workspace/garden-sample-project/garden-sample-project/config/global.yaml': Error: Invalid template string (
### Expected behavior
garden should parse the `${modules["${parent.name}-publish-image"].version}` .

**Comment by vvagaytsev** [comment]
Hi @ishantagarwal-x213235, thanks for reporting the issue! Could you please provide the garden config to reproduce it? It might be that the `${modules}` are referenced from the wrong context.

**Comment by ishantagarwal-x213235** [comment]
@vvagaytsev Kindly use the project https://github.com/ishantagarwal-x213235/garden-sample-project for reproduce this issue.

Here is the yaml file having properties required for project
https://github.com/ishantagarwal-x213235/garden-sample-project/blob/main/config/global.yaml

here is the garden template
https://github.com/ishantagarwal-x213235/garden-sample-project/blob/main/template/garden/spring-service-module.garden.yml

**Comment by vvagaytsev** [comment]
@ishantagarwal-x213235 which command did you use? Is the reproducible with `garden validate`?

**Comment by ishantagarwal-x213235** [comment]
@vvagaytsev 
here is the command
`garden plugins pulumi preview`

**Comment by vvagaytsev** [comment]
Ah, sorry, I missed that in the description :)

**Comment by ishantagarwal-x213235** [comment]
Hi @vvagaytsev 
Could you kindly provide an update on the progress of the task, and please don't hesitate to reach out if you encounter any challenges or require assistance in reproducing it? Your support is greatly appreciated, and I'm here to help ensure a successful outcome

**Comment by vvagaytsev** [comment]
@ishantagarwal-x213235 sorry for the delayed reply. It's still in the backlog, I'm working on something else now. We'll check if someone can take this.
