### ISSUE TITLE
[FEATURE]: show garden version from the command detail in the commands list.

### ISSUE THREAD

**Issue by kroher** [garden-io/garden#5254]
## Feature Request

Currently I have to click/drill on a command row to see what version of garden cli was used to kick it off, it would be super useful to have that on the command list page in garden cloud.

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by bulliana** [comment]
Hey @kroher, thanks for the suggestion 🙌 . We have addressed that and you should be able to see it soon.
