### ISSUE TITLE
Customisable versioning/tagging

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#526]
Similarly to how Skaffold allows customisation on version tags (https://skaffold.dev/docs/how-tos/taggers/), we could offer a project-level configuration option to customise the formatting of version strings.

Supporting sha256 source code checksums would also be nice, but possibly slightly difficult to implement across various different types of source modules.

**Comment by eysi09** [comment]
This came up in the community Slack recently. Here's the comment for context:

> However, reconfiguring `image` as an object as you suggested would be a strong feature I think. Currently, I have configured Flux to handle the logic for image promotion based on the commit hash tag from garden, but being able to explicitly state a versioning strategy within the `garden.yml` that I can match up in Flux would be even better.
