### ISSUE TITLE
[FEATURE]:  Stale Twitter icon

### ISSUE THREAD

**Issue by Ayush9026** [garden-io/garden#5467]
### Background / Motivation

Twitter is now Xcorp update twitter icon with 'x' marked in screenshot below.

![Garden io](https://github.com/garden-io/garden/assets/114745463/90d8c3db-01df-4446-a4a9-fee8d892f64b)

### What should the user be able to do?

Updated twitter icon will tell user that organization is updated.

### Why do they want to do this? What problem does it solve?

This shows organization is up to date

### Suggested Implementation(s)

change icon with new one.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by shumailxyz** [comment]
Thanks for pointing. We'll track it internally. 
I'll close this issue here it's not in the scope of our open source product.
