### ISSUE TITLE
Run integration tests in CI

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#552]
We need to be able to run our integration tests in CI. One solution would be to use Azure pipelines. We've experimented with this before but never got it to work properly. However, this blog posts appears to outline a working solution: https://blog.gripdev.xyz/2018/10/19/kubernetes-integration-testing-minikube-azure-pipelines-happy/

There's a separate issue, #550, for setting up a proper integration test suite.

**Comment by edvald** [comment]
Done in #842
