### ISSUE TITLE
Crash: toKubernetesError encountered an unknown error unexpectedly during Kub...

### ISSUE THREAD

**Issue by DanielKillenberger** [garden-io/garden#5559]
### Error message

✖ deploy.platform-ui        → Failed (took 8.7 sec)
✖ deploy.platform-ui        → Failed resolving status for Deploy type=container name=platform-ui (took 9.32 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20toKubernetesError%20encountered%20an%20unknown%20error%20unexpectedly%20during%20Kub...

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed resolving status for Deploy type=container name=platform-ui (took 9.32 sec). This is what happened:
Error: Cannot parse content. No Content-Type defined.
  at ObjectSerializer.parse (file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:5[67](https://github.com/FQX-AG/fqx/actions/runs/7206185255/job/19631282968?pr=1915#step:9:68)762:21)
  at CoreV1ApiResponseProcessor.readNamespacedPodLogWithHttpInfo (file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:601871:111)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async retry (file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:[69](https://github.com/FQX-AG/fqx/actions/runs/7206185255/job/19631282968?pr=1915#step:9:70)8396:20)
  at async requestWithRetry (file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:698422:20)
  at async file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:702239:19
  at async Promise.all (index 0)
  at async file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:702302:25
  at async Promise.all (index 0)
  at async getFormattedPodLogs (file:///github/home/.local/share/garden/1702543490-UakctbW.r/rollup/garden.mjs:702297:21)
────────────────────────────────────────────────────────────────────────────────────────────────────

toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: readNamespacedPodLog: toKubernetesError encountered an unknown error unexpectedly during readNamespacedPodLog: Cannot parse content. No Content-Type defined.

### What did you do?

Run deploy in CI

### Your environment

gardendev/garden-gcloud:0.13.21-alpine on github actions
### Frequency

Happens every time now on this specific PR with minimal changes.

**Comment by DanielKillenberger** [comment]
Deleting the deployment and retrying fixed the issue as a workaround.

**Comment by stefreak** [comment]
We saw this before in #5529 but failed to reproduce this error. Thank you for reporting this @DanielKillenberger! CC @twelvemo @worldofgeese

**Comment by stefreak** [comment]
If  reproducing this is hard, it might be enough to investigate which kind of errors `ObjectSerializer.parse` can throw, and then handle these kinds of errors in `toKubernetesError` (https://github.com/garden-io/garden/blob/63eff7db2d2e277d26a5d6c51dc491d24a59144f/core/src/plugins/kubernetes/retry.ts#L87) and making sure that it is considered a retryable error in `shouldRetry` https://github.com/garden-io/garden/blob/63eff7db2d2e277d26a5d6c51dc491d24a59144f/core/src/plugins/kubernetes/retry.ts#L158

**Comment by stefreak** [comment]
If the error was really permanent until the deployment has been deleted then simply retrying wouldn't help. Very strange. It would be good if we learn somehow how to trigger this bug.

**Comment by twelvemo** [comment]
@stefreak there was also another error serializing from the Kubernetes API recently reported on slack. I agree it would be really good to get to the bottom of these. Thanks for the pointers!
