### ISSUE TITLE
Deployment of Helm charts with a test pod always timeouts

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#558]
## Bug

When a Helm chart is created with the `helm create` command, it contains a test Pod under `templates/tests/test-connection.yaml`. Furthermore, many official Helm charts will contain test Pods of some sort. When Garden deploys such a chart, the Pod shows up as missing in the `waitForResources` function, causing it to eventually timeout.

Current workaround is simply to delete the YAML for the test Pod. For remote charts, the user would first have to clone or fork and remove the test.

### Current Behavior

`garden deploy` timeouts when deploying a Helm chart with a test Pod.

### Expected behavior

`garden deploy` doesn't timeout.

### Reproducible example

The `vote-helm-test-pod-bug` contains a reproducible example and logs the error. On that branch, the `vote` service of the `vote-helm` example contains the default Helm test Pod, defined in `vote-example/vote/templates/test-connection.yaml`. So the steps would be (assuming current directory is garden root):

```sh
git fetch origin
git checkout vote-helm-test-pod-bug
cd examples/vote-helm
garden deploy vote
```

### Suggested solution(s)

N/A

### Additional context

Ran into this when installing the official Ambassador chart.

### Your environment

`garden version`

Latest `master` 

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`

**Comment by edvald** [comment]
Fixed in #560
