### ISSUE TITLE
Invalid links in quickstart-example README

### ISSUE THREAD

**Issue by porterchris** [garden-io/garden#5605]
The following links in the quickstart-example README are invalid and render as Page Not Found on the docs site:

https://github.com/garden-io/quickstart-example/blob/main/README.md?plain=1#L22-L23
```
This repository contains the Garden Quickstart example. Please see our [Quickstart Guide](https://docs.garden.io/basics/quickstart) for step-by-step instructions on how to deploy this project. If you see any issues or bugs, kindly report them
to the [main Garden repo](https://github.com/garden-io/garden/issues/new).
```

https://github.com/garden-io/quickstart-example/blob/main/README.md?plain=1#L68
```
You can learn more about the Kubernetes action types [in our docs](https://docs.garden.io/kubernetes-plugins/action-types).
```

**Comment by twelvemo** [comment]
Thanks for reporting @porterchris ! We'll fix this right away.
