### ISSUE TITLE
Crash: Missing cli argument in custom command wrapper

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#5627]
## Crash report

Running a custom command from the REPL leads to a crash. The same custom command runs successfully when run outside of `garden dev`.

### Error message
Error: Missing cli argument in custom command wrapper.
    at CustomCommandWrapper.action (file:///Users/anna/Library/Application%20Support/io.garden.garden/1704208798-iZ51DU2.r/rollu

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS
* **Garden version:** 0.13.23

### Workaround

This crash is reproducible.

**Comment by stefreak** [comment]
Duplicates #4668
