### ISSUE TITLE
get status command fails if Helm module hasn't been built

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#564]
### Current Behavior

When running `garden get status` before building a Helm module that has a base chart, I get the following error:

```
garden get status

Command failed: /Users/eysi/.garden/tools/helm/6309c46338caf006/darwin-amd64/helm --tiller-namespace vote-helm --kube-cont
ext docker-for-desktop inspect values /Users/eysi/code/garden-io/garden/examples/vote-helm/.garden/build/api
Error: no Chart.yaml exists in directory "/Users/eysi/code/garden-io/garden/examples/vote-helm/.garden/build/api"
```

### Expected behavior

`garden get status` should return the project status.

### Reproducible example

Change to the `vote-helm` example directory and:

```
rm -rf ./garden
garden get status
```

### Suggested solution(s)

Build before getting status?

### Your environment

Latest `master`.

**Comment by edvald** [comment]
Fixed a while back (forget which PR, sorry 😬)
