### ISSUE TITLE
[FEATURE]: publish local images using the `local-kubernetes` provider

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#5659]
### Background / Motivation

A community user (EDIT: and a customer) uses Garden for all their image builds. For ad-hoc testing using the `local-kubernetes` provider they can't easily tag an image with `latest`..

### What should the user be able to do?

A user should be able to explicitly publish to the local registry using the `local-kubernetes` provider.

### Why do they want to do this? What problem does it solve?

It bridges the gap between local and remote workflows, explicitly between `kubernetes` and `local-kubernetes` providers.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by twelvemo** [comment]
@salotz thanks for letting us know. We will close this for now but feel free to reopen if this becomes important.
