### ISSUE TITLE
Integration test Garden with Garden

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#566]
We should transition to running our integration tests for Garden using Garden itself once we've added some more test sets to our integration testing suite.

Specifically, we could encapsulate each test set (e.g. "pre-release", "performance" etc.) in a test spec, using the build and service configs as needed (including dependencies) to orchestrate the execution of the whole thing.

We could also use different environments to run the test sets with different base configurations (e.g. on Minikube VS some other k8s implementation).

@edvald: Am I missing anything from this description?

**Comment by eysi09** [comment]
Closed with #840
