### ISSUE TITLE
Version command fails if not in a project directory

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#570]
### Current Behavior

`garden version` returns `Not a project directory (or any of the parent directories):``

if not in a project directory. `garden --version` works however.

### Expected behavior

`garden version` should work in a non-project directory, just like `garden --version` does.

### Reproducible example

N/A

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

Lastest `master`

**Comment by edvald** [comment]
This has been fixed (not sure when exactly)
