### ISSUE TITLE
0.13: [Bug]: Multi-line secrets decrypted improperly in garden >0.13.24

### ISSUE THREAD

**Issue by alexkuretz** [garden-io/garden#5813]
### Current Behavior

I'm updating a project that was previously building with Garden 0.12.67 and fails with Garden 0.13.27. I eventually discovered it's a problem decoding multi-line secrets (in this case a JWT token and NATS credential). I stepped through Garden versions and found that the change occurred between 0.13.24 (good) and 0.13.25 (bad).

We use Garden Cloud for secrets management. This is a container module running in /v0 compatibility mode. We use buildkit.

### Expected behavior

Multi-line secrets should appear in full, not just the first line

### Reproducible example
Secret:
```
This
Secret
Is
On
Multiple
Lines
```
garden.yml:
```
kind: Module
type: container
name: service-test
buildArgs:
  MULTI_LINE_SECRET: ${secrets.MULTI_LINE_SECRET}
```
Dockerfile:
```
FROM osgeo/gdal:ubuntu-small-3.6.0
WORKDIR /var/task
ARG MULTI_LINE_SECRET
RUN echo $MULTI_LINE_SECRET
```
command:
```
garden build service-test
```
0.13.24 output:
```
#10 [5/5] RUN echo This
Secret
Is
On
Multiple
Lines
#10 2.420 This Secret Is On Multiple Lines
#10 DONE 2.6s
```
0.13.25+ output:
```
#10 [5/5] RUN echo This
#10 2.725 This
#10 DONE 3.2s
```

### Workaround

Maybe base64 encode? Haven't tried other than to roll-back to Garden 0.13.24.  I suppose I could try converting to actions. This broke several of our projects while I was trying to get the whole org updated to run on 0.13 from 0.12.

### Suggested solution(s)

Not sure what broke so don't know.

### Additional context
N/A

### Your environment

* **OS:** Ubuntu 22.04 in WSLv2
* **How I'm running Kubernetes:** EKS

0.13.24 is good
0.13.25 is bad

**Comment by vvagaytsev** [comment]
Thanks for reporting this @alexkuretz!

I've checked the [changelog between 0.13.24 and 0.13.25](https://github.com/garden-io/garden/compare/0.13.24...0.13.25). It looks like the only change that affected buildkit command execution was done in #5712.

It might be related to the command escaping. In [0.13.28](https://github.com/garden-io/garden/releases/tag/0.13.28) we fixed the escaping of the shell commands (#5811). That fix could affect this issue too. Could you please try out garden 0.13.28?

**Comment by alexkuretz** [comment]
Alright, I think it's fixed, thanks.

I did notice the out-of-order logs messages issue, is that an item you're aware of and tracking or should I make a new issue? It makes it hard to debug.

```
#8 [3/3] RUN echo This
On
Lines
Multiple
Is
#8 0.541 This Secret Is On Multiple Lines
```

**Comment by eysi09** [comment]
I can confirm the issue with logs being displayed out of order.

Tracked separately here #5857
