### ISSUE TITLE
Can't reliably install Garden in GitHub Actions

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#5905]
### Current Behavior

While using the Garden install script, we are experiencing intermittent failures on GitHub actions.
It timeouts after more than 90 seconds even after 1 retry.

### Expected behavior

The installation works

### Reproducible example

In a GitHub workflow, use

```
curl -sL https://get.garden.io/install.sh | bash -s "0.13.17" && echo "$HOME/.garden/bin" >> $GITHUB_PATH
```

### Workaround

Relaunch the GitHub Action manually until it works (can take hours).

### Suggested solution(s)

Move the binary or use a CDN.

**Comment by antoinelyset** [comment]
Small update to say, we just experienced it again just right now (small volume). I'm reporting it in case you can correlate it to something.

**Comment by stefreak** [comment]
@antoinelyset thank you for sharing this with us. For understanding the issue better, could you modify the script slightly adding `-x` option to bash:

```curl -sL https://get.garden.io/install.sh | bash -x -s "0.13.17" && echo "$HOME/.garden/bin" >> $GITHUB_PATH```

Please share the exact error message and/or the log output with -x option with us.

Are you using official GitHub action runners, or self-hosted runners?

**Comment by antoinelyset** [comment]
We are using official GitHub action Runners. From what I was seeing when I debugged the failures, it couldn't reliably download the binary.

See screenshots:

![Screenshot 2024-04-18 at 16 28 13](https://github.com/garden-io/garden/assets/1465371/f58d6bc4-9326-4a15-a18d-ec6112a3fb11)
![Screenshot 2024-04-18 at 16 27 52](https://github.com/garden-io/garden/assets/1465371/9f2bc007-0f2e-4014-9c80-e4cb9b795e15)

**Comment by stefreak** [comment]
@antoinelyset as a temporary pain relieve, could you try using the garden github action (https://github.com/garden-io/garden-action/tree/main)?

It's downloading garden differently (using the GitHub API, authenticated with the GitHub action token).

In the mean time, I'm working on improving the error handling in that script so we learn what's happening (e.g. HTTP response code)

**Comment by antoinelyset** [comment]
Oh! I didn't know you had this, that's very welcomed! Thanks!

**Comment by stefreak** [comment]
@antoinelyset feel free to tell me what you think about the action, and if it works more reliably for you.

**Comment by antoinelyset** [comment]
I just changed our workflows! Thanks for pointing me in this direction. I will reopen the issue if I re-encounter this issue.
