### ISSUE TITLE
In cluster building docs out of date for GCP

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#5938]
Google is replacing the classic container registry with Artifacts registry https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

[current instructions](https://docs.garden.io/kubernetes-plugins/guides/in-cluster-building#using-in-cluster-building-with-gcr) do not work, mainly due to the `gcrAccess` IAM role not working with the new Artifacts registry which is now used by default. 

I went through the process of getting in cluster building to work with the new artifacts registry and will submit a pr with the updated instructions if I have time (might happen this weekend 🤞, but I'll just inform you via this issue for now)

**Comment by 10ko** [comment]
Hi @Orzelius 👋 !! 
I just wanted to make sure I understand the issue, if you follow the link you posted you'll see in the right below section the instructions for setting up a registry with GAR. Are those instructions also not working or are you just going to remove the section `Using in-cluster building with GCR`?

Sending hugs, thanks for raising this!

**Comment by Orzelius** [comment]
Ah yes, you're completely right. Closing this as not relevant.
