### ISSUE TITLE
Error during Windows installation

### ISSUE THREAD

**Issue by JordyBaylac** [garden-io/garden#596]
### Current Behavior

When installing on Windows using:

`Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/garden-io/garden/master/support/install.ps1'))`

Next error is received:

![image](https://user-images.githubusercontent.com/13772770/53857129-0fdef580-3fa3-11e9-9318-ffd0d0c6dec5.png)

### Additional context

When checked the script `https://raw.githubusercontent.com/garden-io/garden/master/support/install.ps1` it is in fact trying to access `"https://github.com/garden-io/releases/latest"` which is not accessible (404 on the above capture).

### Your environment

Windows 10 Pro 64bit

`garden version`

  garder : The term 'garder' is not recognized as the name of a cmdlet,...

`kubectl version`

 Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

`docker version`

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.13.0
  StackAPI:         v1beta2

**Comment by eysi09** [comment]
Hi Jody, thanks for pointing this out!

Yes, looks like the URL string is wrong and should be `https://github.com/garden-io/garden/releases/latest`.

I can fix this once I'm at the office, a couple of hours from now. Also happy to accept a pull request :)

**Comment by eysi09** [comment]
Closed in #597
