### ISSUE TITLE
Bug in In-Cluster Building docs in ECR IRSA config

### ISSUE THREAD

**Issue by alexkuretz** [garden-io/garden#5977]
## Bug

Spent a few hours on this one, the docs have a bug in the [Web Identity Role config snippet](https://docs.garden.io/kubernetes-plugins/guides/in-cluster-building#using-in-cluster-building-with-irsa-iam-roles-for-service-accounts). 

### Current Behavior

Errors trying pull/push images to ECR, such as:

`Not authorized to perform sts:AssumeRoleWithWebIdentity`
`credentials not found in native keychain`

### Expected behavior

Able to push and pull images to ECR

### Suggested solution(s)

Because of the wildcard it's required to put the condition in a "StringLike" instead of "StringEquals".
https://github.com/aws-actions/configure-aws-credentials/issues/318#issuecomment-1145133984

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<account-id>:oidc-provider/oidc.eks.<region>.amazonaws.com/id/<oidc-provider-id>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                  "oidc.eks.<region>.amazonaws.com/id/<oidc-provider-id>:sub": "system:serviceaccount:*:garden-in-cluster-builder"
                },
                "StringEquals": {
                    "oidc.eks.<region>.amazonaws.com/id/<oidc-provider-id>:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

### Your environment

* **OS:** Linux AL2023
* **How I'm running Kubernetes:** EKS
garden version 0.13.29

**Comment by twelvemo** [comment]
Hi @alexkuretz , you are absolutely correct, sorry you lost a couple of hours over this. Will create a PR with a fix right away.
