### ISSUE TITLE
[FEATURE]: Return outputs from terraform as json string

### ISSUE THREAD

**Issue by ITHedgeHog** [garden-io/garden#6046]
### Background / Motivation

We use Azure CLI to set the secrets based on terraform output - when we put all of these outputs together it is longer than the buffer (9K characters).

We would like to access the entire outputs as a json string.

### What should the user be able to do?

access ${actions.deploy.<name>.outputs.* as a json string.

### Why do they want to do this? What problem does it solve?

I can't use terraform in garden for any members of my team using Windows.

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

**Comment by twelvemo** [comment]
Hi @ITHedgeHog , this actually already works if you use the `jsonEncode` template helper function, since `outputs` is a plain object e.g.: `${jsonEncode(actions.deploy.tf.outputs)}` or `${jsonEncode(providers.terraform.outputs)}`.
