### ISSUE TITLE
`cleanup deploy` for CRs does behave as you would think

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#6074]
### Current Behavior

I'm running [CNPG](https://github.com/cloudnative-pg/cloudnative-pg). The helm chart defines CNPG CRDs (namely `Cluster` and `Backup`) and installs a controller for them.

In my garden stack I am deploying different `Cluster` and `Backup` resources (via `helm` and plain `kubernetes` Deploy actions), which works as expected.
However, I have found that running `cleanup deploy ...` for the garden actions does not remove the CRs from the Kubernetes API.

### Expected behavior

I would expect Garden to clean up all API resources deployed and not just "normal" ones like `Deployment` etc.

### Reproducible example

I can if you can't reproduce, but the behavior is plain enough.

### Workaround

I typically can go "nuclear" and run `cleanup namespace` which just deletes the whole namespace.

### Suggested solution(s)

I'm not sure if you can automatically track CRs deployed through garden actions, but this would be ideal.

Next would be to allow for some cleanup options to specify what to cleanup for `Deploy` action types. Similar to the cleanup option for the `exec` Deploy action type, but for all of them.

### Your environment

* **OS:** OpenSuse Tumbleweed
* **How I'm running Kubernetes:** GKE

`garden version`
garden version: 0.13.30

**Comment by twelvemo** [comment]
The delete handler for Helm deploys calls `helm uninstall`. Can you check if `helm uninstall` without garden removes the CRs?
I am curious about the Kubernetes deploy actions though. Can you check if the CRs contain a label with `garden.io`? We delete those resources by label.

**Comment by salotz** [comment]
> The delete handler for Helm deploys calls helm uninstall. Can you check if helm uninstall without garden removes the CRs?

I'm looking into this. It might be an issue with the way Helm handles resources created during hook stages.

I'll look into the other resources when I have the chance.

**Comment by salotz** [comment]
@twelvemo indeed the first part of this was due to a misunderstanding on my part of how Helm manages resources created during hooks.

I will close for now as it might be a while until I can repro the other part, and probably I was just confused.
