### ISSUE TITLE
A typo in `garden util profile-project` command description

### ISSUE THREAD

**Issue by omry-arpaly** [garden-io/garden#6202]
### Current behavior
command:
``` garden util```
output:
```USAGE
  garden util <command> [options]

COMMANDS
  util fetch-tools      Pre-fetch plugin tools.
  util hide-warning     Hide a specific warning message.
  util mutagen          Run any Mutagen CLI command in the context of the current project.
  util profile-project  Renders a high-level sumamry of actions and modules in your project.
                                             ^^^^^^^
```

### Expected behavior
Same thing, without the typo :-)
### Suggested solution(s)

Fix it in these files:
[docs/reference/commands.md](https://github.com/garden-io/garden/blob/ed4d038a56e9dfb1792610f777b2ce01a2a0702b/docs/reference/commands.md?plain=1#L5927)
[core/src/commands/util/profile-project.ts](https://github.com/garden-io/garden/blob/ed4d038a56e9dfb1792610f777b2ce01a2a0702b/core/src/commands/util/profile-project.ts#L20)

### Your environment

garden version: 0.13.31

### Note
I could have done it myself, given permissions to branch and create a PR 🙏

**Comment by vvagaytsev** [comment]
HI @omry-arpaly! Thanks for reporting this!

I've already created a quick PR for this :) If you want to contribute, then you'll have to fork the Garden repo and create a PR from there. Please see out contributing guidelines for more details.

**Comment by omry-arpaly** [comment]
Cool @vvagaytsev!
Thanks! :-)
