### ISSUE TITLE
0.13: [Bug]: npm ci missing from garden plugins pulumi preview command

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6256]
`garden plugins pulumi preview` command is not installing the npm packages while it was doing it in previous 0.12 garden version.

Captured below logs with garden 0.12 version

> ℹ thx-gcs-iam-package       → Getting build status for v-c0e68e517e...
> ℹ thx-gcs-iam-package       → Building version v-c0e68e517e...
> ℹ thx-gcs-iam-package       → [npm ci]: npm warn deprecated @opentelemetry/api-metrics@0.32.0: Please use @opentelemetry/api >= 1.3.0
> ℹ thx-gcs-iam-package       → [npm ci]: 
> ℹ thx-gcs-iam-package       → [npm ci]: added 321 packages, and audited [32](https://github.com/X/123#step:6:33)2 packages in 7s
> ℹ thx-gcs-iam-package       → [npm ci]: 
> ℹ thx-gcs-iam-package       → [npm ci]: 43 packages are looking for funding
> ℹ thx-gcs-iam-package       → [npm ci]:   run `npm fund` for details
> ℹ thx-gcs-iam-package       → [npm ci]: 
> ℹ thx-gcs-iam-package       → [npm ci]: 2 moderate severity vulnerabilities
> ℹ thx-gcs-iam-package       → [npm ci]: 
> ℹ thx-gcs-iam-package       → [npm ci]: To address all issues, run:
> ℹ thx-gcs-iam-package       → [npm ci]:   npm audit fix
> ℹ thx-gcs-iam-package       → [npm ci]: 
> ℹ thx-gcs-iam-package       → [npm ci]: Run `npm audit` for details.
> ✔ thx-gcs-iam-package       → [npm ci]: Run `npm audit` for details. → Done (took 7.2 sec)
> ℹ thx-gcs-iam-infra         → Running pulumi preview

Captured below logs with garden 0.13 version

> ℹ garden                    → Initializing...
> Project is configured with `apiVersion: garden.io/v0`, running with backwards compatibility.
> ⚠ garden-cloud              → You are not logged in. To use Garden Cloud, log in with the garden login command.
> ℹ garden                    → Running in environment dev.default
> Running pulumi preview for actions thx-gcs-iam-infra 
> 
> ℹ providers                 → Resolving providers...
> ℹ pulumi                    → Configuring provider...
> ✔ pulumi                    → Provider configured
> ✔ pulumi                    → Provider ready
> ✔ providers                 → Finished resolving providers (took 0.1 sec)
> ℹ providers                 → Resolving providers...
> ℹ exec                      → Configuring provider...
> ✔ exec                      → Provider configured
> ✔ exec                      → Provider ready
> ✔ providers                 → Finished resolving providers (took 0 sec)
> ℹ graph                     → Resolving actions and modules...
> ✔ graph                     → Finished resolving graph (took 0.4 sec)
> ℹ garden                    → Finished initializing Garden (took 1.8 sec)
> 
> 
> ℹ deploy.thx-gcs-iam-infra  → Running pulumi preview
> ✖ deploy.thx-gcs-iam-infra  → Failed (took 4.1 sec)
> ✖ deploy.thx-gcs-iam-infra  → Failed processing Deploy type=pulumi name=thx-gcs-iam-infra (from module thx-gcs-iam-infra) (took 4.11 sec). This is what happened:

npm-ci is completely missing from 0.13 garden version logs.

**Expected behaviour** 
garden plugins pulumi preview command should install the npm packages and then trigger the pulumi preview 

**Actual behavirour**
garden plugins pulumi preview command only trigger the pulumi preview command which got failed because of absence of npm modules.

**Comment by ishantagarwal-x213235** [comment]
Thanks @thsig for response. I sent an email with detail logs for both version. Pl take a look and let me know in case of any more info required.

**Comment by ishantagarwal-x213235** [comment]
Kindly update the progress @thsig

**Comment by thsig** [comment]
@ishantagarwal-x213235 I think the PR for this should be good to go now (once the tests are passing in CI). After it's been merged, it will be included in the next release.

**Comment by ishantagarwal-x213235** [comment]
Thanks @thsig

**Comment by vvagaytsev** [comment]
@ishantagarwal-x213235 we released the fix in [0.13.34](https://github.com/garden-io/garden/releases/tag/0.13.34).
