### ISSUE TITLE
CLI returns exit code 1 when help or --version args passed

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#626]
The following commands return exit code `1` instead of `0`:

```sh
garden --version
garden help
```

Note that `garden --help` returns `0` as expected and `garden version` returns `0` if in a project directory but fails with `Not a project directory (or any of the parent directories): ...` otherwise.

**Comment by eysi09** [comment]
We need to fix this for Garden to work properly in CI.

**Comment by edvald** [comment]
Hmm, why is that?

**Comment by eysi09** [comment]
Well, this was kind of poorly phrased, Garden works fine in CI regardless.

The above was more of a note to self since I'm trying Garden on different CI systems and like to verify that it's properly installed on the agent by running `garden --version`. However, that causes the CI job to fail because it returns exit code `1`.

**Comment by eysi09** [comment]
Closed in #669
