### ISSUE TITLE
[FEATURE]: Module as job / cronjob in kubernetes

### ISSUE THREAD

**Issue by fabianboerner** [garden-io/garden#6321]
### Background / Motivation

We would like to have microservices that run as triggered jobs or scheduled cronjobs

### What should the user be able to do?

Add a schedule definition to a module

### Why do they want to do this? What problem does it solve?

Modules that are idle can be run if needed.

### Suggested Implementation(s)

Add a section for cronjobs scheduling in the garden.yaml file.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

Pretty important because we are running a node module that needs 2 - 6 GB of ram but for spikes if needed all the time this is driving out cluster costs up. To not make this a custom kubernetes deployment without the benefit of garden its crucial for us to not change the development cycle.

**Comment by twelvemo** [comment]
@fabianboerner you can use a kubernetes action to deploy any kind of kubernetes resource including `jobs` and `cronjobs` with garden see https://docs.garden.io/kubernetes-plugins/actions/deploy/kubernetes.

Does this answer your question or if not feel free to share some more context?

**Comment by fabianboerner** [comment]
Ok, i have overlooked that thank you.

Von: Anna Mager ***@***.***>
Datum: Dienstag, 30. Juli 2024 um 15:33
An: garden-io/garden ***@***.***>
Cc: Fabian Börner ***@***.***>, Mention ***@***.***>
Betreff: Re: [garden-io/garden] [FEATURE]: Module as job / cronjob in kubernetes (Issue #6321)

@fabianboerner<https://github.com/fabianboerner> you can use a kubernetes action to deploy any kind of kubernetes resource including jobs and cronjobs with garden see https://docs.garden.io/kubernetes-plugins/actions/deploy/kubernetes.

Does this answer your question or if not feel free to share some more context?
