### ISSUE TITLE
crashing with SYNCHRONOUS TERMINATION NOTICE error

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6322]
We've have observed crashing many times with garden when using ```garden deploy``` command with pulumi provider.

> SYNCHRONOUS TERMINATION NOTICE: When explicitly exiting the process via process.exit or via a parent process, asynchronous tasks in your exitHooks will not run. Either remove these tasks, use gracefulExit() instead of process.exit(), or ensure your parent process sends a SIGINT to the process running this code.
> node:events:498
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
>     at _write (node:internal/streams/writable:481:11)
>     at Writable.write (node:internal/streams/writable:502:10)
>     at Socket.ondata (node:internal/streams/readable:1007:22)
>     at Socket.emit (node:events:532:35)
>     at Socket.emit (node:domain:488:12)
>     at Readable.read (node:internal/streams/readable:780:10)
>     at Socket.read (node:net:772:39)
>     at flow (node:internal/streams/readable:1281:53)
>     at resume_ (node:internal/streams/readable:1260:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Emitted 'error' event on Transform instance at:
>     at Transform.onerror (node:internal/streams/readable:1026:14)
>     at Transform.emit (node:events:532:35)
>     at Transform.emit (node:domain:488:12)
>     at emitErrorNT (node:internal/streams/destroy:170:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   code: 'ERR_STREAM_WRITE_AFTER_END'
> }

**Comment by thsig** [comment]
Hi @ishantagarwal-x213235, thanks for reporting this.

Do you have any more logs or details to share around this?

Also, do you know how often this happens? Does this always happen in this project or more like 30% of the time? Just trying to narrow down the causes.
