### ISSUE TITLE
Build dependencies are not watched when watching a particular service

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#633]
### Current Behavior

When running `garden deploy some-service --watch`, where `some-service` has a build dependency, modifying the build dependency does not trigger a reload.

### Expected behavior

I'd expect the service to be re-built and re-deployed.

### Reproducible example

In `examples/hello-world`, run `garden deploy hello-container -w`. Then modify a file in `hello-npm-package`.

### Suggested solution(s)

When running `garden deploy -w` for a specific service, we ignore watch events for modules other than the service's parent module. We should include its build dependencies.

### Additional context

This is not an issue for `garden dev` or when running `garden deploy -w` without specifying a service to watch.

### Your environment

Latest master.

**Comment by 10ko** [comment]
Fixd in #761
