### ISSUE TITLE
Crash: Synchronization monitor has crashed 10 times. Aborting

### ISSUE THREAD

**Issue by caitlynachen** [garden-io/garden#6345]
## Crash report

Failed resolving status for Deploy type=kubernetes name=bazel-kube (from module bazel-kube) (took 2.16 sec). This is what happened:
Synchronization monitor has crashed 10 times. Aborting.
### Your environment

* **OS:** 
* **How I'm running Kubernetes:** 
* **Garden version:**

**Comment by vvagaytsev** [comment]
Hi @caitlynachen!

Thanks for reporting this! What Garden version have you used?
Please note, that starting from the version 0.13.33, Garden uses a new sync Daemon.
So, it order to make it working, you should stop the old sync Daemons, see the [troubleshooting instructions](https://docs.garden.io/guides/code-synchronization#restarting-sync-daemon).

Those instructions should have been displayed in the error message as a hint to fix it. Could you please provide the full console output as a part of the issue description?

Please let us know if the Daemon restart doesn't help.

**Comment by 10ko** [comment]
Hi @caitlynachen, I am going to close this, feel free to reopen if the solution by @vvagaytsev is not working.
