### ISSUE TITLE
[Bug]: `garden login` fails (401 - Unauthorized)

### ISSUE THREAD

**Issue by fosskers** [garden-io/garden#6431]
### Current behavior

The [Garden Docs](https://docs.garden.io/kubernetes-plugins/ephemeral-k8s/login-web-dashboard) say that no extra configuration is necessary for `garden login` to work, and that used to be the case for me until today. `garden dev` fails to open access to the Dashboard, and a standalone `garden login` call yields:

```
An error occurred while verifying client auth token with the Garden dashboard: Response code 401 (Unauthorized). Response status code: 401
```

But it's not clear to me what it's trying to authorize against, or what token it's attempting to do it with.

### Expected behavior

I can use `garden login` and `garden dev` as advertised.

### Reproducible example

1. Install and use `garden` with success.
2. Wait 2 months.
3. Attempt `garden dev` again to implement a new feature in a work project.
4. Be denied.
5. Install newest version.
6. Notice it still happens.
7. Ask for help on Github.

Humour aside, let me know if there is any other information I can provide.

### Your environment

* **OS:** Arch Linux
* **How I'm running Kubernetes:** Rancher
* Version: 0.13.39

**Comment by fosskers** [comment]
It turns out that a manual `garden logout` was necessary. It likely cleared out something stale in some cache somewhere, after which a `garden login` then worked.

**Comment by eysi09** [comment]
Hi @fosskers 

Happy to hear you solved this since it would've taken a while to reproduce. Feel free to reopen if you bump into this again. We did roll out some minor changes around the auth token recently which might be related. 

Also, the error message is obviously not good enough, we'll look into that.

**Comment by alexkuretz** [comment]
My devs have been complaining that they are needing to logout/login daily after the most recent self-update, and I've observed it trying to access the dashboard. Auth used to persist until recently.
