### ISSUE TITLE
[Bug]: You need to define an absolute base url for the server

### ISSUE THREAD

**Issue by maxim-cpg** [garden-io/garden#6476]
### Current behavior

Trying to setup remote k8s cluster I got into some weird state that i'm not sure what to do. 
We have remote cluster in our local LAN which is open via `kubectl proxy`. I can access cluster from my local machine and run `kubectl` commands without problems. However, when I try to use the same cluster within garden it fails with:
```
✖ providers                 → Failed processing resolve provider kubernetes (took 0.02 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error while performing Kubernetes API operation readNamespace: Error

You need to define an absolute base url for the server.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed resolving one or more providers:
- kubernetes
```

### Expected behavior

Able to use remote k8s cluster or at least have an error which explains the problem.

### Additional context

Config:
```
- name: kubernetes
    environments: [preview]
    context: beast-context
    namespace: ${environment.namespace} # <--- Ensure the K8s namespace matches the Garden namespace
    defaultHostname: ${var.base-hostname}
    deploymentRegistry:
      hostname: australia-southeast1-docker.pkg.dev
      namespace: default
    imagePullSecrets: # You can set multiple secrets here
      - name: gar-config
        namespace: default
```
Secret is configured on remote cluster and it seems that it's failing before that.
kubeConfig:
```
apiVersion: v1
clusters:
- cluster:
    server: http://192.168.10.25:8080
  name: beast-cluster
contexts:
- context:
    cluster: beast-cluster
    user: ""
  name: beast-context
current-context: beast-context
```
### Your environment

* **OS:** Mac OS 14.6.1 (23G93)
* **How I'm running Kubernetes:** Remote Cluster(OrbStack). Proxied using kubectl proxy. 

garden version: 0.13.39

**Comment by twelvemo** [comment]
@maxim-cpg just a few questions to help understand what might be going on:
1. Is kubectl proxy running on your local machine?
2. Just to make sure even though you already posted your kubeconfig: There is no additonal proxy config in the kubeconfig see https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy
3. What is the proxy needed for? Is the k8s api not reachable in the local network without the proxy? And if it is proxied to localhost why is the address in the address in the kubeconfig not on localhost?

Note: i might make wrong assumptions here, just trying to understand the setup a bit better.

**Comment by maxim-cpg** [comment]
1. Kubectl proxy is running on a remote server which is located in our office.
2. We ran proxy via daemon like that `kubectl proxy --api-prefix=/ --accept-hosts="^.*" --port=8080 --address=0.0.0.0` no any other extra configs. 
3. Good question, I couldn't figure out an easy authentication mechanism for kubectl. I couldn't use x509 cert because that only works for `127.0.0.1,localhost` ip address. Actually created an [issue](https://github.com/orbstack/orbstack/issues/1456) in orbstack to try to resolve it.

**Comment by twelvemo** [comment]
Ah i see that explains the `You need to define an absolute base url for the server.` error message. Happy it is working now. I will close this issue now, but let us know if you run into more issues with garden.
