### ISSUE TITLE
[Bug]: Opentelemetry missing span when using "-o yaml" option

### ISSUE THREAD

**Issue by har-cpol** [garden-io/garden#6482]
### Current behavior

When opentelemtry is enabled, and using "-o yaml" on any command, the last span generated references an unexisting parent span.

![image](https://github.com/user-attachments/assets/05aa0b93-ddaf-4fa6-ba6a-494bb6df71b1)

On the image:
- Last span has parentId: '2469d70b49e96758'
- No span has been exported with this spanId

In fact, there is no root span at all in this trace - so I expect that the root span is not correctly sent.

### Expected behavior

All spans should be exported. 
E.g. when we do not add the "-o yaml" option:

![image](https://github.com/user-attachments/assets/0e99b3c6-6214-48c9-823e-a417201835ff)

Here we do have the root span exported (last one: parentId is undefined)

### Reproducible example

Any command that supports -o yaml:
- OTEL_TRACES_EXPORTER=console garden get version -o yaml
- OTEL_TRACES_EXPORTER=console garden get status -o yaml
- OTEL_TRACES_EXPORTER=console garden get test result mytest -o yaml

### Workaround

none

### Suggested solution(s)

I suspect some span not correctly finished - but I'm not an expert on opentracing api JS

### Additional context

- There was no trace parent defined in my environment variables (no OTEL_TRACE_PARENT or TRACEPARENT env variable set)
- On the example runs, I did not have the opentelemtry provider. I did try it before, and if I remember correctly it had same result

### Your environment

* **OS: Fedora Linux** 
* **How I'm running Kubernetes: N/A**

`garden version`

garden version: 0.13.38

**Comment by eysi09** [comment]
Thanks for the bug report and repro! We'll look into this.
