### ISSUE TITLE
Use & maintain our own rsync sidecar container image

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#666]
Currently, we're using this image for our rsync sidecar container: https://hub.docker.com/r/eugenmayer/rsync

I believe this is the image used by Docker Sync for their rsync option.

So far, hot reloading for the Kubernetes plugin has been the only place we use an rsync sidecar container.

Our remote building functionality will also make use of an rsync sidecar container, so we'll likely start wanting more control over the specifics.

We should either use an explicit version of `eugenmayer/rsync` or make our own fork.

**Comment by edvald** [comment]
We might actually consider just switching to Mutagen, instead of going through extra work for a stopgap implementation.
