### ISSUE TITLE
Dashboard: Add container select when there are more than one in the service's pod

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#678]
We should add a container select to the dashboard UI when there's more than one container in the service's pod — e.g. to the right of the service dropdown on this screenshot.

![Screenshot 2019-03-28 at 13 20 25](https://user-images.githubusercontent.com/382137/55157307-5cf65780-515c-11e9-976d-3fab301d4079.png)

This would e.g. be useful for services that include a noisy sidecar container.

**Comment by eysi09** [comment]
Is this possible with the `logs` command? The dashboard just calls `garden logs`.

**Comment by eysi09** [comment]
@thsig ^

Shouldn't we start at the CLI level and then implement the dashboard UI? So it's more of an issue of adding a `--container` flag to the logs command.

**Comment by edvald** [comment]
I don't think that makes a lot of sense. "Container" isn't a concept that Garden itself should be natively aware of. We'd need to think about some more generic structure, which feels like fairly low priority considering the effort.
