### ISSUE TITLE
Hot reload doesn't work if service already deployed

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#686]
## Bug

If a service is already deployed and ready, doing `garden dev --hot my-service` won't re-deploy it with the rsync sidecar container. The status check simply reports that the service has already been deployed.

### Current Behavior

If you try hot re-loading a service that's already been deployed you get the following error:

```
Failed hot-reloading service node-service. Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed: rsync -vrptgo /Users/eysi/code/garden-io/garden/examples/hot-reload/node-service/ rsync://lo
calhost:52515/volume/app/
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1677) [sender=3.1.3]
————————————————————————————————————————————————————————————————————————————————
```

...because there's no rsync container for rsync to connect to.

You can verify this by doing `kubectl get pods -n hot-reload` and note that the node-service pod has only 1 container.

### Expected behavior

The rsync command should find its target and the service should hot reload.

### Reproducible example

```
cd examples/hot-reload
garden deploy
garden dev --hot node-service
touch node-service/foo.txt
```

### Your environment

`garden version`

Latest `master`

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
```
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by eysi09** [comment]
Current workaround is to make sure the service hasn't been deployed before running a command with the `--hot` flag. If it is already deployed, delete it with:
```sh
garden delete service my-service
```
and then run the hot reload command again:
```sh
garden dev --hot my-service
```
(or `garden deploy --hot my-service`).

**Comment by edvald** [comment]
I did a cursory look, and it seems `kubectl diff` is incorrectly reporting the deployed service to match the resources with hot-reload enabled. ☠️ I'll investigate why the %!" that could be.

**Comment by thsig** [comment]
Should we go back to adding/using a `"garden.io/hotReload" = "true" | "false"` flag in the metadata of k8s deployments for making comparisons in this case? Or just look for the presence of a sidecar container with the appropriate name?

Given how buggy/flaky/ill-specified the diffing logic in `kubectl` is, I wonder whether we should just take this sort of thing into our own hands when it's framework stuff, and we are able to have full control. @edvald

**Comment by edvald** [comment]
The issue isn't how we formulate the deployments, but rather how the diff actually happens. I'd started some work on this, was hoping to finish on Friday but didn't quite get it done. Let's review that tomorrow.

**Comment by thsig** [comment]
Yeah, good point. Ideally, we'd make the diffing work in general, but if not, I was just wondering whether we should have our own, separate track of comparison logic in addition to the diffing, to detect any varieties of differentness that kubectl seems to ignore. I.e. 
```
if (kubectl thinks it's different || the framework thinks it's different) {
  'tis different
}
```
