### ISSUE TITLE
Implement custom arguments for the run task command

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#692]
For some tasks, it can be useful to pass arguments when running the task via the run task command.

An example is `rake db:migrate` and friends.

To illustrate, here are a few variants:
```
rake db:rollback
rake db:rollback STEP=2
rake db:migrate VERSION=20080906120000
```
This could be parametrized in a module's config as follows:
```yaml
kind: Module
type: container
...
tasks:
  - name: rake-db
    args: [rake db:$1 $2] 
    defaults: [migrate]
```
This would be reflected in the CLI as follows:
```
garden run task rake-db
# => rake db:migrate

garden run task rake-db rollback
# => rake db:rollback

garden run task rake-db migrate VERSION=20080906120000
# => rake db:migrate VERSION=20080906120000

garden run task rake-db VERSION=20080906120000
# => rake db:VERSION=20080906120000, which will result in an error
```
I don't have a strong opinion on how all this should be designed, but I suspect this may bring up a larger discussion about how our CLI handles arguments/options.

This is not an urgent feature (although it would be very nice for users of many frameworks), so we should feel free to take our time discussing the design implications.

**Comment by BlacKCaT27** [comment]
I think this is a great idea and would love to see it extended to every `run` command. For example, I would love to be able to say something like `garden run test <module name> <tests name> **<args to be passed down into dockerfile>**`

Then I could modify the dockerfile to conditionally run either all tests or only pass the test names passed in as an ARG to the executed test runner. This way, I can use garden to run full end-to-end tests, but can easily execute just a single end-to-end test (say, while I'm writing new ones), without having to tweak the garden file every time.
