### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#717]
Our contributing docs have become a little stale. The following needs updating:

- [x] Update commit types section in CONTRIBUTING.md
- [x] Add section about pre-commit checks to CONTRIBUTING.md
- [x] Add a step to release process for acknowledging external contributors.
- [x] Add "improvement" commit type to changelog config
- [x] Fix `garden serve` path, should be inside an example project
- [x] Fix debugging setup and update relevant docs. (Our current method of debugging doesn't work on the latest versions of Chrome. Browser extensions don't work either.)

**Comment by thsig** [comment]
Here's a suggested addition to the contributing docs:
> If you’ve created a prerelease, e.g. `v1.2.3-0`, and want to create a new prerelease `v1.2.3-1` which includes changes made on master since `v1.2.3-0` was created, do the following:
> 1. `git checkout v1.2.3-0`
> 2. `git rebase master`
> 3. `./bin/release.ts prerelease`
> 
> When you’re ready to release, check out `master` again and run `./bin/release.ts` with `minor` or `patch`. This way, the version bump commits created by the prereleases are omitted from the final history.

**Comment by eysi09** [comment]
Debug setup is still broken but at least it's documented.
