### ISSUE TITLE
Cannot read property 'detail' of undefined

### ISSUE THREAD

**Issue by phluks** [garden-io/garden#729]
## Bug

I attempted to go through your [quick-start](https://docs.garden.io/basics/quick-start)

### Current Behavior

When I run
`garden get status`

I get this error
`Cannot read property 'detail' of undefined`

### Expected behavior

No error

### Reproducible example

I'm not sure. I guess it works for you

### Additional context

I'm running Ubuntu 18.04 Linux.
I was quite confused by the [installation guide](https://docs.garden.io/basics/installation#step-4-install-garden-cli)

In the end I copied "linux-amd64/garden" from the tar-ball into my path.

I had the same error with both kind and minikube.

Contents of error.log
```
[2019-04-19T21:10:02.756Z] TypeError: Cannot read property 'detail' of undefined
    at Object.<anonymous> (/snapshot/project/garden-service/tmp/dist/build/plugins/kubernetes/init.js:120:77)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/plugins/kubernetes/init.js:11:58)
```

### Your environment
Ubuntu 18.04 Linux.

```
which garden
/home/olav/bin/garden
```

```
garden version
0.9.10
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Mon Oct  1 14:25:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon Oct  1 14:25:33 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
### Also
I hope this is useful.
Let me know if I can help.

**Comment by eysi09** [comment]
Hi @phluks and thanks for pointing this out!

We'll look into this as soon as we're back from Easter holiday on Tuesday. In the mean time, you could try installing [v0.9.9](https://github.com/garden-io/garden/releases/tag/v0.9.9).

We'd also be happy to hear what you found confusing about the installation guide, we're always looking to improve our docs.

**Comment by phluks** [comment]
Hi @eysi09 

I could not find any static release, cloned the repo and checked out v0.9.9

I ran "npm install" which ended with this warning
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
```
Both garden executables throws an error.
```
$find ./ -name garden
./bin/garden
./garden-service/static/bin/garden
$ bin/garden
module.js:549
    throw err;
    ^

Error: Cannot find module '../../build/cli/cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/olav/repos/garden/garden-service/static/bin/garden:3:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by eysi09** [comment]
The original error is because the `static` directory that's in the tar-ball is missing. We use [Zeit/Pkg](https://github.com/zeit/pkg) to package the Node.js project into a binary but we've had to keep the static files separate.

As a result, you'll need to put the entire contents of `linux-amd64/garden` into its own directory, e.g. `/usr/local/garden` and add that to the path. 

So `/usr/local/garden` would include both the `garden` binary and the `static` directory.

And you're right that the installation guide could be clearer in this regard. I'll create a separate issue for that. 

As for the error above, it sounds like you didn't build the code before running it. [The instructions for setting up the dev environment](https://github.com/garden-io/garden/blob/master/CONTRIBUTING.md#setting-up-your-development-environment) are in our CONTRIBUTING docs.

**Comment by eysi09** [comment]
Here's the issue for the doc fix #732.

**Comment by edvald** [comment]
We should also catch this more explicitly, and give better error messages when this happens.

**Comment by tubasbelang** [comment]
https://bit.ly/3u0A1KN
