### ISSUE TITLE
Running multiple garden commands that trigger builds at same time is likely to fail

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#73]
... or cause inconsistent/valid builds.

This could be resolved using locks at the file-system level, by staging builds differently or even using a daemon process to make sure a single task-graph runs for the user.

Other concurrent/conflicting tasks, such as tests and deployments, could also fail or cause issues (depending on how the providers are implemented) but conflicting build tasks are most likely to have a negative impact.

**Comment by eysi09** [comment]
Note that this will be resolved once we've daemonised Garden which we're actively working on.

**Comment by garoose** [comment]
Hey I just wanted to say that this is still causing us trouble. We had to create separate modules for all of our tests (unit/contract/integration/etc.) to avoid them running over each other in the same namespace and failing. The workaround works but unfortunately makes things slower as it has to build the image 3+ times. I was wondering if you have any other workaround ideas or a timeline on daemonization?

Thanks!
Josh
