### ISSUE TITLE
Istio example fails to deploy

### ISSUE THREAD

**Issue by jpreese** [garden-io/garden#735]
### Current Behavior

Istio example fails on the `garden deploy` step, specifically for trying to deploy the bookinfo-gateway service. Sometimes it can't find the gateway, sometimes it can't find the VirtualService. The status code is HTTP 404.

### Expected behavior

Istio deploys successfully.

### Reproducible example

Attempt to deploy the Istio example

### Your environment

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by eysi09** [comment]
Hi @jpreese! Did #736 resolve this?

**Comment by jpreese** [comment]
Yep!
