### ISSUE TITLE
Garden doesn't always push modules for remote envs

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#767]
### Current Behavior

Garden currently doesn't check if a given container image exists in a remote container registry. Instead, it will falsely assume that the image exists remotely if it exists locally.

Consider the following:

1. The remote registry is up to date and contains `my-image:v1`.
2. The user now switches to a local environment, changes the module containing `my-image` and Garden builds and tags it as `my-image:v2`, available locally.
3. The user now switches back to the remote environment and does a `garden deploy`. 

Garden won't detect any changes to the module and will therefore not re-build the image and by extension not push it, since pushing is now a part of the build step (see #754). The remote pod will however look for `my-image:v2` in the remote registry and fail with with a `ErrImagePull` or `ImagePullBackOff` 

### Expected behavior

In step 3 above, I expect Garden to check if `my-image:v2` exists in the remote registry and if not, push it.

### Reproducible example

Follow the steps above.

### Workaround

Run `garden build --force` if you expect the remote registry is not up to date.

**EDIT**:

Note that this is generally not an issue when using in-cluster building with `cluster-docker` or `kaniko`. Read more about [in-cluster building here](https://docs.garden.io/using-garden/in-cluster-building). 

### Suggested solution(s)

As previously suggested, Garden should check if an image exists remotely and push if it can't find it. In general this is non-trivial since different registries may have different image name formats. Perhaps we can use the solution suggested in this [blog post on Inspecting Docker images without pulling them](https://hackernoon.com/inspecting-docker-images-without-pulling-them-4de53d34a604). Then there's also [Skopeo](https://github.com/containers/skopeo).

### Your environment

Latest `master`.

```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

```sh
docker version
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by eysi09** [comment]
As a quick fix, we add could something like a `remoteImagePath` to the schema and have Garden use that to check if the image exists. Not the best UX but could work until we find a more permanent solution.

@edvald, thoughts?

**Comment by edvald** [comment]
I don't believe that's helpful, since the issue is really at the API level. I think we just need to implement something akin to Skopeo. Kinda too bad that it doesn't distribute static binaries, otherwise it'd be much simpler to add.

**Comment by edvald** [comment]
A different workaround would be to _always_ push when applicable. Suboptimal, but solves the issue.
