### ISSUE TITLE
Files will spaces break build/dev/deploy commands

### ISSUE THREAD

**Issue by dylanfoster** [garden-io/garden#797]
### Current Behavior

<img width="1053" alt="Screen Shot 2019-05-29 at 6 47 16 AM" src="https://user-images.githubusercontent.com/5842737/58562191-a0615680-81dd-11e9-8786-6b3f822b7968.png">

**added the console logs here**

### Expected behavior

Commands are successful

### Reproducible example

https://github.com/dylanfoster/garden-test

### Workaround

none

### Suggested solution(s)

Join paths separated by space with some character or better support for ignoring node_modules (and other deps)

### Your environment

`garden version`
0.9.12

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by edvald** [comment]
Thanks for the report! We'll dig into this. 

Meanwhile, you can work around the `node_modules` issue specifically by adding a `.gardenignore` file with an entry for `**/node_modules`. Same syntax as .gitignore files. Or you can use the `include` field on modules to explicitly state files to be included.

@eysi09 we should add more prominent docs for file inclusions and exclusions. They're kinda buried at the moment in references (https://docs.garden.io/reference/config#include).

**Comment by edvald** [comment]
I've reproduced this, fixing now.
