### ISSUE TITLE
Dashboard: Separately query status for providers and each module

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#827]
Currently we have to wait a while before any status is reported on the dashboard. To some degree we can improve this on the service side, but we can improve a lot by querying separately per-module and for providers.

We'd need new commands to serve each, or to allow filtering by provider, service, module etc. in the existing `get status` command. 

I think my preference would be to keep the `get status` command as-is for now and add `get provider-status` and `get service-status` commands, if only because it's easier to do and likely clearer from an API perspective (for example, easier to get a list of all providers if there's a dedicated command that defaults to all providers, unless you add arguments). But I can be persuaded either way tbh.

**Comment by thsig** [comment]
Do we generally expect requests for provider statuses to be faster than for modules? Or is the intuition that several smaller requests will lead to the user seeing incremental results before the whole thing is done?

**Comment by edvald** [comment]
Actually the provider statuses may sometimes take longer, because more things are checked. In any case, the issue is rather that the whole UI feels slow because we essentially wait for the slowest check to finish and then display everything.

**Comment by thsig** [comment]
Yeah, that's true. However, we should probably enact some sort of batching here, since (as I understand it) all major browsers limit the number of concurrent connections, the current caps being somewhere in the region of 5-15 (usually closer to 5 for a given hostname).

That ceiling starts to be relevant for projects with more than 4-5 modules.

**Comment by edvald** [comment]
That'd also be solvable through HTTP/2 or running this over the WebSocket connection. I wouldn't mind batching as an API feature, but the effort might not be warranted.
