### ISSUE TITLE
[Question] The right way to "shut down" garden for a fresh start

### ISSUE THREAD

**Issue by timonbimon** [garden-io/garden#855]
Another usage question:

After running `garden dev` what is the right way to delete the deployed resources for a fresh start?

I tried `garden delete environment local`, but after doing that and running `garden dev` again I started getting errors complaining about customresourcedefinitions already existing

```
Error: release seldon-core-operator failed: customresourcedefinitions.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" already exists
```

which after manually deleting them led to the next error of

```
Error: UPGRADE FAILED: "seldon-core-operator" has no deployed releases
```

which I could only resolve by manually using helm to delete --purge the release, which led me down a rabbit hole of a few other errors before finally being able to run `garden dev` again.

**Comment by edvald** [comment]
You actually had the right idea, and this is a bug. We should be properly purging the Helm releases ahead of deleting the namespaces. We'll see about getting this fixed soon.

**Comment by timonbimon** [comment]
Would be great to have another pre-release with the fixes for this soon! :)

**Comment by 10ko** [comment]
Hi @timonbimon, we are preparing the official release as we speak.
Stay tuned. ;)
