### ISSUE TITLE
Deprecation warning when running garden with node 12.x.x

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#883]
## Bug
When running `garden` with the latest node version the following warning is shown.
```
(node:64017) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
```

### Expected behavior

No warning shown.

### Reproducible example
From the `examples/vote` folder run:
```
nvm use 12
garden dev
```

### Your environment

`garden version: 0.10.0-0`
`node version: v12.1.0`

**Comment by edvald** [comment]
Downgrading to low priority because this is mostly cosmetic, but should in turn be easy to fix.

**Comment by eysi09** [comment]
Is this still an issue @10ko?

**Comment by 10ko** [comment]
I managed to build with 12.x and it looks like this is not happening anymore.
Closing.
