### ISSUE TITLE
Use numeric log levels instead of (or in addition to) named levels?

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#89]
Just a thought. I for one always get confused as to which is more verbose, "verbose" or "debug". And I can imagine us wanting to set multiple levels at some point.

For example, in `kubectl` you can set `--v=8` to dump a lot of logs. We could for example alias the named levels to the numeric levels (0=error, 1=warning, 2=info etc.), and perhaps make `l` an alias for `--loglevel` to make it more concise.

**Comment by eysi09** [comment]
Fixed in #194
