### ISSUE TITLE
Only rebuild on last save when running "garden dev"

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#894]
When running `garden dev` the filesystem is watched and any change will trigger a new build/deploy/tests run.
This also mean that if a user presses 5 times save in 5 seconds Garden will schedule 5 build/deploy/tests runs.

Feature: make Garden interrupt the current run if a user changes a file and restart it.
It might need investigation on how to do it gracefully (I can think of before/after or db to dump for tests) and other stuff.

**Comment by edvald** [comment]
@thsig I've been noticing this as well. Kinda feels like it may be a regression actually?

**Comment by thsig** [comment]
Yeah, sounds like a regression. I'll look into this.

**Comment by thsig** [comment]
> Feature: make Garden interrupt the current run if a user changes a file and restart it.
It might need investigation on how to do it gracefully (I can think of before/after or db to dump for tests) and other stuff.

I like this idea, but we should move this into a separate Github issue if we want to pursue it.

This might involve adding plugin handlers for `cancelBuild`, `cancelDeploy` etc., which the task classes in question would wrap in a `cancel` method. The watch logic could then ask the `TaskGraph` to attempt cancelling a given task (if it supports cancelling for the plugin/handler it represents).
