### ISSUE TITLE
Missing errors output for failed tasks/tests

### ISSUE THREAD

**Issue by benstov** [garden-io/garden#927]
### Current Behavior
Not showing the error for failed task
![Screenshot 2019-07-05 at 16 25 07](https://user-images.githubusercontent.com/7339283/60729146-4f622200-9f42-11e9-871e-c9b4f0b0b52a.png)

### Reproducible example
inside /Users/bensimantov/code/garden-io/garden/examples/vote/services/postgres/garden.yml
change "CREATE TABLE IF NOT EXIST..." to "'CREATE TABLE IF NOT EXIST...'"
run dashboard, click on failed task node to fetch the result
result.output is undefined

### Suggested solution(s)
save errors in config graph

**Comment by edvald** [comment]
@thsig is this still an issue?

**Comment by eysi09** [comment]
This appears to work now:

<img width="715" alt="Screenshot 2019-12-08 at 14 55 49" src="https://user-images.githubusercontent.com/5373776/70390399-e1c39180-19ca-11ea-811d-39004f3b907d.png">
