### ISSUE TITLE
Garden doesn't work in project sub directories

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#936]
### Current Behavior

Garden commands fails with:

```
Not a project directory (or any of the parent directories): /path/to/project/some-dir
```

if run in a sub directory of a project.

### Expected behavior

Garden should work in project sub directories.

### Reproducible example

Go to `demo-project`, cd into `frontend` and run `garden validate`. 

### Workaround

Run Garden commands from root.

**Comment by edvald** [comment]
Hmh. I wonder when this broke. Seems we're missing an appropriate test.
