### ISSUE TITLE
Refactor: move tests next to files they belong to

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#941]
Hi 👋,
Currently the tests for `garden-service` live in their own folder, replicating the structure of the `src/` folder. I propose we move the tests inside the `src/` folder, next to the files we are testing, e.g.:
```
src
└─ cli
        └─ commands
                └─ debug.ts
                └─ deploy.ts
                └─ build.ts
                └─ tests
                        └─ debug.test.ts
                        └─ deploy.test.ts
                        └─ build
                                └─ build.test.ts
                                └─ a-complex-example-of-build.test.ts
                                └─ helper-functions-for-build.test.ts
```
This has multiple benefits:
 - It becomes clear whenever something doesn't have a test.
 - There is less maintenance to do whenever the structure of `src/` changes.
 - It's easier to look for tests from the explorer bar in a lot of editors.

The only disadvantages I can think of are:
 - The `src/` folder will become a bit more "crowded".
 - You will need to change your exclude patterns from `test/**/*` to `**/*.test.ts`.

I'd like this to be a discussion, so shoot your opinion at me! 

Thanks,
E.

**Comment by edvald** [comment]
Yeah I'd be in favor of this 👍

**Comment by eysi09** [comment]
Yeah I agree. In particular the _It becomes clear whenever something doesn't have a test_ point.

**Comment by 10ko** [comment]
Alright then,
We'll schedule this for one of the next releases.
Assigned to myself.
✌️

**Comment by edvald** [comment]
This turns out to be quite tricky, especially now that we have multiple test suites. Do we still want to do this?
