### ISSUE TITLE
Built-in upgrade mechanism

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#949]
We currently check whether the user's using the latest version of Garden, but don't provide a simple command to update Garden itself. A built-in upgrade mechanism would make the process a lot easier. We could also consider making it possible for users to enable automatic upgrades.

**Comment by baspetersdotjpeg** [comment]
Bumping this issue again after receiving a notification from the stalebot - I think it's still relevant and a good feature to have, even if it's not super urgent.

With kind regards,

Bas Peters

COO & Co-founder

garden.io ( https://garden.io/ )

*
*

*Garden Germany GmbH * | * * Hermannstrasse 257 | ( https://goo.gl/maps/XwPpJCrDk432 ) 12049 Berlin ( https://goo.gl/maps/XwPpJCrDk432 ) | Amtsgericht Berlin Charlottenburg | HRB 197024 B | Geschäftsführung: Jon Edvald Vignisson & Sebastiaan Peters

**Comment by eysi09** [comment]
FYI @baspetersdotjpeg: You can also remove the stale label to prevent it from being closed.
