### ISSUE TITLE
Run service with a TTY?

### ISSUE THREAD

**Issue by camertron** [garden-io/garden#959]
Is it possible to run a service with a TTY attached? The use case is to be able to use a debugger like [pry](https://github.com/pry/pry). I believe kubectl now lets you run containers in interactive mode, so it should theoretically be possible with garden?

**Comment by eysi09** [comment]
Hi!

You can run a command inside a running service with `exec` command. E.g. `garden exec my-service /bin/sh` to get a shell in there. Would that help your use case?

**Comment by edvald** [comment]
I expect you're looking to run an instance of a service in "debugging mode", as opposed to shelling into a running container? You can do that using `garden run module <module-name> --interactive --command=<your debug command>`. This will essentially wrap `kubectl run` with the appropriate parameters, after building the container etc., so you have a running instance in the cluster, can connect to other services etc.

Another option would be to use [Telepresence](https://www.telepresence.io/), which works nicely alongside Garden and can help in a few ways with debugging.

**Comment by camertron** [comment]
@edvald yes, that's correct. I think `garden run --interactive` will work, thank you :)
