### ISSUE TITLE
Docs: improve GKE provider guide

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#969]
The GKE installation contains wrong information [here](https://github.com/garden-io/garden/blob/47b8e9f5d770b0718ff73102015283a33fd50c7e/docs/using-garden/cloud-provider-setup.md#configure-dns). Pointing an A record at the cluster's MASTER_IP won't automatically resolve the ingresses created by Garden.

**Comment by edvald** [comment]
We also need to that guide to the table of contents, so that it shows up on docs.garden.io.

**Comment by eysi09** [comment]
It's been added to the main docs so we should prioritise this.
