### ISSUE TITLE
In-cluster building fails on Digital Ocean cluster (provisioned by Containership)

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#995]
In-cluster building doesn't work on Digital Ocean clusters provisioned by Containership. Namely, deploying the `garden-build-sync` pod fails with the following error:

```
Pod garden-build-sync-558bcc7f65-qcmx7: FailedMount - (combined from similar events): MountVolume.SetUp failed for volume "pvc-59f8e968-a96c-1
1e9-b2b5-5678f54e885f" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/5a03a1ac-a96c-11e9-b35d-ce0397646ae0/volumes/kubernetes
.io~nfs/pvc-59f8e968-a96c-11e9-b2b5-5678f54e885f --scope -- mount -t nfs -o noatime,vers=4.1 10.104.36.102:/export/pvc-59f8e968-a96c-11e9-b2b5
-5678f54e885f /var/lib/kubelet/pods/5a03a1ac-a96c-11e9-b35d-ce0397646ae0/volumes/kubernetes.io~nfs/pvc-59f8e968-a96c-11e9-b2b5-5678f54e885f
Output: Running scope as unit run-r4b6c2d043dc248ce91a72d37bc039cf5.scope.
mount: wrong fs type, bad option, bad superblock on 10.104.36.102:/export/pvc-59f8e968-a96c-11e9-b2b5-5678f54e885f,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

This seems to be a [known DigitalOcean issue](https://www.digitalocean.com/community/questions/digitalocean-kubernetes-nodes-packages). I've only noticed this on DO clusters provisioned by Containership.

Not sure if related to #877 but discovered while debugging #983.

Using [local docker builds](https://docs.garden.io/using-garden/remote-kubernetes#local-docker-builds) should still work.

**Comment by eysi09** [comment]
Withholding the bug label for now since this looks a DO problem.

**Comment by solomonope** [comment]
Containership is out of business, I could not recreate this issue.
https://docs.containership.io/en/articles/3354688-containership-shutdown

**Comment by eysi09** [comment]
All right. I'll close this then.
